(in-package #:cl-tmux)

;;;; Command handler rule table — generated by define-command-handlers macro.
;;;;
;;;; This file contains the define-command-handlers macro definition and its
;;;; invocation with the core command handler rules.  Each handler maps a
;;;; keyword dispatch symbol to an action on the current session.
;;;;
;;;; Macros and helper functions used by these handlers are defined in
;;;; dispatch-core.lisp and dispatch-handlers-support.lisp.  The generated
;;;; dispatch-command function is the central entry point for ALL prefix-key
;;;; command dispatch.
;;;;
;;;; Copy-mode command handlers live in dispatch-handlers-copy-mode.lisp.
;;;; Paste-buffer command handlers live in dispatch-handlers-buffer.lisp.

;;; -- Scoped-options handler macro -------------------------------------------
;;;
;;; :show-window-options, :show-session-options, and :show-server-options all
;;; follow the same shape: (show-overlay (with-output-to-string (s) (format s "# SCOPE options") ...)).
;;; define-show-options-handler emits one named helper function per scope so the
;;; three handlers delegate to a generated function rather than duplicating the body.

(defmacro define-show-options-handler (fn-name scope-label &optional scope-arg)
  "Generate a zero-argument function named FN-NAME that shows a scoped options
   overlay.  SCOPE-LABEL is the string written after '# ' in the header line.
   SCOPE-ARG (a keyword) is forwarded to cl-tmux/options:show-options when
   provided; when absent the default (all options) form is used."
  `(defun ,fn-name ()
     ,(format nil "Show an overlay listing ~A options." scope-label)
     (show-overlay
      (with-output-to-string (stream)
        (format stream ,(format nil "# ~A options~%" scope-label))
        ,(if scope-arg
             `(write-string (cl-tmux/options:show-options ,scope-arg) stream)
             `(write-string (cl-tmux/options:show-options) stream))))))

(define-show-options-handler %show-session-options "session")
(define-show-options-handler %show-server-options  "server"  :server)

;;; -- define-command-handlers macro + dispatch-command ----------------------
;;;
;;; Handlers are registered into a hash table at load time; dispatch-command
;;; does a runtime gethash lookup.  This allows multiple define-command-handlers
;;; calls across different files — each one assertz-es additional facts without
;;; requiring the entire handler table to live in one monolithic form.

(defvar *command-dispatch-table* (make-hash-table)
  "Keyword → handler-fn.  Populated by define-command-handlers; consulted by dispatch-command.")

(defmacro define-command-handlers (&rest rules)
  "Register command handlers into *command-dispatch-table*.
   Each RULE is (kw-or-kws &rest body) where kw-or-kws is a keyword or a list
   of keywords (case-sharing, like CL case multi-key clauses).
   SESSION and BYTE are bound in each handler body.
   Multiple calls accumulate; later registrations for the same keyword override earlier ones.
   If a handler returns :QUIT or :DETACH that outcome is forwarded by dispatch-command."
  (let ((forms
         (loop for rule in rules
               for (kw-or-kws . body) = rule
               nconcing
               (let ((kws (if (listp kw-or-kws) kw-or-kws (list kw-or-kws))))
                 (mapcar (lambda (kw)
                           `(setf (gethash ,kw *command-dispatch-table*)
                                  (lambda (session byte)
                                    (declare (ignorable session byte))
                                    ,@body)))
                         kws)))))
    `(progn ,@forms)))

(defun dispatch-command (session cmd byte)
  "Dispatch CMD to its registered handler.  Sets *dirty* for all outcomes
   except :quit and :detach, which are returned as-is.
   NOTE: *dirty* is set even when CMD has no registered handler (unknown command).
   This is intentional — an unrecognised command is still a user interaction
   that may require a display refresh (e.g. to dismiss a stale overlay)."
  (declare (ignorable byte))
  (let* ((handler (gethash cmd *command-dispatch-table*))
         (outcome (when handler (funcall handler session byte))))
    (case outcome
      ((:quit :detach) outcome)
      (otherwise (setf *dirty* t) nil))))

;;; ── Copy-mode dispatch table helper ─────────────────────────────────────────
;;;
;;; 45 copy-mode handlers follow one uniform contract:
;;;   (KEYWORD (%copy-mode-call session #'FUNCTION))
;;; define-copy-mode-dispatch-handlers encodes that contract so the handler
;;; table reads as pure keyword → function-symbol data, with no boilerplate.

(defmacro define-copy-mode-dispatch-handlers (&rest entries)
  "Register copy-mode handlers of the form (%copy-mode-call session #'FN).
   Each ENTRY is (KEYWORD FN-SYMBOL).  Expands to define-command-handlers."
  `(define-command-handlers
     ,@(mapcar (lambda (entry)
                 `(,(first entry) (%copy-mode-call session #',(second entry))))
               entries)))

(defun %copy-mode-call-with-null-arg (session fn)
  "Call FN with SESSION and a trailing NIL argument via %COPY-MODE-CALL."
  (%copy-mode-call session (lambda (s) (funcall fn s nil))))

(define-command-handlers
  (:detach :detach)
  (:new-window (%cmd-new-window session))
  (:next-window (%cmd-cycle-window session #'next-cyclic))
  (:prev-window (%cmd-cycle-window session #'prev-cyclic))
  (:next-pane (%cmd-cycle-pane session #'next-cyclic))
  (:prev-pane (%cmd-cycle-pane session #'prev-cyclic))
  (:split-horizontal (%cmd-split session :v))        ; C-b " adds a horizontal bar → :v stacking
  (:split-vertical   (%cmd-split session :h))        ; C-b % adds a vertical bar   → :h side-by-side
  (:split-horizontal-no-focus (%cmd-split session :v :no-focus t))
  (:split-vertical-no-focus   (%cmd-split session :h :no-focus t))
  (:kill-pane (%handle-kill-result (kill-pane session)))
  (:kill-window (%handle-kill-result (kill-window session (session-active-window session))))
  (:kill-pane-confirm (%kill-current-pane-confirm session))
  (:kill-window-confirm (%kill-current-window-confirm session))
  (:respawn-pane (%respawn-current-pane session))
  (:rename-window (%rename-current-window session))
  (:list-keys (show-overlay (describe-key-bindings)))

  ;; ── Copy-mode handlers ─────────────────────────────────────────────────────
  ;; The 45 standard (%copy-mode-call session #'fn) handlers live in the
  ;; define-copy-mode-dispatch-handlers call in dispatch-handlers-copy-mode.lisp.
  ;; Non-standard copy-mode handlers follow here (cursor-fn / lambdas / no-ops).

  ;; cursor-direction: %copy-mode-cursor-fn builds the one-arg direction lambda
  (:copy-mode-cursor-left   (%copy-mode-call session (%copy-mode-cursor-fn :left)))
  (:copy-mode-cursor-right  (%copy-mode-call session (%copy-mode-cursor-fn :right)))
  (:copy-mode-cursor-up     (%copy-mode-call session (%copy-mode-cursor-fn :up)))
  (:copy-mode-cursor-down   (%copy-mode-call session (%copy-mode-cursor-fn :down)))
  ;; no-op: copy mode reads the live pane, so no explicit refresh step
  (:copy-mode-refresh-from-pane (values))
  ;; copy-pipe variants pass an extra NIL arg the standard path cannot encode.
  (:copy-mode-copy-pipe-and-cancel
   (%copy-mode-call-with-null-arg session #'copy-mode-copy-pipe))
  (:copy-mode-copy-pipe-no-cancel
   (%copy-mode-call-with-null-arg session #'copy-mode-copy-pipe-no-cancel))
  (:copy-mode-copy-pipe-end-of-line-and-cancel
   (%copy-mode-call-with-null-arg session #'copy-mode-copy-pipe-end-of-line))
  ;; search prompts open an interactive prompt — they don't go through %copy-mode-call
  (:copy-mode-search-forward-prompt
   (%copy-mode-search-prompt session "/" #'copy-mode-search-forward))
  (:copy-mode-search-backward-prompt
   (%copy-mode-search-prompt session "?" #'copy-mode-search-backward))
  ;; choose-buffer renders a live buffer listing overlay
  (:copy-mode-choose-buffer
   (show-built-overlay (stream)
     (write-string (%paste-buffer-listing-string
                    (cl-tmux/buffer:list-paste-buffers)
                    :preview-length +buffer-preview-length+)
                   stream)))

  ;; ── Resize commands ────────────────────────────────────────────────────────
  (:resize-left   (resize-pane (session-active-window session) :left))
  (:resize-right  (resize-pane (session-active-window session) :right))
  (:resize-up     (resize-pane (session-active-window session) :up))
  (:resize-down   (resize-pane (session-active-window session) :down))

  ;; ── Paste / send ──────────────────────────────────────────────────────────
  (:select-window (%select-window-by-byte session byte))
  (:paste-buffer
   (let* ((text (cl-tmux/buffer:get-paste-buffer))
          (win  (session-active-window session))
          (ap   (and win (window-active-pane win))))
     (%paste-to-pane ap text)))
  (:send-prefix
   ;; Send the currently configured prefix key byte, not the compile-time default.
   ;; *prefix-key-code* is updated when `set prefix` runs; +prefix-key-code+ is fixed.
   (with-active-pane (ap session)
     (and (not *client-read-only*)
          (%send-byte-to-pane ap cl-tmux/config:*prefix-key-code*))))

  ;; ── Layout commands ────────────────────────────────────────────────────────
  (:select-layout-even-h    (%apply-named-layout-to-session session :even-horizontal))
  (:select-layout-even-v    (%apply-named-layout-to-session session :even-vertical))
  (:select-layout-tiled     (%apply-named-layout-to-session session :tiled))
  (:select-layout-main-h    (%apply-named-layout-to-session session :main-horizontal))
  (:select-layout-main-v    (%apply-named-layout-to-session session :main-vertical))

  ;; ── Pane selection ────────────────────────────────────────────────────────
  (:select-pane-left   (%select-pane-in-direction session :left))
  (:select-pane-right  (%select-pane-in-direction session :right))
  (:select-pane-up     (%select-pane-in-direction session :up))
  (:select-pane-down   (%select-pane-in-direction session :down))

  ;; ── Zoom ──────────────────────────────────────────────────────────────────
  (:zoom-toggle
   (with-active-window (win session)
     (window-zoom-toggle win)))

  ;; ── Session management ────────────────────────────────────────────────────
  (:rename-session (%rename-current-session session))
  (:run-shell (%run-shell-prompt))
  (:if-shell (%if-shell-prompt))

  ;; :list-sessions / :list-sessions-full: static session list overlay.
  ((:list-sessions :list-sessions-full)
   (show-overlay (%format-session-list session)))

  ;; :choose-session: interactive j/k menu to switch sessions (C-b s).
  ;; Builds a menu with one entry per session; selecting switches to it.
  (:choose-session
   (%show-session-menu session))
  (:new-session (%new-session-default-name))
  (:kill-session
   ;; Destroy the current session, then apply detach-on-destroy: :quit (detach →
   ;; exit standalone) or NIL (switch to a survivor; the loop follows it).
   (let ((name (session-name session)))
     (%destroy-session session)
     (let ((action (%detach-on-destroy-action name)))
       (when (eq action :quit) (setf *running* nil))
       action)))
  (:has-session (%has-session-prompt))

  ;; ── Window management ──────────────────────────────────────────────────────
  (:list-windows (show-overlay (%format-window-list session)))
  ;; :choose-window: interactive j/k menu to select a window (C-b w).
  ;; Builds a menu with one entry per window; Enter selects, q/Esc dismisses.
  (:choose-window
   (%show-window-menu session))
  (:last-window
   (let ((prev (session-last-window session)))
     (when prev
       (%with-window-focus-transition (session)
         (session-select-window session prev)
         (setf (window-last-active-time prev) (get-universal-time))))))
  (:move-window (%move-current-window session))
  (:swap-window (%swap-current-window session))
  (:rotate-window (%rotate-current-window session :up))
  (:rotate-window-reverse (%rotate-current-window session :down))
  (:find-window
   (prompt-nonempty "find-window"
                    (lambda (pattern)
                      (%show-window-search-results session pattern))))

  ;; ── Pane management ────────────────────────────────────────────────────────
  (:swap-pane-forward  (%swap-active-pane session :right))
  (:swap-pane-backward (%swap-active-pane session :left))
  (:swap-pane-up       (%swap-active-pane session :up))
  (:swap-pane-down     (%swap-active-pane session :down))
  (:last-pane
   ;; Jump to the previously active pane.
   (let* ((win  (session-active-window session))
          (last (and win (window-last-active win))))
     (when last (%select-pane-with-focus win last))))
  (:display-panes
   ;; Show big per-pane numbers (drawn by the renderer while *display-panes-active*),
   ;; matching real tmux.  An (empty) transient overlay is the timing vehicle: it
   ;; auto-dismisses after display-panes-time ms (and on the next key), and clearing
   ;; it also clears *display-panes-active* so the numbers vanish with it.
   (%show-display-panes-overlay session))

  ;; ── Client switching ───────────────────────────────────────────────────────
  (:switch-client-next (%cmd-cycle-session session #'next-cyclic))
  (:switch-client-prev (%cmd-cycle-session session #'prev-cyclic))
  (:last-session
   (let* ((sessions (sort (mapcar #'cdr *server-sessions*) #'>
                          :key #'session-last-active))
          (second   (second sessions)))
     (when second
       (%switch-to-session second))))

  ;; ── Message / info ─────────────────────────────────────────────────────────
  (:display-message (%display-message-prompt session))
  (:source-file (%source-file-prompt))
  (:show-options
   (show-overlay (cl-tmux/options:show-options)))
  ;; show-window-options / show-session-options / show-server-options:
  ;; per-scope option listing with tmux-style headers.
  (:show-window-options
   (with-active-window (win session)
     (%show-window-options win)))
  (:show-session-options (%show-session-options))
  (:show-server-options  (%show-server-options))
  (:confirm-before (%confirm-before-prompt))

  ;; :wait-for is the canonical wait-for-channel command.
  (:wait-for
   (%signal-channel-prompt "wait-for channel"))

)

;;; ── Copy-mode standard dispatch table ───────────────────────────────────────
;;;
;;; The copy-mode table is split into dispatch-handlers-copy-mode.lisp so this
;;; coordinator file stays focused on shared helpers, macro definitions, and the
;;; main command handler table.
