(in-package #:cl-tmux/test)

;;;; Core dispatch navigation tests.

(describe "dispatch-suite"

  ;;; ── Cyclic helpers (generated by define-cyclic-navigators) ─────────────────

  ;; define-cyclic-navigators is a defined macro that generated next-cyclic and prev-cyclic.
  (it "define-cyclic-navigators-macro-is-defined"
    (expect (macro-function 'cl-tmux::define-cyclic-navigators))
    ;; Both generated functions are symmetric: stepping n and -n return to original.
    (expect (eql 'a (cl-tmux::prev-cyclic '(a b c)
                                          (cl-tmux::next-cyclic '(a b c) 'a)))))

  ;;; ── with-active-pane macro ──────────────────────────────────────────────────

  ;; with-active-pane evaluates to NIL when there is no active pane.
  (it "with-active-pane-returns-nil-for-empty-session"
    (with-fake-session (s :nwindows 0)
      ;; %active-screen uses with-active-pane internally
      (expect (null (cl-tmux::%active-screen s)))))

  ;; with-active-pane is a defined macro.
  (it "with-active-pane-macro-is-defined"
    (expect (macro-function 'cl-tmux::with-active-pane)))

  ;;; ── Window / pane selection ────────────────────────────────────────────────

  ;; C-b n moves to the next window and wraps around.
  (it "dispatch-next-window-cycles"
    (with-fake-session (s :nwindows 2)
      (cl-tmux::dispatch-command s :next-window nil)
      (expect (eq (second (session-windows s)) (session-active-window s)))
      (cl-tmux::dispatch-command s :next-window nil)
      (expect (eq (first (session-windows s)) (session-active-window s)))))

  ;; C-b p from the first window wraps to the last.
  (it "dispatch-prev-window-wraps"
    (with-fake-session (s :nwindows 2)
      (cl-tmux::dispatch-command s :prev-window nil)
      (expect (eq (second (session-windows s)) (session-active-window s)))))

  ;; %notify-pane-focus fires pane-focus-in / pane-focus-out independent of ?1004.
  (it "notify-pane-focus-fires-focus-hooks"
    (with-isolated-hooks
      (let* ((s        (make-fake-session :nwindows 1 :npanes 1))
             (pane     (session-active-pane s))
             (in-fired nil) (out-fired nil))
        (cl-tmux/hooks:add-hook "pane-focus-in"
                                (lambda (&rest _) (declare (ignore _)) (setf in-fired t)))
        (cl-tmux/hooks:add-hook "pane-focus-out"
                                (lambda (&rest _) (declare (ignore _)) (setf out-fired t)))
        (cl-tmux::%notify-pane-focus pane t)
        (expect in-fired :to-be-truthy)
        (cl-tmux::%notify-pane-focus pane nil)
        (expect out-fired :to-be-truthy))))

  ;; Switching panes fires focus-out for the old pane and focus-in for the new.
  (it "select-pane-with-focus-fires-out-then-in"
    (with-isolated-hooks
      (let* ((s         (make-fake-session :nwindows 1 :npanes 2))
             (win       (session-active-window s))
             (panes     (window-panes win))
             (in-count 0) (out-count 0))
        (cl-tmux/hooks:add-hook "pane-focus-in"
                                (lambda (&rest _) (declare (ignore _)) (incf in-count)))
        (cl-tmux/hooks:add-hook "pane-focus-out"
                                (lambda (&rest _) (declare (ignore _)) (incf out-count)))
        (cl-tmux::%select-pane-with-focus win (second panes))
        (expect (= 1 out-count))
        (expect (= 1 in-count)))))

  ;; %run-command-tokens resolves canonical next-window and previous-window commands;
  ;; in a 2-window session both select the second window (next advances, previous wraps).
  (it "run-command-tokens-canonical-next-previous-table"
    (dolist (row '(("next-window" "next-window must advance to the next window")
                   ("previous-window" "previous-window must wrap to the last window")))
      (destructuring-bind (abbrev desc) row
        (declare (ignore desc))
        (with-fake-session (s :nwindows 2)
          (cl-tmux::%run-command-tokens s (list abbrev))
          (expect (eq (second (session-windows s)) (session-active-window s)))))))

  ;; %run-command-tokens resolves the canonical 'rename-window' command through
  ;; *arg-command-table* to rename the active window.
  (it "run-command-tokens-canonical-rename-window-with-arg"
    (with-fake-session (s :nwindows 1)
      (cl-tmux::%run-command-tokens s '("rename-window" "myname"))
      (expect (string= "myname" (window-name (session-active-window s))))))

  ;; C-b o moves to the next pane within the active window.
  (it "dispatch-next-pane-cycles"
    (with-fake-two-pane-session (s)
      (let* ((win (session-active-window s))
             (p0  (first  (window-panes win)))
             (p1  (second (window-panes win))))
        (expect (eq p0 (window-active-pane win)))
        (cl-tmux::dispatch-command s :next-pane nil)
        (expect (eq p1 (window-active-pane win))))))

  ;; C-b <n>: :select-window uses the pressed digit byte to pick the window.
  (it "dispatch-select-window-by-digit"
    (with-fake-session (s :nwindows 3)
      (cl-tmux::dispatch-command s :select-window (char-code #\2))
      (expect (eq (third (session-windows s)) (session-active-window s)))
      (cl-tmux::dispatch-command s :select-window (char-code #\0))
      (expect (eq (first (session-windows s)) (session-active-window s)))))

  ;; An unrecognized command falls through to the passthrough branch: it returns
  ;; NIL (no quit), doesn't error, and still marks the session dirty.
  (it "dispatch-unknown-command-passes-through"
    (with-fake-session (s)
      (expect (null (cl-tmux::dispatch-command s :no-such-command (char-code #\a))))
      (expect cl-tmux::*dirty* :to-be-truthy))))
