(in-package #:cl-tmux/test)

;;;; Core dispatch navigation tests.

(in-suite dispatch-suite)

;;; ── Cyclic helpers (generated by define-cyclic-navigators) ─────────────────

(test define-cyclic-navigators-macro-is-defined
  "define-cyclic-navigators is a defined macro that generated next-cyclic and prev-cyclic."
  (is (macro-function 'cl-tmux::define-cyclic-navigators)
      "define-cyclic-navigators must be a macro")
  ;; Both generated functions are symmetric: stepping n and -n return to original.
  (is (eql 'a (cl-tmux::prev-cyclic '(a b c)
                                    (cl-tmux::next-cyclic '(a b c) 'a)))
      "next then prev returns to same element"))

;;; ── with-active-pane macro ──────────────────────────────────────────────────

(test with-active-pane-returns-nil-for-empty-session
  "with-active-pane evaluates to NIL when there is no active pane."
  (with-fake-session (s :nwindows 0)
    ;; %active-screen uses with-active-pane internally
    (is (null (cl-tmux::%active-screen s))
        "empty session has no active screen")))

(test with-active-pane-macro-is-defined
  "with-active-pane is a defined macro."
  (is (macro-function 'cl-tmux::with-active-pane)))

;;; ── Window / pane selection ────────────────────────────────────────────────

(test dispatch-next-window-cycles
  "C-b n moves to the next window and wraps around."
  (with-fake-session (s :nwindows 2)
    (cl-tmux::dispatch-command s :next-window nil)
    (is (eq (second (session-windows s)) (session-active-window s)))
    (cl-tmux::dispatch-command s :next-window nil)
    (is (eq (first (session-windows s)) (session-active-window s))
        "second :next-window should wrap back to window 1")))

(test dispatch-prev-window-wraps
  "C-b p from the first window wraps to the last."
  (with-fake-session (s :nwindows 2)
    (cl-tmux::dispatch-command s :prev-window nil)
    (is (eq (second (session-windows s)) (session-active-window s)))))

(test notify-pane-focus-fires-focus-hooks
  "%notify-pane-focus fires pane-focus-in / pane-focus-out independent of ?1004."
  (with-isolated-hooks
    (let* ((s        (make-fake-session :nwindows 1 :npanes 1))
           (pane     (session-active-pane s))
           (in-fired nil) (out-fired nil))
      (cl-tmux/hooks:add-hook "pane-focus-in"
                              (lambda (&rest _) (declare (ignore _)) (setf in-fired t)))
      (cl-tmux/hooks:add-hook "pane-focus-out"
                              (lambda (&rest _) (declare (ignore _)) (setf out-fired t)))
      (cl-tmux::%notify-pane-focus pane t)
      (is-true in-fired "focus-in hook fires on focus gain")
      (cl-tmux::%notify-pane-focus pane nil)
      (is-true out-fired "focus-out hook fires on focus loss"))))

(test select-pane-with-focus-fires-out-then-in
  "Switching panes fires focus-out for the old pane and focus-in for the new."
  (with-isolated-hooks
    (let* ((s         (make-fake-session :nwindows 1 :npanes 2))
           (win       (session-active-window s))
           (panes     (window-panes win))
           (in-count 0) (out-count 0))
      (cl-tmux/hooks:add-hook "pane-focus-in"
                              (lambda (&rest _) (declare (ignore _)) (incf in-count)))
      (cl-tmux/hooks:add-hook "pane-focus-out"
                              (lambda (&rest _) (declare (ignore _)) (incf out-count)))
      (cl-tmux::%select-pane-with-focus win (second panes))
      (is (= 1 out-count) "focus-out fires once (old pane)")
      (is (= 1 in-count)  "focus-in fires once (new pane)"))))

(test run-command-tokens-canonical-next-previous-table
  "%run-command-tokens resolves canonical next-window and previous-window commands;
   in a 2-window session both select the second window (next advances, previous wraps)."
  (dolist (row '(("next-window" "next-window must advance to the next window")
                 ("previous-window" "previous-window must wrap to the last window")))
    (destructuring-bind (abbrev desc) row
      (with-fake-session (s :nwindows 2)
        (cl-tmux::%run-command-tokens s (list abbrev))
        (is (eq (second (session-windows s)) (session-active-window s)) desc)))))

(test run-command-tokens-canonical-rename-window-with-arg
  "%run-command-tokens resolves the canonical 'rename-window' command through
   *arg-command-table* to rename the active window."
  (with-fake-session (s :nwindows 1)
    (cl-tmux::%run-command-tokens s '("rename-window" "myname"))
    (is (string= "myname" (window-name (session-active-window s)))
        "rename-window must rename the active window via the arg-table entry")))

(test dispatch-next-pane-cycles
  "C-b o moves to the next pane within the active window."
  (with-fake-two-pane-session (s)
    (let* ((win (session-active-window s))
           (p0  (first  (window-panes win)))
           (p1  (second (window-panes win))))
      (is (eq p0 (window-active-pane win)))
      (cl-tmux::dispatch-command s :next-pane nil)
      (is (eq p1 (window-active-pane win))))))

(test dispatch-select-window-by-digit
  "C-b <n>: :select-window uses the pressed digit byte to pick the window."
  (with-fake-session (s :nwindows 3)
    (cl-tmux::dispatch-command s :select-window (char-code #\2))
    (is (eq (third (session-windows s)) (session-active-window s)))
    (cl-tmux::dispatch-command s :select-window (char-code #\0))
    (is (eq (first (session-windows s)) (session-active-window s)))))

(test dispatch-unknown-command-passes-through
  "An unrecognized command falls through to the passthrough branch: it returns
   NIL (no quit), doesn't error, and still marks the session dirty."
  (with-fake-session (s)
    (is (null (cl-tmux::dispatch-command s :no-such-command (char-code #\a))))
    (is-true cl-tmux::*dirty* "dispatch marks dirty even on passthrough")))
