(in-package #:cl-tmux/test)

;;;; Command dispatch tests (src/application/dispatch/core/dispatch-core.lisp,
;;;;                         src/application/dispatch/core/dispatch-core-targets.lisp,
;;;;                         src/application/dispatch/core/dispatch-core-hooks.lisp,
;;;;                         src/application/dispatch/core/dispatch-core-window-cmds.lisp,
;;;;                         src/application/dispatch/commands/dispatch-commands.lisp,
;;;;                         src/application/dispatch/commands/dispatch-commands-pane.lisp,
;;;;                         src/application/dispatch/commands/dispatch-commands-list.lisp,
;;;;                         src/application/dispatch/commands/dispatch-commands-auto.lisp,
;;;;                         src/application/dispatch/commands/dispatch-commands-runner.lisp,
;;;;                         src/application/dispatch/control/dispatch-control.lisp,
;;;;                         src/application/dispatch/handlers/dispatch-handlers.lisp,
;;;;                         src/application/dispatch/handlers/dispatch-handlers-buffer.lisp).
;;;; Tests: dispatch-suite — dispatch-command, dispatch-prefix-command,
;;;; next-cyclic, prev-cyclic, %copy-mode-active-p, target-resolution helpers
;;;; (%resolve-target-window-pane, %resolve-target-session-window,
;;;; %resolve-window-target-or-active, with-target-session, with-target-context).

(def-suite dispatch-suite :description "Command dispatch and prefix routing")
(in-suite dispatch-suite)

(defmacro with-copy-mode-active-screen ((session-var screen-var &key feed) &body body)
  "Bind SESSION-VAR and SCREEN-VAR in an active copy-mode session.
   Optional FEED seeds the screen before BODY runs."
  `(with-fake-session (,session-var)
     (cl-tmux::dispatch-command ,session-var :copy-mode-enter nil)
     (let ((,screen-var (active-screen ,session-var)))
       ,@(when feed `((feed ,screen-var ,feed)))
       ,@body)))

(defmacro with-mocked-respawn-pane ((calls-var reader-calls-var) &body body)
  "Execute BODY with cl-tmux/model:respawn-pane and cl-tmux::start-reader-thread
   replaced by recording stubs.  Restores originals via unwind-protect.
   CALLS-VAR — list of (session pane start-dir default-command extra-env) tuples,
               accumulated in call order (oldest first).
   READER-CALLS-VAR — list of pane arguments passed to start-reader-thread,
                      accumulated in call order (oldest first)."
  (let ((orig-respawn (gensym "ORIG-RESPAWN"))
        (orig-reader  (gensym "ORIG-READER")))
    `(let* ((,calls-var nil)
            (,reader-calls-var nil)
            (,orig-respawn (fdefinition 'cl-tmux/model:respawn-pane))
            (,orig-reader  (fdefinition 'cl-tmux::start-reader-thread)))
       (unwind-protect
           (progn
             (setf (fdefinition 'cl-tmux/model:respawn-pane)
                   (lambda (session pane &key start-dir default-command extra-env)
                     (setf ,calls-var
                           (append ,calls-var
                                   (list (list session pane start-dir
                                               default-command extra-env))))
                     pane))
             (setf (fdefinition 'cl-tmux::start-reader-thread)
                   (lambda (pane)
                     (setf ,reader-calls-var (append ,reader-calls-var (list pane)))))
             ,@body)
         (setf (fdefinition 'cl-tmux/model:respawn-pane) ,orig-respawn)
         (setf (fdefinition 'cl-tmux::start-reader-thread) ,orig-reader)))))

(defmacro with-stubbed-switch-to-session ((target-var) &body body)
  "Execute BODY with cl-tmux::%switch-to-session replaced by a stub that
   records its TARGET argument into TARGET-VAR.  Restores the original
   function via unwind-protect."
  (let ((orig (gensym "ORIG-SWITCH-TO-SESSION")))
    `(let* ((,target-var nil)
            (,orig (fdefinition 'cl-tmux::%switch-to-session)))
       (unwind-protect
           (progn
             (setf (fdefinition 'cl-tmux::%switch-to-session)
                   (lambda (target) (setf ,target-var target)))
             ,@body)
         (setf (fdefinition 'cl-tmux::%switch-to-session) ,orig)))))

;;; ── Cyclic helpers (generated by define-cyclic-navigators) ─────────────────

(test define-cyclic-navigators-macro-is-defined
  "define-cyclic-navigators is a defined macro that generated next-cyclic and prev-cyclic."
  (is (macro-function 'cl-tmux::define-cyclic-navigators)
      "define-cyclic-navigators must be a macro")
  ;; Both generated functions are symmetric: stepping n and -n return to original.
  (is (eql 'a (cl-tmux::prev-cyclic '(a b c)
                                    (cl-tmux::next-cyclic '(a b c) 'a)))
      "next then prev returns to same element"))

;;; ── with-active-pane macro ──────────────────────────────────────────────────

(test with-active-pane-returns-nil-for-empty-session
  "with-active-pane evaluates to NIL when there is no active pane."
  (with-fake-session (s :nwindows 0)
    ;; %active-screen uses with-active-pane internally
    (is (null (cl-tmux::%active-screen s))
        "empty session has no active screen")))

(test with-active-pane-macro-is-defined
  "with-active-pane is a defined macro."
  (is (macro-function 'cl-tmux::with-active-pane)))

;;; ── Window / pane selection ────────────────────────────────────────────────

(test dispatch-next-window-cycles
  "C-b n moves to the next window and wraps around."
  (with-fake-session (s :nwindows 2)
    (cl-tmux::dispatch-command s :next-window nil)
    (is (eq (second (session-windows s)) (session-active-window s)))
    (cl-tmux::dispatch-command s :next-window nil)
    (is (eq (first (session-windows s)) (session-active-window s))
        "second :next-window should wrap back to window 1")))

(test dispatch-prev-window-wraps
  "C-b p from the first window wraps to the last."
  (with-fake-session (s :nwindows 2)
    (cl-tmux::dispatch-command s :prev-window nil)
    (is (eq (second (session-windows s)) (session-active-window s)))))

(test notify-pane-focus-fires-focus-hooks
  "%notify-pane-focus fires pane-focus-in / pane-focus-out independent of ?1004."
  (with-isolated-hooks
    (let* ((s        (make-fake-session :nwindows 1 :npanes 1))
           (pane     (session-active-pane s))
           (in-fired nil) (out-fired nil))
      (cl-tmux/hooks:add-hook "pane-focus-in"
                              (lambda (&rest _) (declare (ignore _)) (setf in-fired t)))
      (cl-tmux/hooks:add-hook "pane-focus-out"
                              (lambda (&rest _) (declare (ignore _)) (setf out-fired t)))
      (cl-tmux::%notify-pane-focus pane t)
      (is-true in-fired "focus-in hook fires on focus gain")
      (cl-tmux::%notify-pane-focus pane nil)
      (is-true out-fired "focus-out hook fires on focus loss"))))

(test select-pane-with-focus-fires-out-then-in
  "Switching panes fires focus-out for the old pane and focus-in for the new."
  (with-isolated-hooks
    (let* ((s         (make-fake-session :nwindows 1 :npanes 2))
           (win       (session-active-window s))
           (panes     (window-panes win))
           (in-count 0) (out-count 0))
      (cl-tmux/hooks:add-hook "pane-focus-in"
                              (lambda (&rest _) (declare (ignore _)) (incf in-count)))
      (cl-tmux/hooks:add-hook "pane-focus-out"
                              (lambda (&rest _) (declare (ignore _)) (incf out-count)))
      (cl-tmux::%select-pane-with-focus win (second panes))
      (is (= 1 out-count) "focus-out fires once (old pane)")
      (is (= 1 in-count)  "focus-in fires once (new pane)"))))

(test run-command-tokens-canonical-next-previous-table
  "%run-command-tokens resolves canonical next-window and previous-window commands;
   in a 2-window session both select the second window (next advances, previous wraps)."
  (dolist (row '(("next-window" "next-window must advance to the next window")
                 ("previous-window" "previous-window must wrap to the last window")))
    (destructuring-bind (abbrev desc) row
      (with-fake-session (s :nwindows 2)
        (cl-tmux::%run-command-tokens s (list abbrev))
        (is (eq (second (session-windows s)) (session-active-window s)) desc)))))

(test run-command-tokens-canonical-rename-window-with-arg
  "%run-command-tokens resolves the canonical 'rename-window' command through
   *arg-command-table* to rename the active window."
  (with-fake-session (s :nwindows 1)
    (cl-tmux::%run-command-tokens s '("rename-window" "myname"))
    (is (string= "myname" (window-name (session-active-window s)))
        "rename-window must rename the active window via the arg-table entry")))

(test dispatch-next-pane-cycles
  "C-b o moves to the next pane within the active window."
  (with-fake-two-pane-session (s)
    (let* ((win (session-active-window s))
           (p0  (first  (window-panes win)))
           (p1  (second (window-panes win))))
      (is (eq p0 (window-active-pane win)))
      (cl-tmux::dispatch-command s :next-pane nil)
      (is (eq p1 (window-active-pane win))))))

(test dispatch-select-window-by-digit
  "C-b <n>: :select-window uses the pressed digit byte to pick the window."
  (with-fake-session (s :nwindows 3)
    (cl-tmux::dispatch-command s :select-window (char-code #\2))
    (is (eq (third (session-windows s)) (session-active-window s)))
    (cl-tmux::dispatch-command s :select-window (char-code #\0))
    (is (eq (first (session-windows s)) (session-active-window s)))))

(test dispatch-unknown-command-passes-through
  "An unrecognized command falls through to the passthrough branch: it returns
   NIL (no quit), doesn't error, and still marks the session dirty."
  (with-fake-session (s)
    (is (null (cl-tmux::dispatch-command s :no-such-command (char-code #\a))))
    (is-true cl-tmux::*dirty* "dispatch marks dirty even on passthrough")))

;;; ── Rename ──────────────────────────────────────────────────────────────────

(test dispatch-rename-window-opens-prompt
  "C-b , opens a rename prompt seeded with the active window's name, and its
   on-submit closure renames the active window."
  (with-fake-session (s :nwindows 1)
    (let ((*prompt* nil))
      (cl-tmux::dispatch-command s :rename-window nil)
      (is (prompt-active-p) "rename should open a prompt")
      (is (string= "0" (prompt-buffer *prompt*))
          "prompt seeded with current window name")
      (is (functionp (prompt-on-submit *prompt*))
          "prompt should carry an on-submit closure")
      (funcall (prompt-on-submit *prompt*) "renamed")
      (is (string= "renamed" (window-name (session-active-window s)))
          "on-submit closure should rename the active window"))))

;;; ── Copy mode ───────────────────────────────────────────────────────────────

(test dispatch-copy-mode-enter-exit
  "C-b [ enters copy mode on the active screen; exit clears it."
  (with-fake-session (s)
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (is (screen-copy-mode-p (active-screen s)) "copy mode should be on after enter")
    (cl-tmux::dispatch-command s :copy-mode-exit nil)
    (is-false (screen-copy-mode-p (active-screen s)) "copy mode should be off after exit")))

(test copy-mode-active-p-reflects-state
  "%copy-mode-active-p tracks the active screen's copy-mode flag."
  (with-fake-session (s)
    (is-false (cl-tmux::%copy-mode-active-p s))
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (is (cl-tmux::%copy-mode-active-p s))))

(test send-keys-R-resets-pane-terminal-state
  "send-keys -R resets the target pane's terminal state (RIS): the cursor is homed."
  (with-fake-session (s :nwindows 1 :npanes 1)
    (let* ((win  (cl-tmux/model:session-active-window s))
           (pane (cl-tmux/model:window-active-pane win))
           (scr  (cl-tmux/model:pane-screen pane)))
      (setf (cl-tmux/terminal/types:screen-cursor-x scr) 5
            (cl-tmux/terminal/types:screen-cursor-y scr) 3)
      (cl-tmux::%cmd-send-keys-arg s '("-R"))
      (is (= 0 (cl-tmux/terminal/types:screen-cursor-x scr))
          "send-keys -R must home the cursor x")
      (is (= 0 (cl-tmux/terminal/types:screen-cursor-y scr))
          "send-keys -R must home the cursor y"))))

;;; ── send-keys -X copy-mode commands: cursor-left/right + rectangle-toggle ────

(test send-keys-x-command-table
  "The *copy-mode-x-commands* table maps all send-keys -X names to their
   proper copy-mode keywords."
  (dolist (c '(("cursor-left"      :copy-mode-cursor-left)
               ("cursor-right"     :copy-mode-cursor-right)
               ("cursor-up"        :copy-mode-cursor-up)
               ("cursor-down"      :copy-mode-cursor-down)
               ("rectangle-toggle" :copy-mode-rectangle-toggle)
               ("copy-selection"   :copy-mode-copy-selection-no-cancel)
               ("select-word"      :copy-mode-select-word)
               ("other-end"        :copy-mode-other-end)
               ("copy-pipe"        :copy-mode-copy-pipe-no-cancel)
               ("copy-pipe-and-cancel" :copy-mode-copy-pipe-and-cancel)
               ("copy-pipe-end-of-line-and-cancel"
                :copy-mode-copy-pipe-end-of-line-and-cancel)
               ("next-matching-bracket" :copy-mode-next-matching-bracket)
               ("previous-matching-bracket"
                :copy-mode-previous-matching-bracket)))
    (destructuring-bind (name expected) c
      (is (eq expected (copy-mode-x-command-value name))
          "~S must map to ~S" name expected))))

(test send-keys-x-rectangle-toggle-toggles-rect-select
  "send -X rectangle-toggle flips the screen's rectangle (block) selection flag
   instead of starting a stream selection."
  (with-copy-mode-active-screen (s screen)
    (is-false (screen-copy-rect-select-p screen) "rect-select off on entry")
    (is (cl-tmux::%dispatch-send-keys-X s "rectangle-toggle")
        "rectangle-toggle must be a handled -X command")
    (is (screen-copy-rect-select-p screen) "rectangle-toggle turns rect-select ON")
    (cl-tmux::%dispatch-send-keys-X s "rectangle-toggle")
    (is-false (screen-copy-rect-select-p screen) "a second toggle turns it OFF")))

(test send-keys-x-copy-selection-stays-in-copy-mode
  "send -X copy-selection copies the selection and clears it but STAYS in copy
   mode (tmux WINDOW_COPY_CMD_REDRAW), whereas copy-selection-and-cancel exits."
  (is (eq :copy-mode-copy-selection-no-cancel
          (copy-mode-x-command-value "copy-selection"))
      "copy-selection must map to the non-cancelling keyword")
  (is (eq :copy-mode-yank
          (copy-mode-x-command-value "copy-selection-and-cancel"))
      "copy-selection-and-cancel must map to the exit-on-yank keyword"))

(test send-keys-x-rectangle-toggle-restores-temporary-focus
  "send -X rectangle-toggle must temporarily focus the target pane and restore
   the original session/window focus afterward."
  (with-fake-session (s :nwindows 2)
    (let* ((original-window (session-active-window s))
           (original-pane   (session-active-pane s))
           (target-window   (second (session-windows s)))
           (target-pane     (first (window-panes target-window)))
           (target-screen   (pane-screen target-pane)))
      (setf (cl-tmux/model::session-active s) target-window
            (cl-tmux/model::window-active target-window) target-pane)
      (cl-tmux::dispatch-command s :copy-mode-enter nil)
      (setf (cl-tmux/model::session-active s) original-window
            (cl-tmux/model::window-active original-window) original-pane
            (cl-tmux/model::window-active target-window) target-pane)
      (is-false (screen-copy-rect-select-p target-screen)
                "rect-select starts off on the target screen")
      (is (cl-tmux::%dispatch-send-keys-X s "rectangle-toggle" target-pane target-window nil)
          "rectangle-toggle must be handled via the temporary focus helper")
      (is (screen-copy-rect-select-p target-screen)
          "rectangle-toggle must toggle the target screen")
      (is (eq original-window (session-active-window s))
          "session focus must be restored to the original window")
      (is (eq original-pane (session-active-pane s))
          "session focus must be restored to the original pane"))))

(test send-keys-x-copy-pipe-and-cancel-variants
  "send -X copy-pipe-and-cancel without an arg and with an explicit command both
   copy the selection to the paste buffer and exit copy mode.
   Each row: (pipe-args description)."
  (dolist (row '((nil       "copy-pipe-and-cancel (no explicit command)")
                 (("cat")   "copy-pipe-and-cancel with explicit command")))
    (destructuring-bind (pipe-args desc) row
      (let ((cl-tmux/buffer:*paste-buffers* nil))
        (with-option-session (s)
          (with-loop-state
            (cl-tmux/options:set-option "copy-command" "")
            (let ((screen (active-screen s)))
              (feed screen "pipe-me")
              (cl-tmux::dispatch-command s :copy-mode-enter nil)
              (setf (screen-copy-selecting screen) t
                    (screen-copy-mark screen) (cons 0 0)
                    (screen-copy-cursor screen) (cons 0 7))
              (is (cl-tmux::%dispatch-send-keys-X s "copy-pipe-and-cancel" nil nil pipe-args)
                  "~A must be handled" desc)
              (is (string= "pipe-me" (cl-tmux/buffer:get-paste-buffer 0))
                  "~A must copy to the paste buffer" desc)
              (is-false (screen-copy-mode-p screen)
                        "~A must exit copy mode" desc))))))))

(test send-keys-x-copy-pipe-end-of-line-and-cancel-copies-to-eol-and-exits
  "send -X copy-pipe-end-of-line-and-cancel with an explicit command should
   copy from the cursor position through the end of the line and exit copy
   mode."
  (let ((cl-tmux/buffer:*paste-buffers* nil))
    (with-option-session (s)
      (with-loop-state
        (cl-tmux/options:set-option "copy-command" "")
        (let ((screen (active-screen s)))
          (feed screen "pipe-me now")
          (cl-tmux::dispatch-command s :copy-mode-enter nil)
          (setf (screen-copy-selecting screen) t
                (screen-copy-mark screen) (cons 0 5)
                (screen-copy-cursor screen) (cons 0 5))
          (is (cl-tmux::%dispatch-send-keys-X s
                                              "copy-pipe-end-of-line-and-cancel"
                                              nil nil
                                              '("cat"))
              "copy-pipe-end-of-line-and-cancel with an argument must be handled")
          (is (string= "me now" (cl-tmux/buffer:get-paste-buffer 0))
              "text from the cursor through the end of the line must be copied")
          (is-false (screen-copy-mode-p screen)
                    "copy-pipe-end-of-line-and-cancel must exit copy mode"))))))

(test send-keys-x-explicit-jump-commands
  "send -X jump-forward / jump-backward / jump-to / jump-to-backward must pass
   explicit character arguments through to the copy-mode jump helpers."
  (with-copy-mode-active-screen (s screen :feed "hello world")
    (labels ((invoke (command start args)
               (setf (screen-copy-cursor screen) start)
               (is (cl-tmux::%dispatch-send-keys-X s command nil nil args)
                   "~A with an explicit argument must be handled" command)
               (screen-copy-cursor screen)))
      (check-table
       (list
        (list (invoke "jump-forward" (cons 0 0) '("l"))
              (cons 0 2)
              "jump-forward must land on the next matching character")
        (list (invoke "jump-backward" (cons 0 5) '("l"))
              (cons 0 3)
              "jump-backward must land on the previous matching character")
        (list (invoke "jump-to" (cons 0 0) '("l"))
              (cons 0 1)
              "jump-to must land just before the next matching character")
        (list (invoke "jump-to-backward" (cons 0 5) '("l"))
              (cons 0 4)
              "jump-to-backward must land just after the previous matching character"))
       :test #'equal))))

(test send-keys-x-explicit-text-commands
  "send -X search-forward-text / search-backward-text must accept explicit
   search text, including multi-token arguments, without opening a prompt."
  (labels ((invoke (feed command start args)
             (with-copy-mode-active-screen (s screen :feed feed)
               (setf (screen-copy-cursor screen) start)
               (is (cl-tmux::%dispatch-send-keys-X s command nil nil args)
                   "~A with an explicit argument must be handled" command)
               (list (screen-copy-cursor screen)
                     (cl-tmux/terminal/types:screen-copy-search-term screen)))))
    (check-table
     (list
      (list (invoke "abc def abc" "search-forward-text" (cons 0 0) '("abc"))
            (list (cons 0 8) "abc")
            "search-forward-text must jump to the next matching text")
      (list (invoke "abc def abc" "search-backward-text" (cons 0 11) '("abc"))
            (list (cons 0 8) "abc")
            "search-backward-text must jump to the previous matching text")
      (list (invoke "zzzabc defzzz" "search-forward-text" (cons 0 0) '("abc" "def"))
            (list (cons 0 3) "abc def")
            "search-forward-text must join multiple positional tokens"))
     :test #'equal)))

(test send-keys-x-goto-line-jumps-to-line-number
  "send -X goto-line with an argument parses the line number and moves the copy
   cursor to the requested row."
  (with-copy-mode-active-screen (s screen)
    (labels ((invoke (args)
               (setf (screen-copy-cursor screen) (cons 0 0))
               (is (cl-tmux::%dispatch-send-keys-X s "goto-line" nil nil args)
                   "goto-line with explicit arguments must be handled")
               (screen-copy-cursor screen)))
      (check-table
       (list
        (list (invoke '("2"))
              (cons 1 0)
              "goto-line 2 must land on row 1")
        (list (invoke '("2" "ignored"))
              (cons 1 0)
              "goto-line must ignore trailing positional tokens"))
       :test #'equal))))

(test send-keys-x-cursor-left-right-move-cursor
  "send -X cursor-right / cursor-left move the copy-mode cursor horizontally
   (previously both mis-mapped to begin-selection, which did not move it)."
  (with-fake-session (s)
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (let ((screen (active-screen s)))
      (cl-tmux::%dispatch-send-keys-X s "cursor-right")
      (is (= 1 (cdr (screen-copy-cursor screen)))
          "cursor-right moves the cursor to column 1 (from the initial column 0)")
      (cl-tmux::%dispatch-send-keys-X s "cursor-left")
      (is (= 0 (cdr (screen-copy-cursor screen)))
          "cursor-left moves the cursor back to column 0"))))

(test send-keys-x-cursor-up-down-move-cursor-vertically
  "send -X cursor-up / cursor-down move the copy cursor vertically (the -X names
   previously only scrolled a line, inconsistent with the arrow-key path)."
  (with-fake-session (s)
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (let* ((screen (active-screen s))
           (h      (screen-height screen)))
      (cl-tmux::%dispatch-send-keys-X s "cursor-up")
      (is (= (- h 2) (car (screen-copy-cursor screen)))
          "cursor-up moves the cursor one row up from the bottom")
      (cl-tmux::%dispatch-send-keys-X s "cursor-down")
      (is (= (- h 1) (car (screen-copy-cursor screen)))
          "cursor-down moves the cursor back to the bottom row"))))

;;; ── Detach / kill ───────────────────────────────────────────────────────────

(test dispatch-detach-returns-detach
  "C-b d returns :detach and does NOT clear *running* itself (the caller decides:
   standalone stops, a server merely disconnects the client)."
  (with-fake-session (s)
    (is (eq :detach (cl-tmux::dispatch-command s :detach nil)))
    (is-true cl-tmux::*running* "dispatch-command must not clear *running*")))

(test dispatch-kill-last-returns-quit-table
  "Killing the last window or last pane ends the session with :quit."
  (with-fake-session (s :nwindows 1)
    (is (eq :quit (cl-tmux::dispatch-command s :kill-window nil))
        "killing last window → :quit"))
  (with-fake-session (s :nwindows 1 :npanes 1)
    (is (eq :quit (cl-tmux::dispatch-command s :kill-pane nil))
        "killing last pane → :quit")))

(test dispatch-kill-one-of-two-windows-survives
  "Killing one of two windows leaves the session running with the other."
  (with-fake-session (s :nwindows 2)
    (is (null (cl-tmux::dispatch-command s :kill-window nil)))
    (is (= 1 (length (session-windows s))))))

;;; ── Prefix routing ──────────────────────────────────────────────────────────

(test dispatch-prefix-routes-binding
  "dispatch-prefix-command looks the byte up in the binding table (d → detach)."
  (with-fake-session (s)
    (is (eq :detach (cl-tmux::dispatch-prefix-command s (char-code #\d))))))

(test prefix-q-exits-copy-mode
  "In copy mode, the prefix-routed 'q' exits copy mode."
  (with-fake-session (s)
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (cl-tmux::dispatch-prefix-command s (char-code #\q))
    (is-false (screen-copy-mode-p (active-screen s)))))

;;; ── %active-screen ───────────────────────────────────────────────────────────

(test active-screen-returns-active-pane-screen
  "%active-screen returns the screen of the session's active pane."
  (with-fake-session (s)
    (let ((ap (session-active-pane s)))
      (is (eq (pane-screen ap)
              (cl-tmux::%active-screen s))
          "%active-screen must return the active pane's screen"))))

(test active-screen-returns-nil-for-empty-session
  "%active-screen returns NIL when no pane is active."
  (with-fake-session (s :nwindows 0)
    (is (null (cl-tmux::%active-screen s)))))

;;; ── %cmd-cycle-window ────────────────────────────────────────────────────────

(test cmd-cycle-window-advances-selection
  "%cmd-cycle-window advances the active window via CYCLER."
  (with-fake-session (s :nwindows 3)
    (let* ((w1 (first  (session-windows s)))
           (w2 (second (session-windows s))))
      (is (eq w1 (session-active-window s)))
      (cl-tmux::%cmd-cycle-window s #'cl-tmux::next-cyclic)
      (is (eq w2 (session-active-window s))))))

;;; ── %cmd-cycle-pane ──────────────────────────────────────────────────────────

(test cmd-cycle-pane-advances-pane-selection
  "%cmd-cycle-pane advances the active pane via CYCLER."
  (with-fake-two-pane-session (s)
    (let* ((win (session-active-window s))
           (p0  (first  (window-panes win)))
           (p1  (second (window-panes win))))
      (is (eq p0 (window-active-pane win)))
      (cl-tmux::%cmd-cycle-pane s #'cl-tmux::next-cyclic)
      (is (eq p1 (window-active-pane win))))))

;;; ── focus events (?1004) on pane switch ──────────────────────────────────────

(test notify-pane-focus-noop-without-pty
  "%notify-pane-focus is a safe no-op for a pane with no live PTY (fd <= 0),
   even when focus events are enabled."
  (let ((pane (make-pane :id 1 :x 0 :y 0 :width 20 :height 5 :fd -1
                         :screen (make-screen 20 5))))
    (setf (cl-tmux/terminal/types:screen-focus-events (pane-screen pane)) t)
    (is (null (cl-tmux::%notify-pane-focus pane t))
        "no PTY → %notify-pane-focus returns NIL without writing")
    (finishes (cl-tmux::%notify-pane-focus pane nil))))

(test notify-pane-focus-writes-focus-in-to-pty
  "With focus events enabled and a live fd, %notify-pane-focus delivers the
   focus-gained report ESC[I to the pane's PTY."
  (with-pipe-fds (rfd wfd)
    (let ((pane (make-pane :id 1 :x 0 :y 0 :width 20 :height 5 :fd wfd
                           :screen (make-screen 20 5))))
      (setf (cl-tmux/terminal/types:screen-focus-events (pane-screen pane)) t)
      (cl-tmux::%notify-pane-focus pane t)
      (let ((ready (cl-tmux/pty:select-fds (list rfd) 200000)))  ; 200 ms
        (is-true ready "the PTY read-end must be readable after a focus report")
        (when ready
          (cffi:with-foreign-object (buf :uint8 8)
            (let ((n (cffi:foreign-funcall "read"
                                           :int rfd :pointer buf :unsigned-long 3
                                           :long)))
              (is (= 3 n) "focus-in report must be exactly 3 bytes (got ~D)" n)
              (is (= 27 (cffi:mem-aref buf :uint8 0)) "byte 0 must be ESC (27)")
              (is (= 91 (cffi:mem-aref buf :uint8 1)) "byte 1 must be #\\[ (91)")
              (is (= 73 (cffi:mem-aref buf :uint8 2)) "byte 2 must be #\\I (73)"))))))))

(test notify-pane-focus-disabled-screen-writes-nothing
  "A pane whose app did NOT enable focus events receives no report even with a
   live fd, and select-fds reports the pipe idle."
  (with-pipe-fds (rfd wfd)
    (let ((pane (make-pane :id 1 :x 0 :y 0 :width 20 :height 5 :fd wfd
                           :screen (make-screen 20 5))))
      ;; focus-events left NIL (default)
      (cl-tmux::%notify-pane-focus pane t)
      (is (null (cl-tmux/pty:select-fds (list rfd) 20000))
          "no focus report must reach an opted-out pane (pipe must stay idle)"))))

(test select-pane-with-focus-switches-and-tolerates-no-pty
  "%select-pane-with-focus changes the active pane and runs the focus-notify path
   without error even when panes have no PTY and focus events are enabled."
  (with-fake-two-pane-session (s)
    (let* ((win (session-active-window s))
           (p0  (first  (window-panes win)))
           (p1  (second (window-panes win))))
      (setf (cl-tmux/terminal/types:screen-focus-events (pane-screen p0)) t)
      (setf (cl-tmux/terminal/types:screen-focus-events (pane-screen p1)) t)
      (is (eq p0 (window-active-pane win)))
      (finishes (cl-tmux::%select-pane-with-focus win p1))
      (is (eq p1 (window-active-pane win))
          "%select-pane-with-focus must make p1 the active pane"))))

;;; ── %derive-hook-session resolver clauses ────────────────────────────────────

(test derive-hook-session-returns-nil-for-nil
  "%derive-hook-session returns NIL when TARGET is NIL."
  (is (null (cl-tmux::%derive-hook-session nil))
      "%derive-hook-session must return NIL for a NIL target"))

(test derive-hook-session-returns-session-directly
  "%derive-hook-session returns a session object unchanged."
  (with-fake-session (s)
    (is (eq s (cl-tmux::%derive-hook-session s))
        "%derive-hook-session must return the session itself for a session target")))

(test derive-hook-session-resolves-from-window
  "%derive-hook-session resolves the owning session from a window object."
  (with-fake-session (s)
    (with-command-test-state (s)
      (let ((win (session-active-window s)))
        (is (eq s (cl-tmux::%derive-hook-session win))
            "%derive-hook-session must return the session owning the window")))))

(test derive-hook-session-resolves-from-pane
  "%derive-hook-session resolves the owning session from a pane object."
  (with-fake-session (s)
    (with-command-test-state (s)
      (let ((pane (session-active-pane s)))
        (is (eq s (cl-tmux::%derive-hook-session pane))
            "%derive-hook-session must return the session owning the pane")))))

(test derive-hook-session-returns-nil-for-unknown-type
  "%derive-hook-session returns NIL for an unrecognised target type."
  (is (null (cl-tmux::%derive-hook-session :not-a-model-object))
      "%derive-hook-session must return NIL for an unrecognised target type"))

;;; ── %dispatch-hook-entry string-hook path ────────────────────────────────────

(test dispatch-hook-entry-string-hook-runs-command
  "%dispatch-hook-entry with a string entry runs it as a command via %run-command-line.
   Exercises the string-hook branch (the ignore-errors / handler-case path) directly."
  (with-fake-session (s :nwindows 1)
    (let ((*overlay* nil))
      ;; 'list-windows' is a safe command that opens an overlay.
      (cl-tmux::%dispatch-hook-entry s "list-windows")
      (assert-overlay-active
       "%dispatch-hook-entry with a string hook must run the command"))))

(test dispatch-hook-entry-string-hook-error-shows-overlay
  "%dispatch-hook-entry with a string hook that errors reports the error as an overlay
   instead of silently swallowing it."
  (with-fake-session (s)
    (let ((*overlay* nil))
      ;; Deliberately break the string to cause %run-command-line to fail.
      ;; We use a command name that will not resolve in the command table.
      (cl-tmux::%dispatch-hook-entry s "nonexistent-hook-command-xyz")
      ;; After an error the overlay must contain an error report OR remain nil
      ;; (depending on whether the command runner returns an error vs. overlay).
      ;; The important invariant is that no condition escapes to the caller.
      (finishes (values) "error in string hook must not propagate to the caller"))))

(test dispatch-hook-entry-keyword-hook-dispatches-command
  "%dispatch-hook-entry with a keyword entry dispatches it as a command directly."
  (with-fake-session (s)
    (let ((*overlay* nil))
      (cl-tmux::%dispatch-hook-entry s :list-windows)
      (assert-overlay-active
       "%dispatch-hook-entry with a keyword hook must dispatch the command"))))

;;; ── %cmd-cycle-session ───────────────────────────────────────────────────────

(test cmd-cycle-session-advances-to-next-session
  "%cmd-cycle-session with next-cyclic switches to the next session in the registry."
  (let* ((s1 (make-fake-session))
         (s2 (make-fake-session)))
    (setf (cl-tmux::session-name s1) "alpha"
          (cl-tmux::session-name s2) "beta")
    (let ((cl-tmux::*server-sessions* (list (cons "alpha" s1) (cons "beta" s2))))
      (with-stubbed-switch-to-session (switched-to)
        (cl-tmux::%cmd-cycle-session s1 #'cl-tmux::next-cyclic)
        (is (eq s2 switched-to)
            "%cmd-cycle-session must advance to the next session")))))

(test cmd-cycle-session-noop-with-single-session
  "%cmd-cycle-session is a no-op when SESSION is the only session (wraps to itself)."
  (let ((s (make-fake-session)))
    (setf (cl-tmux::session-name s) "only")
    (let ((cl-tmux::*server-sessions* (list (cons "only" s))))
      (with-stubbed-switch-to-session (switched-to)
        (cl-tmux::%cmd-cycle-session s #'cl-tmux::next-cyclic)
        (is-false switched-to
                  "%cmd-cycle-session must not switch when there is only one session")))))

;;; ── %copy-mode-call NIL-screen path ─────────────────────────────────────────

(test copy-mode-call-nil-screen-returns-nil
  "%copy-mode-call returns NIL without calling FN when the active screen is NIL.
   Exercises the guard path inside %copy-mode-call."
  (with-fake-session (s :nwindows 0)
    ;; Session with no windows → no active screen.
    (let ((fn-called nil))
      (is (null (cl-tmux::%copy-mode-call s (lambda (screen)
                                              (declare (ignore screen))
                                              (setf fn-called t)
                                              :was-called)))
          "%copy-mode-call on a windowless session must return NIL")
      (is-false fn-called
                "%copy-mode-call must not call FN when there is no active screen"))))

;;; ── %overlay-lines-string ────────────────────────────────────────────────────

(test overlay-lines-string-joins-lines-with-newlines
  "%overlay-lines-string renders a non-empty list as newline-separated text."
  (is (string= "foo" (cl-tmux::%overlay-lines-string '("foo")))
      "single-line list renders without trailing newline")
  (is (string= (format nil "foo~%bar")
               (cl-tmux::%overlay-lines-string '("foo" "bar")))
      "two-line list renders lines separated by a newline"))

(test overlay-lines-string-returns-empty-string-for-nil
  "%overlay-lines-string returns the EMPTY fallback (default \"\") for NIL input."
  (is (string= "" (cl-tmux::%overlay-lines-string nil))
      "NIL list produces empty string by default")
  (is (string= "none" (cl-tmux::%overlay-lines-string nil "none"))
      "NIL list returns the custom EMPTY argument"))

;;; ── %overlayf ────────────────────────────────────────────────────────────────

(test overlayf-renders-formatted-overlay
  "%overlayf shows a one-line overlay built from a FORMAT control string."
  (with-fake-session (s)
    (let ((*overlay* nil))
      (cl-tmux::%overlayf "hello ~A" "world")
      (is (overlay-active-p) "%overlayf must activate an overlay")
      (is (search "hello world" *overlay*)
          "%overlayf must format its args into the overlay text"))))

;;; ── %flag-value and %flag-present-p ──────────────────────────────────────────

(test flag-value-returns-associated-value
  "%flag-value returns the cdr of the matching (char . value) entry, or NIL when absent."
  (let ((flags (list (cons #\a "alpha") (cons #\b "beta"))))
    (dolist (row '((#\a "alpha" "flag \\a present")
                   (#\b "beta"  "flag \\b present")
                   (#\z nil     "absent flag returns NIL")))
      (destructuring-bind (ch expected desc) row
        (is (equal expected (cl-tmux::%flag-value flags ch))
            "~A" desc)))))

(test flag-present-p-returns-true-iff-flag-present
  "%flag-present-p returns true when FLAGS contains CHAR, NIL otherwise."
  (let ((flags (list (cons #\a t) (cons #\b nil))))
    (is-true  (cl-tmux::%flag-present-p flags #\a)
              "flag \\a must be present")
    (is-true  (cl-tmux::%flag-present-p flags #\b)
              "flag \\b has a NIL value but is still present")
    (is-false (cl-tmux::%flag-present-p flags #\z)
              "absent flag \\z must not be present")))

;;; ── show-built-overlay ───────────────────────────────────────────────────────

(test show-built-overlay-renders-body-to-overlay
  "show-built-overlay shows an overlay whose text is built by writing to STREAM."
  (with-fake-session (s)
    (let ((*overlay* nil))
      (cl-tmux::show-built-overlay (out)
        (write-string "dispatch-test-sentinel" out))
      (is (overlay-active-p) "show-built-overlay must activate an overlay")
      (is (search "dispatch-test-sentinel" *overlay*)
          "show-built-overlay must use the STREAM body text"))))

;;; ── %active-window-pane ──────────────────────────────────────────────────────

(test active-window-pane-returns-window-and-pane
  "%active-window-pane returns the active window and its active pane as two values."
  (with-fake-session (s :nwindows 1 :npanes 1)
    (multiple-value-bind (win pane) (cl-tmux::%active-window-pane s)
      (is (eq (session-active-window s) win)
          "%active-window-pane first value must be the active window")
      (is (eq (window-active-pane win) pane)
          "%active-window-pane second value must be the active pane"))))

(test active-window-pane-returns-nil-nil-for-windowless-session
  "%active-window-pane returns NIL, NIL when the session has no windows."
  (with-fake-session (s :nwindows 0)
    (multiple-value-bind (win pane) (cl-tmux::%active-window-pane s)
      (is (null win)  "%active-window-pane window must be NIL for empty session")
      (is (null pane) "%active-window-pane pane must be NIL for empty session"))))

;;; ── with-active-window macro ─────────────────────────────────────────────────

(test with-active-window-evaluates-body-with-active-window
  "with-active-window evaluates BODY binding WIN-VAR to the active window."
  (with-fake-session (s :nwindows 1)
    (let ((win-seen nil))
      (cl-tmux::with-active-window (w s)
        (setf win-seen w))
      (is (eq (session-active-window s) win-seen)
          "with-active-window must bind the active window"))))

(test with-active-window-returns-nil-for-empty-session
  "with-active-window evaluates to NIL when no active window exists."
  (with-fake-session (s :nwindows 0)
    (let ((body-ran nil))
      (is (null (cl-tmux::with-active-window (w s)
                  (setf body-ran t)
                  w))
          "with-active-window on empty session must return NIL")
      (is-false body-ran
                "with-active-window must not evaluate BODY when there is no window"))))

;;; ── %session-of-window and %session-of-pane ─────────────────────────────────

(test session-of-window-returns-owning-session
  "%session-of-window returns the session whose window list contains WIN."
  (with-fake-session (s :nwindows 1)
    (with-command-test-state (s)
      (let ((win (session-active-window s)))
        (is (eq s (cl-tmux::%session-of-window win))
            "%session-of-window must return the owning session")))))

(test session-of-window-returns-nil-when-not-found
  "%session-of-window returns NIL for a window not in any registered session."
  (with-fake-session (s :nwindows 1)
    (let ((orphan (make-fake-window 99 "orphan")))
      (let ((cl-tmux::*server-sessions* (list (cons "0" s))))
        (is (null (cl-tmux::%session-of-window orphan))
            "%session-of-window must return NIL for an unregistered window")))))

(test session-of-pane-returns-owning-session
  "%session-of-pane returns the session one of whose windows contains PANE."
  (with-fake-session (s :nwindows 1)
    (with-command-test-state (s)
      (let ((pane (session-active-pane s)))
        (is (eq s (cl-tmux::%session-of-pane pane))
            "%session-of-pane must return the owning session")))))

(test session-of-pane-returns-nil-for-nil
  "%session-of-pane returns NIL when PANE is NIL."
  (is (null (cl-tmux::%session-of-pane nil))
      "%session-of-pane must return NIL for NIL input"))

;;; ── run-command-hooks ────────────────────────────────────────────────────────

(test run-command-hooks-fires-for-session-target
  "run-command-hooks dispatches the registered command hook for a session target.
   run-command-hooks consults cl-tmux/hooks:*command-hooks* (populated by
   set-command-hook / the set-hook config directive), not the lisp-callback
   registry that add-hook populates — that registry is fired by run-hooks."
  (with-isolated-hooks
    (with-fake-session (s :nwindows 1)
      (with-command-test-state (s :overlay t)
        (cl-tmux/hooks:set-command-hook "after-new-window" :list-windows)
        (cl-tmux::run-command-hooks "after-new-window" s)
        (assert-overlay-active
         "run-command-hooks must dispatch the registered command hook")))))

(test run-command-hooks-noop-for-nil-target
  "run-command-hooks is a no-op when TARGET is NIL (no session to dispatch against)."
  (with-isolated-hooks
    (with-fake-session (s :nwindows 1)
      (with-command-test-state (s :overlay t)
        (cl-tmux/hooks:set-command-hook "after-new-window" :list-windows)
        (finishes (cl-tmux::run-command-hooks "after-new-window" nil)
                  "run-command-hooks with NIL target must not signal")
        (is-false (overlay-active-p)
                  "run-command-hooks with NIL target must not dispatch any hook")))))

;;; ── *command-dispatch-table* ─────────────────────────────────────────────────

(test command-dispatch-table-is-hash-table
  "*command-dispatch-table* is a hash-table mapping keywords to handler functions."
  (is (hash-table-p cl-tmux::*command-dispatch-table*)
      "*command-dispatch-table* must be a hash-table")
  (is (functionp (gethash :detach cl-tmux::*command-dispatch-table*))
      ":detach must be a registered handler function")
  (is (functionp (gethash :next-window cl-tmux::*command-dispatch-table*))
      ":next-window must be a registered handler function"))

;;; ── define-command-handlers macro ────────────────────────────────────────────

(test define-command-handlers-registers-into-dispatch-table
  "define-command-handlers populates *command-dispatch-table* for new keywords."
  ;; Use a unique test keyword that won't collide with real handlers.
  (let ((orig (gethash :test-dispatch-sentinel cl-tmux::*command-dispatch-table*)))
    (unwind-protect
         (progn
           (cl-tmux::define-command-handlers
             (:test-dispatch-sentinel (+ 1 2)))
           (is (functionp (gethash :test-dispatch-sentinel
                                   cl-tmux::*command-dispatch-table*))
               "define-command-handlers must register a handler function"))
      (if orig
          (setf (gethash :test-dispatch-sentinel cl-tmux::*command-dispatch-table*) orig)
          (remhash :test-dispatch-sentinel cl-tmux::*command-dispatch-table*)))))

;;; ── define-copy-mode-dispatch-handlers macro ─────────────────────────────────

(test define-copy-mode-dispatch-handlers-macro-is-defined
  "define-copy-mode-dispatch-handlers is a defined macro."
  (is (macro-function 'cl-tmux::define-copy-mode-dispatch-handlers)
      "define-copy-mode-dispatch-handlers must be a macro"))

;;; ── define-directional-handlers macro ────────────────────────────────────────

(test define-directional-handlers-macro-is-defined
  "define-directional-handlers is a defined macro."
  (is (macro-function 'cl-tmux::define-directional-handlers)
      "define-directional-handlers must be a macro"))

(test define-directional-handlers-registers-into-dispatch-table
  "define-directional-handlers registers one handler per (keyword direction)
   entry, each calling (helper-fn session direction)."
  (let ((calls nil))
    (cl-tmux::define-directional-handlers
        (lambda (session direction) (push (cons session direction) calls))
      (:test-directional-sentinel-a :left)
      (:test-directional-sentinel-b :right))
    (unwind-protect
         (progn
           (is (functionp (gethash :test-directional-sentinel-a
                                   cl-tmux::*command-dispatch-table*))
               "define-directional-handlers must register :test-directional-sentinel-a")
           (with-fake-session (s)
             (cl-tmux::dispatch-command s :test-directional-sentinel-a nil)
             (is (equal (cons s :left) (first calls))
                 "the generated handler must call helper-fn with session and direction")
             (cl-tmux::dispatch-command s :test-directional-sentinel-b nil)
             (is (equal (cons s :right) (first calls))
                 "each entry must thread its own direction keyword")))
      (remhash :test-directional-sentinel-a cl-tmux::*command-dispatch-table*)
      (remhash :test-directional-sentinel-b cl-tmux::*command-dispatch-table*))))

;;; ── %resize-active-window-pane ───────────────────────────────────────────────

(test resize-active-window-pane-resizes-active-window
  "%resize-active-window-pane resizes the active pane of SESSION's active
   window via dispatch-command's :resize-* handlers."
  (with-fake-session (s :nwindows 1)
    (finishes (cl-tmux::dispatch-command s :resize-left nil))
    (finishes (cl-tmux::dispatch-command s :resize-right nil))
    (finishes (cl-tmux::dispatch-command s :resize-up nil))
    (finishes (cl-tmux::dispatch-command s :resize-down nil))))

;;; ── %copy-mode-call-with-null-arg ────────────────────────────────────────────

(test copy-mode-call-with-null-arg-calls-fn-with-null
  "%copy-mode-call-with-null-arg calls FN with SESSION and NIL when an active screen exists."
  (with-fake-session (s)
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (let ((received-arg :unset))
      (cl-tmux::%copy-mode-call-with-null-arg
       s
       (lambda (screen null-arg)
         (declare (ignore screen))
         (setf received-arg null-arg)))
      (is (null received-arg)
          "%copy-mode-call-with-null-arg must pass NIL as the trailing arg"))))

;;; ── define-show-options-handler macro ────────────────────────────────────────

(test define-show-options-handler-macro-is-defined
  "define-show-options-handler is a defined macro."
  (is (macro-function 'cl-tmux::define-show-options-handler)
      "define-show-options-handler must be a macro"))

(test show-session-options-renders-overlay
  "%show-session-options (generated by define-show-options-handler) shows an overlay
   with '# session options' header."
  (with-fake-session (s)
    (let ((*overlay* nil))
      (cl-tmux::%show-session-options)
      (is (overlay-active-p) "%show-session-options must open an overlay")
      (is (search "session" *overlay*)
          "%show-session-options overlay must reference 'session' scope"))))

(test show-server-options-renders-overlay
  "%show-server-options (generated by define-show-options-handler with :server scope)
   shows an overlay with 'server' in it."
  (with-fake-session (s)
    (let ((*overlay* nil))
      (cl-tmux::%show-server-options)
      (is (overlay-active-p) "%show-server-options must open an overlay")
      (is (search "server" *overlay*)
          "%show-server-options overlay must reference 'server' scope"))))

;;; ── %with-window-focus-transition macro ──────────────────────────────────────

(test with-window-focus-transition-fires-hooks-on-window-change
  "%with-window-focus-transition fires the session-window-changed hook when
   the active window changes inside BODY."
  (with-isolated-hooks
    (let* ((s (make-fake-session :nwindows 2))
           (fired nil))
      (with-command-test-state (s)
        (cl-tmux/hooks:add-hook
         cl-tmux/hooks:+hook-session-window-changed+
         (lambda (&rest _) (declare (ignore _)) (setf fired t)))
        (cl-tmux::%with-window-focus-transition (s)
          (session-select-window s (second (session-windows s))))
        (is-true fired
                 "%with-window-focus-transition must fire session-window-changed when window changes")))))

(test with-window-focus-transition-no-hook-when-window-unchanged
  "%with-window-focus-transition does not fire session-window-changed when
   BODY leaves the active window the same."
  (with-isolated-hooks
    (let* ((s (make-fake-session :nwindows 2))
           (fired nil))
      (with-command-test-state (s)
        (cl-tmux/hooks:add-hook
         cl-tmux/hooks:+hook-session-window-changed+
         (lambda (&rest _) (declare (ignore _)) (setf fired t)))
        (cl-tmux::%with-window-focus-transition (s)
          ;; BODY makes no change — same active window.
          (values))
        (is-false fired
                  "%with-window-focus-transition must NOT fire hook when window is unchanged")))))

;;; ── %compute-window-base-index table-driven ──────────────────────────────────

(test compute-window-base-index-table-driven
  "%compute-window-base-index dispatch: :at-index, :after-current, :before-current,
   and the no-flags fallback each return the correct value."
  (with-fake-session (s :nwindows 1)
    (let* ((win (session-active-window s))
           (wid (cl-tmux/model:window-id win)))
      (check-table
       (list
        (list (cl-tmux::%compute-window-base-index win :at-index 7)
              7
              ":at-index 7 must return 7")
        (list (cl-tmux::%compute-window-base-index win :after-current t)
              (1+ wid)
              ":after-current must return wid+1")
        (list (cl-tmux::%compute-window-base-index win :before-current t)
              wid
              ":before-current must return wid")
        (list (cl-tmux::%compute-window-base-index win)
              (or (cl-tmux/options:get-option "base-index") 0)
              "no flags must return base-index option value (default 0)"))
       :test #'=))))

;;; ── next-cyclic / prev-cyclic table-driven ───────────────────────────────────

(test cyclic-navigators-table-driven
  "next-cyclic and prev-cyclic both follow modular-arithmetic stepping, and
   next-cyclic falls back to index 0 when CURRENT is not found in the list."
  (check-table
   (list
    (list (cl-tmux::next-cyclic '(a b c) 'a) 'b "next from a → b")
    (list (cl-tmux::next-cyclic '(a b c) 'c) 'a "next from c wraps to a")
    (list (cl-tmux::next-cyclic '(a b c) 'missing) 'b
          "next from an unknown element falls back to index 0 -> element 1")
    (list (cl-tmux::prev-cyclic '(a b c) 'b) 'a "prev from b → a")
    (list (cl-tmux::prev-cyclic '(a b c) 'a) 'c "prev from a wraps to c"))
   :test #'eql))

;;; ── %resolve-target-window-pane ──────────────────────────────────────────────

(test resolve-target-window-pane-returns-current-when-target-str-nil
  "%resolve-target-window-pane returns CURRENT-WINDOW/CURRENT-PANE unchanged
   when TARGET-STR is absent."
  (with-fake-session (s :nwindows 2 :npanes 1)
    (let* ((win  (first (session-windows s)))
           (pane (window-active-pane win)))
      (multiple-value-bind (rwin rpane)
          (cl-tmux::%resolve-target-window-pane s nil win pane)
        (is (eq win rwin)
            "%resolve-target-window-pane with NIL target-str must return current-window")
        (is (eq pane rpane)
            "%resolve-target-window-pane with NIL target-str must return current-pane")))))

(test resolve-target-window-pane-resolves-window-and-its-active-pane
  "%resolve-target-window-pane, given a target-str naming another window (but
   no pane component), returns that window and its own active pane."
  (with-fake-session (s :nwindows 2 :npanes 1)
    (with-command-test-state (s)
      (let* ((cur-win  (first (session-windows s)))
             (cur-pane (window-active-pane cur-win))
             (tgt-win  (second (session-windows s)))
             (tgt-pane (window-active-pane tgt-win))
             (tgt-str  (format nil "@~A" (cl-tmux/model:window-id tgt-win))))
        (multiple-value-bind (rwin rpane)
            (cl-tmux::%resolve-target-window-pane s tgt-str cur-win cur-pane)
          (is (eq tgt-win rwin)
              "%resolve-target-window-pane must resolve the target window")
          (is (eq tgt-pane rpane)
              "%resolve-target-window-pane must default to the target window's active pane"))))))

(test resolve-target-window-pane-falls-back-to-active-window-for-unresolvable-target
  "%resolve-target-window-pane, given a TARGET-STR that names no existing
   window (e.g. a stale window id), falls back to SESSION's active window
   and pane rather than returning NIL (resolve-target's window clause always
   defaults to session-active-window when the lookup itself fails)."
  (with-fake-session (s :nwindows 1 :npanes 1)
    (with-command-test-state (s)
      (let* ((cur-win  (session-active-window s))
             (cur-pane (window-active-pane cur-win)))
        (multiple-value-bind (rwin rpane)
            (cl-tmux::%resolve-target-window-pane s "@999" cur-win cur-pane)
          (is (eq cur-win rwin)
              "%resolve-target-window-pane must fall back to the active window for an unresolvable target")
          (is (eq cur-pane rpane)
              "%resolve-target-window-pane must fall back to the active pane for an unresolvable target"))))))

;;; ── %resolve-target-session-window ───────────────────────────────────────────

(test resolve-target-session-window-returns-current-when-target-str-nil
  "%resolve-target-session-window returns SESSION/CURRENT-WINDOW unchanged
   when TARGET-STR is absent."
  (with-fake-session (s :nwindows 1)
    (let ((win (session-active-window s)))
      (multiple-value-bind (rsess rwin)
          (cl-tmux::%resolve-target-session-window s nil win nil)
        (is (eq s rsess)
            "%resolve-target-session-window with NIL target-str must return SESSION")
        (is (eq win rwin)
            "%resolve-target-session-window with NIL target-str must return CURRENT-WINDOW")))))

(test resolve-target-session-window-resolves-window-in-same-session
  "%resolve-target-session-window, given a target-str naming another window in
   the same session, returns that session and window."
  (with-fake-session (s :nwindows 2)
    (with-command-test-state (s)
      (let* ((cur-win (first (session-windows s)))
             (tgt-win (second (session-windows s)))
             (tgt-str (format nil "@~A" (cl-tmux/model:window-id tgt-win))))
        (multiple-value-bind (rsess rwin)
            (cl-tmux::%resolve-target-session-window s tgt-str cur-win nil)
          (is (eq s rsess)
              "%resolve-target-session-window must resolve to the owning session")
          (is (eq tgt-win rwin)
              "%resolve-target-session-window must resolve the target window"))))))

(test resolve-target-session-window-falls-back-to-active-window-for-unresolvable-target
  "%resolve-target-session-window, given a TARGET-STR that names no existing
   window, falls back to SESSION and its active window rather than returning
   NIL (mirrors resolve-target's unconditional session-active-window fallback)."
  (with-fake-session (s :nwindows 1)
    (with-command-test-state (s)
      (let ((cur-win (session-active-window s)))
        (multiple-value-bind (rsess rwin)
            (cl-tmux::%resolve-target-session-window s "@999" cur-win nil)
          (is (eq s rsess)
              "%resolve-target-session-window must fall back to SESSION for an unresolvable target")
          (is (eq cur-win rwin)
              "%resolve-target-session-window must fall back to the active window for an unresolvable target"))))))

;;; ── %resolve-window-target-or-active ─────────────────────────────────────────

(test resolve-window-target-or-active-falls-back-to-active-window
  "%resolve-window-target-or-active returns SESSION's active window when
   TARGET-STR is NIL."
  (with-fake-session (s :nwindows 1)
    (is (eq (session-active-window s)
            (cl-tmux::%resolve-window-target-or-active s nil))
        "%resolve-window-target-or-active with NIL target-str must return the active window")))

(test resolve-window-target-or-active-resolves-named-target
  "%resolve-window-target-or-active resolves TARGET-STR to a non-active window
   when it names one."
  (with-fake-session (s :nwindows 2)
    (let* ((tgt-win (second (session-windows s)))
           (tgt-str (format nil "~A" (cl-tmux/model:window-id tgt-win))))
      (is (eq tgt-win (cl-tmux::%resolve-window-target-or-active s tgt-str))
          "%resolve-window-target-or-active must resolve a valid target-str to that window"))))

;;; ── with-target-session macro ────────────────────────────────────────────────

(test with-target-session-runs-body-with-session-when-target-str-nil
  "with-target-session binds TARGET-SESSION to SESSION and runs BODY when
   TARGET-STR is NIL."
  (with-fake-session (s)
    (is (eq s (cl-tmux::with-target-session (ts nil s) ts))
        "with-target-session with NIL target-str must bind TARGET-SESSION to SESSION")))

(test with-target-session-resolves-named-target
  "with-target-session binds TARGET-SESSION to the resolved session when
   TARGET-STR names one registered in *server-sessions*."
  (let* ((s1 (make-fake-session))
         (s2 (make-fake-session)))
    (setf (cl-tmux::session-name s1) "alpha"
          (cl-tmux::session-name s2) "beta")
    (let ((cl-tmux::*server-sessions* (list (cons "alpha" s1) (cons "beta" s2))))
      (is (eq s2 (cl-tmux::with-target-session (ts "beta" s1) ts))
          "with-target-session must resolve TARGET-STR to the named session"))))

(test with-target-session-on-missing-skip-returns-nil-without-running-body
  "with-target-session with the default :skip ON-MISSING does not run BODY when
   TARGET-STR fails to resolve."
  (with-fake-session (s)
    (let ((cl-tmux::*server-sessions* (list (cons "0" s)))
          (body-ran nil))
      (is (null (cl-tmux::with-target-session (ts "no-such-session" s)
                  (setf body-ran t)
                  ts))
          "with-target-session must return NIL when the target is unresolved and ON-MISSING is :skip")
      (is-false body-ran
                "with-target-session must not run BODY when the target is unresolved and ON-MISSING is :skip"))))

(test with-target-session-on-missing-current-runs-body-with-session
  "with-target-session with ON-MISSING :current runs BODY against SESSION even
   when TARGET-STR fails to resolve."
  (with-fake-session (s)
    (let ((cl-tmux::*server-sessions* (list (cons "0" s))))
      (is (eq s (cl-tmux::with-target-session (ts "no-such-session" s
                                               :on-missing :current)
                  ts))
          "with-target-session with ON-MISSING :current must run BODY with TARGET-SESSION bound to SESSION"))))

(test with-target-session-on-missing-error-shows-message-and-returns-nil
  "with-target-session with ON-MISSING :error shows the MESSAGE overlay
   (formatted with TARGET-STR) and returns NIL without running BODY."
  (with-fake-session (s)
    (with-command-test-state (s :overlay t)
      (let ((body-ran nil))
        (is (null (cl-tmux::with-target-session (ts "no-such-session" s
                                                 :message "no session: ~A"
                                                 :on-missing :error)
                    (setf body-ran t)
                    ts))
            "with-target-session with ON-MISSING :error must return NIL")
        (is-false body-ran
                  "with-target-session with ON-MISSING :error must not run BODY")
        (is (search "no-such-session" *overlay*)
            "with-target-session with ON-MISSING :error must format TARGET-STR into MESSAGE")))))

;;; ── with-target-context macro ────────────────────────────────────────────────

(test with-target-context-defaults-to-current-session-window-pane
  "with-target-context binds TARGET-SESSION/WINDOW/PANE to SESSION's current
   window and pane when TARGET-STR is NIL."
  (with-fake-session (s :nwindows 1 :npanes 1)
    (with-command-test-state (s)
      (multiple-value-bind (ts tw tp)
          (cl-tmux::with-target-context (ts tw tp s nil)
            (values ts tw tp))
        (is (eq s ts) "with-target-context must default TARGET-SESSION to SESSION")
        (is (eq (session-active-window s) tw)
            "with-target-context must default TARGET-WINDOW to the active window")
        (is (eq (window-active-pane tw) tp)
            "with-target-context must default TARGET-PANE to the active pane")))))

(test with-target-context-resolves-named-window-target
  "with-target-context resolves TARGET-STR naming another window in SESSION to
   that window; since TARGET-STR carries no pane component, TARGET-PANE
   defaults to SESSION's (not the target window's) currently active pane."
  (with-fake-session (s :nwindows 2 :npanes 1)
    (with-command-test-state (s)
      (let* ((cur-pane (session-active-pane s))
             (tgt-win  (second (session-windows s)))
             (tgt-str  (format nil "@~A" (cl-tmux/model:window-id tgt-win))))
        (multiple-value-bind (ts tw tp)
            (cl-tmux::with-target-context (ts tw tp s tgt-str)
              (values ts tw tp))
          (is (eq s ts) "with-target-context must resolve TARGET-SESSION to the owning session")
          (is (eq tgt-win tw) "with-target-context must resolve TARGET-WINDOW to the named window")
          (is (eq cur-pane tp)
              "with-target-context must default TARGET-PANE to SESSION's active pane when TARGET-STR has no pane component"))))))
