(in-package #:cl-tmux/test)

(in-suite layout-tree-suite)

;;; ── layout-leaves and define-layout-visitor edge cases ──────────────────────

(test layout-leaves-nil-tree-returns-empty-list
  "layout-leaves on a NIL node (empty window tree) returns NIL."
  (is (null (layout-leaves nil))
      "layout-leaves NIL must return NIL"))

(test layout-leaves-single-leaf-returns-one-pane
  "layout-leaves on a bare leaf returns a list of exactly that leaf's pane."
  (let* ((leaf (tl-leaf 1 10 5))
         (pane (layout-leaf-pane leaf)))
    (is (equal (list pane) (layout-leaves leaf))
        "single leaf must yield (list pane)")))

;; axis-floor is tested in layout-geometry-tests.lisp (axis-floor-returns-correct-minimum).

(test direct-child-side-identifies-first-and-second
  "%direct-child-side returns (split :first) or (split :second) for direct children
   and (NIL NIL) for unrelated nodes."
  (let* ((l0    (tl-leaf 1 1 1))
         (l1    (tl-leaf 2 1 1))
         (split (make-layout-split :h l0 l1)))
    (multiple-value-bind (p s) (cl-tmux/model::%direct-child-side split l0)
      (is (eq split p) "parent must be the split")
      (is (eq :first s) "first child -> :first"))
    (multiple-value-bind (p s) (cl-tmux/model::%direct-child-side split l1)
      (is (eq split p))
      (is (eq :second s) "second child -> :second"))
    (multiple-value-bind (p s) (cl-tmux/model::%direct-child-side split (tl-leaf 99 1 1))
      (is (null p) "non-child -> NIL parent")
      (is (null s) "non-child -> NIL side"))))

(test layout-find-parent-returns-nil-for-nil-node
  "layout-find-parent on a NIL node returns (values NIL NIL)."
  (multiple-value-bind (p s) (layout-find-parent nil (tl-leaf 1 1 1))
    (is (null p) "nil node must return nil parent")
    (is (null s) "nil node must return nil side")))

(test define-layout-visitor-macro-generates-correct-visitor
  "define-layout-visitor generates a function with the declared null/leaf/split clauses.
   The layout-leaves function (generated by the macro) covers all three cases."
  ;; Nil case
  (is (null (layout-leaves nil)) "nil -> empty list")
  ;; Leaf case
  (let ((leaf (tl-leaf 42 1 1)))
    (is (equal (list (layout-leaf-pane leaf)) (layout-leaves leaf))
        "leaf -> (list pane)"))
  ;; Split case -- verify both subtrees are collected
  (let* ((l0   (tl-leaf 1 1 1))
         (l1   (tl-leaf 2 1 1))
         (tree (make-layout-split :h l0 l1)))
    (is (= 2 (length (layout-leaves tree)))
        "split -> both children collected")))

(test define-layout-fold-macro-is-defined
  "define-layout-fold generates multi-argument recursive tree functions.
   Tested via layout-find-leaf and layout-min-extent, both generated by the macro."
  ;; layout-find-leaf: fold with extra pane arg
  (let* ((l0   (tl-leaf 1 1 1))
         (l1   (tl-leaf 2 1 1))
         (tree (make-layout-split :h l0 l1))
         (p0   (layout-leaf-pane l0)))
    (is (eq l0 (layout-find-leaf tree p0))  "fold finds pane in subtree")
    (is (null (layout-find-leaf tree (make-pane :id 99 :fd -1 :pid -1
                                                :screen (make-screen 1 1))))
        "fold returns NIL for pane not in tree"))
  ;; layout-min-extent: fold with extra orient arg -- nil case returns 0
  (is (= 0 (cl-tmux/model::layout-min-extent nil :h))
      "nil node returns 0 extent")
  (is (= 0 (cl-tmux/model::layout-min-extent nil :v))
      "nil node returns 0 extent for :v"))

