(in-package #:cl-tmux/test)

(describe "layout-tree-suite"

  ;;; ── layout-leaves and define-layout-visitor edge cases ──────────────────────

  ;; layout-leaves on a NIL node (empty window tree) returns NIL.
  (it "layout-leaves-nil-tree-returns-empty-list"
    (expect (null (layout-leaves nil))))

  ;; layout-leaves on a bare leaf returns a list of exactly that leaf's pane.
  (it "layout-leaves-single-leaf-returns-one-pane"
    (let* ((leaf (tl-leaf 1 10 5))
           (pane (layout-leaf-pane leaf)))
      (expect (equal (list pane) (layout-leaves leaf)))))

  ;; axis-floor is tested in layout-geometry-tests.lisp (axis-floor-returns-correct-minimum).

  ;; %direct-child-side returns (split :first) or (split :second) for direct children
  ;; and (NIL NIL) for unrelated nodes.
  (it "direct-child-side-identifies-first-and-second"
    (let* ((l0    (tl-leaf 1 1 1))
           (l1    (tl-leaf 2 1 1))
           (split (make-layout-split :h l0 l1)))
      (multiple-value-bind (p s) (cl-tmux/model::%direct-child-side split l0)
        (expect (eq split p))
        (expect (eq :first s)))
      (multiple-value-bind (p s) (cl-tmux/model::%direct-child-side split l1)
        (expect (eq split p))
        (expect (eq :second s)))
      (multiple-value-bind (p s) (cl-tmux/model::%direct-child-side split (tl-leaf 99 1 1))
        (expect (null p))
        (expect (null s)))))

  ;; layout-find-parent on a NIL node returns (values NIL NIL).
  (it "layout-find-parent-returns-nil-for-nil-node"
    (multiple-value-bind (p s) (layout-find-parent nil (tl-leaf 1 1 1))
      (expect (null p))
      (expect (null s))))

  ;; define-layout-visitor generates a function with the declared null/leaf/split clauses.
  ;; The layout-leaves function (generated by the macro) covers all three cases.
  (it "define-layout-visitor-macro-generates-correct-visitor"
    ;; Nil case
    (expect (null (layout-leaves nil)))
    ;; Leaf case
    (let ((leaf (tl-leaf 42 1 1)))
      (expect (equal (list (layout-leaf-pane leaf)) (layout-leaves leaf))))
    ;; Split case -- verify both subtrees are collected
    (let* ((l0   (tl-leaf 1 1 1))
           (l1   (tl-leaf 2 1 1))
           (tree (make-layout-split :h l0 l1)))
      (expect (= 2 (length (layout-leaves tree))))))

  ;; define-layout-fold generates multi-argument recursive tree functions.
  ;; Tested via layout-find-leaf and layout-min-extent, both generated by the macro.
  (it "define-layout-fold-macro-is-defined"
    ;; layout-find-leaf: fold with extra pane arg
    (let* ((l0   (tl-leaf 1 1 1))
           (l1   (tl-leaf 2 1 1))
           (tree (make-layout-split :h l0 l1))
           (p0   (layout-leaf-pane l0)))
      (expect (eq l0 (layout-find-leaf tree p0)))
      (expect (null (layout-find-leaf tree (make-pane :id 99 :fd -1 :pid -1
                                                  :screen (make-screen 1 1))))))
    ;; layout-min-extent: fold with extra orient arg -- nil case returns 0
    (expect (= 0 (cl-tmux/model::layout-min-extent nil :h)))
    (expect (= 0 (cl-tmux/model::layout-min-extent nil :v)))))
