(in-package #:cl-tmux)

;;;; VT100 / mouse / CSI byte constants used by the keystroke and event pipeline.
;;;;
;;;; Extracted here as pure data so events-core.lisp and all later event files
;;;; can reference named constants without mixing data into dispatch logic.

;;; ── VT100 escape-sequence byte constants ───────────────────────────────────
(defconstant +byte-esc+         27  "ASCII ESC (0x1B)")
(defconstant +byte-csi-bracket+ 91  "CSI introducer '[' (0x5B)")
(defconstant +byte-arrow-up+    65  "CUU final byte 'A' (0x41)")
(defconstant +byte-arrow-down+  66  "CUD final byte 'B' (0x42)")
(defconstant +byte-arrow-left+  68  "CUB final byte 'D'")
(defconstant +byte-arrow-right+ 67  "CUF final byte 'C'")
(defconstant +byte-q+          113  "Lowercase 'q' for copy-mode exit (0x71)")
(defconstant +byte-j+          106  "Lowercase 'j' — vi down / overlay scroll-down (0x6A)")
(defconstant +byte-k+          107  "Lowercase 'k' — vi up / overlay scroll-up (0x6B)")

;;; ── Additional copy-mode navigation byte constants ──────────────────────────
;;; Named for every raw byte used in the copy-mode dispatch table so that readers
;;; can audit the mapping without cross-referencing ASCII tables.
(defconstant +byte-h+          104  "Lowercase 'h' — vi left (0x68)")
(defconstant +byte-l+          108  "Lowercase 'l' — vi right (0x6C)")
(defconstant +byte-w+          119  "Lowercase 'w' — vi word-forward (0x77)")
(defconstant +byte-b+           98  "Lowercase 'b' — vi word-backward (0x62)")
(defconstant +byte-e+          101  "Lowercase 'e' — vi word-end (0x65)")
(defconstant +byte-f+          102  "Lowercase 'f' — vi jump-forward-to-char (0x66)")
(defconstant +byte-g+          103  "Lowercase 'g' — vi jump-to-top (0x67)")
(defconstant +byte-i+          105  "Lowercase 'i' — exit copy mode (insert, 0x69)")
(defconstant +byte-n+          110  "Lowercase 'n' — search next (0x6E)")
(defconstant +byte-r+          114  "Lowercase 'r' — rectangle select toggle (0x72)")
(defconstant +byte-t+          116  "Lowercase 't' — vi jump-to-before-char (0x74)")
(defconstant +byte-v+          118  "Lowercase 'v' — begin selection (0x76)")
(defconstant +byte-y+          121  "Lowercase 'y' — yank/copy (0x79)")
(defconstant +byte-capital-a+   65  "Uppercase 'A' — append selection (0x41)")
(defconstant +byte-capital-d+   68  "Uppercase 'D' — copy to end of line (0x44)")
(defconstant +byte-capital-f+   70  "Uppercase 'F' — vi jump-backward-to-char (0x46)")
(defconstant +byte-capital-g+   71  "Uppercase 'G' — jump to bottom (0x47)")
(defconstant +byte-capital-h+   72  "Uppercase 'H' — cursor to top of screen (0x48)")
(defconstant +byte-capital-l+   76  "Uppercase 'L' — cursor to bottom of screen (0x4C)")
(defconstant +byte-capital-m+   77  "Uppercase 'M' — cursor to middle of screen (0x4D)")
(defconstant +byte-capital-n+   78  "Uppercase 'N' — search prev (0x4E)")
(defconstant +byte-capital-t+   84  "Uppercase 'T' — vi jump-to-after-prev-char (0x54)")
(defconstant +byte-capital-v+   86  "Uppercase 'V' — begin line selection (0x56)")
(defconstant +byte-capital-y+   89  "Uppercase 'Y' — copy current line (0x59)")
(defconstant +byte-dollar+      36  "Dollar sign '$' — go to line end (0x24)")
(defconstant +byte-slash+       47  "Slash '/' — search forward (0x2F)")
(defconstant +byte-question+    63  "Question mark '?' — search backward (0x3F)")
(defconstant +byte-space+       32  "Space ' ' — begin selection (0x20)")

;;; ── CSI modifier-sequence byte constants ────────────────────────────────────
;;; These appear in ESC [ 1 ; MOD FINAL sequences generated by terminal emulators
;;; for Ctrl-arrow and Meta-arrow key combinations.
(defconstant +byte-csi-param-1+  49  "CSI intermediate parameter '1' (0x31)")
(defconstant +byte-csi-semi+     59  "CSI parameter separator ';' (0x3B)")
(defconstant +byte-csi-mod-ctrl+ 53  "CSI modifier '5' — Ctrl key (0x35)")
(defconstant +byte-csi-mod-meta+ 51  "CSI modifier '3' — Meta/Alt key (0x33)")
(defconstant +byte-tilde+       126  "VT function-key terminator '~' (0x7E)")
(defconstant +byte-sgr-lt+       60  "SGR mouse introducer '<' (0x3C)")
(defconstant +byte-digit-0+      48  "ASCII digit '0' (0x30)")
(defconstant +byte-digit-9+      57  "ASCII digit '9' (0x39)")

;;; ── Function-key parameter constants ────────────────────────────────────────
;;; NOTE: +byte-page-up-param+ (53) has the same numeric value as
;;; +byte-csi-mod-ctrl+ (53) — they are semantically distinct: the former is the
;;; literal digit '5' in ESC [ 5 ~, the latter is the modifier byte in ESC [ 1 ; 5 F.
;;; Both constants are kept to make code at their respective call sites self-documenting.
(defconstant +byte-page-up-param+   53  "ESC [ 5 ~ PageUp parameter byte '5' (0x35)")
(defconstant +byte-page-down-param+ 54  "ESC [ 6 ~ PageDown parameter byte '6' (0x36)")

;;; ── SS3 introducer ──────────────────────────────────────────────────────────
;;; ESC O <final> is the SS3 form xterm/screen/tmux terminals use for F1-F4
;;; (ESC O P/Q/R/S) and Home/End (ESC O H/F).  It collides with Alt+O (a 2-byte
;;; meta chord ESC O), so the decoder defers one byte after ESC O and lets
;;; escape-time disambiguate — exactly as physical terminals do.
(defconstant +byte-ss3-o+ 79 "ESC O SS3 introducer, ASCII 'O' (0x4F).")

;;; ── Mouse button-number constants ───────────────────────────────────────────
;;; These are X10-encoded button numbers (raw byte minus 32).
(defconstant +mouse-btn-left+          0  "Left mouse button press (X10 btn 0).")
(defconstant +mouse-btn-middle+        1  "Middle mouse button press (X10 btn 1) — paste.")
(defconstant +mouse-btn-release-x10+   3  "X10 release marker (btn 3+32=35).")
(defconstant +mouse-btn-motion+       32  "Button-1 drag/motion (X10 btn 32).")
(defconstant +mouse-btn-scroll-up+    64  "Scroll-wheel up (X10 btn 64).")
(defconstant +mouse-btn-scroll-down+  65  "Scroll-wheel down (X10 btn 65).")

;;; ── SGR mouse final-byte constants ──────────────────────────────────────────
;;; ASCII 'M' (77) is used as both the X10 mouse-sequence intro final byte and the
;;; SGR press final byte.  A single constant covers both roles; the old duplicate
;;; +byte-sgr-press+ has been removed.
(defconstant +byte-ascii-m+     77  "ASCII 'M' (0x4D) — X10 mouse intro and SGR press final.")
(defconstant +byte-sgr-release+ 109 "ASCII 'm' (0x6D) — SGR mouse release final byte.")
(defconstant +byte-ascii-u+    117 "ASCII 'u' (0x75) — CSI-u (fixterms extended-keys) final byte.")
(defconstant +byte-focus-in+    73 "ASCII 'I' (0x49) — ESC [ I focus-gained report (?1004).")
(defconstant +byte-focus-out+   79 "ASCII 'O' (0x4F) — ESC [ O focus-lost report (?1004).")

;;; ── Printable ASCII graphic range constants ──────────────────────────────────
;;; These bounds are used in CSI-u and meta-key decoding guards to delimit the
;;; printable ASCII range.  Named here so the intent of range checks is explicit
;;; rather than encoded as magic literals.
(defconstant +byte-first-graphic+ 33
  "ASCII '!' — the first printable non-space graphic character (0x21).
   Used as the lower bound of the CSI-u printable codepoint range.")
(defconstant +byte-last-graphic+  126
  "ASCII '~' — the last printable ASCII character before DEL (0x7E).
   Used as the upper bound of the CSI-u printable codepoint range.")
(defconstant +byte-del+           127
  "ASCII DEL (0x7F).  Excluded from meta-key decoding since it is
   mapped as a named key (BSpace) rather than a printable chord target.")

;;; ── Ctrl-letter escape offset ────────────────────────────────────────────────
;;; The canonical transformation from a raw Ctrl byte (1–26) to its uppercase
;;; ASCII letter (A–Z) is byte+64.  This constant documents the arithmetic.
(defconstant +byte-ctrl-to-upper-offset+ 64
  "Offset added to a Ctrl byte (1..26 for ^A..^Z, 27..31 for ^[..^_) to recover
   the corresponding uppercase ASCII letter or symbol.  Named to replace the
   opaque '+64' literal in %control-byte-key-name.")

;;; ── Copy-mode uppercase / control constants ──────────────────────────────────
;;; Raw byte values for uppercase letters and Ctrl codes used in the copy-mode
;;; dispatch table that previously lacked named constants (the table used bare integers).
(defconstant +byte-capital-j+   74 "Uppercase 'J' — scroll viewport down one line (0x4A).")
(defconstant +byte-capital-k+   75 "Uppercase 'K' — scroll viewport up one line (0x4B).")
(defconstant +byte-capital-w+   87 "Uppercase 'W' — WORD-forward whitespace-delimited (0x57).")
(defconstant +byte-capital-b+   66
  "Uppercase 'B' — WORD-backward whitespace-delimited (0x42).
   NOTE: shares numeric value 66 with +byte-arrow-down+.  They are semantically disjoint:
   arrow-down is the final byte of a CSI sequence and never appears as a raw byte in
   single-byte copy-mode dispatch.")
(defconstant +byte-capital-e+   69 "Uppercase 'E' — WORD-end whitespace-delimited (0x45).")
(defconstant +byte-caret+       94 "Caret '^' — back-to-indentation in copy mode (0x5E).")
(defconstant +byte-lowercase-z+ 122 "Lowercase 'z' — scroll-middle in copy mode (0x7A).")
(defconstant +byte-ctrl-v+      22 "C-v — toggle rectangle select in copy mode (0x16).")
(defconstant +byte-hash+        35 "Hash '#' — search backward for word under cursor (0x23).")
(defconstant +byte-asterisk+    42 "Asterisk '*' — search forward for word under cursor (0x2A).")
(defconstant +byte-ctrl-s+      19 "C-s — incremental forward search in copy mode (0x13).")
(defconstant +byte-ctrl-r+      18 "C-r — incremental backward search in copy mode (0x12).")
(defconstant +byte-ctrl-j+      10 "C-j — newline / accept (equivalent to Enter in copy mode) (0x0A).")
