(in-package #:cl-tmux)

;;;; Copy-mode -X facts (send-keys -X dispatch).

;;; Real tmux's `send-keys -X <name>` dispatches a named copy-mode action.
;;; This file owns the canonical fact tables. Dispatch logic lives in
;;; dispatch-commands-pane-x.lisp.

(defmacro define-copy-mode-x-command-table (&rest entries)
  "Build *COPY-MODE-X-COMMANDS* from a declarative name -> keyword table.
   Each ENTRY is (\"command-name\" keyword)."
  `(defparameter *copy-mode-x-commands*
     (list ,@(mapcar (lambda (entry)
                       `(cons ,(first entry) ,(second entry)))
                     entries))
     "Alist mapping send-keys -X command names to copy-mode dispatch keywords."))

(define-copy-mode-x-command-table
  ("begin-selection"              :copy-mode-begin-selection)
  ("begin-line-selection"         :copy-mode-begin-line-selection)
  ("clear-selection"              :copy-mode-clear-selection)
  ("copy-selection"               :copy-mode-copy-selection-no-cancel)
  ("copy-selection-and-cancel"    :copy-mode-yank)
  ("copy-selection-no-clear"      :copy-mode-copy-selection-no-clear)
  ("cancel"                       :copy-mode-exit)
  ("cursor-up"                    :copy-mode-cursor-up)
  ("cursor-down"                  :copy-mode-cursor-down)
  ("cursor-left"                  :copy-mode-cursor-left)
  ("cursor-right"                 :copy-mode-cursor-right)
  ("page-up"                      :copy-mode-page-up)
  ("page-down"                    :copy-mode-page-down)
  ("halfpage-up"                  :copy-mode-half-page-up)
  ("halfpage-down"                :copy-mode-half-page-down)
  ("halfpage-down-and-cancel"     :copy-mode-half-page-down-and-cancel)
  ("stop-selection"               :copy-mode-stop-selection)
  ("toggle-position"              :copy-mode-toggle-position)
  ("previous-prompt"              :copy-mode-previous-prompt)
  ("next-prompt"                  :copy-mode-next-prompt)
  ("search-again"                 :copy-mode-search-next)
  ("search-reverse"               :copy-mode-search-prev)
  ("search-forward"               :copy-mode-search-forward-prompt)
  ("search-backward"              :copy-mode-search-backward-prompt)
  ("search-forward-incremental"   :copy-mode-search-forward-incremental)
  ("search-backward-incremental"  :copy-mode-search-backward-incremental)
  ("top-line"                     :copy-mode-high)
  ("middle-line"                  :copy-mode-middle)
  ("bottom-line"                  :copy-mode-low)
  ("history-top"                  :copy-mode-top)
  ("history-bottom"               :copy-mode-bottom)
  ("next-word"                    :copy-mode-word-forward)
  ("previous-word"                :copy-mode-word-backward)
  ("next-word-end"                :copy-mode-word-end)
  ("next-space"                   :copy-mode-space-forward)
  ("previous-space"               :copy-mode-space-backward)
  ("next-space-end"               :copy-mode-space-end)
  ("rectangle-toggle"             :copy-mode-rectangle-toggle)
  ("rectangle-on"                 :copy-mode-rectangle-on)
  ("rectangle-off"                :copy-mode-rectangle-off)
  ("cursor-centre-vertical"       :copy-mode-cursor-centre-vertical)
  ("cursor-centre-horizontal"     :copy-mode-cursor-centre-horizontal)
  ("copy-end-of-line"             :copy-mode-copy-end-of-line)
  ("copy-end-of-line-and-cancel"  :copy-mode-copy-end-of-line-and-cancel)
  ("copy-line"                    :copy-mode-copy-line)
  ("copy-line-and-cancel"         :copy-mode-copy-line-and-cancel)
  ("append-selection"             :copy-mode-append-selection)
  ("append-selection-and-cancel"  :copy-mode-append-selection-and-cancel)
  ("back-to-indentation"          :copy-mode-back-to-indentation)
  ("start-of-line"                :copy-mode-line-start)
  ("end-of-line"                  :copy-mode-line-end)
  ("scroll-up"                    :copy-mode-scroll-up-line)
  ("scroll-down"                  :copy-mode-scroll-down-line)
  ("scroll-middle"                :copy-mode-scroll-middle)
  ("scroll-down-and-cancel"       :copy-mode-scroll-down-and-cancel)
  ("page-down-and-cancel"         :copy-mode-page-down-and-cancel)
  ("cursor-down-and-cancel"       :copy-mode-cursor-down-and-cancel)
  ("scroll-to-mouse"              :copy-mode-scroll-to-mouse)
  ("select-word"                  :copy-mode-select-word)
  ("copy-pipe"                    :copy-mode-copy-pipe-no-cancel)
  ("copy-pipe-and-cancel"         :copy-mode-copy-pipe-and-cancel)
  ("copy-pipe-end-of-line-and-cancel"
   :copy-mode-copy-pipe-end-of-line-and-cancel)
  ("previous-paragraph"           :copy-mode-prev-paragraph)
  ("next-paragraph"               :copy-mode-next-paragraph)
  ("jump-to-mark"                 :copy-mode-jump-to-mark)
  ("set-mark"                     :copy-mode-set-mark)
  ("select-line"                  :copy-mode-begin-line-selection)
  ("refresh-from-pane"            :copy-mode-refresh-from-pane)
  ("jump-again"                   :copy-mode-jump-again)
  ("jump-reverse"                 :copy-mode-jump-reverse)
  ("other-end"                    :copy-mode-other-end)
  ("next-matching-bracket"        :copy-mode-next-matching-bracket)
  ("previous-matching-bracket"    :copy-mode-previous-matching-bracket))

(defmacro define-send-keys-x-explicit-arg-specs (&rest specs)
  "Define canonical send-keys -X explicit-argument facts."
  `(defparameter *send-keys-x-explicit-arg-specs*
     ',specs
     "Canonical send-keys -X explicit-argument facts: (name kind handler)."))

(define-send-keys-x-explicit-arg-specs
  ("jump-forward"                  :char copy-mode-jump-forward)
  ("jump-backward"                 :char copy-mode-jump-backward)
  ("jump-to-forward"               :char copy-mode-jump-to)
  ("jump-to-backward"              :char copy-mode-jump-to-backward)
  ("goto-line"                     :line copy-mode-goto-line)
  ("search-forward-text"           :text copy-mode-search-forward)
  ("search-backward-text"          :text copy-mode-search-backward)
  ("copy-pipe"                     :text copy-mode-copy-pipe-no-cancel)
  ("copy-pipe-and-cancel"          :text copy-mode-copy-pipe)
  ("copy-pipe-end-of-line-and-cancel"
   :text copy-mode-copy-pipe-end-of-line)
  ("copy-pipe-end-of-line"         :text copy-mode-copy-pipe-end-of-line-no-cancel)
  ("copy-pipe-no-clear"            :text copy-mode-copy-pipe-no-clear)
  ("copy-pipe-line"                :text copy-mode-copy-pipe-line)
  ("copy-pipe-line-and-cancel"     :text copy-mode-copy-pipe-line-and-cancel)
  ("pipe"                          :text copy-mode-pipe-no-cancel)
  ("pipe-no-clear"                 :text copy-mode-pipe-no-clear)
  ("pipe-and-cancel"               :text copy-mode-pipe-and-cancel)
  ("selection-mode"                :text copy-mode-selection-mode))
