(in-package #:cl-tmux)

;;;; list-commands usage string table — pure data, no logic.
;;;;
;;;; Maps canonical command name → tmux usage-flags string matching the real
;;;; tmux cmd_entry.args field so `list-commands -F #{command_list_usage}`
;;;; output is script-compatible.

(defparameter *command-usage-table*
  '(("attach-session"       . "[-dErx] [-c working-directory] [-f flags] [-t target-session]")
    ("bind-key"             . "[-nrN] [-T key-table] [-X] key [note] command [argument ...]")
    ("break-pane"           . "[-abdP] [-F format] [-n window-name] [-s src-pane] [-t dst-window]")
    ("capture-pane"         . "[-aCeJNpPqS] [-b buffer-name] [-E end-line] [-s src-pane] [-S start-line] [-t target-pane]")
    ("choose-buffer"        . "[-GNrZ] [-F format] [-f filter] [-O sort-order] [-t target-pane] [template]")
    ("choose-client"        . "[-GNrZ] [-F format] [-f filter] [-O sort-order] [-t target-pane] [template]")
    ("choose-tree"          . "[-GNrsw] [-F format] [-f filter] [-O sort-order] [-t target-pane] [template]")
    ("clear-history"        . "[-H] [-t target-pane]")
    ("clear-prompt-history" . "[-T prompt-type]")
    ("clock-mode"           . "[-t target-pane]")
    ("command-prompt"       . "[-1bFikN] [-I inputs] [-p prompts] [-t target-client] [-T prompt-type] [template]")
    ("confirm-before"       . "[-b] [-p prompt] [-t target-client] command")
    ("copy-mode"            . "[-eHMuq] [-s src-pane] [-t target-pane]")
    ("customize-mode"       . "[-NZ] [-F format] [-f filter] [-t target-pane]")
    ("delete-buffer"        . "[-b buffer-name]")
    ("detach-client"        . "")
    ("display-menu"         . "[-O] [-b border-lines] [-c target-client] [-C menu-cursor] [-H selected-style] [-s style] [-S separator-style] [-t target-pane] [-T title] [-x position] [-y position] name key command ...")
    ("display-message"      . "[-l] [-d delay] [-F format] [-t target-pane] [message]")
    ("display-panes"        . "[-bN] [-d duration] [-F format] [-t target-client] [template]")
    ("display-popup"        . "[-BCE] [-b border-lines] [-c target-client] [-d start-directory] [-e environment] [-h height] [-s style] [-S border-style] [-t target-pane] [-T title] [-w width] [-x position] [-y position] [shell-command [argument ...]]")
    ("find-window"          . "[-CimnNrT] [-F format] [-t target-pane] match-string")
    ("has-session"          . "[-t target-session]")
    ("if-shell"             . "[-bF] [-t target-pane] shell-command command [command]")
    ("join-pane"            . "[-bdfhv] [-l size] [-s src-pane] [-t dst-pane]")
    ("kill-pane"            . "[-a] [-t target-pane]")
    ("kill-server"          . "")
    ("kill-session"         . "[-aC] [-t target-session]")
    ("kill-window"          . "[-a] [-t target-window]")
    ("last-pane"            . "[-de] [-t target-window]")
    ("last-window"          . "[-t target-session]")
    ("link-window"          . "[-adbk] [-s src-window] [-t dst-window]")
    ("list-buffers"         . "[-F format] [-f filter]")
    ("list-clients"         . "[-F format] [-f filter] [-t target-session]")
    ("list-commands"        . "[-F format] [command]")
    ("list-keys"            . "[-1aN] [-P prefix-string] [-T key-table] [key]")
    ("list-panes"           . "[-as] [-F format] [-f filter] [-t target]")
    ("list-sessions"        . "[-F format] [-f filter]")
    ("list-windows"         . "[-a] [-F format] [-f filter] [-t target-session]")
    ("load-buffer"          . "[-b buffer-name] path")
    ("lock-client"          . "[-t target-client]")
    ("lock-server"          . "")
    ("lock-session"         . "[-at] [-t target-session]")
    ("move-pane"            . "[-bdfhv] [-l size] [-s src-pane] [-t dst-pane]")
    ("move-window"          . "[-abrdk] [-s src-window] [-t dst-window]")
    ("new-session"          . "[-AdEP] [-c start-directory] [-e environment] [-F format] [-n window-name] [-s session-name] [-t target-session] [-x width] [-y height] [shell-command [argument ...]]")
    ("new-window"           . "[-abdkPS] [-c start-directory] [-e environment] [-F format] [-n window-name] [-t target-window] [shell-command [argument ...]]")
    ("next-layout"          . "[-t target-window]")
    ("next-window"          . "[-a] [-t target-session]")
    ("paste-buffer"         . "[-dpr] [-b buffer-name] [-s separator] [-t target-pane]")
    ("pipe-pane"            . "[-IOo] [-t target-pane] [shell-command]")
    ("previous-layout"      . "[-t target-window]")
    ("previous-window"      . "[-a] [-t target-session]")
    ("refresh-client"       . "[-S] [-C size] [-f flags]")
    ("rename-session"       . "[-t target-session] new-name")
    ("rename-window"        . "[-t target-window] new-name")
    ("resize-pane"          . "[-DLMRUZ] [-t target-pane] [-x width] [-y height] [adjustment]")
    ("resize-window"        . "[-aADLRU] [-t target-window] [-x width] [-y height] [adjustment]")
    ("respawn-pane"         . "[-k] [-c start-directory] [-e environment] [-t target-pane] [shell-command [argument ...]]")
    ("respawn-window"       . "[-k] [-c start-directory] [-e environment] [-t target-window] [shell-command [argument ...]]")
    ("rotate-window"        . "[-DU] [-t target-window]")
    ("run-shell"            . "[-bCE] [-c start-directory] [shell-command [argument ...]]")
    ("save-buffer"          . "[-a] [-b buffer-name] path")
    ("select-layout"        . "[-Enop] [-t target-window] [layout-name]")
    ("select-pane"          . "[-DdegGlLlMmRU] [-T title] [-t target-pane]")
    ("select-window"        . "[-lnpT] [-t target-window]")
    ("send-keys"            . "[-FHlMRX] [-N repeat-count] [-t target-pane] key ...")
    ("send-prefix"          . "[-2] [-t target-pane]")
    ("server-access"        . "[-adlrw] [user]")
    ("set-buffer"           . "[-aw] [-b buffer-name] [-n new-buffer-name] [-t target-client] data")
    ("set-environment"      . "[-Fhgru] [-t target-session] name [value]")
    ("set-hook"             . "[-agpRuw] [-t target-pane] hook-name [command]")
    ("set-option"           . "[-aFgopqsuUw] [-t target-pane] option [value]")
    ("set-window-option"    . "[-aFgoqu] [-t target-window] option [value]")
    ("show-buffer"          . "[-b buffer-name]")
    ("show-environment"     . "[-hgs] [-t target-session] [name]")
    ("show-messages"        . "[-JT] [-t target-client]")
    ("show-options"         . "[-AgHpqsvw] [-t target-pane] [option]")
    ("show-window-options"  . "[-gvA] [-t target-window] [option]")
    ("show-session-options" . "[-gvA] [-t target-session] [option]")
    ("show-server-options"  . "[-gvA] [option]")
    ("source-file"          . "[-Fnqv] [path ...]")
    ("split-window"         . "[-bdfhIvPZ] [-c start-directory] [-e environment] [-F format] [-l size] [-t target-pane] [shell-command [argument ...]]")
    ("start-server"         . "")
    ("suspend-client"       . "[-t target-client]")
    ("swap-pane"            . "[-DU] [-s src-pane] [-t dst-pane]")
    ("swap-window"          . "[-d] [-s src-window] [-t dst-window]")
    ("switch-client"        . "[-lnpr] [-t target-session] [-T key-table]")
    ("unbind-key"           . "[-anq] [-T key-table] key")
    ("unlink-window"        . "[-k] [-t target-window]")
    ("wait-for"             . "[-SLU] channel"))
  "Maps canonical command name to tmux usage flags string.")
