(in-package #:cl-tmux/test)

;;;; scroll tests — part C: direct-line-edit (insert/delete lines), 
;;;; scroll-screen-to-history, DEC Rectangle operations (DECERA/DECFRA/DECCRA).

;;; ── SUITE: insert-lines / delete-lines direct calls ─────────────────────────
;;;
;;; insert-lines and delete-lines are generated by define-line-edit-rules and
;;; were previously only tested via the CSI path.  These direct-call tests
;;; cover edge cases: n=0, n > region-size.

(def-suite direct-line-edit
  :description "Direct calls to insert-lines and delete-lines"
  :in terminal-suite)
(in-suite direct-line-edit)

(test insert-lines-at-row-zero-pushes-content-down
  "insert-lines 1 at row 0 pushes all existing rows down."
  (with-screen (s 5 4)
    (feed-lines s "AA" "BB" "CC")
    (cl-tmux/terminal/actions:set-cursor s 0 0)
    (cl-tmux/terminal/actions:insert-lines s 1)
    ;; Row 0 must be blank (newly inserted); old row 0 moves to row 1.
    (is (row-blank-p s 0) "row 0 must be blank after insert-lines 1 at row 0")
    (check-row s 1 "AA")))

(test delete-lines-at-row-zero-pulls-content-up
  "delete-lines 1 at row 0 pulls all rows up; the bottom row becomes blank."
  (with-screen (s 5 4)
    (feed-lines s "AA" "BB" "CC" "DD")
    (cl-tmux/terminal/actions:set-cursor s 0 0)
    (cl-tmux/terminal/actions:delete-lines s 1)
    ;; Old row 1 ("BB") becomes row 0; bottom row becomes blank.
    (check-row s 0 "BB")
    (is (row-blank-p s 3) "bottom row must be blank after delete-lines 1 at row 0")))

(test insert-lines-ignored-when-cursor-above-scroll-region
  "IL is a no-op when the cursor is above the scroll-top (outside the region): it
   must not shift rows that lie outside the scroll region."
  (with-screen (s 5 5)
    (feed-lines s "AA" "BB" "CC" "DD" "EE")
    (feed s (esc "[3;5r"))      ; DECSTBM region rows 3-5 (0-based 2-4); homes cursor (0,0)
    (check-cursor s 0 0)        ; cursor is above scroll-top (row 2)
    (cl-tmux/terminal/actions:insert-lines s 1)
    (check-row s 0 "AA")        ; rows above the region must be untouched
    (check-row s 1 "BB")
    (check-row s 2 "CC")))

(test delete-lines-ignored-when-cursor-above-scroll-region
  "DL is likewise a no-op above the scroll region."
  (with-screen (s 5 5)
    (feed-lines s "AA" "BB" "CC" "DD" "EE")
    (feed s (esc "[3;5r"))      ; region rows 2-4 (0-based); cursor homed to (0,0)
    (cl-tmux/terminal/actions:delete-lines s 1)
    (check-row s 0 "AA")
    (check-row s 1 "BB")))

(test delete-lines-n-larger-than-region-blanks-all-region-rows
  "delete-lines with n >= region size blanks every row in the region."
  (with-screen (s 5 4)
    (feed-lines s "AA" "BB" "CC" "DD")
    (cl-tmux/terminal/actions:set-cursor s 0 0)
    (cl-tmux/terminal/actions:delete-lines s 99)
    ;; Every row must be blank
    (dotimes (y 4)
      (is (row-blank-p s y)
          "row ~D must be blank after oversized delete-lines" y))))

(test insert-lines-n-larger-than-region-blanks-all-region-rows
  "insert-lines with n >= region size blanks every row in the region."
  (with-screen (s 5 4)
    (feed-lines s "AA" "BB" "CC" "DD")
    (cl-tmux/terminal/actions:set-cursor s 0 0)
    (cl-tmux/terminal/actions:insert-lines s 99)
    ;; Every row must be blank
    (dotimes (y 4)
      (is (row-blank-p s y)
          "row ~D must be blank after oversized insert-lines" y))))

;;; ── SUITE: scroll-screen-to-history direct tests ─────────────────────────────
;;;
;;; Coverage gap: scroll-screen-to-history was only exercised indirectly through
;;; the scroll-on-clear integration test.  These direct tests verify:
;;;   1. Row-ordering in the scrollback (top row ends up oldest, newest-first list).
;;;   2. The alt-screen no-op guard.
;;;   3. That the history cap is respected after the push.

(def-suite scroll-screen-to-history-suite
  :description "Direct tests for scroll-screen-to-history row-ordering and guards"
  :in terminal-suite)
(in-suite scroll-screen-to-history-suite)

(test scroll-screen-to-history-pushes-all-rows
  "scroll-screen-to-history pushes every visible row into the scrollback buffer."
  (with-screen (s 5 3)
    (feed-lines s "AA" "BB" "CC")
    (cl-tmux/terminal/actions:scroll-screen-to-history s)
    (is (= 3 (length (cl-tmux/terminal/types:screen-scrollback s)))
        "scrollback must have 3 entries after pushing a 3-row screen")))

(test scroll-screen-to-history-top-row-is-oldest
  "scroll-screen-to-history pushes rows top→bottom so the top row ends up OLDEST
   (deepest in the newest-first scrollback list).  The bottom row is the most-recent
   (first) entry after the push."
  (with-screen (s 5 3)
    ;; Write distinct content so we can identify which row is which.
    (feed-lines s "ROW0" "ROW1" "ROW2")
    (cl-tmux/terminal/actions:scroll-screen-to-history s)
    (let ((scrollback (cl-tmux/terminal/types:screen-scrollback s)))
      ;; newest-first: index 0 = last pushed = row 2 (bottom row = most recent).
      (let ((newest-row (first scrollback))
            (oldest-row (first (last scrollback))))
        (is (char= #\R (cell-char (aref newest-row 0)))
            "first scrollback entry (newest) must start with 'R' from ROW2")
        ;; Distinguish ROW0 (oldest) from ROW2 (newest) by checking col 3:
        ;; ROW0 has char '0' at col 3 (0-indexed: R=0,O=1,W=2,0=3)
        ;; ROW2 has char '2' at col 3.
        (is (char= #\0 (cell-char (aref oldest-row 3)))
            "last scrollback entry (oldest) must be ROW0 — char at col 3 must be '0'")
        (is (char= #\2 (cell-char (aref newest-row 3)))
            "first scrollback entry (newest) must be ROW2 — char at col 3 must be '2'")))))

(test scroll-screen-to-history-is-noop-on-alt-screen
  "scroll-screen-to-history must be a no-op when the alternate screen is active."
  (with-screen (s 5 3)
    (feed-lines s "AA" "BB" "CC")
    ;; Enter the alternate screen.
    (cl-tmux/terminal/actions:enter-alt-screen s)
    (cl-tmux/terminal/actions:scroll-screen-to-history s)
    ;; Scrollback must remain empty — the alt screen has no history.
    (is (null (cl-tmux/terminal/types:screen-scrollback s))
        "scroll-screen-to-history must not push to scrollback on the alt screen")))

(test scroll-screen-to-history-respects-history-cap
  "scroll-screen-to-history enforces the history limit after pushing all rows."
  (with-screen (s 5 10)
    ;; Pre-fill 10 rows with content.
    (dotimes (_ 10) (feed s "AAAAA"))
    ;; Install a small cap so the push will trim.
    (let ((cl-tmux/terminal/actions:*history-limit-function* (lambda () 5)))
      (cl-tmux/terminal/actions:scroll-screen-to-history s))
    (is (<= (length (cl-tmux/terminal/types:screen-scrollback s)) 5)
        "scrollback must be trimmed to 5 after scroll-screen-to-history with cap 5")))

;;; ── SUITE: DEC Rectangle operations (DECERA / DECFRA / DECCRA) ───────────────
;;;
;;; Coverage gap: DECERA, DECFRA, and DECCRA had no dedicated unit tests.
;;; These tests cover normal operation, degenerate (empty) rectangles,
;;; out-of-bounds clamping, and overlapping DECCRA regions.

(def-suite dec-rect-ops-suite
  :description "DECERA / DECFRA / DECCRA DEC rectangle operation unit tests"
  :in terminal-suite)
(in-suite dec-rect-ops-suite)

;;; ── DECERA — Erase Rectangular Area ─────────────────────────────────────────

(test decera-erases-rectangle
  "DECERA blanks every cell in the specified 1-based rectangle."
  (with-screen (s 10 5)
    (feed s "AAAAAAAAAA")     ; row 0 = "AAAAAAAAAA"
    (feed s "BBBBBBBBBB")     ; row 1
    ;; Erase a 3×2 rectangle: rows 1-2 (1-based), cols 2-4 (1-based)
    (cl-tmux/terminal/actions:decera s 1 2 2 4)
    ;; Row 0 (1-based row 1), cols 1-3 (0-based) must be blank
    (is (char= #\Space (char-at s 1 0)) "decera: col 1 row 0 must be blank")
    (is (char= #\Space (char-at s 2 0)) "decera: col 2 row 0 must be blank")
    (is (char= #\Space (char-at s 3 0)) "decera: col 3 row 0 must be blank")
    ;; Cells outside the rectangle must be unchanged
    (is (char= #\A (char-at s 0 0)) "decera: col 0 row 0 must be preserved")
    (is (char= #\A (char-at s 4 0)) "decera: col 4 row 0 must be preserved")))

(test decera-degenerate-rectangle-is-noop
  "DECERA with a degenerate rectangle (top > bottom) is a no-op."
  (with-screen (s 5 5)
    (feed s "AAAAA")
    ;; top > bottom (3 > 1 in 1-based) → degenerate
    (cl-tmux/terminal/actions:decera s 3 1 1 5)
    (is (char= #\A (char-at s 0 0))
        "decera with degenerate rect must not erase any cells")))

(test decera-clamps-out-of-bounds-rectangle
  "DECERA parameters beyond the screen edge are clamped to the screen bounds."
  (with-screen (s 5 3)
    (feed s "AAAAA")
    ;; Rectangle extends beyond screen: bottom=99, right=99 → clamped to height-1, width-1
    (cl-tmux/terminal/actions:decera s 1 1 99 99)
    ;; Entire screen must be erased (clamped to full screen)
    (dotimes (y 3)
      (is (row-blank-p s y) "decera out-of-bounds: row ~D must be blank" y))))

;;; ── DECFRA — Fill Rectangular Area ──────────────────────────────────────────

(test decfra-fills-rectangle-with-char
  "DECFRA fills every cell in the specified 1-based rectangle with CHAR-CODE."
  (with-screen (s 10 5)
    ;; Fill rows 1-2 (0-based 0-1), cols 2-4 (0-based 1-3) with 'X' (code 88).
    (cl-tmux/terminal/actions:decfra s 88 1 2 2 4)
    (is (char= #\X (char-at s 1 0)) "decfra: col 1 row 0 must be 'X'")
    (is (char= #\X (char-at s 2 0)) "decfra: col 2 row 0 must be 'X'")
    (is (char= #\X (char-at s 3 0)) "decfra: col 3 row 0 must be 'X'")
    (is (char= #\X (char-at s 1 1)) "decfra: col 1 row 1 must be 'X'")
    ;; Cells outside the rectangle must remain blank.
    (is (char= #\Space (char-at s 0 0)) "decfra: col 0 row 0 must remain blank")
    (is (char= #\Space (char-at s 4 0)) "decfra: col 4 row 0 must remain blank")))

(test decfra-zero-char-code-fills-with-space
  "DECFRA with char-code 0 substitutes space (code 32) per VT specification."
  (with-screen (s 5 3)
    (feed s "AAAAA")
    (cl-tmux/terminal/actions:decfra s 0 1 1 1 5)
    (dotimes (x 5)
      (is (char= #\Space (char-at s x 0))
          "decfra char-code 0: col ~D must be space" x))))

(test decfra-degenerate-rectangle-is-noop
  "DECFRA with a degenerate rectangle (left > right) is a no-op."
  (with-screen (s 5 3)
    (feed s "AAAAA")
    ;; left > right: 5 > 1 (inverted) → degenerate
    (cl-tmux/terminal/actions:decfra s 88 1 5 1 1)
    (is (char= #\A (char-at s 0 0))
        "decfra with degenerate rect must not change any cells")))

;;; ── DECCRA — Copy Rectangular Area ──────────────────────────────────────────

(test deccra-copies-rectangle-to-target
  "DECCRA copies a source rectangle to a non-overlapping target."
  (with-screen (s 10 5)
    ;; Write 'A' in a 3×2 block at rows 1-2 cols 1-3 (1-based).
    (cl-tmux/terminal/actions:decfra s 65 1 1 2 3)  ; 'A'=65
    ;; Copy that block to rows 4-5 cols 6-8 (1-based).
    (cl-tmux/terminal/actions:deccra s 1 1 2 3 4 6)
    ;; Target: 0-based rows 3-4, cols 5-7 must contain 'A'.
    (is (char= #\A (char-at s 5 3)) "deccra: target col 5 row 3 must be 'A'")
    (is (char= #\A (char-at s 6 3)) "deccra: target col 6 row 3 must be 'A'")
    (is (char= #\A (char-at s 7 3)) "deccra: target col 7 row 3 must be 'A'")
    ;; Source must be unchanged.
    (is (char= #\A (char-at s 0 0)) "deccra: source col 0 row 0 must remain 'A'")))

(test deccra-overlapping-regions-are-handled-correctly
  "DECCRA with overlapping source and target regions must not corrupt data.
   The source is buffered before writing, so a shift-right overlap is safe."
  (with-screen (s 10 3)
    ;; Write 'A','B','C' in cols 0-2 of row 0.
    (cl-tmux/terminal/actions:write-char-at-cursor s #\A)
    (cl-tmux/terminal/actions:write-char-at-cursor s #\B)
    (cl-tmux/terminal/actions:write-char-at-cursor s #\C)
    ;; Copy 1-based cols 1-3 row 1 to cols 2-4 row 1 (shift right by 1).
    (cl-tmux/terminal/actions:deccra s 1 1 1 3 1 2)
    ;; After the copy, cols 1-3 (0-based) of row 0 must contain A,B,C.
    (is (char= #\A (char-at s 1 0)) "overlapping deccra: col 1 must be 'A'")
    (is (char= #\B (char-at s 2 0)) "overlapping deccra: col 2 must be 'B'")
    (is (char= #\C (char-at s 3 0)) "overlapping deccra: col 3 must be 'C'")))

(test deccra-degenerate-source-is-noop
  "DECCRA with a degenerate source rectangle (top > bottom) is a no-op."
  (with-screen (s 5 3)
    (cl-tmux/terminal/actions:decfra s 65 1 1 3 5)   ; fill whole screen with 'A'
    ;; Degenerate source: top=3 > bottom=1
    (cl-tmux/terminal/actions:deccra s 3 1 1 5 1 1)
    ;; Target must remain unchanged (still 'A' or blank — no copy occurred).
    (is (char= #\A (char-at s 0 0))
        "deccra with degenerate source must not modify the target")))

(test deccra-target-clamped-to-screen-bounds
  "DECCRA clamps the target rectangle to the screen bounds when it extends beyond."
  (with-screen (s 5 3)
    ;; Write 'Z' in a 2×2 block at rows 1-2 cols 1-2 (1-based).
    (cl-tmux/terminal/actions:decfra s 90 1 1 2 2)   ; 'Z'=90
    ;; Copy to rows 3-99 cols 4-99 (1-based) — extends well past the screen.
    ;; Only the in-bounds portion (row 2 col 3, i.e. 0-based row 2 col 3) should be written.
    (cl-tmux/terminal/actions:deccra s 1 1 2 2 3 4)
    ;; 0-based: target starts at row 2, col 3 — at least that cell must be 'Z'.
    (is (char= #\Z (char-at s 3 2))
        "deccra: clamped target cell (col 3, row 2) must be 'Z'")))
