(in-package #:cl-tmux)

(defparameter *dispatch-command-specs-compat-session-entries*
  '((%cmd-set-hook ("set-hook"))
    (%cmd-set-option ("set" "set-option" "sets" "set-session-option")
     :public-name "set-option")
    (%cmd-set-window-option ("setw" "set-window-option")
     :public-name "set-window-option")
    (%cmd-show-environment-arg ("show-environment"))
    (%cmd-list-sessions-arg ("list-sessions" "ls"))
    (%cmd-list-clients-arg ("list-clients"))
    (%cmd-refresh-client-arg ("refresh-client"))
    (%cmd-lock-client-arg ("lock-client"))
    (%cmd-lock-session-arg ("lock-session"))
    (%cmd-has-session-arg ("has-session"))
    (%cmd-attach-session-arg ("attach-session"))
    (%cmd-switch-client ("switch-client"))
    (%cmd-server-access ("server-access"))
    (%cmd-wait-for-arg ("wait-for"))))
