(in-package #:cl-tmux)

(defparameter *dispatch-command-specs-core-pane-entries*
  '((:kill-pane '%cmd-kill-pane ("kill-pane"))
    (:split-horizontal '%cmd-split-window ("split-window")
     :named-names ("split-window"))
    (:list-keys '%cmd-list-keys-arg ("list-keys"))
    (:list-panes '%cmd-list-panes-arg-full ("list-panes"))
    (:copy-mode-enter '%cmd-copy-mode-arg ("copy-mode")
     :named-names ("copy-mode"))
    (:paste-buffer '%cmd-paste-buffer ("paste-buffer"))
    (:list-buffers '%cmd-list-buffers ("list-buffers"))
    (:show-buffer '%cmd-show-buffer ("show-buffer"))
    (:choose-buffer '%cmd-choose-buffer ("choose-buffer"))
    (:delete-buffer '%cmd-delete-buffer ("delete-buffer"))
    (:save-buffer '%cmd-save-buffer ("save-buffer"))
    (:load-buffer '%cmd-load-buffer ("load-buffer"))
    (:capture-pane '%cmd-capture-pane-arg ("capture-pane"))
    (:clear-history '%cmd-clear-history-arg ("clear-history"))
    (:respawn-pane '%cmd-respawn-pane-arg ("respawn-pane"))
    (:send-keys '%cmd-send-keys-arg ("send-keys" "send-key" "send"))
    (:mark-pane '%cmd-mark-pane ("mark-pane"))
    (:clear-mark '%cmd-clear-mark ("clear-mark"))
    (:bind-key '%cmd-bind-key-arg ("bind-key" "bind"))
    (:unbind-key '%cmd-unbind-key-arg ("unbind-key" "unbind"))
    (:break-pane '%cmd-break-pane-arg ("break-pane"))
    (:join-pane '%cmd-join-pane-arg ("join-pane" "move-pane"))
    (:swap-pane-forward '%cmd-swap-pane-arg ("swap-pane")
     :named-names ("swap-pane"))
    (:last-pane '%cmd-last-pane-arg ("last-pane"))
    (:pipe-pane '%cmd-pipe-pane-arg ("pipe-pane"))
    (:send-prefix '%cmd-send-prefix-arg ("send-prefix" "sendp"))
    (:resize-window '%cmd-resize-window-arg ("resize-window"))
    (:respawn-window '%cmd-respawn-window-arg ("respawn-window"))
    (:move-pane '%cmd-move-pane ("move-pane"))
    (:synchronize-panes '%cmd-synchronize-panes ("synchronize-panes"))
    (:select-pane '%cmd-select-pane ("select-pane"))
    (:resize-pane '%cmd-resize-pane ("resize-pane"))))
