(in-package #:cl-tmux)

;;;; Command handler rule table — generated by define-command-handlers macro.
;;;;
;;;; This file contains the define-command-handlers macro definition and its
;;;; invocation with the core command handler rules.  Each handler maps a
;;;; keyword dispatch symbol to an action on the current session.
;;;;
;;;; Macros and helper functions used by these handlers are defined in
;;;; dispatch-core.lisp.  The generated dispatch-command function is the
;;;; central entry point for ALL prefix-key command dispatch.
;;;;
;;;; Copy-mode command handlers live in dispatch-handlers-copy-mode.lisp.
;;;; Paste-buffer command handlers live in dispatch-handlers-buffer.lisp.

;;; -- Scoped-options handler macro -------------------------------------------
;;;
;;; :show-window-options, :show-session-options, and :show-server-options all
;;; follow the same shape: (show-overlay (with-output-to-string (s) (format s "# SCOPE options") ...)).
;;; define-show-options-handler emits one named helper function per scope so the
;;; three handlers delegate to a generated function rather than duplicating the body.

(defmacro define-show-options-handler (fn-name scope-label &optional scope-arg)
  "Generate a zero-argument function named FN-NAME that shows a scoped options
   overlay.  SCOPE-LABEL is the string written after '# ' in the header line.
   SCOPE-ARG (a keyword) is forwarded to cl-tmux/options:show-options when
   provided; when absent the default (all options) form is used."
  `(defun ,fn-name ()
     ,(format nil "Show an overlay listing ~A options." scope-label)
     (show-overlay
      (with-output-to-string (stream)
        (format stream ,(format nil "# ~A options~%" scope-label))
        ,(if scope-arg
             `(write-string (cl-tmux/options:show-options ,scope-arg) stream)
             `(write-string (cl-tmux/options:show-options) stream))))))

(define-show-options-handler %show-window-options  "window")
(define-show-options-handler %show-session-options "session")
(define-show-options-handler %show-server-options  "server"  :server)

;;; -- define-command-handlers macro + dispatch-command ----------------------
;;;
;;; Handlers are registered into a hash table at load time; dispatch-command
;;; does a runtime gethash lookup.  This allows multiple define-command-handlers
;;; calls across different files — each one assertz-es additional facts without
;;; requiring the entire handler table to live in one monolithic form.

(defvar *command-dispatch-table* (make-hash-table)
  "Keyword → handler-fn.  Populated by define-command-handlers; consulted by dispatch-command.")

(defmacro define-command-handlers (&rest rules)
  "Register command handlers into *command-dispatch-table*.
   Each RULE is (kw-or-kws &rest body) where kw-or-kws is a keyword or a list
   of keywords (case-sharing, like CL case multi-key clauses).
   SESSION and BYTE are bound in each handler body.
   Multiple calls accumulate; later registrations for the same keyword override earlier ones.
   If a handler returns :QUIT or :DETACH that outcome is forwarded by dispatch-command."
  (let ((forms
         (loop for rule in rules
               for (kw-or-kws . body) = rule
               nconcing
               (let ((kws (if (listp kw-or-kws) kw-or-kws (list kw-or-kws))))
                 (mapcar (lambda (kw)
                           `(setf (gethash ,kw *command-dispatch-table*)
                                  (lambda (session byte)
                                    (declare (ignorable session byte))
                                    ,@body)))
                         kws)))))
    `(progn ,@forms)))

(defun dispatch-command (session cmd byte)
  "Dispatch CMD to its registered handler.  Sets *dirty* for all outcomes
   except :quit and :detach, which are returned as-is."
  (declare (ignorable byte))
  (let* ((handler (gethash cmd *command-dispatch-table*))
         (outcome (when handler (funcall handler session byte))))
    (case outcome
      ((:quit :detach) outcome)
      (otherwise (setf *dirty* t) nil))))

;;; -- Buffer preview constant -----------------------------------------------
;;;
;;; Buffer listing and preview truncate content to this many characters.
;;; Previously the literal 40 appeared three times across handlers; a single
;;; named constant makes intent explicit and keeps all three in sync.

(defconstant +buffer-preview-length+ 40
  "Maximum characters shown in a paste-buffer preview listing.")

(defun %confirm-prompt (msg ok-fn)
  "Show MSG as a y/n prompt; call OK-FN (no args) when the user types y/Y."
  (prompt-start msg ""
                (lambda (input)
                  (when (string-equal input "y")
                    (funcall ok-fn)))))

(defun %copy-mode-search-prompt (session prompt-char search-fn)
  "Open a copy-mode search prompt with PROMPT-CHAR prefix and call SEARCH-FN
   on the entered term when non-empty."
  (let ((screen (%active-screen session)))
    (when screen
      (prompt-start prompt-char ""
                    (lambda (term)
                      (unless (string= term "")
                        (funcall search-fn screen term)))))))

(defun %copy-mode-cursor-fn (direction)
  "Return a one-arg function that moves the copy-mode cursor in DIRECTION."
  (lambda (s) (copy-mode-move-cursor s direction)))

(define-command-handlers
  (:detach :detach)
  (:new-window (%cmd-new-window session))
  (:next-window (%cmd-cycle-window session #'next-cyclic))
  (:prev-window (%cmd-cycle-window session #'prev-cyclic))
  (:next-pane (%cmd-cycle-pane session #'next-cyclic))
  (:prev-pane (%cmd-cycle-pane session #'prev-cyclic))
  (:split-horizontal (%cmd-split session :v))        ; C-b " adds a horizontal bar → :v stacking
  (:split-vertical   (%cmd-split session :h))        ; C-b % adds a vertical bar   → :h side-by-side
  (:split-horizontal-no-focus (%cmd-split session :v :no-focus t))
  (:split-vertical-no-focus   (%cmd-split session :h :no-focus t))
  (:kill-pane   (%handle-kill-result (kill-pane session)))
  (:kill-window (%handle-kill-result (kill-window session (session-active-window session))))
  (:kill-pane-confirm
   (with-active-window (win session)
     (let* ((ap  (window-active-pane win))
            (msg (if ap (format nil "kill-pane ~D? (y/n)" (pane-id ap)) "kill-pane? (y/n)")))
       (%confirm-prompt msg (lambda () (%handle-kill-result (kill-pane session)))))))
  (:kill-window-confirm
   (with-active-window (win session)
     (%confirm-prompt (format nil "kill-window ~A? (y/n)" (window-name win))
                      (lambda () (%handle-kill-result
                                  (kill-window session (session-active-window session)))))))
  (:respawn-pane
   (with-active-window (win session)
     (let ((ap (window-active-pane win)))
       (when ap
         (let ((new-pane (respawn-pane ap)))
           (start-reader-thread new-pane))))))
  (:rename-window
   (with-active-window (win session)
     (prompt-start "rename-window" (window-name win)
                   (lambda (name) (rename-window win name)))))
  (:list-keys (show-overlay (describe-key-bindings)))

  ;; ── Copy-mode command handlers ─────────────────────────────────────────────
  ;; Rules are defined here so dispatch-command covers them in one case form.
  ;; The implementations delegate to helpers in dispatch-handlers-copy-mode.lisp.

  (:copy-mode-enter            (%copy-mode-call session #'copy-mode-enter))
  (:copy-mode-exit             (%copy-mode-call session #'copy-mode-exit))
  (:copy-mode-begin-selection  (%copy-mode-call session #'copy-mode-begin-selection))
  (:copy-mode-other-end        (%copy-mode-call session #'copy-mode-other-end))
  ;; Jump-to-char repeat/reverse (vi ; and ,)
  (:copy-mode-jump-again        (%copy-mode-call session #'copy-mode-jump-again))
  (:copy-mode-jump-reverse      (%copy-mode-call session #'copy-mode-jump-reverse))
  (:copy-mode-clear-selection  (%copy-mode-call session #'copy-mode-clear-selection))
  (:copy-mode-select-word      (%copy-mode-call session #'copy-mode-select-word))
  (:copy-mode-yank             (%copy-mode-call session #'copy-mode-yank))
  (:copy-mode-word-forward     (%copy-mode-call session #'copy-mode-word-forward))
  (:copy-mode-word-backward    (%copy-mode-call session #'copy-mode-word-backward))
  (:copy-mode-word-end         (%copy-mode-call session #'copy-mode-word-end))
  (:copy-mode-space-forward    (%copy-mode-call session #'copy-mode-space-forward))
  (:copy-mode-space-backward   (%copy-mode-call session #'copy-mode-space-backward))
  (:copy-mode-space-end        (%copy-mode-call session #'copy-mode-space-end))
  (:copy-mode-line-start       (%copy-mode-call session #'copy-mode-line-start))
  (:copy-mode-back-to-indentation (%copy-mode-call session #'copy-mode-back-to-indentation))
  (:copy-mode-line-end         (%copy-mode-call session #'copy-mode-line-end))
  ;; Horizontal cursor movement and rectangle (block) selection toggle — the
  ;; proper targets for `send -X cursor-left`/`cursor-right`/`rectangle-toggle`
  ;; (previously mis-mapped to begin-selection).  copy-mode-move-cursor takes a
  ;; direction, so it is wrapped in a one-arg lambda for %copy-mode-call.
  (:copy-mode-cursor-left      (%copy-mode-call session (%copy-mode-cursor-fn :left)))
  (:copy-mode-cursor-right     (%copy-mode-call session (%copy-mode-cursor-fn :right)))
  ;; cursor-up/down move the copy cursor (scrolling the viewport at the edges),
  ;; matching the arrow-key path; the -X names previously only scrolled a line.
  (:copy-mode-cursor-up        (%copy-mode-call session (%copy-mode-cursor-fn :up)))
  (:copy-mode-cursor-down      (%copy-mode-call session (%copy-mode-cursor-fn :down)))
  (:copy-mode-rectangle-toggle (%copy-mode-call session #'copy-mode-toggle-rectangle))
  (:copy-mode-top              (%copy-mode-call session #'copy-mode-top))
  (:copy-mode-bottom           (%copy-mode-call session #'copy-mode-bottom))
  (:copy-mode-high             (%copy-mode-call session #'copy-mode-high))
  (:copy-mode-middle           (%copy-mode-call session #'copy-mode-middle))
  (:copy-mode-low              (%copy-mode-call session #'copy-mode-low))
  (:copy-mode-page-up          (%copy-mode-call session #'copy-mode-page-up))
  (:copy-mode-page-down        (%copy-mode-call session #'copy-mode-page-down))
  (:copy-mode-half-page-up     (%copy-mode-call session #'copy-mode-half-page-up))
  (:copy-mode-half-page-down   (%copy-mode-call session #'copy-mode-half-page-down))
  (:copy-mode-scroll-up-line   (%copy-mode-call session #'copy-mode-scroll-up-line))
  (:copy-mode-scroll-down-line (%copy-mode-call session #'copy-mode-scroll-down-line))
  (:copy-mode-scroll-middle    (%copy-mode-call session #'copy-mode-scroll-middle))
  (:copy-mode-jump-to-mark     (%copy-mode-call session #'copy-mode-jump-to-mark))
  (:copy-mode-set-mark         (%copy-mode-call session #'copy-mode-set-mark))
  (:copy-mode-refresh-from-pane (values))  ; no-op — copy mode always reads live pane
  (:copy-mode-prev-paragraph   (%copy-mode-call session #'copy-mode-previous-paragraph))
  (:copy-mode-next-paragraph   (%copy-mode-call session #'copy-mode-next-paragraph))
  (:copy-mode-begin-line-selection (%copy-mode-call session #'copy-mode-begin-line-selection))
  (:copy-mode-copy-end-of-line  (%copy-mode-call session #'copy-mode-copy-end-of-line))
  (:copy-mode-copy-line         (%copy-mode-call session #'copy-mode-copy-line))
  (:copy-mode-append-selection  (%copy-mode-call session #'copy-mode-append-selection))
  (:copy-mode-append-selection-and-cancel
   (%copy-mode-call session #'copy-mode-append-selection-and-cancel))
  (:copy-mode-copy-pipe-no-cancel
   (%copy-mode-call session (lambda (s) (copy-mode-copy-pipe-no-cancel s nil))))
  (:copy-mode-search-next      (%copy-mode-call session #'copy-mode-search-next))
  (:copy-mode-search-prev      (%copy-mode-call session #'copy-mode-search-prev))
  (:copy-mode-search-forward-prompt
   (%copy-mode-search-prompt session "/" #'copy-mode-search-forward))
  (:copy-mode-search-backward-prompt
   (%copy-mode-search-prompt session "?" #'copy-mode-search-backward))
  (:copy-mode-search-forward-incremental
   (%copy-mode-call session #'copy-mode-search-forward-incremental))
  (:copy-mode-search-backward-incremental
   (%copy-mode-call session #'copy-mode-search-backward-incremental))
  (:copy-mode-next-matching-bracket
   (%copy-mode-call session #'copy-mode-next-matching-bracket))
  ;; search-forward-text / search-backward-text: handled via extra-args in
  ;; %dispatch-send-keys-X; these keyword stubs are never invoked but must
  ;; exist so the keyword table lookup does not fall through to "unrecognised".
  (:copy-mode-search-forward-text  (values))
  (:copy-mode-search-backward-text (values))
  (:copy-mode-choose-buffer
   (show-overlay
    (with-output-to-string (stream)
      (let ((buffers (cl-tmux/buffer:list-paste-buffers)))
        (if buffers
            (loop for buffer in buffers
                  for index from 0
                  do (format stream "~D: ~A~%"
                             index
                             (subseq buffer 0 (min +buffer-preview-length+
                                                   (length buffer)))))
            (format stream "(no paste buffers)~%"))))))

  ;; ── Resize commands ────────────────────────────────────────────────────────
  (:resize-left   (resize-pane (session-active-window session) :left))
  (:resize-right  (resize-pane (session-active-window session) :right))
  (:resize-up     (resize-pane (session-active-window session) :up))
  (:resize-down   (resize-pane (session-active-window session) :down))

  ;; ── Paste / send ──────────────────────────────────────────────────────────
  (:select-window (when byte (select-window-by-number session (- byte (char-code #\0)))))
  (:paste-buffer
   (let* ((text (cl-tmux/buffer:get-paste-buffer))
          (win  (session-active-window session))
          (ap   (and win (window-active-pane win))))
     (%paste-to-pane ap text)))
  (:send-prefix
   ;; Send the currently configured prefix key byte, not the compile-time default.
   ;; *prefix-key-code* is updated when `set prefix` runs; +prefix-key-code+ is fixed.
   (flet ((byte-vec (b)
            (make-array 1 :element-type '(unsigned-byte 8) :initial-element b)))
     (with-active-pane (ap session)
       (when (> (pane-fd ap) 0)
         (pty-write (pane-fd ap) (byte-vec cl-tmux/config:*prefix-key-code*))))))

  ;; ── Layout commands ────────────────────────────────────────────────────────
  (:select-layout-even-h    (%apply-named-layout-to-session session :even-horizontal))
  (:select-layout-even-v    (%apply-named-layout-to-session session :even-vertical))
  (:select-layout-tiled     (%apply-named-layout-to-session session :tiled))
  (:select-layout-main-h    (%apply-named-layout-to-session session :main-horizontal))
  (:select-layout-main-v    (%apply-named-layout-to-session session :main-vertical))

  ;; ── Pane selection ────────────────────────────────────────────────────────
  (:select-pane-left   (%select-pane-in-direction session :left))
  (:select-pane-right  (%select-pane-in-direction session :right))
  (:select-pane-up     (%select-pane-in-direction session :up))
  (:select-pane-down   (%select-pane-in-direction session :down))

  ;; ── Zoom ──────────────────────────────────────────────────────────────────
  (:zoom-toggle
   (with-active-window (win session)
     (window-zoom-toggle win)))

  ;; ── Session management ────────────────────────────────────────────────────
  (:rename-session
   (prompt-start "rename-session" (session-name session)
                 (lambda (name)
                   ;; Refuses a duplicate name and fires session-renamed (shared
                   ;; chokepoint with the rename-session command).
                   (%rename-session-checked session name))))
  (:run-shell
   (prompt-start "run-shell" ""
                 (lambda (cmd)
                   (unless (string= cmd "")
                     (let ((output (run-shell cmd)))
                       (show-overlay output))))))
  (:if-shell
   (prompt-start "if-shell" ""
                 (lambda (cmd)
                   (unless (string= cmd "")
                     (if-shell cmd
                               (lambda () (show-overlay (format nil "[if-shell] ~A: ok" cmd)))
                               :else-fn (lambda () (show-overlay (format nil "[if-shell] ~A: non-zero exit" cmd))))))))

  ;; :list-sessions / :list-sessions-full: static session list overlay.
  ((:list-sessions :list-sessions-full)
   (show-overlay (%format-session-list session)))

  ;; :choose-session: interactive j/k menu to switch sessions (C-b s).
  ;; Builds a menu with one entry per session; selecting switches to it.
  (:choose-session
   (let* ((sessions (if *server-sessions*
                        *server-sessions*
                        (list (cons (session-name session) session))))
          (items    (mapcar
                     (lambda (entry)
                       (let ((name (car entry))
                             (sess (cdr entry)))
                         (cons (format nil "~A~A (~D window~:P)"
                                       (if (eq sess session) "*" " ")
                                       name
                                       (length (cl-tmux/model:session-windows sess)))
                               ;; Command: switch-client via prompt-aware %run-command-line.
                               ;; Store as a cons (switch-to-session . name) handled by
                               ;; :menu-select dispatch extension.
                               (list :switch-client name))))
                     sessions)))
     (show-menu (make-menu :title "choose-session (j/k, Enter)" :items items :selected-index 0))
     (show-overlay (%format-menu *active-menu*))))
  (:new-session
   (let* ((rows (- *term-rows* *status-height*))
          (cols *term-cols*)
          (n    (1+ (length *server-sessions*)))
          (name (format nil "~D" n)))
     (new-session name rows cols)))
  (:kill-session
   ;; Destroy the current session, then apply detach-on-destroy: :quit (detach →
   ;; exit standalone) or NIL (switch to a survivor; the loop follows it).
   (let ((name (session-name session)))
     (%destroy-session session)
     (let ((action (%detach-on-destroy-action name)))
       (when (eq action :quit) (setf *running* nil))
       action)))
  (:has-session
   (prompt-start "has-session" ""
                 (lambda (name)
                   (let ((found (server-find-session name)))
                     (show-overlay (if found "yes" "no"))))))

  ;; ── Window management ──────────────────────────────────────────────────────
  (:list-windows (show-overlay (%format-window-list session)))
  ;; :choose-window: interactive j/k menu to select a window (C-b w).
  ;; Builds a menu with one entry per window; Enter selects, q/Esc dismisses.
  (:choose-window
   (let* ((wins  (session-windows session))
          (act   (session-active-window session))
          (items (mapcar (lambda (w)
                           (cons (format nil "~A~A: ~A (~D pane~:P)"
                                         (if (eq w act) "*" " ")
                                         (window-id w)
                                         (window-name w)
                                         (length (window-panes w)))
                                 ;; Command: select this window by id.
                                 (list :select-window (window-id w))))
                         wins)))
     (if items
         (progn
           (show-menu (make-menu :title "choose-window (j/k, Enter)" :items items :selected-index 0))
           (show-overlay (%format-menu *active-menu*)))
         (show-overlay "(no windows)"))))
  (:last-window
   (let ((prev (session-last-window session)))
     (when prev
       (%with-window-focus-transition (session)
         (session-select-window session prev)
         (setf (window-last-active-time prev) (get-universal-time))))))
  (:move-window
   (with-active-window (win session)
     (prompt-start "move-window" ""
                   (lambda (idx-str)
                     (let ((idx (ignore-errors (parse-integer idx-str))))
                       (when idx
                         (session-move-window session win idx)))))))
  (:swap-window
   (with-active-window (win session)
     (prompt-start "swap-window" ""
                   (lambda (idx-str)
                     ;; The typed value is a window INDEX (id), not a list position.
                     (let ((dst-id (ignore-errors (parse-integer idx-str))))
                       (when dst-id
                         (%swap-window-ids
                          session win
                          (find dst-id (session-windows session)
                                :key #'window-id))))))))
  (:rotate-window
   (with-active-window (win session)
     (window-rotate win :up)))
  (:rotate-window-reverse
   (with-active-window (win session)
     (window-rotate win :down)))
  (:find-window
   (prompt-start "find-window" ""
                 (lambda (pattern)
                   (unless (string= pattern "")
                     (let* ((wins (session-windows session))
                            ;; Shared with the scriptable find-window command so the
                            ;; match rule has a single definition (%window-matches-pattern-p).
                            (matches
                             (remove-if-not
                              (lambda (w) (%window-matches-pattern-p w pattern))
                              wins)))
                       (show-overlay
                        (if matches
                            (with-output-to-string (stream)
                              (dolist (w matches)
                                (format stream "~A: ~A~A~%"
                                        (cl-tmux/model:window-id w)
                                        (window-name w)
                                        (if (eq w (session-active-window session))
                                            " [active]" ""))))
                            (format nil "no windows matching ~S~%" pattern))))))))

  ;; ── Pane management ────────────────────────────────────────────────────────
  (:swap-pane-forward  (%swap-active-pane session :right))
  (:swap-pane-backward (%swap-active-pane session :left))
  (:swap-pane-up       (%swap-active-pane session :up))
  (:swap-pane-down     (%swap-active-pane session :down))
  (:last-pane
   ;; Jump to the previously active pane.  The byte arg encodes a -Z zoom
   ;; toggle modifier: when called with a specific flag byte, zoom the pane.
   ;; In practice :last-pane is always dispatched without a zoom flag via C-b ;
   ;; but %cmd-last-pane-arg (the arg-taking variant) can pass :zoom-toggle.
   (let* ((win  (session-active-window session))
          (last (and win (window-last-active win))))
     (when last (%select-pane-with-focus win last))))
  (:display-panes
   ;; Show big per-pane numbers (drawn by the renderer while *display-panes-active*),
   ;; matching real tmux.  An (empty) transient overlay is the timing vehicle: it
   ;; auto-dismisses after display-panes-time ms (and on the next key), and clearing
   ;; it also clears *display-panes-active* so the numbers vanish with it.
   (with-active-window (win session)
     (let ((panes (window-panes win)))
       (when panes
         (let* ((panes-ms (or (cl-tmux/options:get-option "display-panes-time") 1000))
                (saved-ms (cl-tmux/options:get-option "display-time" 750)))
           (cl-tmux/options:set-option "display-time" panes-ms)
           (show-transient-overlay "")            ; resets *display-panes-active* to NIL …
           (setf cl-tmux/prompt:*display-panes-active* t)  ; … then we arm it
           (cl-tmux/options:set-option "display-time" saved-ms)
           (setf *dirty* t))))))

  ;; ── Client switching ───────────────────────────────────────────────────────
  (:switch-client-next (%cmd-cycle-session session #'next-cyclic))
  (:switch-client-prev (%cmd-cycle-session session #'prev-cyclic))
  (:last-session
   (let* ((sessions (sort (mapcar #'cdr *server-sessions*) #'>
                          :key #'session-last-active))
          (second   (second sessions)))
     (when second
       (%switch-to-session second))))

  ;; ── Message / info ─────────────────────────────────────────────────────────
  (:display-message
   (prompt-start "display-message" ""
                 (lambda (msg)
                   (unless (string= msg "")
                     ;; Expand the message as a format too, so the two-step prompt
                     ;; and the one-line "display-message <fmt>" behave the same.
                     (%cmd-display-message session (list msg))))))
  (:source-file
   (prompt-start "source-file" ""
                 (lambda (path)
                   (unless (string= path "")
                     (load-config-file (pathname path))))))
  (:show-options
   (show-overlay (cl-tmux/options:show-options)))
  (:show-option
   (prompt-start "show-option" ""
                 (lambda (name)
                   (unless (string= name "")
                     (show-overlay (cl-tmux/options:show-option name))))))
  ;; show-window-options / show-session-options / show-server-options:
  ;; per-scope option listing.  cl-tmux uses a flat global store; these show
  ;; it with a scope header to match real tmux output format.
  ;; The three bodies are generated by define-show-options-handler above.
  (:show-window-options  (%show-window-options))
  (:show-session-options (%show-session-options))
  (:show-server-options  (%show-server-options))
  (:confirm-before
   (prompt-start "confirm? (y/n)" ""
                 (lambda (input)
                   (when (and (not (string= input ""))
                              (string-equal input "y"))
                     (show-overlay "[confirmed]")))))

  ;; :wait-for is the canonical wait-for-channel command.
  (:wait-for
   (%signal-channel-prompt "wait-for channel"))

)
