(in-package #:cl-tmux)

(defparameter *dispatch-command-specs-core-session-entries*
  '((:new-window '%cmd-new-window-arg ("new-window"))
    (:new-session '%cmd-new-session-arg ("new-session" "new"))
    (:kill-session '%cmd-kill-session-arg ("kill-session"))
    (:detach '%cmd-detach-client-arg ("detach-client")
     :named-names ("detach" "detach-client"))
    (:next-window '%cmd-next-window-arg ("next-window"))
    (:prev-window '%cmd-previous-window-arg ("previous-window")
     :named-names ("prev-window" "previous-window"))
    (:rename-session '%cmd-rename-session ("rename-session" "rename"))
    (:list-sessions '%cmd-list-sessions-arg ("list-sessions" "ls"))
    (:choose-session '%cmd-choose-session ("choose-session"))
    (:refresh-client '%cmd-refresh-client-arg ("refresh-client"))
    (:choose-client '%cmd-choose-client ("choose-client"))
    (:lock-session '%cmd-lock-session-arg ("lock-session"))
    (:unlock-session '%cmd-unlock-session ("unlock-session"))
    (:has-session '%cmd-has-session-arg ("has-session"))
    (:wait-for '%cmd-wait-for-arg ("wait-for"))
    (:server-info '%cmd-server-info ("server-info"))
    (:list-clients '%cmd-list-clients-arg ("list-clients"))
    (:suspend-client '%cmd-suspend-client ("suspend-client"))
    (:lock-server '%cmd-lock-server ("lock-server"))
    (:kill-server '%cmd-kill-server ("kill-server"))
    (:start-server '%cmd-start-server ("start-server"))
    (:attach-session '%cmd-attach-session-arg ("attach-session"))
    (:show-environment '%cmd-show-environment-arg ("show-environment"))
    (:set-environment '%cmd-set-environment-prompt ("set-environment"))
    (:show-prompt-history '%cmd-show-prompt-history ("show-prompt-history"))
    (:clear-prompt-history '%cmd-clear-prompt-history ("clear-prompt-history"))
    (:detach-all-clients '%cmd-detach-all-clients ("detach-all-clients"))
    (:lock-client '%cmd-lock-client-arg ("lock-client"))
    (:display-info '%cmd-display-info ("display-info"))))
