(in-package #:cl-tmux)

(defparameter *dispatch-command-specs-core-misc-entries*
  '((:set-buffer '%cmd-set-buffer-arg ("set-buffer")
                 :public-name "set-buffer")
    (:display-message '%cmd-display-message ("display-message"))
    (:display-menu '%cmd-display-menu-arg ("display-menu")
                   :named-names ("menu"))
    (:set-hook '%cmd-set-hook ("set-hook"))
    (:set-option '%cmd-set-option ("set-option"))
    (:set-window-option '%cmd-set-window-option ("set-window-option"))
    (:show-options '%cmd-show-options-arg ("show-options"))
    (:show-messages '%cmd-show-messages-arg ("show-messages"))
    (:show-window-options '%cmd-show-window-options-arg ("show-window-options"))
    (:show-session-options '%cmd-show-session-options-arg ("show-session-options"))
    (:show-server-options '%cmd-show-server-options-arg ("show-server-options"))
    (:server-access '%cmd-server-access ("server-access"))
    (:run-shell '%cmd-run-shell-arg ("run-shell"))
    (:if-shell '%cmd-if-shell-arg ("if-shell"))
    (:source-file '%cmd-source-file ("source-file"))
    (:list-commands '%cmd-list-commands-arg ("list-commands"))
    (:customize-mode '%cmd-customize-mode ("customize-mode"))))
