(in-package #:cl-tmux)

;;;; Command handler rule table — generated by define-command-handlers macro.
;;;;
;;;; This file contains the define-command-handlers macro definition and its
;;;; invocation with the core command handler rules.  Each handler maps a
;;;; keyword dispatch symbol to an action on the current session.
;;;;
;;;; Macros and helper functions used by these handlers are defined in
;;;; dispatch-core.lisp.  The generated dispatch-command function is the
;;;; central entry point for ALL prefix-key command dispatch.
;;;;
;;;; Copy-mode command handlers live in dispatch-handlers-copy-mode.lisp.
;;;; Paste-buffer command handlers live in dispatch-handlers-buffer.lisp.

;;; -- Scoped-options handler macro -------------------------------------------
;;;
;;; :show-window-options, :show-session-options, and :show-server-options all
;;; follow the same shape: (show-overlay (with-output-to-string (s) (format s "# SCOPE options") ...)).
;;; define-show-options-handler emits one named helper function per scope so the
;;; three handlers delegate to a generated function rather than duplicating the body.

(defmacro define-show-options-handler (fn-name scope-label &optional scope-arg)
  "Generate a zero-argument function named FN-NAME that shows a scoped options
   overlay.  SCOPE-LABEL is the string written after '# ' in the header line.
   SCOPE-ARG (a keyword) is forwarded to cl-tmux/options:show-options when
   provided; when absent the default (all options) form is used."
  `(defun ,fn-name ()
     ,(format nil "Show an overlay listing ~A options." scope-label)
     (show-overlay
      (with-output-to-string (stream)
        (format stream ,(format nil "# ~A options~%" scope-label))
        ,(if scope-arg
             `(write-string (cl-tmux/options:show-options ,scope-arg) stream)
             `(write-string (cl-tmux/options:show-options) stream))))))

(define-show-options-handler %show-window-options  "window")
(define-show-options-handler %show-session-options "session")
(define-show-options-handler %show-server-options  "server"  :server)

;;; -- define-command-handlers macro + dispatch-command ----------------------
;;;
;;; Handlers are registered into a hash table at load time; dispatch-command
;;; does a runtime gethash lookup.  This allows multiple define-command-handlers
;;; calls across different files — each one assertz-es additional facts without
;;; requiring the entire handler table to live in one monolithic form.

(defvar *command-dispatch-table* (make-hash-table)
  "Keyword → handler-fn.  Populated by define-command-handlers; consulted by dispatch-command.")

(defmacro define-command-handlers (&rest rules)
  "Register command handlers into *command-dispatch-table*.
   Each RULE is (kw-or-kws &rest body) where kw-or-kws is a keyword or a list
   of keywords (case-sharing, like CL case multi-key clauses).
   SESSION and BYTE are bound in each handler body.
   Multiple calls accumulate; later registrations for the same keyword override earlier ones.
   If a handler returns :QUIT or :DETACH that outcome is forwarded by dispatch-command."
  (let ((forms
         (loop for rule in rules
               for (kw-or-kws . body) = rule
               nconcing
               (let ((kws (if (listp kw-or-kws) kw-or-kws (list kw-or-kws))))
                 (mapcar (lambda (kw)
                           `(setf (gethash ,kw *command-dispatch-table*)
                                  (lambda (session byte)
                                    (declare (ignorable session byte))
                                    ,@body)))
                         kws)))))
    `(progn ,@forms)))

(defun dispatch-command (session cmd byte)
  "Dispatch CMD to its registered handler.  Sets *dirty* for all outcomes
   except :quit and :detach, which are returned as-is."
  (declare (ignorable byte))
  (let* ((handler (gethash cmd *command-dispatch-table*))
         (outcome (when handler (funcall handler session byte))))
    (case outcome
      ((:quit :detach) outcome)
      (otherwise (setf *dirty* t) nil))))

;;; -- Buffer preview constant -----------------------------------------------
;;;
;;; Buffer listing and preview truncate content to this many characters.
;;; Previously the literal 40 appeared three times across handlers; a single
;;; named constant makes intent explicit and keeps all three in sync.

(defconstant +buffer-preview-length+ 40
  "Maximum characters shown in a paste-buffer preview listing.")

(defun %confirm-prompt (msg ok-fn)
  "Show MSG as a y/n prompt; call OK-FN (no args) when the user types y/Y."
  (prompt-start msg ""
                (lambda (input)
                  (when (string-equal input "y")
                    (funcall ok-fn)))
                :single-key t))

(defun prompt-nonempty (label callback &key history)
  "Start a prompt labelled LABEL; call CALLBACK with the input only when non-empty."
  (prompt-start label ""
                (lambda (input)
                  (unless (string= input "")
                    (funcall callback input)))
                :history history))

(defun prompt-integer (label callback)
  "Start a prompt labelled LABEL; call CALLBACK with the parsed integer when the
   input parses as a valid integer.  Silently ignores non-numeric input."
  (prompt-start label ""
                (lambda (input)
                  (let ((n (ignore-errors (parse-integer input))))
                    (when n (funcall callback n))))))

(defun %byte-vector (byte)
  "Return a one-byte unsigned vector containing BYTE."
  (make-array 1 :element-type '(unsigned-byte 8) :initial-element byte))

(defun %copy-mode-search-prompt (session prompt-char search-fn)
  "Open a copy-mode search prompt with PROMPT-CHAR prefix and call SEARCH-FN
   on the entered term when non-empty."
  (let ((screen (%active-screen session)))
    (when screen
      (prompt-nonempty prompt-char
                       (lambda (term) (funcall search-fn screen term))))))

(defun %show-jk-menu (title items &optional empty-msg)
  "Show ITEMS as an interactive j/k menu titled TITLE.
   When ITEMS is empty and EMPTY-MSG is given, show EMPTY-MSG as a plain overlay instead."
  (if (and (null items) empty-msg)
      (show-overlay empty-msg)
      (progn
        (show-menu (make-menu :title title :items items :selected-index 0))
        (show-overlay (%format-menu *active-menu*)))))

;;; ── Copy-mode dispatch table helper ─────────────────────────────────────────
;;;
;;; 45 copy-mode handlers follow one uniform contract:
;;;   (KEYWORD (%copy-mode-call session #'FUNCTION))
;;; define-copy-mode-dispatch-handlers encodes that contract so the handler
;;; table reads as pure keyword → function-symbol data, with no boilerplate.

(defmacro define-copy-mode-dispatch-handlers (&rest entries)
  "Register copy-mode handlers of the form (%copy-mode-call session #'FN).
   Each ENTRY is (KEYWORD FN-SYMBOL).  Expands to define-command-handlers."
  `(define-command-handlers
     ,@(mapcar (lambda (entry)
                 `(,(first entry) (%copy-mode-call session #',(second entry))))
               entries)))

(defun %copy-mode-cursor-fn (direction)
  "Return a one-arg function that moves the copy-mode cursor in DIRECTION."
  (lambda (s) (copy-mode-move-cursor s direction)))

(define-command-handlers
  (:detach :detach)
  (:new-window (%cmd-new-window session))
  (:next-window (%cmd-cycle-window session #'next-cyclic))
  (:prev-window (%cmd-cycle-window session #'prev-cyclic))
  (:next-pane (%cmd-cycle-pane session #'next-cyclic))
  (:prev-pane (%cmd-cycle-pane session #'prev-cyclic))
  (:split-horizontal (%cmd-split session :v))        ; C-b " adds a horizontal bar → :v stacking
  (:split-vertical   (%cmd-split session :h))        ; C-b % adds a vertical bar   → :h side-by-side
  (:split-horizontal-no-focus (%cmd-split session :v :no-focus t))
  (:split-vertical-no-focus   (%cmd-split session :h :no-focus t))
  (:kill-pane   (%handle-kill-result (kill-pane session)))
  (:kill-window (%handle-kill-result (kill-window session (session-active-window session))))
  (:kill-pane-confirm
   (with-active-window (win session)
     (let* ((ap  (window-active-pane win))
            (msg (if ap (format nil "kill-pane ~D? (y/n)" (pane-id ap)) "kill-pane? (y/n)")))
       (%confirm-prompt msg (lambda () (%handle-kill-result (kill-pane session)))))))
  (:kill-window-confirm
   (with-active-window (win session)
     (%confirm-prompt (format nil "kill-window ~A? (y/n)" (window-name win))
                      (lambda () (%handle-kill-result
                                  (kill-window session (session-active-window session)))))))
  (:respawn-pane
   (with-active-window (win session)
     (let ((ap (window-active-pane win)))
       (when ap
         (let ((new-pane (respawn-pane ap)))
           (start-reader-thread new-pane))))))
  (:rename-window
   (with-active-window (win session)
     (prompt-start "rename-window" (window-name win)
                   (lambda (name) (rename-window win name)))))
  (:list-keys (show-overlay (describe-key-bindings)))

  ;; ── Copy-mode handlers ─────────────────────────────────────────────────────
  ;; The 45 standard (%copy-mode-call session #'fn) handlers live in the
  ;; define-copy-mode-dispatch-handlers call in dispatch-handlers-copy-mode.lisp.
  ;; Non-standard copy-mode handlers follow here (cursor-fn / lambdas / no-ops).

  ;; cursor-direction: %copy-mode-cursor-fn builds the one-arg direction lambda
  (:copy-mode-cursor-left   (%copy-mode-call session (%copy-mode-cursor-fn :left)))
  (:copy-mode-cursor-right  (%copy-mode-call session (%copy-mode-cursor-fn :right)))
  (:copy-mode-cursor-up     (%copy-mode-call session (%copy-mode-cursor-fn :up)))
  (:copy-mode-cursor-down   (%copy-mode-call session (%copy-mode-cursor-fn :down)))
  ;; no-op: copy mode reads the live pane, so no explicit refresh step
  (:copy-mode-refresh-from-pane (values))
  ;; copy-pipe variants pass an extra NIL arg the standard path cannot encode.
  (:copy-mode-copy-pipe-and-cancel
   (%copy-mode-call session (lambda (s) (copy-mode-copy-pipe s nil))))
  (:copy-mode-copy-pipe-no-cancel
   (%copy-mode-call session (lambda (s) (copy-mode-copy-pipe-no-cancel s nil))))
  (:copy-mode-copy-pipe-end-of-line-and-cancel
   (%copy-mode-call session (lambda (s) (copy-mode-copy-pipe-end-of-line s nil))))
  ;; search prompts open an interactive prompt — they don't go through %copy-mode-call
  (:copy-mode-search-forward-prompt
   (%copy-mode-search-prompt session "/" #'copy-mode-search-forward))
  (:copy-mode-search-backward-prompt
   (%copy-mode-search-prompt session "?" #'copy-mode-search-backward))
  ;; stubs: handled via extra-args in %dispatch-send-keys-X so the table lookup doesn't miss
  (:copy-mode-search-forward-text  (values))
  (:copy-mode-search-backward-text (values))
  ;; choose-buffer renders a live buffer listing overlay
  (:copy-mode-choose-buffer
   (show-built-overlay (stream)
     (let ((buffers (cl-tmux/buffer:list-paste-buffers)))
       (if buffers
           (loop for buffer in buffers
                 for index from 0
                 do (format stream "~D: ~A~%"
                            index
                            (subseq buffer 0 (min +buffer-preview-length+
                                                  (length buffer)))))
           (format stream "(no paste buffers)~%")))))

  ;; ── Resize commands ────────────────────────────────────────────────────────
  (:resize-left   (resize-pane (session-active-window session) :left))
  (:resize-right  (resize-pane (session-active-window session) :right))
  (:resize-up     (resize-pane (session-active-window session) :up))
  (:resize-down   (resize-pane (session-active-window session) :down))

  ;; ── Paste / send ──────────────────────────────────────────────────────────
  (:select-window (when byte (select-window-by-number session (- byte (char-code #\0)))))
  (:paste-buffer
   (let* ((text (cl-tmux/buffer:get-paste-buffer))
          (win  (session-active-window session))
          (ap   (and win (window-active-pane win))))
     (%paste-to-pane ap text)))
  (:send-prefix
   ;; Send the currently configured prefix key byte, not the compile-time default.
   ;; *prefix-key-code* is updated when `set prefix` runs; +prefix-key-code+ is fixed.
   (with-active-pane (ap session)
     (when (and (not *client-read-only*) (> (pane-fd ap) 0))
       (pty-write (pane-fd ap) (%byte-vector cl-tmux/config:*prefix-key-code*)))))

  ;; ── Layout commands ────────────────────────────────────────────────────────
  (:select-layout-even-h    (%apply-named-layout-to-session session :even-horizontal))
  (:select-layout-even-v    (%apply-named-layout-to-session session :even-vertical))
  (:select-layout-tiled     (%apply-named-layout-to-session session :tiled))
  (:select-layout-main-h    (%apply-named-layout-to-session session :main-horizontal))
  (:select-layout-main-v    (%apply-named-layout-to-session session :main-vertical))

  ;; ── Pane selection ────────────────────────────────────────────────────────
  (:select-pane-left   (%select-pane-in-direction session :left))
  (:select-pane-right  (%select-pane-in-direction session :right))
  (:select-pane-up     (%select-pane-in-direction session :up))
  (:select-pane-down   (%select-pane-in-direction session :down))

  ;; ── Zoom ──────────────────────────────────────────────────────────────────
  (:zoom-toggle
   (with-active-window (win session)
     (window-zoom-toggle win)))

  ;; ── Session management ────────────────────────────────────────────────────
  (:rename-session
   (prompt-start "rename-session" (session-name session)
                 (lambda (name)
                   ;; Refuses a duplicate name and fires session-renamed (shared
                   ;; chokepoint with the rename-session command).
                   (%rename-session-checked session name))))
  (:run-shell
   (prompt-nonempty "run-shell"
                    (lambda (cmd)
                      (show-overlay (run-shell cmd)))))
  (:if-shell
   (prompt-nonempty "if-shell"
                    (lambda (cmd)
                      (if-shell cmd
                                (lambda () (%overlayf "[if-shell] ~A: ok" cmd))
                                :else-fn (lambda () (%overlayf "[if-shell] ~A: non-zero exit" cmd))))))

  ;; :list-sessions / :list-sessions-full: static session list overlay.
  ((:list-sessions :list-sessions-full)
   (show-overlay (%format-session-list session)))

  ;; :choose-session: interactive j/k menu to switch sessions (C-b s).
  ;; Builds a menu with one entry per session; selecting switches to it.
  (:choose-session
   (let* ((sessions (or *server-sessions*
                        (list (cons (session-name session) session))))
          (items    (loop for (name . sess) in sessions
                          collect (cons (format nil "~A~A (~D window~:P)"
                                                (if (eq sess session) "*" " ")
                                                name
                                                (length (cl-tmux/model:session-windows sess)))
                                        ;; Command stored as (:switch-client name),
                                        ;; dispatched by :menu-select.
                                        (list :switch-client name)))))
     (%show-jk-menu "choose-session (j/k, Enter)" items)))
  (:new-session
   (let* ((rows (- *term-rows* *status-height*))
          (cols *term-cols*)
          (n    (1+ (length *server-sessions*)))
          (name (format nil "~D" n)))
     (new-session name rows cols)))
  (:kill-session
   ;; Destroy the current session, then apply detach-on-destroy: :quit (detach →
   ;; exit standalone) or NIL (switch to a survivor; the loop follows it).
   (let ((name (session-name session)))
     (%destroy-session session)
     (let ((action (%detach-on-destroy-action name)))
       (when (eq action :quit) (setf *running* nil))
       action)))
  (:has-session
   (prompt-start "has-session" ""
                 (lambda (name)
                   (let ((found (server-find-session name)))
                     (show-overlay (if found "yes" "no"))))))

  ;; ── Window management ──────────────────────────────────────────────────────
  (:list-windows (show-overlay (%format-window-list session)))
  ;; :choose-window: interactive j/k menu to select a window (C-b w).
  ;; Builds a menu with one entry per window; Enter selects, q/Esc dismisses.
  (:choose-window
   (let* ((wins  (session-windows session))
          (act   (session-active-window session))
          (items (mapcar (lambda (w)
                           (cons (format nil "~A~A: ~A (~D pane~:P)"
                                         (if (eq w act) "*" " ")
                                         (window-id w)
                                         (window-name w)
                                         (length (window-panes w)))
                                 ;; Command: select this window by id.
                                 (list :select-window (window-id w))))
                         wins)))
     (%show-jk-menu "choose-window (j/k, Enter)" items "(no windows)")))
  (:last-window
   (let ((prev (session-last-window session)))
     (when prev
       (%with-window-focus-transition (session)
         (session-select-window session prev)
         (setf (window-last-active-time prev) (get-universal-time))))))
  (:move-window
   (with-active-window (win session)
     (prompt-integer "move-window"
                     (lambda (idx) (session-move-window session win idx)))))
  (:swap-window
   (with-active-window (win session)
     ;; The typed value is a window INDEX (id), not a list position.
     (prompt-integer "swap-window"
                     (lambda (dst-id)
                       (%swap-window-ids
                        session win
                        (find dst-id (session-windows session)
                              :key #'window-id))))))
  (:rotate-window
   (with-active-window (win session)
     (window-rotate win :up)))
  (:rotate-window-reverse
   (with-active-window (win session)
     (window-rotate win :down)))
  (:find-window
   (prompt-nonempty "find-window"
                    (lambda (pattern)
                      (let* ((wins    (session-windows session))
                             (matches (remove-if-not
                                       (lambda (w) (%window-matches-pattern-p w pattern))
                                       wins)))
                        (show-overlay
                         (if matches
                             (with-output-to-string (stream)
                               (dolist (w matches)
                                 (format stream "~A: ~A~A~%"
                                         (cl-tmux/model:window-id w)
                                         (window-name w)
                                         (if (eq w (session-active-window session))
                                             " [active]" ""))))
                             (format nil "no windows matching ~S~%" pattern)))))))

  ;; ── Pane management ────────────────────────────────────────────────────────
  (:swap-pane-forward  (%swap-active-pane session :right))
  (:swap-pane-backward (%swap-active-pane session :left))
  (:swap-pane-up       (%swap-active-pane session :up))
  (:swap-pane-down     (%swap-active-pane session :down))
  (:last-pane
   ;; Jump to the previously active pane.  The byte arg encodes a -Z zoom
   ;; toggle modifier: when called with a specific flag byte, zoom the pane.
   ;; In practice :last-pane is always dispatched without a zoom flag via C-b ;
   ;; but %cmd-last-pane-arg (the arg-taking variant) can pass :zoom-toggle.
   (let* ((win  (session-active-window session))
          (last (and win (window-last-active win))))
     (when last (%select-pane-with-focus win last))))
  (:display-panes
   ;; Show big per-pane numbers (drawn by the renderer while *display-panes-active*),
   ;; matching real tmux.  An (empty) transient overlay is the timing vehicle: it
   ;; auto-dismisses after display-panes-time ms (and on the next key), and clearing
   ;; it also clears *display-panes-active* so the numbers vanish with it.
   (with-active-window (win session)
     (let ((panes (window-panes win)))
       (when panes
         (let* ((panes-ms (or (cl-tmux/options:get-option "display-panes-time") 1000))
                (saved-ms (cl-tmux/options:get-option "display-time" 750)))
           (cl-tmux/options:set-option "display-time" panes-ms)
           (show-transient-overlay "")            ; resets *display-panes-active* to NIL …
           (setf cl-tmux/prompt:*display-panes-active* t)  ; … then we arm it
           (cl-tmux/options:set-option "display-time" saved-ms)
           (setf *dirty* t))))))

  ;; ── Client switching ───────────────────────────────────────────────────────
  (:switch-client-next (%cmd-cycle-session session #'next-cyclic))
  (:switch-client-prev (%cmd-cycle-session session #'prev-cyclic))
  (:last-session
   (let* ((sessions (sort (mapcar #'cdr *server-sessions*) #'>
                          :key #'session-last-active))
          (second   (second sessions)))
     (when second
       (%switch-to-session second))))

  ;; ── Message / info ─────────────────────────────────────────────────────────
  (:display-message
   (prompt-nonempty "display-message"
                    (lambda (msg)
                      (%cmd-display-message session (list msg)))))
  (:source-file
   (prompt-nonempty "source-file"
                    (lambda (path)
                      (load-config-file (pathname path)))))
  (:show-options
   (show-overlay (cl-tmux/options:show-options)))
  ;; show-window-options / show-session-options / show-server-options:
  ;; per-scope option listing.  cl-tmux uses a flat global store; these show
  ;; it with a scope header to match real tmux output format.
  ;; The three bodies are generated by define-show-options-handler above.
  (:show-window-options  (%show-window-options))
  (:show-session-options (%show-session-options))
  (:show-server-options  (%show-server-options))
  (:confirm-before
   (prompt-start "confirm? (y/n)" ""
                 (lambda (input)
                   (when (string-equal input "y")
                     (show-overlay "[confirmed]")))))

  ;; :wait-for is the canonical wait-for-channel command.
  (:wait-for
   (%signal-channel-prompt "wait-for channel"))

)

;;; ── Copy-mode standard dispatch table ───────────────────────────────────────
;;;
;;; The copy-mode table is split into dispatch-handlers-copy-mode.lisp so this
;;; coordinator file stays focused on shared helpers, macro definitions, and the
;;; main command handler table.
