(in-package #:cl-tmux)

(defparameter *dispatch-command-specs-core-window-entries*
  '((:kill-window '%cmd-kill-window ("kill-window"))
    (:rename-window '%cmd-rename-window ("rename-window"))
    (:list-windows '%cmd-list-windows-arg ("list-windows"))
    (:display-panes '%cmd-display-panes-arg ("display-panes"))
    (:show-hooks '%cmd-show-hooks ("show-hooks"))
    (:zoom-toggle '%cmd-zoom-toggle ("zoom-toggle"))
    (:choose-tree '%cmd-choose-tree ("choose-tree"))
    (:choose-window '%cmd-choose-window ("choose-window"))
    (:select-window '%cmd-select-window ("select-window"))
    (:move-window-prompt '%cmd-move-window ("move-window")
     :named-names ("move-window"))
    (:link-window '%cmd-link-window ("link-window"))
    (:unlink-window '%cmd-unlink-window ("unlink-window"))
    (:select-layout '%cmd-select-layout ("select-layout"))
    (:rotate-window '%cmd-rotate-window-arg ("rotate-window"))
    (:find-window '%cmd-find-window-arg ("find-window"))
    (:command-prompt '%cmd-command-prompt-arg ("command-prompt"))
    (:last-window '%cmd-last-window-arg ("last-window"))
    (:display-popup '%cmd-display-popup ("display-popup"))
    (:next-layout '%cmd-next-layout ("next-layout"))
    (:previous-layout '%cmd-previous-layout ("previous-layout"))
    (:swap-window '%cmd-swap-window ("swap-window"))
    (:confirm-before '%cmd-confirm-before ("confirm-before"))
    (:clock-mode '%cmd-clock-mode ("clock-mode"))))
