(in-package #:cl-tmux)

(defparameter *dispatch-command-specs-compat-window-entries*
  '((%cmd-select-window ("select-window"))
    (%cmd-swap-window ("swap-window"))
    (%cmd-move-window ("move-window"))
    (%cmd-link-window ("link-window"))
    (%cmd-unlink-window ("unlink-window"))
    (%cmd-select-layout ("select-layout" "selectl"))
    (%cmd-new-window-arg ("new-window"))
    (%cmd-resize-window-arg ("resize-window"))
    (%cmd-list-windows-arg ("list-windows" "lsw"))
    (%cmd-rotate-window-arg ("rotate-window"))
    (%cmd-find-window-arg ("find-window"))
    (%cmd-respawn-window-arg ("respawn-window"))
    (%cmd-next-window-arg ("next-window"))
    (%cmd-previous-window-arg ("previous-window"))
    (%cmd-last-window-arg ("last-window"))
    (%cmd-confirm-before-arg ("confirm-before"))
    (%cmd-command-prompt-arg ("command-prompt"))
    (%cmd-display-menu-arg ("display-menu"))
    (%cmd-display-popup ("display-popup"))))
