(in-package #:cl-tmux)

(defparameter *dispatch-command-specs-compat-pane-entries*
  '((%cmd-select-pane ("select-pane" "selectp"))
    (%cmd-send-keys-arg ("send-keys" "send-key" "send"))
    (%cmd-resize-pane-arg ("resize-pane" "resizep"))
    (%cmd-pipe-pane-arg ("pipe-pane" "pipep"))
    (%cmd-list-panes-arg-full ("list-panes"))
    (%cmd-display-panes-arg ("display-panes"))
    (%cmd-copy-mode-arg ("copy-mode"))
    (%cmd-list-keys-arg ("list-keys"))
    (%cmd-swap-pane-arg ("swap-pane"))
    (%cmd-join-pane-arg ("join-pane" "move-pane"))
    (%cmd-break-pane-arg ("break-pane"))
    (%cmd-clear-history-arg ("clear-history"))
    (%cmd-respawn-pane-arg ("respawn-pane"))
    (%cmd-last-pane-arg ("last-pane"))))
