(in-package #:cl-tmux)

;;;; Command handler rule table — generated by define-command-handlers macro.
;;;;
;;;; This file contains the define-command-handlers macro definition and its
;;;; invocation with the core command handler rules.  Each handler maps a
;;;; keyword dispatch symbol to an action on the current session.
;;;;
;;;; Macros and helper functions used by these handlers are defined in
;;;; dispatch-core.lisp.  The generated dispatch-command function is the
;;;; central entry point for ALL prefix-key command dispatch.
;;;;
;;;; Copy-mode command handlers live in dispatch-handlers-copy-mode.lisp.
;;;; Paste-buffer command handlers live in dispatch-handlers-buffer.lisp.

;;; -- define-command-handlers macro + dispatch-command ----------------------

(defmacro define-command-handlers (&rest rules)
  "Each RULE is (keyword &body forms); SESSION and BYTE are bound in each body.
   If a rule evaluates to :QUIT or :DETACH that outcome is returned directly.
   All other outcomes mark *DIRTY* and return NIL."
  `(defun dispatch-command (session cmd byte)
     (declare (ignorable byte))
     (let ((outcome
             (case cmd
               ,@(mapcar (lambda (rule)
                           (destructuring-bind (kw &rest body) rule
                             `(,kw (progn ,@body))))
                         rules)
               (otherwise nil))))
       (case outcome
         ((:quit :detach) outcome)
         (otherwise (setf *dirty* t) nil)))))

;;; -- Popup overlay constants -----------------------------------------------
;;;
;;; These bounds cap the popup overlay geometry so it never exceeds the
;;; terminal dimensions.  Named constants replace the magic literals 60, 15, 4
;;; that previously appeared inline in the :display-popup handler.

(defconstant +popup-max-width+  60 "Maximum column width of a popup overlay.")
(defconstant +popup-max-height+ 15 "Maximum row height of a popup overlay.")
(defconstant +popup-margin+      4 "Row margin subtracted from terminal height for popups.")

;;; -- Buffer preview constant -----------------------------------------------
;;;
;;; Buffer listing and preview truncate content to this many characters.
;;; Previously the literal 40 appeared three times across handlers; a single
;;; named constant makes intent explicit and keeps all three in sync.

(defconstant +buffer-preview-length+ 40
  "Maximum characters shown in a paste-buffer preview listing.")

;;; -- Popup overlay formatter helper -----------------------------------------
;;;
;;; Extracted from the :display-popup handler to match the established pattern
;;; of named formatters (%format-menu, %format-tree-entry, %format-window-list).

(defun %format-popup-overlay (title output)
  "Format a popup overlay string with box-drawing borders.
   TITLE is the popup header text; OUTPUT is the body content."
  (format nil "┌─ ~A ─┐~%~A~%└~A┘"
          title
          (or output "")
          (make-string (+ 2 (length title)) :initial-element #\─)))

(define-command-handlers
  (:detach :detach)
  (:new-window (%cmd-new-window session))
  (:next-window (%cmd-cycle-window session #'next-cyclic))
  (:prev-window (%cmd-cycle-window session #'prev-cyclic))
  (:next-pane (%cmd-cycle-pane session #'next-cyclic))
  (:prev-pane (%cmd-cycle-pane session #'prev-cyclic))
  (:split-horizontal (%cmd-split session :v))        ; C-b " adds a horizontal bar → :v stacking
  (:split-vertical   (%cmd-split session :h))        ; C-b % adds a vertical bar   → :h side-by-side
  (:split-horizontal-no-focus (%cmd-split session :v :no-focus t))
  (:split-vertical-no-focus   (%cmd-split session :h :no-focus t))
  (:kill-pane   (%handle-kill-result (kill-pane session)))
  (:kill-window (%handle-kill-result (kill-window session (session-active-window session))))
  (:kill-pane-confirm
   ;; Show a y/n prompt; call kill-pane only when the user enters "y"/"Y".
   (with-active-window (win session)
     (let* ((ap  (window-active-pane win))
            (msg (if ap
                     (format nil "kill-pane ~D? (y/n)" (pane-id ap))
                     "kill-pane? (y/n)")))
       (prompt-start msg ""
                     (lambda (input)
                       (when (string-equal input "y")
                         (%handle-kill-result (kill-pane session))))))))
  (:kill-window-confirm
   (with-active-window (win session)
     (let ((msg (format nil "kill-window ~A? (y/n)" (window-name win))))
       (prompt-start msg ""
                     (lambda (input)
                       (when (string-equal input "y")
                         (%handle-kill-result
                          (kill-window session (session-active-window session)))))))))
  (:respawn-pane
   (with-active-window (win session)
     (let ((ap (window-active-pane win)))
       (when ap
         (let ((new-pane (respawn-pane ap)))
           (start-reader-thread new-pane))))))
  (:rename-window
   (with-active-window (win session)
     (prompt-start "rename-window" (window-name win)
                   (lambda (name) (rename-window win name)))))
  (:list-keys (show-overlay (describe-key-bindings)))

  ;; ── Copy-mode command handlers ─────────────────────────────────────────────
  ;; Rules are defined here so dispatch-command covers them in one case form.
  ;; The implementations delegate to helpers in dispatch-handlers-copy-mode.lisp.

  (:copy-mode-enter            (%copy-mode-call session #'copy-mode-enter))
  (:copy-mode-exit             (%copy-mode-call session #'copy-mode-exit))
  (:copy-mode-begin-selection  (%copy-mode-call session #'copy-mode-begin-selection))
  (:copy-mode-yank             (%copy-mode-call session #'copy-mode-yank))
  (:copy-mode-word-forward     (%copy-mode-call session #'copy-mode-word-forward))
  (:copy-mode-word-backward    (%copy-mode-call session #'copy-mode-word-backward))
  (:copy-mode-word-end         (%copy-mode-call session #'copy-mode-word-end))
  (:copy-mode-line-start       (%copy-mode-call session #'copy-mode-line-start))
  (:copy-mode-line-end         (%copy-mode-call session #'copy-mode-line-end))
  (:copy-mode-top              (%copy-mode-call session #'copy-mode-top))
  (:copy-mode-bottom           (%copy-mode-call session #'copy-mode-bottom))
  (:copy-mode-high             (%copy-mode-call session #'copy-mode-high))
  (:copy-mode-middle           (%copy-mode-call session #'copy-mode-middle))
  (:copy-mode-low              (%copy-mode-call session #'copy-mode-low))
  (:copy-mode-page-up          (%copy-mode-call session #'copy-mode-page-up))
  (:copy-mode-page-down        (%copy-mode-call session #'copy-mode-page-down))
  (:copy-mode-half-page-up     (%copy-mode-call session #'copy-mode-half-page-up))
  (:copy-mode-half-page-down   (%copy-mode-call session #'copy-mode-half-page-down))
  (:copy-mode-scroll-up-line   (%copy-mode-call session #'copy-mode-scroll-up-line))
  (:copy-mode-scroll-down-line (%copy-mode-call session #'copy-mode-scroll-down-line))
  (:copy-mode-begin-line-selection (%copy-mode-call session #'copy-mode-begin-line-selection))
  (:copy-mode-copy-end-of-line (%copy-mode-call session #'copy-mode-copy-end-of-line))
  (:copy-mode-copy-line        (%copy-mode-call session #'copy-mode-copy-line))
  (:copy-mode-search-next      (%copy-mode-call session #'copy-mode-search-next))
  (:copy-mode-search-prev      (%copy-mode-call session #'copy-mode-search-prev))
  (:copy-mode-search-forward-prompt
   (let ((active-screen (%active-screen session)))
     (when active-screen
       (prompt-start "/" ""
                     (lambda (term)
                       (unless (string= term "")
                         (copy-mode-search-forward active-screen term)))))))
  (:copy-mode-search-backward-prompt
   (let ((active-screen (%active-screen session)))
     (when active-screen
       (prompt-start "?" ""
                     (lambda (term)
                       (unless (string= term "")
                         (copy-mode-search-backward active-screen term)))))))
  (:copy-mode-choose-buffer
   (show-overlay
    (with-output-to-string (stream)
      (let ((buffers (cl-tmux/buffer:list-paste-buffers)))
        (if buffers
            (loop for buffer in buffers
                  for index from 0
                  do (format stream "~D: ~A~%"
                             index
                             (subseq buffer 0 (min +buffer-preview-length+
                                                   (length buffer)))))
            (format stream "(no paste buffers)~%"))))))

  ;; ── Resize commands ────────────────────────────────────────────────────────
  (:resize-left   (resize-pane (session-active-window session) :left))
  (:resize-right  (resize-pane (session-active-window session) :right))
  (:resize-up     (resize-pane (session-active-window session) :up))
  (:resize-down   (resize-pane (session-active-window session) :down))

  ;; ── Paste / send ──────────────────────────────────────────────────────────
  (:select-window (when byte (select-window-by-number session (- byte (char-code #\0)))))
  (:paste-buffer
   (let* ((text (cl-tmux/buffer:get-paste-buffer))
          (win  (session-active-window session))
          (ap   (and win (window-active-pane win))))
     (%paste-to-pane ap text)))
  (:send-prefix
   (flet ((byte-vec (b)
            (make-array 1 :element-type '(unsigned-byte 8) :initial-element b)))
     (with-active-pane (ap session)
       (when (> (pane-fd ap) 0)
         (pty-write (pane-fd ap) (byte-vec +prefix-key-code+))))))

  ;; ── Layout commands ────────────────────────────────────────────────────────
  (:select-layout-even-h    (%apply-named-layout-to-session session :even-horizontal))
  (:select-layout-even-v    (%apply-named-layout-to-session session :even-vertical))
  (:select-layout-tiled     (%apply-named-layout-to-session session :tiled))
  (:select-layout-main-h    (%apply-named-layout-to-session session :main-horizontal))
  (:select-layout-main-v    (%apply-named-layout-to-session session :main-vertical))

  ;; ── Pane selection ────────────────────────────────────────────────────────
  (:select-pane-left   (%select-pane-in-direction session :left))
  (:select-pane-right  (%select-pane-in-direction session :right))
  (:select-pane-up     (%select-pane-in-direction session :up))
  (:select-pane-down   (%select-pane-in-direction session :down))

  ;; ── Zoom ──────────────────────────────────────────────────────────────────
  (:zoom-toggle
   (with-active-window (win session)
     (window-zoom-toggle win)))

  ;; ── Session management ────────────────────────────────────────────────────
  (:rename-session
   (prompt-start "rename-session" (session-name session)
                 (lambda (name)
                   (unless (string= name "")
                     (server-remove-session (session-name session))
                     (rename-session session name)
                     (server-add-session session)))))
  (:run-shell
   (prompt-start "run-shell" ""
                 (lambda (cmd)
                   (unless (string= cmd "")
                     (let ((output (run-shell cmd)))
                       (show-overlay output))))))
  (:if-shell
   (prompt-start "if-shell" ""
                 (lambda (cmd)
                   (unless (string= cmd "")
                     (if-shell cmd
                               (lambda () (show-overlay (format nil "[if-shell] ~A: ok" cmd)))
                               :else-fn (lambda () (show-overlay (format nil "[if-shell] ~A: non-zero exit" cmd))))))))

  ;; :list-sessions, :list-sessions-full, and :choose-session share the same body.
  ;; The three keywords are kept as distinct binding targets (some bound to
  ;; different key-table entries) but a single shared form removes duplication.
  ((:list-sessions :list-sessions-full :choose-session)
   (show-overlay (%format-session-list session)))
  (:new-session
   (let* ((rows (- *term-rows* *status-height*))
          (cols *term-cols*)
          (n    (1+ (length *server-sessions*)))
          (name (format nil "~D" n)))
     (new-session name rows cols)))
  (:kill-session
   (let ((name (session-name session)))
     (dolist (pane (all-panes session))
       (ignore-errors (pty-close (pane-fd pane) (pane-pid pane))))
     (server-remove-session name)
     (if (null *server-sessions*)
         (progn (setf *running* nil) :quit)
         nil)))
  (:has-session
   (prompt-start "has-session" ""
                 (lambda (name)
                   (let ((found (server-find-session name)))
                     (show-overlay (if found "yes" "no"))))))

  ;; ── Window management ──────────────────────────────────────────────────────
  (:list-windows (show-overlay (%format-window-list session)))
  (:choose-window
   (let* ((wins  (session-windows session))
          (items (mapcar (lambda (w)
                           (cons (format nil "~A: ~A" (window-id w) (window-name w))
                                 (window-id w)))
                         wins)))
     (if items
         (progn
           (setf *active-menu*
                 (make-menu :title "choose-window" :items items :selected-index 0))
           (show-overlay (%format-menu *active-menu*))
           (prompt-start "window: " ""
                         (lambda (input)
                           (let ((n (ignore-errors (parse-integer input))))
                             (when n
                               (%with-window-focus-transition (session)
                                 (select-window-by-number session n))))
                           (setf *active-menu* nil)
                           (clear-overlay))))
         (show-overlay "(no windows)"))))
  (:last-window
   (let ((prev (session-last-window session)))
     (when prev
       (%with-window-focus-transition (session)
         (session-select-window session prev)
         (setf (window-last-active-time prev) (get-universal-time))))))
  (:move-window
   (with-active-window (win session)
     (prompt-start "move-window" ""
                   (lambda (idx-str)
                     (let ((idx (ignore-errors (parse-integer idx-str))))
                       (when idx
                         (session-move-window session win idx)))))))
  (:swap-window
   (with-active-window (win session)
     (let* ((wins    (session-windows session))
            (src-idx (position win wins)))
       (prompt-start "swap-window" ""
                     (lambda (idx-str)
                       (let ((dst (ignore-errors (parse-integer idx-str))))
                         (when (and dst src-idx)
                           (session-swap-windows session src-idx dst))))))))
  (:rotate-window
   (with-active-window (win session)
     (window-rotate win :up)))
  (:rotate-window-reverse
   (with-active-window (win session)
     (window-rotate win :down)))
  (:find-window
   (prompt-start "find-window" ""
                 (lambda (pattern)
                   (unless (string= pattern "")
                     (let* ((wins (session-windows session))
                            (matches
                             (remove-if-not
                              (lambda (w)
                                (search pattern (window-name w) :test #'char-equal))
                              wins)))
                       (show-overlay
                        (if matches
                            (with-output-to-string (stream)
                              (dolist (w matches)
                                (format stream "~A: ~A~A~%"
                                        (position w wins)
                                        (window-name w)
                                        (if (eq w (session-active-window session))
                                            " [active]" ""))))
                            (format nil "no windows matching ~S~%" pattern))))))))

  ;; ── Pane management ────────────────────────────────────────────────────────
  (:swap-pane-forward  (%swap-active-pane session :right))
  (:swap-pane-backward (%swap-active-pane session :left))
  (:last-pane
   (let* ((win  (session-active-window session))
          (last (and win (window-last-active win))))
     (when last (%select-pane-with-focus win last))))
  (:display-panes
   (with-active-window (win session)
     (let ((panes (window-panes win)))
       (when panes
         (show-overlay
          (with-output-to-string (stream)
            (dolist (p panes)
              (format stream "Pane ~D: ~Dx~D at (~D,~D)~A~%"
                      (pane-id p)
                      (pane-width p) (pane-height p)
                      (pane-x p) (pane-y p)
                      (if (eq p (window-active-pane win)) " [active]" "")))))))))

  ;; ── Client switching ───────────────────────────────────────────────────────
  (:switch-client-next
   (let* ((sessions (mapcar #'cdr *server-sessions*))
          (next     (and sessions (next-cyclic sessions session))))
     (when (and next (not (eq next session)))
       (session-touch next)
       (setf *dirty* t))))
  (:switch-client-prev
   (let* ((sessions (mapcar #'cdr *server-sessions*))
          (prev     (and sessions (prev-cyclic sessions session))))
     (when (and prev (not (eq prev session)))
       (session-touch prev)
       (setf *dirty* t))))
  (:last-session
   (let* ((sessions (sort (mapcar #'cdr *server-sessions*) #'>
                          :key #'session-last-active))
          (second   (second sessions)))
     (when second
       (session-touch second)
       (setf *dirty* t))))

  ;; ── Message / info ─────────────────────────────────────────────────────────
  (:display-message
   (prompt-start "display-message" ""
                 (lambda (msg)
                   (unless (string= msg "")
                     ;; Expand the message as a format too, so the two-step prompt
                     ;; and the one-line "display-message <fmt>" behave the same.
                     (%cmd-display-message session (list msg))))))
  (:source-file
   (prompt-start "source-file" ""
                 (lambda (path)
                   (unless (string= path "")
                     (load-config-file (pathname path))))))
  (:show-options
   (show-overlay (cl-tmux/options:show-options)))
  (:show-option
   (prompt-start "show-option" ""
                 (lambda (name)
                   (unless (string= name "")
                     (show-overlay (cl-tmux/options:show-option name))))))
  ;; show-window-options / show-session-options: per-scope option listing.
  ;; Currently cl-tmux uses a flat global store; these show the same global
  ;; table but with a scope label, matching tmux's output format closely enough
  ;; for transparency.  Per-window local options are shown when a window is active.
  (:show-window-options
   (show-overlay
    (with-output-to-string (s)
      (format s "# window options~%")
      (write-string (cl-tmux/options:show-options) s))))
  (:show-session-options
   (show-overlay
    (with-output-to-string (s)
      (format s "# session options~%")
      (write-string (cl-tmux/options:show-options) s))))
  (:show-server-options
   (show-overlay
    (with-output-to-string (s)
      (format s "# server options~%")
      (write-string (cl-tmux/options:show-options :server) s))))
  (:confirm-before
   (prompt-start "confirm? (y/n)" ""
                 (lambda (input)
                   (when (and (not (string= input ""))
                              (string-equal input "y"))
                     (show-overlay "[confirmed]")))))

  ;; :wait-for is the canonical wait-for-channel command.
  (:wait-for
   (%signal-channel-prompt "wait-for channel"))

  ;; ── Popup / menu overlays ──────────────────────────────────────────────────
  (:display-popup
   (prompt-start "popup command" ""
                 (lambda (cmd)
                   (unless (string= cmd "")
                     (let ((output (run-shell cmd)))
                       (setf *active-popup*
                             (make-popup :title cmd
                                         :width  (min +popup-max-width+  *term-cols*)
                                         :height (min +popup-max-height+ (- *term-rows* +popup-margin+))
                                         :screen nil
                                         :pane   nil))
                       (show-overlay (%format-popup-overlay cmd output)))))))
  (:display-popup-dismiss
   (setf *active-popup* nil))
  (:display-menu
   (let ((items (list (cons "New Window"    :new-window)
                      (cons "Next Window"   :next-window)
                      (cons "Prev Window"   :prev-window)
                      (cons "Kill Pane"     :kill-pane)
                      (cons "Kill Window"   :kill-window)
                      (cons "Zoom Toggle"   :zoom-toggle)
                      (cons "List Sessions" :list-sessions)
                      (cons "Detach"        :detach))))
     (setf *active-menu* (make-menu :title "Menu" :items items :selected-index 0))
     (show-overlay (%format-menu *active-menu*))))
  (:menu-next
   (when *active-menu*
     (let ((n (length (menu-items *active-menu*))))
       (setf (menu-selected-index *active-menu*)
             (mod (1+ (menu-selected-index *active-menu*)) n))
       (show-overlay (%format-menu *active-menu*)))))
  (:menu-prev
   (when *active-menu*
     (let ((n (length (menu-items *active-menu*))))
       (setf (menu-selected-index *active-menu*)
             (mod (1- (menu-selected-index *active-menu*)) n))
       (show-overlay (%format-menu *active-menu*)))))
  (:menu-select
   (when *active-menu*
     (let* ((idx  (menu-selected-index *active-menu*))
            (item (nth idx (menu-items *active-menu*)))
            (cmd  (cdr item)))
       (setf *active-menu* nil)
       (clear-overlay)
       (when cmd
         (dispatch-command session cmd byte)))))
  (:menu-dismiss
   (setf *active-menu* nil)
   (clear-overlay))

  ;; ── Break / join pane ─────────────────────────────────────────────────────
  (:break-pane
   (with-active-window (win session)
     (when (> (length (window-panes win)) 1)
       (let ((new-win (break-pane session)))
         (when new-win
           (start-reader-thread (window-active-pane new-win)))))))
  (:join-pane
   (with-active-window (dst-win session)
     (prompt-start "join-pane from window" ""
                   (lambda (idx-str)
                     (let ((idx (ignore-errors (parse-integer idx-str))))
                       (when idx
                         (let* ((src-win  (nth idx (session-windows session)))
                                (src-pane (and src-win (window-active-pane src-win))))
                           (when src-pane
                             (join-pane session src-win src-pane dst-win :h)))))))))

  ;; ── Pipe pane / synchronize ────────────────────────────────────────────────
  (:pipe-pane
   (with-active-pane (ap session)
     (if (pane-pipe-fd ap)
         (pipe-pane-close ap)
         (prompt-start "pipe-pane command" ""
                       (lambda (cmd)
                         (unless (string= cmd "")
                           (pipe-pane-open ap cmd)))))))
  (:synchronize-panes
   (%toggle-synchronize-panes))
  (:lock-session
   (setf (session-locked-p session) t))
  (:unlock-session
   (setf (session-locked-p session) nil))

  ;; ── Command prompt ────────────────────────────────────────────────────────
  (:command-prompt
   (prompt-start ": " ""
                 (lambda (input)
                   (unless (string= input "")
                     ;; Arg-aware: parses "<command> <args...>" so commands like
                     ;; display-message #{session_name} run with their arguments.
                     (%run-command-line session input)))))

  ;; ── Miscellaneous commands ─────────────────────────────────────────────────
  (:refresh-client
   ;; Force an immediate redraw of the terminal.  Useful after terminal resize
   ;; or when the display has been corrupted by another program.
   (setf *dirty* t))
  (:send-keys
   (with-active-pane (ap session)
     (prompt-start "send-keys" ""
                   (lambda (input)
                     (unless (string= input "")
                       (send-keys-to-pane ap input))))))
  (:clock-mode
   (with-active-pane (ap session)
     (setf *clock-mode-pane-id*
           (if (eql *clock-mode-pane-id* (pane-id ap))
               nil
               (pane-id ap)))))
  (:show-messages
   (show-overlay
    (if *message-log*
        (format nil "~{~A~%~}"
                (mapcar #'cdr *message-log*))
        "(no messages)")))
  (:show-hooks
   (show-overlay (cl-tmux/hooks:describe-command-hooks)))
  (:capture-pane
   (with-active-pane (ap session)
     (show-overlay (capture-pane ap))))
  (:clear-history
   (with-active-pane (ap session)
     (cl-tmux/terminal/actions:clear-scrollback (pane-screen ap))))
  (:choose-tree
   (show-overlay
    (with-output-to-string (stream)
      (let ((current-name (session-name session)))
        (if *server-sessions*
            (loop for (name . sess) in *server-sessions*
                  do (%format-tree-entry stream name current-name
                                         (session-windows sess)
                                         (session-active-window sess)))
            (%format-tree-entry stream current-name current-name
                                (session-windows session)
                                (session-active-window session)))))))
  (:set-window-option  (%set-option-from-prompt "set-window-option"))
  (:set-session-option (%set-option-from-prompt "set-session-option"))

  ;; ── Paste-buffer commands ─────────────────────────────────────────────────
  ;; These delegate to helpers; the full implementations live in
  ;; dispatch-handlers-buffer.lisp, loaded after this file.
  (:list-buffers   (%cmd-list-buffers))
  (:show-buffer    (%cmd-show-buffer))
  (:choose-buffer  (%cmd-choose-buffer session))
  (:delete-buffer  (%cmd-delete-buffer))
  (:save-buffer    (%cmd-save-buffer))
  (:load-buffer    (%cmd-load-buffer))

  ;; ── Mark / layout helpers ─────────────────────────────────────────────────
  (:mark-pane
   (with-active-pane (ap session)
     (if (pane-marked ap)
         (setf (pane-marked ap) nil)
         (progn
           (with-active-window (win session)
             (dolist (p (window-panes win))
               (setf (pane-marked p) nil)))
           (setf (pane-marked ap) t)))))
  (:clear-mark
   (with-active-window (win session)
     (dolist (p (window-panes win))
       (setf (pane-marked p) nil))))
  (:select-layout-spread
   (%apply-named-layout-to-session session :even-horizontal))
  (:next-layout
   (with-active-window (win session)
     (let* ((layouts #(:even-horizontal :even-vertical :tiled
                       :main-horizontal :main-vertical))
            (current (cl-tmux/model:window-layout-cycle-index win))
            (next    (mod (1+ current) (length layouts)))
            (name    (aref layouts next)))
       (setf (cl-tmux/model:window-layout-cycle-index win) next)
       (%apply-named-layout-to-session session name))))
  (:choose-client
   (show-overlay
    (with-output-to-string (stream)
      (format stream "Clients:~%")
      (format stream "  0: local  ~A  ~Dx~D~%"
              (session-name session)
              *term-cols*
              *term-rows*))))
  (:display-info
   (with-active-pane (ap session)
     (let* ((win    (session-active-window session))
            (screen (pane-screen ap)))
       (show-overlay
        (format nil "Session: ~A~%Window: ~A (~Dx~D) [~D pane~:P]~%Pane: ~D at (~D,~D) ~Dx~D~A"
                (session-name session)
                (if win (window-name win) "none")
                (if win (window-width  win) 0)
                (if win (window-height win) 0)
                (if win (length (window-panes win)) 0)
                (pane-id ap)
                (pane-x ap) (pane-y ap)
                (pane-width ap) (pane-height ap)
                (if (and screen (screen-copy-mode-p screen)) " [copy]" ""))))))
  (:move-window-prompt
   (with-active-window (win session)
     (prompt-start "move-window to index" ""
                   (lambda (idx-str)
                     (let ((idx (ignore-errors (parse-integer idx-str))))
                       (when idx
                         (session-move-window session win idx)))))))
  (:bind-key
   (prompt-start "bind key: " ""
                 (lambda (input)
                   (unless (string= input "")
                     (let* ((parts   (uiop:split-string input :separator " "))
                            (key-tok (and (first parts)
                                         (cl-tmux/config::%parse-key-token (first parts))))
                            (cmd-str (second parts))
                            (kw      (and cmd-str
                                          (cl-tmux/config::%command-keyword cmd-str))))
                       (if kw
                           (progn
                             (set-key-binding key-tok kw)
                             (show-overlay (format nil "bound ~A -> ~(~A~)" key-tok kw)))
                           (show-overlay (format nil "unknown command: ~A"
                                                 (or cmd-str input)))))))))
  (:unbind-key
   (prompt-start "unbind key: " ""
                 (lambda (input)
                   (unless (string= input "")
                     (let ((k (cl-tmux/config::%parse-key-token input)))
                       (remove-key-binding k)
                       (show-overlay (format nil "unbound ~A" k)))))))
  (:select-window-prompt
   (prompt-start "select window (name or number): " ""
                 (lambda (input)
                   (unless (string= input "")
                     (let* ((idx (ignore-errors (parse-integer input)))
                            (win (or (and idx (nth idx (session-windows session)))
                                     (find input (session-windows session)
                                           :key #'window-name
                                           :test #'string-equal))))
                       (if win
                           (%with-window-focus-transition (session)
                             (session-select-window session win))
                           (show-overlay (format nil "no window: ~A" input)))))))))
