(in-package #:cl-tmux/test)

;;;; Command dispatch tests (src/dispatch.lisp).
;;;; Tests: dispatch-suite — dispatch-command, dispatch-prefix-command,
;;;; next-cyclic, prev-cyclic, copy-mode-active-p.

(def-suite dispatch-suite :description "Command dispatch and prefix routing")
(in-suite dispatch-suite)

;;; ── Cyclic helpers (generated by define-cyclic-navigators) ─────────────────

(test next-cyclic-wraps
  "next-cyclic advances and wraps past the end."
  (is (eql 'b (cl-tmux::next-cyclic '(a b c) 'a)))
  (is (eql 'a (cl-tmux::next-cyclic '(a b c) 'c)))
  (is (eql 'b (cl-tmux::next-cyclic '(a b c) 'missing))))   ; unknown → idx 0 → element 1

(test prev-cyclic-wraps
  "prev-cyclic steps back and wraps past the front."
  (is (eql 'a (cl-tmux::prev-cyclic '(a b c) 'b)))
  (is (eql 'c (cl-tmux::prev-cyclic '(a b c) 'a))))

(test define-cyclic-navigators-macro-is-defined
  "define-cyclic-navigators is a defined macro that generated next-cyclic and prev-cyclic."
  (is (macro-function 'cl-tmux::define-cyclic-navigators)
      "define-cyclic-navigators must be a macro")
  ;; Both generated functions are symmetric: stepping n and -n return to original.
  (is (eql 'a (cl-tmux::prev-cyclic '(a b c)
                                    (cl-tmux::next-cyclic '(a b c) 'a)))
      "next then prev returns to same element"))

;;; ── with-active-pane macro ──────────────────────────────────────────────────

(test with-active-pane-returns-nil-for-empty-session
  "with-active-pane evaluates to NIL when there is no active pane."
  (let ((s (make-session :id 1 :name "0" :windows nil)))
    (with-loop-state
      ;; %active-screen uses with-active-pane internally
      (is (null (cl-tmux::%active-screen s))
          "empty session has no active screen"))))

(test with-active-pane-macro-is-defined
  "with-active-pane is a defined macro."
  (is (macro-function 'cl-tmux::with-active-pane)))

;;; ── Window / pane selection ────────────────────────────────────────────────

(test dispatch-next-window-cycles
  "C-b n moves to the next window and wraps around."
  (let ((s (make-fake-session :nwindows 2)))
    (with-loop-state
      (cl-tmux::dispatch-command s :next-window nil)
      (is (eq (second (session-windows s)) (session-active-window s)))
      (cl-tmux::dispatch-command s :next-window nil)
      (is (eq (first (session-windows s)) (session-active-window s))
          "second :next-window should wrap back to window 1"))))

(test dispatch-prev-window-wraps
  "C-b p from the first window wraps to the last."
  (let ((s (make-fake-session :nwindows 2)))
    (with-loop-state
      (cl-tmux::dispatch-command s :prev-window nil)
      (is (eq (second (session-windows s)) (session-active-window s))))))

(test dispatch-next-pane-cycles
  "C-b o moves to the next pane within the active window."
  (let* ((s   (make-fake-session :nwindows 1 :npanes 2))
         (win (session-active-window s))
         (p0  (first  (window-panes win)))
         (p1  (second (window-panes win))))
    (with-loop-state
      (is (eq p0 (window-active-pane win)))
      (cl-tmux::dispatch-command s :next-pane nil)
      (is (eq p1 (window-active-pane win))))))

(test dispatch-select-window-by-digit
  "C-b <n>: :select-window uses the pressed digit byte to pick the window."
  (let ((s (make-fake-session :nwindows 3)))
    (with-loop-state
      (cl-tmux::dispatch-command s :select-window (char-code #\2))
      (is (eq (third (session-windows s)) (session-active-window s)))
      (cl-tmux::dispatch-command s :select-window (char-code #\0))
      (is (eq (first (session-windows s)) (session-active-window s))))))

(test dispatch-unknown-command-passes-through
  "An unrecognized command falls through to the passthrough branch: it returns
   NIL (no quit), doesn't error, and still marks the session dirty."
  (let ((s (make-fake-session)))
    (with-loop-state
      (is (null (cl-tmux::dispatch-command s :no-such-command (char-code #\a))))
      (is-true cl-tmux::*dirty* "dispatch marks dirty even on passthrough"))))

;;; ── Rename ──────────────────────────────────────────────────────────────────

(test dispatch-rename-window-opens-prompt
  "C-b , opens a rename prompt seeded with the active window's name, and its
   on-submit closure renames the active window."
  (let ((s (make-fake-session :nwindows 1)))
    (let ((*prompt* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
      (cl-tmux::dispatch-command s :rename-window nil)
      (is (prompt-active-p) "rename should open a prompt")
      (is (string= "0" (prompt-buffer *prompt*))
          "prompt seeded with current window name")
      (is (functionp (prompt-on-submit *prompt*))
          "prompt should carry an on-submit closure")
      ;; Running the closure with a new name renames the active window.
      (funcall (prompt-on-submit *prompt*) "renamed")
      (is (string= "renamed" (window-name (session-active-window s)))
          "on-submit closure should rename the active window"))))

;;; ── Copy mode ───────────────────────────────────────────────────────────────

(test dispatch-copy-mode-enter-exit
  "C-b [ enters copy mode on the active screen; exit clears it."
  (let ((s (make-fake-session)))
    (with-loop-state
      (cl-tmux::dispatch-command s :copy-mode-enter nil)
      (is (screen-copy-mode-p (active-screen s)) "copy mode should be on after enter")
      (cl-tmux::dispatch-command s :copy-mode-exit nil)
      (is (not (screen-copy-mode-p (active-screen s))) "copy mode should be off after exit"))))

(test copy-mode-active-p-reflects-state
  "copy-mode-active-p tracks the active screen's copy-mode flag."
  (let ((s (make-fake-session)))
    (with-loop-state
      (is (not (cl-tmux::copy-mode-active-p s)))
      (cl-tmux::dispatch-command s :copy-mode-enter nil)
      (is (cl-tmux::copy-mode-active-p s)))))

;;; ── Detach / kill ───────────────────────────────────────────────────────────

(test dispatch-detach-returns-detach
  "C-b d returns :detach and does NOT clear *running* itself (the caller decides:
   standalone stops, a server merely disconnects the client)."
  (let ((s (make-fake-session)))
    (let ((cl-tmux::*running* t) (cl-tmux::*dirty* nil))
      (is (eq :detach (cl-tmux::dispatch-command s :detach nil)))
      (is-true cl-tmux::*running* "dispatch-command must not clear *running*"))))

(test dispatch-kill-last-window-quits
  "Killing the only window ends the session (:quit)."
  (let ((s (make-fake-session :nwindows 1)))
    (with-loop-state
      (is (eq :quit (cl-tmux::dispatch-command s :kill-window nil))))))

(test dispatch-kill-one-of-two-windows-survives
  "Killing one of two windows leaves the session running with the other."
  (let ((s (make-fake-session :nwindows 2)))
    (with-loop-state
      (is (null (cl-tmux::dispatch-command s :kill-window nil)))
      (is (= 1 (length (session-windows s)))))))

(test dispatch-kill-last-pane-quits
  "Killing the sole pane of the sole window ends the session (:quit)."
  (let ((s (make-fake-session :nwindows 1 :npanes 1)))
    (with-loop-state
      (is (eq :quit (cl-tmux::dispatch-command s :kill-pane nil))))))

;;; ── Prefix routing ──────────────────────────────────────────────────────────

(test dispatch-prefix-routes-binding
  "dispatch-prefix-command looks the byte up in the binding table (d → detach)."
  (let ((s (make-fake-session)))
    (let ((cl-tmux::*running* t) (cl-tmux::*dirty* nil))
      (is (eq :detach (cl-tmux::dispatch-prefix-command s (char-code #\d)))))))

(test prefix-q-exits-copy-mode
  "In copy mode, the prefix-routed 'q' exits copy mode."
  (let ((s (make-fake-session)))
    (with-loop-state
      (cl-tmux::dispatch-command s :copy-mode-enter nil)
      (cl-tmux::dispatch-prefix-command s (char-code #\q))
      (is (not (screen-copy-mode-p (active-screen s)))))))

;;; ── %active-screen ───────────────────────────────────────────────────────────

(test active-screen-returns-active-pane-screen
  "%active-screen returns the screen of the session's active pane."
  (let* ((s  (make-fake-session))
         (ap (session-active-pane s)))
    (with-loop-state
      (is (eq (pane-screen ap)
              (cl-tmux::%active-screen s))
          "%active-screen must return the active pane's screen"))))

(test active-screen-returns-nil-for-empty-session
  "%active-screen returns NIL when no pane is active."
  (let ((s (make-session :id 1 :name "0" :windows nil)))
    (with-loop-state
      (is (null (cl-tmux::%active-screen s))))))

;;; ── %cmd-cycle-window ────────────────────────────────────────────────────────

(test cmd-cycle-window-advances-selection
  "%cmd-cycle-window advances the active window via CYCLER."
  (let* ((s  (make-fake-session :nwindows 3))
         (w1 (first  (session-windows s)))
         (w2 (second (session-windows s))))
    (with-loop-state
      (is (eq w1 (session-active-window s)))
      (cl-tmux::%cmd-cycle-window s #'cl-tmux::next-cyclic)
      (is (eq w2 (session-active-window s))))))

;;; ── %cmd-cycle-pane ──────────────────────────────────────────────────────────

(test cmd-cycle-pane-advances-pane-selection
  "%cmd-cycle-pane advances the active pane via CYCLER."
  (let* ((s   (make-fake-session :nwindows 1 :npanes 2))
         (win (session-active-window s))
         (p0  (first  (window-panes win)))
         (p1  (second (window-panes win))))
    (with-loop-state
      (is (eq p0 (window-active-pane win)))
      (cl-tmux::%cmd-cycle-pane s #'cl-tmux::next-cyclic)
      (is (eq p1 (window-active-pane win))))))

;;; ── list-keys overlay ───────────────────────────────────────────────────────

(test dispatch-list-keys-shows-overlay
  "C-b ? opens the key-binding help overlay."
  (let ((s (make-fake-session)))
    (let ((*overlay* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
      (cl-tmux::dispatch-command s :list-keys nil)
      (is (overlay-active-p) "list-keys should open the help overlay"))))

(test define-command-handlers-macro-is-defined
  "define-command-handlers is a defined macro."
  (is (macro-function 'cl-tmux::define-command-handlers)))

(test define-copy-mode-key-overrides-macro-is-defined
  "define-copy-mode-key-overrides is a defined macro."
  (is (macro-function 'cl-tmux::define-copy-mode-key-overrides)))

;;; ── select-pane-left/right/up/down dispatch ─────────────────────────────────
;;;
;;; These tests use the shared fixture macros from helpers.lisp instead of
;;; duplicating the setup inline.  with-two-pane-h-session and
;;; with-two-pane-v-session already encode the exact same geometry.

(test dispatch-select-pane-right-moves-active-pane
  ":select-pane-right moves the active pane to the right neighbour."
  (with-two-pane-h-session (sess win p0 p1)
    (with-loop-state
      (is (eq p0 (window-active-pane win)) "p0 is active initially")
      (cl-tmux::dispatch-command sess :select-pane-right nil)
      (is (eq p1 (window-active-pane win))
          "active pane must be p1 after :select-pane-right"))))

(test dispatch-select-pane-left-moves-active-pane
  ":select-pane-left moves the active pane to the left neighbour."
  (with-two-pane-h-session (sess win p0 p1)
    (with-loop-state
      ;; Start on p1, then go left.
      (window-select-pane win p1)
      (cl-tmux::dispatch-command sess :select-pane-left nil)
      (is (eq p0 (window-active-pane win))
          "active pane must be p0 after :select-pane-left"))))

(test dispatch-select-pane-right-noop-at-rightmost
  ":select-pane-right is a no-op when the active pane has no right neighbour."
  (with-two-pane-h-session (sess win p0 p1)
    (with-loop-state
      ;; Make p1 (rightmost) active, then try to go further right.
      (is (eq p0 (window-active-pane win)) "p0 is active initially")
      (window-select-pane win p1)
      (cl-tmux::dispatch-command sess :select-pane-right nil)
      (is (eq p1 (window-active-pane win))
          "active pane must remain p1 when no right neighbour exists"))))

(test dispatch-select-pane-down-moves-active-pane
  ":select-pane-down moves the active pane to the pane below."
  (with-two-pane-v-session (sess win p0 p1)
    (with-loop-state
      (is (eq p0 (window-active-pane win)) "p0 is active initially")
      (cl-tmux::dispatch-command sess :select-pane-down nil)
      (is (eq p1 (window-active-pane win))
          "active pane must be p1 after :select-pane-down"))))

(test dispatch-select-pane-up-moves-active-pane
  ":select-pane-up moves the active pane to the pane above."
  (with-two-pane-v-session (sess win p0 p1)
    (with-loop-state
      ;; Start on p1 (bottom), then go up.
      (window-select-pane win p1)
      (cl-tmux::dispatch-command sess :select-pane-up nil)
      (is (eq p0 (window-active-pane win))
          "active pane must be p0 after :select-pane-up"))))

;;; ── zoom-toggle dispatch ────────────────────────────────────────────────────

(test dispatch-zoom-toggle-sets-zoom-flag
  ":zoom-toggle zooms the active pane in and marks window-zoom-p as T."
  (with-two-pane-h-session (sess win p0 p1)
    (with-loop-state
      (is (and p0 p1) "both panes exist")
      (cl-tmux::dispatch-command sess :zoom-toggle nil)
      (is-true (cl-tmux/model:window-zoom-p win)
               "window-zoom-p must be T after :zoom-toggle dispatch")
      ;; Toggle back off.
      (cl-tmux::dispatch-command sess :zoom-toggle nil)
      (is-false (cl-tmux/model:window-zoom-p win)
                "window-zoom-p must be NIL after second :zoom-toggle dispatch"))))

;;; ── rename-session dispatch ─────────────────────────────────────────────────

(test dispatch-rename-session-opens-prompt
  ":rename-session opens a prompt seeded with the current session name, and
   its on-submit closure renames the session."
  (let ((s (make-fake-session :nwindows 1)))
    (let ((*prompt* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
      (cl-tmux::dispatch-command s :rename-session nil)
      (is (prompt-active-p) "rename-session must open a prompt")
      (is (string= "0" (prompt-buffer *prompt*))
          "prompt must be seeded with the current session name \"0\"")
      (funcall (prompt-on-submit *prompt*) "newsess")
      (is (string= "newsess" (session-name s))
          "on-submit must rename the session to the supplied name"))))

;;; ── %select-pane-in-direction ───────────────────────────────────────────────
;;;
;;; Use the shared fixture macros to avoid repeating pane/window/session setup.

(test select-pane-in-direction-right-selects-right-pane
  "%select-pane-in-direction :right from the left pane selects the right pane."
  (with-two-pane-h-session (sess win p0 p1)
    (with-loop-state
      (is (eq p0 (window-active-pane win)) "p0 is active initially")
      (cl-tmux::%select-pane-in-direction sess :right)
      (is (eq p1 (window-active-pane win))
          "active pane must be p1 after %select-pane-in-direction :right"))))

(test select-pane-in-direction-left-selects-left-pane
  "%select-pane-in-direction :left from the right pane selects the left pane."
  (with-two-pane-h-session (sess win p0 p1)
    (with-loop-state
      (window-select-pane win p1)
      (cl-tmux::%select-pane-in-direction sess :left)
      (is (eq p0 (window-active-pane win))
          "active pane must be p0 after %select-pane-in-direction :left"))))

(test select-pane-in-direction-noop-when-no-neighbor
  "%select-pane-in-direction is a no-op when the active pane has no neighbor
   in the requested direction."
  (with-two-pane-h-session (sess win p0 p1)
    (is (not (null p0)) "fixture created")
    (window-select-pane win p1)          ; start at the rightmost pane
    (with-loop-state
      (cl-tmux::%select-pane-in-direction sess :right)
      (is (eq p1 (window-active-pane win))
          "active pane must remain p1 when no right neighbor exists"))))

(test select-pane-in-direction-vertical-down-selects-lower-pane
  "%select-pane-in-direction :down from the top pane selects the bottom pane."
  (with-two-pane-v-session (sess win p0 p1)
    (with-loop-state
      (is (eq p0 (window-active-pane win)) "p0 is active initially")
      (cl-tmux::%select-pane-in-direction sess :down)
      (is (eq p1 (window-active-pane win))
          "active pane must be p1 after %select-pane-in-direction :down"))))

;;; ── %apply-named-layout-to-session ──────────────────────────────────────────

(test apply-named-layout-even-horizontal-repositions-panes
  "%apply-named-layout-to-session :even-horizontal repositions two panes into
   equal-width columns and rebuilds the window tree."
  (let* ((p0   (make-no-pty-pane 1  0 0 10 24))
         (p1   (make-no-pty-pane 2 11 0 10 24))
         (win  (make-window :id 1 :name "w" :width 81 :height 24
                            :panes (list p0 p1)
                            :tree (make-layout-split :h
                                     (make-layout-leaf p0)
                                     (make-layout-leaf p1)
                                     1/2)))
         (sess (make-session :id 1 :name "0" :windows (list win))))
    (window-select-pane win p0)
    (session-select-window sess win)
    (with-loop-state
      (cl-tmux::%apply-named-layout-to-session sess :even-horizontal)
      ;; After even-horizontal: avail-w = 81 - 1 = 80, each-w = 40.
      ;; p0 should be at x=0, p1 at x=41, both width=40.
      (is (= 0  (pane-x p0)) "p0 x must be 0 after even-horizontal layout")
      (is (= 40 (pane-width p0)) "p0 width must be 40 after even-horizontal layout")
      (is (= 41 (pane-x p1)) "p1 x must be 41 after even-horizontal layout")
      (is (= 40 (pane-width p1)) "p1 width must be 40 after even-horizontal layout"))))

(test apply-named-layout-even-vertical-repositions-panes
  "%apply-named-layout-to-session :even-vertical repositions two panes into
   equal-height rows and rebuilds the window tree."
  (let* ((p0   (make-no-pty-pane 1 0  0 80 10))
         (p1   (make-no-pty-pane 2 0 11 80 10))
         (win  (make-window :id 1 :name "w" :width 80 :height 21
                            :panes (list p0 p1)
                            :tree (make-layout-split :v
                                     (make-layout-leaf p0)
                                     (make-layout-leaf p1)
                                     1/2)))
         (sess (make-session :id 1 :name "0" :windows (list win))))
    (window-select-pane win p0)
    (session-select-window sess win)
    (with-loop-state
      (cl-tmux::%apply-named-layout-to-session sess :even-vertical)
      ;; After even-vertical: avail-h = 21 - 1 = 20, each-h = 10.
      ;; p0 should be at y=0, p1 at y=11, both height=10.
      (is (= 0  (pane-y p0)) "p0 y must be 0 after even-vertical layout")
      (is (= 10 (pane-height p0)) "p0 height must be 10 after even-vertical layout")
      (is (= 11 (pane-y p1)) "p1 y must be 11 after even-vertical layout")
      (is (= 10 (pane-height p1)) "p1 height must be 10 after even-vertical layout"))))

(test apply-named-layout-noop-for-empty-session
  "%apply-named-layout-to-session with no active window is a no-op."
  (let ((sess (make-session :id 1 :name "0" :windows nil)))
    (with-loop-state
      (finishes (cl-tmux::%apply-named-layout-to-session sess :even-horizontal))
      "calling with no active window must not signal an error")))

;;; ── :list-windows dispatch ───────────────────────────────────────────────────

(test dispatch-list-windows-shows-overlay
  ":list-windows opens an overlay containing the window name and marks *dirty*."
  (let ((s (make-fake-session :nwindows 1)))
    (let ((*overlay* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
      (cl-tmux::dispatch-command s :list-windows nil)
      (is (overlay-active-p)
          ":list-windows must open the overlay")
      (is-true cl-tmux::*dirty*
               ":list-windows must mark *dirty*"))))

(test dispatch-list-windows-overlay-contains-window-name
  ":list-windows overlay text includes the active window name."
  (let ((s (make-fake-session :nwindows 2)))
    (let ((*overlay* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
      (cl-tmux::dispatch-command s :list-windows nil)
      (is (overlay-active-p) "overlay must be open")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search "1" text)
            "overlay must contain the first window entry")))))

;;; ── :list-sessions dispatch ──────────────────────────────────────────────────

(test dispatch-list-sessions-empty-registry-shows-overlay
  ":list-sessions with empty *server-sessions* falls back to the session-name
   single-line format and still opens an overlay."
  (let ((s (make-fake-session :nwindows 1)))
    (let ((*overlay* nil)
          (cl-tmux::*dirty* nil)
          (cl-tmux::*running* t)
          (cl-tmux::*server-sessions* nil))
      (cl-tmux::dispatch-command s :list-sessions nil)
      (is (overlay-active-p)
          ":list-sessions must open an overlay even when *server-sessions* is nil")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search (session-name s) text)
            "fallback overlay must contain the session name")))))

(test dispatch-list-sessions-populated-registry-shows-all-sessions
  ":list-sessions with *server-sessions* populated lists every registered
   session and marks the current one with an asterisk."
  (let* ((s    (make-fake-session :nwindows 1))
         (name (session-name s)))
    (let ((*overlay* nil)
          (cl-tmux::*dirty* nil)
          (cl-tmux::*running* t)
          (cl-tmux::*server-sessions* (list (cons name s))))
      (cl-tmux::dispatch-command s :list-sessions nil)
      (is (overlay-active-p)
          ":list-sessions must open an overlay")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search name text)
            "overlay must contain the session name")
        (is (search "*" text)
            "current session must be marked with an asterisk")))))

;;; ── :display-panes dispatch ──────────────────────────────────────────────────

(test dispatch-display-panes-shows-overlay-with-pane-entries
  ":display-panes with a 2-pane session opens an overlay whose text contains
   two pane entries and marks the active pane as [active]."
  (with-two-pane-h-session (sess win p0 p1)
    (is (and win p0 p1) "session with 2 panes")
    (let ((*overlay* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
      (cl-tmux::dispatch-command sess :display-panes nil)
      (is (overlay-active-p)
          ":display-panes must open an overlay")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search "Pane 1" text)
            "overlay must mention pane 1")
        (is (search "Pane 2" text)
            "overlay must mention pane 2")
        (is (search "[active]" text)
            "overlay must mark the active pane with [active]")))))

(test dispatch-display-panes-marks-dirty
  ":display-panes sets *dirty* to T."
  (let* ((p0  (make-no-pty-pane 1 0 0 80 24))
         (win (make-window :id 1 :name "w" :width 80 :height 24
                           :panes (list p0)
                           :tree (make-layout-leaf p0)))
         (sess (make-session :id 1 :name "0" :windows (list win))))
    (window-select-pane win p0)
    (session-select-window sess win)
    (let ((*overlay* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
      (cl-tmux::dispatch-command sess :display-panes nil)
      (is-true cl-tmux::*dirty*
               ":display-panes must mark *dirty*"))))

;;; ── :swap-pane-forward dispatch ──────────────────────────────────────────────
;;;
;;; Use the shared fixture macro to avoid repeating pane/window/session setup.

(test dispatch-swap-pane-forward-changes-pane-order
  ":swap-pane-forward swaps the active pane with the next pane in the list."
  (with-two-pane-h-session (sess win p0 p1)
    (with-loop-state
      ;; p0 is active and at index 0; forward swap puts p1 at index 0.
      (cl-tmux::dispatch-command sess :swap-pane-forward nil)
      (is (eq p1 (first (window-panes win)))
          "after :swap-pane-forward, p1 must be first in the panes list")
      (is (eq p0 (second (window-panes win)))
          "after :swap-pane-forward, p0 must be second in the panes list"))))

(test dispatch-swap-pane-forward-marks-dirty
  ":swap-pane-forward marks *dirty*."
  (with-two-pane-h-session (sess win p0 p1)
    (is (and win p0 p1) "fixture created")
    (let ((cl-tmux::*running* t) (cl-tmux::*dirty* nil))
      (cl-tmux::dispatch-command sess :swap-pane-forward nil)
      (is-true cl-tmux::*dirty*
               ":swap-pane-forward must mark *dirty*"))))

;;; ── :swap-pane-backward dispatch ─────────────────────────────────────────────

(test dispatch-swap-pane-backward-changes-pane-order
  ":swap-pane-backward swaps the active pane with the previous pane (wrapping)."
  (with-two-pane-h-session (sess win p0 p1)
    ;; Start with p1 active so that backward swap moves it to index 0.
    (window-select-pane win p1)
    (with-loop-state
      (cl-tmux::dispatch-command sess :swap-pane-backward nil)
      (is (eq p1 (first (window-panes win)))
          "after :swap-pane-backward from p1, p1 must be first in the panes list")
      (is (eq p0 (second (window-panes win)))
          "after :swap-pane-backward from p1, p0 must be second in the panes list"))))

(test dispatch-swap-pane-backward-marks-dirty
  ":swap-pane-backward marks *dirty*."
  (with-two-pane-h-session (sess win p0 p1)
    (is (not (null p0)) "fixture created")
    (window-select-pane win p1)
    (let ((cl-tmux::*running* t) (cl-tmux::*dirty* nil))
      (cl-tmux::dispatch-command sess :swap-pane-backward nil)
      (is-true cl-tmux::*dirty*
               ":swap-pane-backward must mark *dirty*"))))

;;; ── :kill-pane-confirm dispatch ──────────────────────────────────────────────

(test dispatch-kill-pane-confirm-opens-prompt
  ":kill-pane-confirm opens a y/n prompt and does NOT kill immediately."
  (let ((s (make-fake-session :nwindows 1 :npanes 2)))
    (let ((*prompt* nil) (cl-tmux::*running* t) (cl-tmux::*dirty* nil))
      (cl-tmux::dispatch-command s :kill-pane-confirm nil)
      (is (prompt-active-p)
          ":kill-pane-confirm must open a prompt")
      ;; Window should still have both panes (no kill yet).
      (is (= 2 (length (window-panes (session-active-window s))))
          ":kill-pane-confirm must not kill the pane before confirmation"))))

(test dispatch-kill-pane-confirm-kills-on-y
  ":kill-pane-confirm kills the pane when the user submits \"y\"."
  (let ((s (make-fake-session :nwindows 1 :npanes 2)))
    (let ((*prompt* nil) (cl-tmux::*running* t) (cl-tmux::*dirty* nil))
      (cl-tmux::dispatch-command s :kill-pane-confirm nil)
      (is (prompt-active-p) "prompt must be open")
      ;; Submit "y" — should kill the active pane.
      (funcall (prompt-on-submit *prompt*) "y")
      (is (= 1 (length (window-panes (session-active-window s))))
          "submitting \"y\" must kill the active pane"))))

(test dispatch-kill-pane-confirm-no-kill-on-n
  ":kill-pane-confirm does NOT kill when the user submits \"n\"."
  (let ((s (make-fake-session :nwindows 1 :npanes 2)))
    (let ((*prompt* nil) (cl-tmux::*running* t) (cl-tmux::*dirty* nil))
      (cl-tmux::dispatch-command s :kill-pane-confirm nil)
      (is (prompt-active-p) "prompt must be open")
      ;; Submit "n" — should NOT kill.
      (funcall (prompt-on-submit *prompt*) "n")
      (is (= 2 (length (window-panes (session-active-window s))))
          "submitting \"n\" must NOT kill the pane"))))

;;; ── :kill-window-confirm dispatch ────────────────────────────────────────────

(test dispatch-kill-window-confirm-opens-prompt
  ":kill-window-confirm opens a y/n prompt and does NOT kill immediately."
  (let ((s (make-fake-session :nwindows 2)))
    (let ((*prompt* nil) (cl-tmux::*running* t) (cl-tmux::*dirty* nil))
      (cl-tmux::dispatch-command s :kill-window-confirm nil)
      (is (prompt-active-p)
          ":kill-window-confirm must open a prompt")
      ;; Both windows should still be present.
      (is (= 2 (length (session-windows s)))
          ":kill-window-confirm must not kill the window before confirmation"))))

(test dispatch-kill-window-confirm-kills-on-y
  ":kill-window-confirm kills the window when the user submits \"y\"."
  (let ((s (make-fake-session :nwindows 2)))
    (let ((*prompt* nil) (cl-tmux::*running* t) (cl-tmux::*dirty* nil))
      (cl-tmux::dispatch-command s :kill-window-confirm nil)
      (is (prompt-active-p) "prompt must be open")
      ;; Submit "y" — should kill the active window.
      (funcall (prompt-on-submit *prompt*) "y")
      (is (= 1 (length (session-windows s)))
          "submitting \"y\" must kill the active window"))))

(test dispatch-kill-window-confirm-no-kill-on-n
  ":kill-window-confirm does NOT kill when the user submits \"n\"."
  (let ((s (make-fake-session :nwindows 2)))
    (let ((*prompt* nil) (cl-tmux::*running* t) (cl-tmux::*dirty* nil))
      (cl-tmux::dispatch-command s :kill-window-confirm nil)
      (is (prompt-active-p) "prompt must be open")
      ;; Submit "n" — should NOT kill.
      (funcall (prompt-on-submit *prompt*) "n")
      (is (= 2 (length (session-windows s)))
          "submitting \"n\" must NOT kill the window"))))

(test dispatch-kill-window-confirm-prompt-includes-window-name
  ":kill-window-confirm prompt label includes the current window name."
  (let ((s (make-fake-session :nwindows 1)))
    (let ((*prompt* nil) (cl-tmux::*running* t) (cl-tmux::*dirty* nil))
      (let ((wname (window-name (session-active-window s))))
        (cl-tmux::dispatch-command s :kill-window-confirm nil)
        (is (prompt-active-p) "prompt must be open")
        (is (search wname (prompt-label *prompt*))
            "prompt label must contain the window name")))))

;;; ── :send-prefix dispatch ────────────────────────────────────────────────────

(test dispatch-send-prefix-command-is-defined
  ":send-prefix command is registered in dispatch-command without error."
  ;; We cannot test actual PTY writes in unit tests (fd=-1), but we verify
  ;; that dispatching :send-prefix does not signal any error and marks dirty.
  (let ((s (make-fake-session)))
    (with-loop-state
      ;; Should not error even with fd=-1 (the guard (> fd 0) protects the write).
      (finishes (cl-tmux::dispatch-command s :send-prefix nil))
      (is-true cl-tmux::*dirty* ":send-prefix must mark *dirty*"))))

;;; ── unbound prefix key no-op ─────────────────────────────────────────────────

(test dispatch-unknown-command-is-noop
  "An unrecognized prefix key is silently discarded (no passthrough corruption)."
  ;; Previously the otherwise clause called %passthrough-prefix, injecting
  ;; raw bytes into the pane.  After the fix it must be a silent no-op.
  (let ((s (make-fake-session)))
    (with-loop-state
      ;; Dispatching an unknown command must return NIL and must not error.
      (is (null (cl-tmux::dispatch-command s :no-such-command-xyz nil))
          "unknown command must return NIL")
      (is-true cl-tmux::*dirty*
               "dispatch must mark *dirty* even for unknown commands"))))

;;; ── :paste-buffer bracketed-paste wrapping ───────────────────────────────────

(test dispatch-paste-buffer-no-crash-without-buffer
  ":paste-buffer with an empty paste buffer is a no-op (no error, marks dirty)."
  (let ((s (make-fake-session)))
    (with-loop-state
      (finishes (cl-tmux::dispatch-command s :paste-buffer nil))
      (is-true cl-tmux::*dirty* ":paste-buffer must mark *dirty*"))))

;;; ── :command-prompt dispatch ─────────────────────────────────────────────────

(test dispatch-command-prompt-opens-prompt
  ":command-prompt opens a prompt with label \": \"."
  (let ((s (make-fake-session)))
    (let ((*prompt* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
      (cl-tmux::dispatch-command s :command-prompt nil)
      (is (prompt-active-p) ":command-prompt must open a prompt")
      (is (string= ": " (prompt-label *prompt*))
          ":command-prompt prompt label must be \": \""))))

(test dispatch-command-prompt-empty-input-is-noop
  ":command-prompt with empty input does not crash."
  (let ((s (make-fake-session)))
    (let ((*prompt* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
      (cl-tmux::dispatch-command s :command-prompt nil)
      (is (prompt-active-p) "prompt must be open")
      (finishes (funcall (prompt-on-submit *prompt*) "")
                "empty input must not signal an error"))))

(test dispatch-command-prompt-unknown-command-shows-overlay
  ":command-prompt with an unknown command name shows an error overlay."
  (let ((s (make-fake-session)))
    (let ((*prompt* nil) (*overlay* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
      (cl-tmux::dispatch-command s :command-prompt nil)
      (funcall (prompt-on-submit *prompt*) "no-such-command-xyz")
      (is (overlay-active-p) "unknown command must open an error overlay")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search "unknown command" text)
            "overlay must contain the 'unknown command' error message")))))

(test dispatch-command-prompt-known-command-executes
  ":command-prompt with 'list-windows' executes that command (opens overlay)."
  (let ((s (make-fake-session :nwindows 1)))
    (let ((*prompt* nil) (*overlay* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
      (cl-tmux::dispatch-command s :command-prompt nil)
      (funcall (prompt-on-submit *prompt*) "list-windows")
      (is (overlay-active-p) "list-windows via command-prompt must open an overlay"))))

;;; ── %dispatch-named-command helper ──────────────────────────────────────────

(test dispatch-named-command-new-window
  "%dispatch-named-command \"next-window\" selects the next window."
  ;; Use next-window (no fork/no thread) to avoid leaking reader threads
  ;; that would prevent later PTY tests from forking.
  (let ((s (make-fake-session :nwindows 2)))
    (let ((*overlay* nil) (cl-tmux::*running* t) (cl-tmux::*dirty* nil))
      (cl-tmux::%dispatch-named-command s "next-window")
      (is-true cl-tmux::*dirty*
               "%dispatch-named-command 'next-window' must mark *dirty*")
      (is (eq (second (session-windows s)) (session-active-window s))
          "next-window must switch to the second window"))))

(test dispatch-named-command-unknown-shows-overlay
  "%dispatch-named-command with an unrecognized name shows an overlay."
  (let ((s (make-fake-session)))
    (let ((*overlay* nil) (cl-tmux::*running* t) (cl-tmux::*dirty* nil))
      (cl-tmux::%dispatch-named-command s "totally-unknown-xyz")
      (is (overlay-active-p) "unknown command must open an error overlay")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search "unknown command" text) "overlay must mention 'unknown command'")
        (is (search "totally-unknown-xyz" text)
            "overlay must include the bad command name")))))

;;; ── :show-messages dispatch ──────────────────────────────────────────────────

(test dispatch-show-messages-empty-log-shows-overlay
  ":show-messages with empty *message-log* opens an overlay saying '(no messages)'."
  (let ((s (make-fake-session)))
    (let ((*overlay* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t)
          (cl-tmux::*message-log* nil))
      (cl-tmux::dispatch-command s :show-messages nil)
      (is (overlay-active-p) ":show-messages must open an overlay")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search "no messages" text)
            "overlay must say '(no messages)' when log is empty")))))

(test dispatch-show-messages-populated-log-shows-entries
  ":show-messages with entries in *message-log* lists them."
  (let ((s (make-fake-session)))
    (let ((*overlay* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t)
          (cl-tmux::*message-log* (list (cons 0 "hello") (cons 1 "world"))))
      (cl-tmux::dispatch-command s :show-messages nil)
      (is (overlay-active-p) ":show-messages must open an overlay")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search "hello" text) "overlay must contain 'hello'")
        (is (search "world" text) "overlay must contain 'world'")))))

;;; ── :display-message logs to *message-log* ───────────────────────────────────

(test dispatch-display-message-logs-to-message-log
  ":display-message on-submit calls add-message-log, appending the message."
  (let ((s (make-fake-session)))
    (let ((*prompt* nil) (*overlay* nil)
          (cl-tmux::*dirty* nil) (cl-tmux::*running* t)
          (cl-tmux::*message-log* nil))
      (cl-tmux::dispatch-command s :display-message nil)
      (is (prompt-active-p) ":display-message must open a prompt")
      ;; Submit a non-empty message.
      (funcall (prompt-on-submit *prompt*) "test-log-entry")
      (is (not (null cl-tmux::*message-log*))
          "*message-log* must be non-nil after submitting a message")
      (let ((last-msg (cdr (first cl-tmux::*message-log*))))
        (is (string= "test-log-entry" last-msg)
            "first message-log entry must be the submitted message (got ~S)" last-msg)))))

;;; ── :clock-mode dispatch ─────────────────────────────────────────────────────

(test dispatch-clock-mode-toggles-pane-id
  ":clock-mode sets *clock-mode-pane-id* to the active pane's id."
  (let ((s (make-fake-session)))
    (let ((cl-tmux::*dirty* nil) (cl-tmux::*running* t)
          (cl-tmux::*clock-mode-pane-id* nil))
      (cl-tmux::dispatch-command s :clock-mode nil)
      (let ((ap (session-active-pane s)))
        (is (eql (pane-id ap) cl-tmux::*clock-mode-pane-id*)
            "*clock-mode-pane-id* must be set to active pane id after first :clock-mode")
        ;; Toggle off
        (cl-tmux::dispatch-command s :clock-mode nil)
        (is (null cl-tmux::*clock-mode-pane-id*)
            "*clock-mode-pane-id* must be nil after second :clock-mode (toggle off)")))))

;;; ── :capture-pane dispatch ───────────────────────────────────────────────────

(test dispatch-capture-pane-shows-overlay
  ":capture-pane opens an overlay containing the pane content."
  (let ((s (make-fake-session)))
    (let ((*overlay* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
      ;; Feed some text into the active pane's screen.
      (let ((ap (session-active-pane s)))
        (when ap
          (feed (pane-screen ap) "CAPTEST")))
      (cl-tmux::dispatch-command s :capture-pane nil)
      (is (overlay-active-p) ":capture-pane must open an overlay")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search "CAPTEST" text)
            "capture-pane overlay must contain the pane's fed content")))))

;;; ── :send-keys dispatch ──────────────────────────────────────────────────────

(test dispatch-send-keys-opens-prompt
  ":send-keys opens a prompt for the keys string."
  (let ((s (make-fake-session)))
    (let ((*prompt* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
      (cl-tmux::dispatch-command s :send-keys nil)
      (is (prompt-active-p) ":send-keys must open a prompt")
      (is (string= "send-keys" (prompt-label *prompt*))
          ":send-keys prompt label must be \"send-keys\""))))

(test dispatch-send-keys-no-crash-with-no-pty
  ":send-keys on-submit with a no-PTY pane (fd=-1) does not signal an error."
  (let ((s (make-fake-session)))
    (let ((*prompt* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
      (cl-tmux::dispatch-command s :send-keys nil)
      (is (prompt-active-p) "prompt must be open")
      ;; Submitting keys to fd=-1 pane must not error.
      (finishes (funcall (prompt-on-submit *prompt*) "hello")
                "send-keys on-submit must not error with fd=-1 pane"))))

;;; ── :choose-tree dispatch ────────────────────────────────────────────────────

(test dispatch-choose-tree-shows-overlay
  ":choose-tree opens an overlay with session and window entries."
  (let ((s (make-fake-session :nwindows 2)))
    (let ((*overlay* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t)
          (cl-tmux::*server-sessions* nil))
      (cl-tmux::dispatch-command s :choose-tree nil)
      (is (overlay-active-p) ":choose-tree must open an overlay")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search (session-name s) text)
            "overlay must contain the session name")))))

(test dispatch-choose-tree-with-server-sessions
  ":choose-tree with multiple server sessions lists them all."
  (let* ((s1 (make-fake-session :nwindows 1))
         (s2 (make-fake-session :nwindows 2))
         (reg (list (cons (session-name s1) s1)
                    (cons (session-name s2) s2))))
    (let ((*overlay* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t)
          (cl-tmux::*server-sessions* reg))
      (cl-tmux::dispatch-command s1 :choose-tree nil)
      (is (overlay-active-p) ":choose-tree must open an overlay with server sessions")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search (session-name s1) text)
            "overlay must contain session 1 name")
        (is (search (session-name s2) text)
            "overlay must contain session 2 name")))))

;;; ── :set-window-option dispatch ──────────────────────────────────────────────

(test dispatch-set-window-option-opens-prompt
  ":set-window-option opens a prompt."
  (let ((s (make-fake-session)))
    (let ((*prompt* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
      (cl-tmux::dispatch-command s :set-window-option nil)
      (is (prompt-active-p) ":set-window-option must open a prompt")
      (is (string= "set-window-option" (prompt-label *prompt*))
          ":set-window-option prompt label must be \"set-window-option\""))))

;;; ── :set-session-option dispatch ─────────────────────────────────────────────

(test dispatch-set-session-option-opens-prompt
  ":set-session-option opens a prompt."
  (let ((s (make-fake-session)))
    (let ((*prompt* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
      (cl-tmux::dispatch-command s :set-session-option nil)
      (is (prompt-active-p) ":set-session-option must open a prompt")
      (is (string= "set-session-option" (prompt-label *prompt*))
          ":set-session-option prompt label must be \"set-session-option\""))))

;;; ── :confirm-before dispatch ─────────────────────────────────────────────────
;;;
;;; confirm-before is implemented in dispatch.lisp as a prompt with an
;;; on-submit lambda.  The helper below eliminates repetition across the input
;;; variants.

(defmacro with-confirm-before-prompt ((on-submit-var) &body body)
  "Activate a confirm-before prompt in an isolated environment and bind
   ON-SUBMIT-VAR to the prompt's on-submit function, then execute BODY."
  `(let ((sess (make-fake-session)))
     (with-loop-state
       (with-clean-prompt
         (let ((*overlay* nil))
           (cl-tmux::dispatch-command sess :confirm-before nil)
           (is-true (prompt-active-p)
                    "dispatch-command :confirm-before must activate a prompt")
           (let ((,on-submit-var (prompt-on-submit *prompt*)))
             ,@body))))))

(test confirm-before-y-dispatches
  "dispatch-command :confirm-before activates a prompt; submitting \"y\" shows the overlay."
  (with-confirm-before-prompt (on-submit)
    (funcall on-submit "y")
    (is (overlay-active-p)
        "on-submit with \"y\" must show the [confirmed] overlay")))

(test confirm-before-n-cancels
  "dispatch-command :confirm-before activates a prompt; submitting \"n\" does NOT show overlay."
  (with-confirm-before-prompt (on-submit)
    (funcall on-submit "n")
    (is (null (overlay-active-p))
        "on-submit with \"n\" must NOT show the overlay")))

(test confirm-before-empty-cancels
  "dispatch-command :confirm-before activates a prompt; submitting \"\" does NOT show overlay."
  (with-confirm-before-prompt (on-submit)
    (funcall on-submit "")
    (is (null (overlay-active-p))
        "on-submit with empty string must NOT show the overlay")))

;;; ── %set-option-from-prompt helper ──────────────────────────────────────────

(test set-option-from-prompt-helper-opens-prompt
  "%set-option-from-prompt opens a prompt with the given label."
  (let ((*prompt* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
    (cl-tmux::%set-option-from-prompt "test-label")
    (is (prompt-active-p) "%set-option-from-prompt must open a prompt")
    (is (string= "test-label" (prompt-label *prompt*))
        "%set-option-from-prompt prompt label must match the argument")))

(test set-option-from-prompt-sets-option
  "%set-option-from-prompt on-submit with 'name value' calls set-option."
  (let ((*prompt* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
    (cl-tmux::%set-option-from-prompt "set-window-option")
    (is (prompt-active-p) "prompt must be open")
    ;; Submit "mouse on" which maps to set-option "mouse" "on"
    (finishes (funcall (prompt-on-submit *prompt*) "mouse on")
              "%set-option-from-prompt on-submit must not error")))

;;; ── %paste-to-pane helper ────────────────────────────────────────────────────

(test paste-to-pane-no-crash-fd-minus-one
  "%paste-to-pane with fd=-1 pane is a no-op (guard skips the write)."
  (let* ((screen (make-screen 20 5))
         (pane   (make-pane :id 1 :fd -1 :pid -1 :x 0 :y 0 :width 20 :height 5
                            :screen screen)))
    (finishes (cl-tmux::%paste-to-pane pane "hello world")
              "%paste-to-pane must not error with fd=-1 pane")))

(test paste-to-pane-nil-text-is-noop
  "%paste-to-pane with nil text is a no-op."
  (let* ((screen (make-screen 20 5))
         (pane   (make-pane :id 1 :fd -1 :pid -1 :x 0 :y 0 :width 20 :height 5
                            :screen screen)))
    (finishes (cl-tmux::%paste-to-pane pane nil)
              "%paste-to-pane with nil text must not error")))

;;; ── %format-tree-entry helper ────────────────────────────────────────────────

(test format-tree-entry-marks-current-session
  "%format-tree-entry marks the current session with an asterisk."
  (let* ((screen (make-screen 20 5))
         (pane   (make-pane :id 1 :fd -1 :pid -1 :x 0 :y 0 :width 20 :height 5
                            :screen screen))
         (win    (make-window :id 0 :name "test-win" :width 20 :height 5
                              :panes (list pane)
                              :tree  (make-layout-leaf pane))))
    (window-select-pane win pane)
    (let ((output
            (with-output-to-string (s)
              (cl-tmux::%format-tree-entry s "mysess" "mysess"
                                          (list win) win))))
      (is (search "* mysess" output)
          "current session must be marked with '* ' prefix")
      (is (search "test-win" output)
          "window name must appear in the output"))))

(test format-tree-entry-non-current-session-uses-space
  "%format-tree-entry uses '  ' prefix for non-current sessions."
  (let* ((screen (make-screen 20 5))
         (pane   (make-pane :id 1 :fd -1 :pid -1 :x 0 :y 0 :width 20 :height 5
                            :screen screen))
         (win    (make-window :id 0 :name "w" :width 20 :height 5
                              :panes (list pane)
                              :tree  (make-layout-leaf pane))))
    (window-select-pane win pane)
    (let ((output
            (with-output-to-string (s)
              (cl-tmux::%format-tree-entry s "other" "current"
                                          (list win) win))))
      (is (not (search "* other" output))
          "non-current session must not start with '* '")
      (is (search "  other" output)
          "non-current session must start with '  '"))))

;;; ── :choose-session / :list-sessions-full aliases ────────────────────────────

(test dispatch-choose-session-shows-session-list
  ":choose-session shows the session list overlay (same body as :list-sessions)."
  (let ((s (make-fake-session :nwindows 1)))
    (let ((*overlay* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t)
          (cl-tmux::*server-sessions* nil))
      (cl-tmux::dispatch-command s :choose-session nil)
      (is (overlay-active-p) ":choose-session must open an overlay")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search (session-name s) text)
            ":choose-session overlay must contain the session name")))))

(test dispatch-list-sessions-full-shows-session-list
  ":list-sessions-full shows the session list overlay."
  (let ((s (make-fake-session :nwindows 1)))
    (let ((*overlay* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t)
          (cl-tmux::*server-sessions* nil))
      (cl-tmux::dispatch-command s :list-sessions-full nil)
      (is (overlay-active-p) ":list-sessions-full must open an overlay"))))

;;; ── :resize-left/:resize-right/:resize-up/:resize-down dispatch ──────────────

(test dispatch-resize-commands-do-not-error
  "The four resize commands dispatch without signalling an error."
  (let ((s (make-fake-session)))
    (with-loop-state
      (dolist (cmd '(:resize-left :resize-right :resize-up :resize-down))
        (finishes (cl-tmux::dispatch-command s cmd nil)
                  "~A must not signal an error" cmd)))))

;;; ── :rotate-window / :rotate-window-reverse dispatch ─────────────────────────

(test dispatch-rotate-window-does-not-error
  ":rotate-window dispatches without error on a single-pane window."
  (let ((s (make-fake-session :nwindows 1 :npanes 1)))
    (with-loop-state
      (finishes (cl-tmux::dispatch-command s :rotate-window nil)
                ":rotate-window must not signal an error"))))

(test dispatch-rotate-window-reverse-does-not-error
  ":rotate-window-reverse dispatches without error on a single-pane window."
  (let ((s (make-fake-session :nwindows 1 :npanes 1)))
    (with-loop-state
      (finishes (cl-tmux::dispatch-command s :rotate-window-reverse nil)
                ":rotate-window-reverse must not signal an error"))))

;;; ── :split-horizontal / :split-vertical (no-focus) dispatch ─────────────────

(test dispatch-split-horizontal-no-focus-does-not-error
  ":split-horizontal-no-focus dispatches without error."
  (let ((s (make-fake-session :nwindows 1 :npanes 1)))
    (with-loop-state
      (finishes (cl-tmux::dispatch-command s :split-horizontal-no-focus nil)
                ":split-horizontal-no-focus must not signal an error"))))

(test dispatch-split-vertical-no-focus-does-not-error
  ":split-vertical-no-focus dispatches without error."
  (let ((s (make-fake-session :nwindows 1 :npanes 1)))
    (with-loop-state
      (finishes (cl-tmux::dispatch-command s :split-vertical-no-focus nil)
                ":split-vertical-no-focus must not signal an error"))))

;;; ── :synchronize-panes toggle ────────────────────────────────────────────────

(test dispatch-synchronize-panes-toggles
  ":synchronize-panes toggles the option and shows an overlay."
  (let ((s (make-fake-session)))
    (let ((*overlay* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
      (cl-tmux/options:set-option "synchronize-panes" nil)
      (cl-tmux::dispatch-command s :synchronize-panes nil)
      (is (overlay-active-p) ":synchronize-panes must show an overlay")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search "ON" text) "first toggle must produce ON message"))
      ;; Toggle back off.
      (cl-tmux::dispatch-command s :synchronize-panes nil)
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search "OFF" text) "second toggle must produce OFF message")))))

;;; ── :lock-session / :unlock-session dispatch ─────────────────────────────────

(test dispatch-lock-unlock-session
  ":lock-session sets session-locked-p; :unlock-session clears it."
  (let ((s (make-fake-session)))
    (with-loop-state
      (is-false (session-locked-p s) "session must be unlocked initially")
      (cl-tmux::dispatch-command s :lock-session nil)
      (is-true  (session-locked-p s) "session must be locked after :lock-session")
      (cl-tmux::dispatch-command s :unlock-session nil)
      (is-false (session-locked-p s) "session must be unlocked after :unlock-session"))))

;;; ── :last-window dispatch ────────────────────────────────────────────────────

(test dispatch-last-window-selects-previous-window
  ":last-window selects the previously active window."
  (let ((s (make-fake-session :nwindows 2)))
    (with-loop-state
      (let* ((w0 (first  (session-windows s)))
             (w1 (second (session-windows s))))
        ;; Visit w1, then switch back to w0.
        (session-select-window s w1)
        (session-select-window s w0)
        ;; :last-window should go back to w1.
        (cl-tmux::dispatch-command s :last-window nil)
        (is (eq w1 (session-active-window s))
            ":last-window must return to the previously active window")))))

;;; ── :show-options / :show-option dispatch ────────────────────────────────────

(test dispatch-show-options-shows-overlay
  ":show-options opens an overlay listing global options."
  (let ((s (make-fake-session)))
    (let ((*overlay* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
      (cl-tmux::dispatch-command s :show-options nil)
      (is (overlay-active-p) ":show-options must open an overlay"))))

(test dispatch-show-option-opens-prompt
  ":show-option opens a prompt for the option name."
  (let ((s (make-fake-session)))
    (let ((*prompt* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
      (cl-tmux::dispatch-command s :show-option nil)
      (is (prompt-active-p) ":show-option must open a prompt"))))

;;; ── :respawn-pane dispatch ────────────────────────────────────────────────────

(test dispatch-respawn-pane-does-not-error
  ":respawn-pane dispatches without error on a no-PTY fake session."
  (let ((s (make-fake-session :nwindows 1 :npanes 1)))
    (with-loop-state
      ;; respawn-pane tries to fork a shell; it may fail in test sandbox.
      ;; We verify dispatch does not error at the dispatch layer itself.
      (handler-case
          (progn
            (cl-tmux::dispatch-command s :respawn-pane nil)
            (is-true t ":respawn-pane dispatched without error"))
        (error (e)
          (declare (ignore e))
          (is-true t ":respawn-pane signalled at PTY level (expected in sandbox)"))))))

;;; ── :pipe-pane dispatch ──────────────────────────────────────────────────────

(test dispatch-pipe-pane-opens-prompt-when-not-open
  ":pipe-pane opens a prompt for the command when no pipe is open."
  (let ((s (make-fake-session)))
    (let ((*prompt* nil) (cl-tmux::*dirty* nil) (cl-tmux::*running* t))
      (cl-tmux::dispatch-command s :pipe-pane nil)
      (is (prompt-active-p) ":pipe-pane must open a prompt when pipe is not open"))))

;;; ── :last-pane dispatch ──────────────────────────────────────────────────────

(test dispatch-last-pane-selects-previous-pane
  ":last-pane selects the previously active pane."
  (let* ((s   (make-fake-session :nwindows 1 :npanes 2))
         (win (session-active-window s))
         (p0  (first  (window-panes win)))
         (p1  (second (window-panes win))))
    (with-loop-state
      ;; Visit p1, then switch back to p0.
      (window-select-pane win p1)
      (window-select-pane win p0)
      ;; :last-pane should return to p1.
      (cl-tmux::dispatch-command s :last-pane nil)
      (is (eq p1 (window-active-pane win))
          ":last-pane must select the previously active pane"))))

;;; ── %format-window-list helper ───────────────────────────────────────────────

(test format-window-list-includes-active-marker
  "%format-window-list includes an asterisk on the active window line and
   lists each window by id and name."
  (let ((s (make-fake-session :nwindows 2)))
    (let* ((text (cl-tmux::%format-window-list s))
           (aw   (session-active-window s)))
      (is (stringp text) "%format-window-list must return a string")
      (is (search (window-name aw) text)
          "output must mention the active window name")
      (is (search "*" text)
          "output must mark the active window with an asterisk"))))

(test format-window-list-shows-pane-count
  "%format-window-list includes the pane count for each window."
  (let ((s (make-fake-session :nwindows 1 :npanes 2)))
    (let ((text (cl-tmux::%format-window-list s)))
      ;; The format string ends each line with "[N pane(s)]".
      (is (search "pane" text)
          "output must include the word 'pane'"))))

;;; ── %format-session-list helper ──────────────────────────────────────────────

(test format-session-list-fallback-uses-session-name
  "%format-session-list with empty *server-sessions* falls back to the
   session-name one-line entry."
  (let ((s (make-fake-session :nwindows 1)))
    (let ((cl-tmux::*server-sessions* nil))
      (let ((text (cl-tmux::%format-session-list s)))
        (is (stringp text) "%format-session-list must return a string")
        (is (search (session-name s) text)
            "fallback output must contain the session name")))))

(test format-session-list-marks-current-session
  "%format-session-list with a populated *server-sessions* marks the current
   session with an asterisk."
  (let* ((s    (make-fake-session :nwindows 1))
         (name (session-name s)))
    (let ((cl-tmux::*server-sessions* (list (cons name s))))
      (let ((text (cl-tmux::%format-session-list s)))
        (is (search "*" text) "current session must be marked with an asterisk")
        (is (search name text) "output must contain the session name")))))

;;; ── %copy-mode-call helper ────────────────────────────────────────────────────

(test copy-mode-call-invokes-fn-on-active-screen
  "%copy-mode-call invokes FN on the active screen when copy mode is on."
  (let ((s (make-fake-session)))
    (with-loop-state
      (cl-tmux::dispatch-command s :copy-mode-enter nil)
      (let ((called-with nil))
        (cl-tmux::%copy-mode-call s (lambda (sc) (setf called-with sc)))
        (is (eq (active-screen s) called-with)
            "%copy-mode-call must pass the active screen to FN")))))

(test copy-mode-call-skips-when-no-session-has-no-screen
  "%copy-mode-call on a windowless session is a no-op (no error)."
  (let ((s (make-session :id 1 :name "0" :windows nil)))
    (with-loop-state
      (finishes (cl-tmux::%copy-mode-call s (lambda (sc) (declare (ignore sc)) nil))
                "%copy-mode-call must not error when there is no active screen"))))

;;; ── %handle-kill-result helper ────────────────────────────────────────────────

(test handle-kill-result-sets-running-nil-on-quit
  "%handle-kill-result clears *running* when RESULT is :quit."
  (let ((cl-tmux::*running* t))
    (cl-tmux::%handle-kill-result :quit)
    (is-false cl-tmux::*running*
              "*running* must be NIL after :quit")))

(test handle-kill-result-preserves-running-for-nil
  "%handle-kill-result does NOT clear *running* for a NIL result."
  (let ((cl-tmux::*running* t))
    (cl-tmux::%handle-kill-result nil)
    (is-true cl-tmux::*running*
             "*running* must remain T for nil result")))

(test handle-kill-result-returns-its-argument
  "%handle-kill-result returns its argument unchanged."
  (let ((cl-tmux::*running* t))
    (is (eq :quit (cl-tmux::%handle-kill-result :quit)))
    (is (null (cl-tmux::%handle-kill-result nil)))))
