(in-package #:cl-tmux/test)

;;;; Command dispatch tests (src/dispatch-core.lisp,
;;;;                         src/dispatch-commands.lisp,
;;;;                         src/dispatch-commands-pane.lisp,
;;;;                         src/dispatch-commands-auto.lisp,
;;;;                         src/dispatch-commands-runner.lisp,
;;;;                         src/dispatch-control.lisp,
;;;;                         src/dispatch-handlers.lisp,
;;;;                         src/dispatch-handlers-buffer.lisp).
;;;; Tests: dispatch-suite — dispatch-command, dispatch-prefix-command,
;;;; next-cyclic, prev-cyclic, %copy-mode-active-p.

(def-suite dispatch-suite :description "Command dispatch and prefix routing")
(in-suite dispatch-suite)

;;; ── Cyclic helpers (generated by define-cyclic-navigators) ─────────────────

(test next-cyclic-wraps
  "next-cyclic advances and wraps past the end."
  (is (eql 'b (cl-tmux::next-cyclic '(a b c) 'a)))
  (is (eql 'a (cl-tmux::next-cyclic '(a b c) 'c)))
  (is (eql 'b (cl-tmux::next-cyclic '(a b c) 'missing))))   ; unknown → idx 0 → element 1

(test prev-cyclic-wraps
  "prev-cyclic steps back and wraps past the front."
  (is (eql 'a (cl-tmux::prev-cyclic '(a b c) 'b)))
  (is (eql 'c (cl-tmux::prev-cyclic '(a b c) 'a))))

(test define-cyclic-navigators-macro-is-defined
  "define-cyclic-navigators is a defined macro that generated next-cyclic and prev-cyclic."
  (is (macro-function 'cl-tmux::define-cyclic-navigators)
      "define-cyclic-navigators must be a macro")
  ;; Both generated functions are symmetric: stepping n and -n return to original.
  (is (eql 'a (cl-tmux::prev-cyclic '(a b c)
                                    (cl-tmux::next-cyclic '(a b c) 'a)))
      "next then prev returns to same element"))

;;; ── with-active-pane macro ──────────────────────────────────────────────────

(test with-active-pane-returns-nil-for-empty-session
  "with-active-pane evaluates to NIL when there is no active pane."
  (with-empty-session (s)
    (with-loop-state
      ;; %active-screen uses with-active-pane internally
      (is (null (cl-tmux::%active-screen s))
          "empty session has no active screen"))))

(test with-active-pane-macro-is-defined
  "with-active-pane is a defined macro."
  (is (macro-function 'cl-tmux::with-active-pane)))

;;; ── Window / pane selection ────────────────────────────────────────────────

(test dispatch-next-window-cycles
  "C-b n moves to the next window and wraps around."
  (with-fake-session (s :nwindows 2)
    (cl-tmux::dispatch-command s :next-window nil)
    (is (eq (second (session-windows s)) (session-active-window s)))
    (cl-tmux::dispatch-command s :next-window nil)
    (is (eq (first (session-windows s)) (session-active-window s))
        "second :next-window should wrap back to window 1")))

(test dispatch-prev-window-wraps
  "C-b p from the first window wraps to the last."
  (with-fake-session (s :nwindows 2)
    (cl-tmux::dispatch-command s :prev-window nil)
    (is (eq (second (session-windows s)) (session-active-window s)))))

(test notify-pane-focus-fires-focus-hooks
  "%notify-pane-focus fires pane-focus-in / pane-focus-out independent of ?1004."
  (with-isolated-hooks
    (let* ((s        (make-fake-session :nwindows 1 :npanes 1))
           (pane     (session-active-pane s))
           (in-fired nil) (out-fired nil))
      (cl-tmux/hooks:add-hook "pane-focus-in"
                              (lambda (&rest _) (declare (ignore _)) (setf in-fired t)))
      (cl-tmux/hooks:add-hook "pane-focus-out"
                              (lambda (&rest _) (declare (ignore _)) (setf out-fired t)))
      (cl-tmux::%notify-pane-focus pane t)
      (is-true in-fired "focus-in hook fires on focus gain")
      (cl-tmux::%notify-pane-focus pane nil)
      (is-true out-fired "focus-out hook fires on focus loss"))))

(test select-pane-with-focus-fires-out-then-in
  "Switching panes fires focus-out for the old pane and focus-in for the new."
  (with-isolated-hooks
    (let* ((s         (make-fake-session :nwindows 1 :npanes 2))
           (win       (session-active-window s))
           (panes     (window-panes win))
           (in-count 0) (out-count 0))
      (cl-tmux/hooks:add-hook "pane-focus-in"
                              (lambda (&rest _) (declare (ignore _)) (incf in-count)))
      (cl-tmux/hooks:add-hook "pane-focus-out"
                              (lambda (&rest _) (declare (ignore _)) (incf out-count)))
      (cl-tmux::%select-pane-with-focus win (second panes))
      (is (= 1 out-count) "focus-out fires once (old pane)")
      (is (= 1 in-count)  "focus-in fires once (new pane)"))))

(test run-command-tokens-abbrev-next-dispatches
  "%run-command-tokens resolves the tmux abbreviation 'next' (no-arg named-table
   path) to :next-window."
  (with-fake-session (s :nwindows 2)
    (cl-tmux::%run-command-tokens s '("next"))
    (is (eq (second (session-windows s)) (session-active-window s))
        "abbrev 'next' must advance to the next window")))

(test run-command-tokens-abbrev-prev-dispatches
  "%run-command-tokens resolves the abbreviation 'prev' (no-arg named-table path)
   to :prev-window, which from the first window wraps to the last."
  (with-fake-session (s :nwindows 2)
    (cl-tmux::%run-command-tokens s '("prev"))
    (is (eq (second (session-windows s)) (session-active-window s))
        "abbrev 'prev' must wrap to the last window")))

(test run-command-tokens-abbrev-renamew-with-arg
  "%run-command-tokens resolves the arg-bearing abbreviation 'renamew' through
   *arg-command-table* to rename the active window."
  (with-fake-session (s :nwindows 1)
    (cl-tmux::%run-command-tokens s '("renamew" "myname"))
    (is (string= "myname" (window-name (session-active-window s)))
        "renamew must rename the active window via the arg-table alias")))

(test dispatch-next-pane-cycles
  "C-b o moves to the next pane within the active window."
  (let* ((s   (make-fake-session :nwindows 1 :npanes 2))
         (win (session-active-window s))
         (p0  (first  (window-panes win)))
         (p1  (second (window-panes win))))
    (with-loop-state
      (is (eq p0 (window-active-pane win)))
      (cl-tmux::dispatch-command s :next-pane nil)
      (is (eq p1 (window-active-pane win))))))

(test dispatch-select-window-by-digit
  "C-b <n>: :select-window uses the pressed digit byte to pick the window."
  (with-fake-session (s :nwindows 3)
    (cl-tmux::dispatch-command s :select-window (char-code #\2))
    (is (eq (third (session-windows s)) (session-active-window s)))
    (cl-tmux::dispatch-command s :select-window (char-code #\0))
    (is (eq (first (session-windows s)) (session-active-window s)))))

(test dispatch-unknown-command-passes-through
  "An unrecognized command falls through to the passthrough branch: it returns
   NIL (no quit), doesn't error, and still marks the session dirty."
  (with-fake-session (s)
    (is (null (cl-tmux::dispatch-command s :no-such-command (char-code #\a))))
    (is-true cl-tmux::*dirty* "dispatch marks dirty even on passthrough")))

;;; ── Rename ──────────────────────────────────────────────────────────────────

(test dispatch-rename-window-opens-prompt
  "C-b , opens a rename prompt seeded with the active window's name, and its
   on-submit closure renames the active window."
  (with-fake-session (s :nwindows 1)
    (let ((*prompt* nil))
      (cl-tmux::dispatch-command s :rename-window nil)
      (is (prompt-active-p) "rename should open a prompt")
      (is (string= "0" (prompt-buffer *prompt*))
          "prompt seeded with current window name")
      (is (functionp (prompt-on-submit *prompt*))
          "prompt should carry an on-submit closure")
      (funcall (prompt-on-submit *prompt*) "renamed")
      (is (string= "renamed" (window-name (session-active-window s)))
          "on-submit closure should rename the active window"))))

;;; ── Copy mode ───────────────────────────────────────────────────────────────

(test dispatch-copy-mode-enter-exit
  "C-b [ enters copy mode on the active screen; exit clears it."
  (with-fake-session (s)
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (is (screen-copy-mode-p (active-screen s)) "copy mode should be on after enter")
    (cl-tmux::dispatch-command s :copy-mode-exit nil)
    (is-false (screen-copy-mode-p (active-screen s)) "copy mode should be off after exit")))

(test copy-mode-active-p-reflects-state
  "%copy-mode-active-p tracks the active screen's copy-mode flag."
  (with-fake-session (s)
    (is-false (cl-tmux::%copy-mode-active-p s))
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (is (cl-tmux::%copy-mode-active-p s))))

(test send-keys-R-resets-pane-terminal-state
  "send-keys -R resets the target pane's terminal state (RIS): the cursor is homed."
  (let* ((s    (make-fake-session :nwindows 1 :npanes 1))
         (win  (cl-tmux/model:session-active-window s))
         (pane (cl-tmux/model:window-active-pane win))
         (scr  (cl-tmux/model:pane-screen pane)))
    (with-loop-state
      (setf (cl-tmux/terminal/types:screen-cursor-x scr) 5
            (cl-tmux/terminal/types:screen-cursor-y scr) 3)
      (cl-tmux::%cmd-send-keys-arg s '("-R"))
      (is (= 0 (cl-tmux/terminal/types:screen-cursor-x scr))
          "send-keys -R must home the cursor x")
      (is (= 0 (cl-tmux/terminal/types:screen-cursor-y scr))
          "send-keys -R must home the cursor y"))))

;;; ── send-keys -X copy-mode commands: cursor-left/right + rectangle-toggle ────

(test send-keys-x-command-table-maps-cursor-and-rectangle
  "The send-keys -X command table maps cursor-left/right and rectangle-toggle to
   their proper copy-mode keywords (no longer the begin-selection approximation)."
  (flet ((kw (name) (cdr (assoc name cl-tmux::*copy-mode-x-commands* :test #'string-equal))))
    (is (eq :copy-mode-cursor-left      (kw "cursor-left")))
    (is (eq :copy-mode-cursor-right     (kw "cursor-right")))
    (is (eq :copy-mode-cursor-up        (kw "cursor-up")))
    (is (eq :copy-mode-cursor-down      (kw "cursor-down")))
    (is (eq :copy-mode-rectangle-toggle (kw "rectangle-toggle")))))

(test send-keys-x-command-table-maps-select-word-and-other-end
  "select-word maps to :copy-mode-select-word, and both other-end (real tmux
   name) and toggle-position map to :copy-mode-other-end (no longer the
   begin-selection placeholder)."
  (flet ((kw (name) (cdr (assoc name cl-tmux::*copy-mode-x-commands* :test #'string-equal))))
    (is (eq :copy-mode-select-word (kw "select-word")))
    (is (eq :copy-mode-other-end   (kw "other-end")))
    (is (eq :copy-mode-other-end   (kw "toggle-position")))))

(test send-keys-x-rectangle-toggle-toggles-rect-select
  "send -X rectangle-toggle flips the screen's rectangle (block) selection flag
   instead of starting a stream selection."
  (with-fake-session (s)
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (let ((screen (active-screen s)))
      (is-false (screen-copy-rect-select-p screen) "rect-select off on entry")
      (is (cl-tmux::%dispatch-send-keys-X s "rectangle-toggle")
          "rectangle-toggle must be a handled -X command")
      (is (screen-copy-rect-select-p screen) "rectangle-toggle turns rect-select ON")
      (cl-tmux::%dispatch-send-keys-X s "rectangle-toggle")
      (is-false (screen-copy-rect-select-p screen) "a second toggle turns it OFF"))))

(test send-keys-x-cursor-left-right-move-cursor
  "send -X cursor-right / cursor-left move the copy-mode cursor horizontally
   (previously both mis-mapped to begin-selection, which did not move it)."
  (with-fake-session (s)
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (let ((screen (active-screen s)))
      (cl-tmux::%dispatch-send-keys-X s "cursor-right")
      (is (= 1 (cdr (screen-copy-cursor screen)))
          "cursor-right moves the cursor to column 1 (from the initial column 0)")
      (cl-tmux::%dispatch-send-keys-X s "cursor-left")
      (is (= 0 (cdr (screen-copy-cursor screen)))
          "cursor-left moves the cursor back to column 0"))))

(test send-keys-x-cursor-up-down-move-cursor-vertically
  "send -X cursor-up / cursor-down move the copy cursor vertically (the -X names
   previously only scrolled a line, inconsistent with the arrow-key path)."
  (with-fake-session (s)
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (let* ((screen (active-screen s))
           (h      (screen-height screen)))
      (cl-tmux::%dispatch-send-keys-X s "cursor-up")
      (is (= (- h 2) (car (screen-copy-cursor screen)))
          "cursor-up moves the cursor one row up from the bottom")
      (cl-tmux::%dispatch-send-keys-X s "cursor-down")
      (is (= (- h 1) (car (screen-copy-cursor screen)))
          "cursor-down moves the cursor back to the bottom row"))))

;;; ── Detach / kill ───────────────────────────────────────────────────────────

(test dispatch-detach-returns-detach
  "C-b d returns :detach and does NOT clear *running* itself (the caller decides:
   standalone stops, a server merely disconnects the client)."
  (with-fake-session (s)
    (is (eq :detach (cl-tmux::dispatch-command s :detach nil)))
    (is-true cl-tmux::*running* "dispatch-command must not clear *running*")))

(test dispatch-kill-last-window-quits
  "Killing the only window ends the session (:quit)."
  (with-fake-session (s :nwindows 1)
    (is (eq :quit (cl-tmux::dispatch-command s :kill-window nil)))))

(test dispatch-kill-one-of-two-windows-survives
  "Killing one of two windows leaves the session running with the other."
  (with-fake-session (s :nwindows 2)
    (is (null (cl-tmux::dispatch-command s :kill-window nil)))
    (is (= 1 (length (session-windows s))))))

(test dispatch-kill-last-pane-quits
  "Killing the sole pane of the sole window ends the session (:quit)."
  (with-fake-session (s :nwindows 1 :npanes 1)
    (is (eq :quit (cl-tmux::dispatch-command s :kill-pane nil)))))

;;; ── Prefix routing ──────────────────────────────────────────────────────────

(test dispatch-prefix-routes-binding
  "dispatch-prefix-command looks the byte up in the binding table (d → detach)."
  (with-fake-session (s)
    (is (eq :detach (cl-tmux::dispatch-prefix-command s (char-code #\d))))))

(test prefix-q-exits-copy-mode
  "In copy mode, the prefix-routed 'q' exits copy mode."
  (with-fake-session (s)
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (cl-tmux::dispatch-prefix-command s (char-code #\q))
    (is-false (screen-copy-mode-p (active-screen s)))))

;;; ── %active-screen ───────────────────────────────────────────────────────────

(test active-screen-returns-active-pane-screen
  "%active-screen returns the screen of the session's active pane."
  (with-fake-session (s)
    (let ((ap (session-active-pane s)))
      (is (eq (pane-screen ap)
              (cl-tmux::%active-screen s))
          "%active-screen must return the active pane's screen"))))

(test active-screen-returns-nil-for-empty-session
  "%active-screen returns NIL when no pane is active."
  (with-empty-session (s)
    (with-loop-state
      (is (null (cl-tmux::%active-screen s))))))

;;; ── %cmd-cycle-window ────────────────────────────────────────────────────────

(test cmd-cycle-window-advances-selection
  "%cmd-cycle-window advances the active window via CYCLER."
  (let* ((s  (make-fake-session :nwindows 3))
         (w1 (first  (session-windows s)))
         (w2 (second (session-windows s))))
    (with-loop-state
      (is (eq w1 (session-active-window s)))
      (cl-tmux::%cmd-cycle-window s #'cl-tmux::next-cyclic)
      (is (eq w2 (session-active-window s))))))

;;; ── %cmd-cycle-pane ──────────────────────────────────────────────────────────

(test cmd-cycle-pane-advances-pane-selection
  "%cmd-cycle-pane advances the active pane via CYCLER."
  (let* ((s   (make-fake-session :nwindows 1 :npanes 2))
         (win (session-active-window s))
         (p0  (first  (window-panes win)))
         (p1  (second (window-panes win))))
    (with-loop-state
      (is (eq p0 (window-active-pane win)))
      (cl-tmux::%cmd-cycle-pane s #'cl-tmux::next-cyclic)
      (is (eq p1 (window-active-pane win))))))

;;; ── focus events (?1004) on pane switch ──────────────────────────────────────

(test notify-pane-focus-noop-without-pty
  "%notify-pane-focus is a safe no-op for a pane with no live PTY (fd <= 0),
   even when focus events are enabled."
  (let ((pane (make-pane :id 1 :x 0 :y 0 :width 20 :height 5 :fd -1
                         :screen (make-screen 20 5))))
    (setf (cl-tmux/terminal/types:screen-focus-events (pane-screen pane)) t)
    (is (null (cl-tmux::%notify-pane-focus pane t))
        "no PTY → %notify-pane-focus returns NIL without writing")
    (finishes (cl-tmux::%notify-pane-focus pane nil))))

(test notify-pane-focus-writes-focus-in-to-pty
  "With focus events enabled and a live fd, %notify-pane-focus delivers the
   focus-gained report ESC[I to the pane's PTY."
  (with-pipe-fds (rfd wfd)
    (let ((pane (make-pane :id 1 :x 0 :y 0 :width 20 :height 5 :fd wfd
                           :screen (make-screen 20 5))))
      (setf (cl-tmux/terminal/types:screen-focus-events (pane-screen pane)) t)
      (cl-tmux::%notify-pane-focus pane t)
      (let ((ready (cl-tmux/pty:select-fds (list rfd) 200000)))  ; 200 ms
        (is-true ready "the PTY read-end must be readable after a focus report")
        (when ready
          (cffi:with-foreign-object (buf :uint8 8)
            (let ((n (cffi:foreign-funcall "read"
                                           :int rfd :pointer buf :unsigned-long 3
                                           :long)))
              (is (= 3 n) "focus-in report must be exactly 3 bytes (got ~D)" n)
              (is (= 27 (cffi:mem-aref buf :uint8 0)) "byte 0 must be ESC (27)")
              (is (= 91 (cffi:mem-aref buf :uint8 1)) "byte 1 must be #\\[ (91)")
              (is (= 73 (cffi:mem-aref buf :uint8 2)) "byte 2 must be #\\I (73)"))))))))

(test notify-pane-focus-disabled-screen-writes-nothing
  "A pane whose app did NOT enable focus events receives no report even with a
   live fd, and select-fds reports the pipe idle."
  (with-pipe-fds (rfd wfd)
    (let ((pane (make-pane :id 1 :x 0 :y 0 :width 20 :height 5 :fd wfd
                           :screen (make-screen 20 5))))
      ;; focus-events left NIL (default)
      (cl-tmux::%notify-pane-focus pane t)
      (is (null (cl-tmux/pty:select-fds (list rfd) 20000))
          "no focus report must reach an opted-out pane (pipe must stay idle)"))))

(test select-pane-with-focus-switches-and-tolerates-no-pty
  "%select-pane-with-focus changes the active pane and runs the focus-notify path
   without error even when panes have no PTY and focus events are enabled."
  (let* ((s   (make-fake-session :nwindows 1 :npanes 2))
         (win (session-active-window s))
         (p0  (first  (window-panes win)))
         (p1  (second (window-panes win))))
    (setf (cl-tmux/terminal/types:screen-focus-events (pane-screen p0)) t)
    (setf (cl-tmux/terminal/types:screen-focus-events (pane-screen p1)) t)
    (with-loop-state
      (is (eq p0 (window-active-pane win)))
      (finishes (cl-tmux::%select-pane-with-focus win p1))
      (is (eq p1 (window-active-pane win))
          "%select-pane-with-focus must make p1 the active pane"))))

;;; ── focus events (?1004) on window switch ────────────────────────────────────

(test cycle-window-delivers-focus-in-to-new-window-pane
  "Switching windows sends ESC[I (focus gained) to the newly active window's pane
   when that pane's app enabled focus events."
  (with-pipe-fds (rfd wfd)
    (let* ((s   (make-fake-session :nwindows 2 :npanes 1))
           (w1  (second (session-windows s)))
           (p1  (window-active-pane w1)))
      ;; Make the SECOND window's pane a live, focus-aware PTY.
      (setf (pane-fd p1) wfd)
      (setf (cl-tmux/terminal/types:screen-focus-events (pane-screen p1)) t)
      (with-loop-state
        (cl-tmux::%cmd-cycle-window s #'cl-tmux::next-cyclic)
        (is (eq w1 (session-active-window s)) "next-window must activate w1")
        (let ((ready (cl-tmux/pty:select-fds (list rfd) 200000)))  ; 200 ms
          (is-true ready "the new window's pane must receive a focus report")
          (when ready
            (cffi:with-foreign-object (buf :uint8 8)
              (let ((n (cffi:foreign-funcall "read"
                                             :int rfd :pointer buf :unsigned-long 3
                                             :long)))
                (is (= 3 n) "focus-in must be 3 bytes (got ~D)" n)
                (is (= 27 (cffi:mem-aref buf :uint8 0)) "byte 0 must be ESC (27)")
                (is (= 73 (cffi:mem-aref buf :uint8 2))
                    "byte 2 must be #\\I (73) for focus gained")))))))))

(test cycle-window-delivers-focus-out-to-old-window-pane
  "Switching away from a window sends ESC[O (focus lost) to the window being left."
  (with-pipe-fds (rfd wfd)
    (let* ((s   (make-fake-session :nwindows 2 :npanes 1))
           (w0  (first (session-windows s)))
           (p0  (window-active-pane w0)))
      ;; The FIRST (currently active) window's pane is the live, focus-aware PTY.
      (setf (pane-fd p0) wfd)
      (setf (cl-tmux/terminal/types:screen-focus-events (pane-screen p0)) t)
      (with-loop-state
        (cl-tmux::%cmd-cycle-window s #'cl-tmux::next-cyclic)
        (let ((ready (cl-tmux/pty:select-fds (list rfd) 200000)))
          (is-true ready "the old window's pane must receive a focus-out report")
          (when ready
            (cffi:with-foreign-object (buf :uint8 8)
              (let ((n (cffi:foreign-funcall "read"
                                             :int rfd :pointer buf :unsigned-long 3
                                             :long)))
                (is (= 3 n) "focus-out must be 3 bytes (got ~D)" n)
                (is (= 27 (cffi:mem-aref buf :uint8 0)) "byte 0 must be ESC (27)")
                (is (= 79 (cffi:mem-aref buf :uint8 2))
                    "byte 2 must be #\\O (79) for focus lost")))))))))

(test cycle-window-with-focus-events-no-pty-no-error
  "Cycling windows runs the focus-transition path without error when panes have no
   PTY, and still changes the active window."
  (let* ((s   (make-fake-session :nwindows 2 :npanes 1))
         (w0  (first  (session-windows s)))
         (w1  (second (session-windows s))))
    (setf (cl-tmux/terminal/types:screen-focus-events
           (pane-screen (window-active-pane w0))) t)
    (setf (cl-tmux/terminal/types:screen-focus-events
           (pane-screen (window-active-pane w1))) t)
    (with-loop-state
      (is (eq w0 (session-active-window s)))
      (finishes (cl-tmux::%cmd-cycle-window s #'cl-tmux::next-cyclic))
      (is (eq w1 (session-active-window s))
          "cycle-window must activate w1 even with focus events on and no PTY"))))

;;; ── list-keys overlay ───────────────────────────────────────────────────────

(test dispatch-list-keys-shows-overlay
  "C-b ? opens the key-binding help overlay."
  (with-fake-session (s)
    (let ((*overlay* nil))
      (cl-tmux::dispatch-command s :list-keys nil)
      (is (overlay-active-p) "list-keys should open the help overlay"))))

(test define-command-handlers-macro-is-defined
  "define-command-handlers is a defined macro."
  (is (macro-function 'cl-tmux::define-command-handlers)))

(test define-copy-mode-key-overrides-macro-is-defined
  "define-copy-mode-key-overrides is a defined macro."
  (is (macro-function 'cl-tmux::define-copy-mode-key-overrides)))

;;; ── select-pane-left/right/up/down dispatch ─────────────────────────────────
;;;
;;; These tests use the shared fixture macros from helpers.lisp instead of
;;; duplicating the setup inline.  with-two-pane-h-session and
;;; with-two-pane-v-session already encode the exact same geometry.

(test dispatch-select-pane-right-moves-active-pane
  ":select-pane-right moves the active pane to the right neighbour."
  (with-two-pane-h-session (sess win p0 p1)
    (with-loop-state
      (is (eq p0 (window-active-pane win)) "p0 is active initially")
      (cl-tmux::dispatch-command sess :select-pane-right nil)
      (is (eq p1 (window-active-pane win))
          "active pane must be p1 after :select-pane-right"))))

(test dispatch-select-pane-left-moves-active-pane
  ":select-pane-left moves the active pane to the left neighbour."
  (with-two-pane-h-session (sess win p0 p1)
    (with-loop-state
      ;; Start on p1, then go left.
      (window-select-pane win p1)
      (cl-tmux::dispatch-command sess :select-pane-left nil)
      (is (eq p0 (window-active-pane win))
          "active pane must be p0 after :select-pane-left"))))

(test dispatch-select-pane-right-noop-at-rightmost
  ":select-pane-right is a no-op when the active pane has no right neighbour."
  (with-two-pane-h-session (sess win p0 p1)
    (with-loop-state
      ;; Make p1 (rightmost) active, then try to go further right.
      (is (eq p0 (window-active-pane win)) "p0 is active initially")
      (window-select-pane win p1)
      (cl-tmux::dispatch-command sess :select-pane-right nil)
      (is (eq p1 (window-active-pane win))
          "active pane must remain p1 when no right neighbour exists"))))

(test dispatch-select-pane-down-moves-active-pane
  ":select-pane-down moves the active pane to the pane below."
  (with-two-pane-v-session (sess win p0 p1)
    (with-loop-state
      (is (eq p0 (window-active-pane win)) "p0 is active initially")
      (cl-tmux::dispatch-command sess :select-pane-down nil)
      (is (eq p1 (window-active-pane win))
          "active pane must be p1 after :select-pane-down"))))

(test dispatch-select-pane-up-moves-active-pane
  ":select-pane-up moves the active pane to the pane above."
  (with-two-pane-v-session (sess win p0 p1)
    (with-loop-state
      ;; Start on p1 (bottom), then go up.
      (window-select-pane win p1)
      (cl-tmux::dispatch-command sess :select-pane-up nil)
      (is (eq p0 (window-active-pane win))
          "active pane must be p0 after :select-pane-up"))))

;;; ── zoom-toggle dispatch ────────────────────────────────────────────────────

(test dispatch-zoom-toggle-sets-zoom-flag
  ":zoom-toggle zooms the active pane in and marks window-zoom-p as T."
  (with-two-pane-h-session (sess win p0 p1)
    (with-loop-state
      (is (and p0 p1) "both panes exist")
      (cl-tmux::dispatch-command sess :zoom-toggle nil)
      (is-true (cl-tmux/model:window-zoom-p win)
               "window-zoom-p must be T after :zoom-toggle dispatch")
      ;; Toggle back off.
      (cl-tmux::dispatch-command sess :zoom-toggle nil)
      (is-false (cl-tmux/model:window-zoom-p win)
                "window-zoom-p must be NIL after second :zoom-toggle dispatch"))))

;;; ── rename-session dispatch ─────────────────────────────────────────────────

(test dispatch-rename-session-opens-prompt
  ":rename-session opens a prompt seeded with the current session name, and
   its on-submit closure renames the session."
  (with-fake-session (s :nwindows 1)
    (let ((*prompt* nil))
      (cl-tmux::dispatch-command s :rename-session nil)
      (is (prompt-active-p) "rename-session must open a prompt")
      (is (string= "0" (prompt-buffer *prompt*))
          "prompt must be seeded with the current session name \"0\"")
      (funcall (prompt-on-submit *prompt*) "newsess")
      (is (string= "newsess" (session-name s))
          "on-submit must rename the session to the supplied name"))))

;;; ── %select-pane-in-direction ───────────────────────────────────────────────
;;;
;;; Use the shared fixture macros to avoid repeating pane/window/session setup.

(test select-pane-in-direction-right-selects-right-pane
  "%select-pane-in-direction :right from the left pane selects the right pane."
  (with-two-pane-h-session (sess win p0 p1)
    (with-loop-state
      (is (eq p0 (window-active-pane win)) "p0 is active initially")
      (cl-tmux::%select-pane-in-direction sess :right)
      (is (eq p1 (window-active-pane win))
          "active pane must be p1 after %select-pane-in-direction :right"))))

(test select-pane-in-direction-left-selects-left-pane
  "%select-pane-in-direction :left from the right pane selects the left pane."
  (with-two-pane-h-session (sess win p0 p1)
    (with-loop-state
      (window-select-pane win p1)
      (cl-tmux::%select-pane-in-direction sess :left)
      (is (eq p0 (window-active-pane win))
          "active pane must be p0 after %select-pane-in-direction :left"))))

(test select-pane-in-direction-noop-when-no-neighbor
  "%select-pane-in-direction is a no-op when the active pane has no neighbor
   in the requested direction."
  (with-two-pane-h-session (sess win p0 p1)
    (is-false (null p0) "fixture created")
    (window-select-pane win p1)          ; start at the rightmost pane
    (with-loop-state
      (cl-tmux::%select-pane-in-direction sess :right)
      (is (eq p1 (window-active-pane win))
          "active pane must remain p1 when no right neighbor exists"))))

(test select-pane-in-direction-vertical-down-selects-lower-pane
  "%select-pane-in-direction :down from the top pane selects the bottom pane."
  (with-two-pane-v-session (sess win p0 p1)
    (with-loop-state
      (is (eq p0 (window-active-pane win)) "p0 is active initially")
      (cl-tmux::%select-pane-in-direction sess :down)
      (is (eq p1 (window-active-pane win))
          "active pane must be p1 after %select-pane-in-direction :down"))))

;;; ── %apply-named-layout-to-session ──────────────────────────────────────────

(test apply-named-layout-even-horizontal-repositions-panes
  "%apply-named-layout-to-session :even-horizontal repositions two panes into
   equal-width columns and rebuilds the window tree."
  (with-two-pane-layout-session (sess win p0 p1)
    (with-loop-state
      (cl-tmux::%apply-named-layout-to-session sess :even-horizontal)
      ;; After even-horizontal: avail-w = 81 - 1 = 80, each-w = 40.
      ;; p0 should be at x=0, p1 at x=41, both width=40.
      (is (= 0  (pane-x p0)) "p0 x must be 0 after even-horizontal layout")
      (is (= 40 (pane-width p0)) "p0 width must be 40 after even-horizontal layout")
      (is (= 41 (pane-x p1)) "p1 x must be 41 after even-horizontal layout")
      (is (= 40 (pane-width p1)) "p1 width must be 40 after even-horizontal layout"))))

(test apply-named-layout-even-vertical-repositions-panes
  "%apply-named-layout-to-session :even-vertical repositions two panes into
   equal-height rows and rebuilds the window tree."
  ;; Use a vertical split (80×21) so the height arithmetic matches the assertions.
  (with-two-pane-v-session (sess win p0 p1)
    (with-loop-state
      (cl-tmux::%apply-named-layout-to-session sess :even-vertical)
      ;; After even-vertical on an 80×21 window: avail-h = 21 - 1 = 20, each-h = 10.
      ;; p0 should be at y=0, p1 at y=11, both height=10.
      (is (= 0  (pane-y p0)) "p0 y must be 0 after even-vertical layout")
      (is (= 10 (pane-height p0)) "p0 height must be 10 after even-vertical layout")
      (is (= 11 (pane-y p1)) "p1 y must be 11 after even-vertical layout")
      (is (= 10 (pane-height p1)) "p1 height must be 10 after even-vertical layout"))))

(test apply-named-layout-noop-for-empty-session
  "%apply-named-layout-to-session with no active window is a no-op."
  (with-empty-session (sess)
    (with-loop-state
      (finishes (cl-tmux::%apply-named-layout-to-session sess :even-horizontal))
      "calling with no active window must not signal an error")))

;;; ── :list-windows dispatch ───────────────────────────────────────────────────

(test dispatch-list-windows-shows-overlay
  ":list-windows opens an overlay containing the window name and marks *dirty*."
  (with-fake-session (s :nwindows 1)
    (let ((*overlay* nil))
      (cl-tmux::dispatch-command s :list-windows nil)
      (is (overlay-active-p)
          ":list-windows must open the overlay")
      (is-true cl-tmux::*dirty*
               ":list-windows must mark *dirty*"))))

(test dispatch-list-windows-overlay-contains-window-name
  ":list-windows overlay text includes the active window name."
  (with-fake-session (s :nwindows 2)
    (let ((*overlay* nil))
      (cl-tmux::dispatch-command s :list-windows nil)
      (is (overlay-active-p) "overlay must be open")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search "1" text)
            "overlay must contain the first window entry")))))

;;; ── :list-sessions dispatch ──────────────────────────────────────────────────

(test dispatch-list-sessions-empty-registry-shows-overlay
  ":list-sessions with empty *server-sessions* falls back to the session-name
   single-line format and still opens an overlay."
  (with-fake-session (s :nwindows 1)
    (let ((*overlay* nil)
          (cl-tmux::*server-sessions* nil))
      (cl-tmux::dispatch-command s :list-sessions nil)
      (is (overlay-active-p)
          ":list-sessions must open an overlay even when *server-sessions* is nil")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search (session-name s) text)
            "fallback overlay must contain the session name")))))

(test dispatch-list-sessions-populated-registry-shows-all-sessions
  ":list-sessions with *server-sessions* populated lists every registered
   session and marks the current one with an asterisk."
  (let* ((s    (make-fake-session :nwindows 1))
         (name (session-name s)))
    (with-loop-state
      (let ((*overlay* nil)
            (cl-tmux::*server-sessions* (list (cons name s))))
        (cl-tmux::dispatch-command s :list-sessions nil)
        (is (overlay-active-p)
            ":list-sessions must open an overlay")
        (let ((text (format nil "~{~A~%~}" (overlay-lines))))
          (is (search name text)
              "overlay must contain the session name")
          (is (search "*" text)
              "current session must be marked with an asterisk"))))))

;;; ── :display-panes dispatch ──────────────────────────────────────────────────

(test dispatch-display-panes-shows-pane-numbers
  ":display-panes with a 2-pane session arms the per-pane number display (via a
   timing overlay) and renders big-digit pane numbers."
  (with-two-pane-h-session (sess win p0 p1)
    (is (and win p0 p1) "session with 2 panes")
    (with-loop-state
      (let ((*overlay* nil) (cl-tmux/prompt:*display-panes-active* nil))
        (cl-tmux::dispatch-command sess :display-panes nil)
        (is (overlay-active-p)
            ":display-panes opens the (timing) overlay")
        (is-true cl-tmux/prompt:*display-panes-active*
                 ":display-panes arms the per-pane number display")
        (let ((frame (cl-tmux/renderer:render-session-to-string sess 24 81)))
          (is (find #\█ frame)
              ":display-panes must render big-digit pane numbers (got no █)"))))))

(test dispatch-display-panes-marks-dirty
  ":display-panes sets *dirty* to T."
  (let ((sess (make-fake-session :nwindows 1 :npanes 1)))
    (with-loop-state
      (let ((*overlay* nil))
        (cl-tmux::dispatch-command sess :display-panes nil)
        (is-true cl-tmux::*dirty*
                 ":display-panes must mark *dirty*")))))

