(in-package #:cl-tmux/test)

;;;; Command dispatch tests (src/dispatch-core.lisp,
;;;;                         src/dispatch-commands.lisp,
;;;;                         src/dispatch-commands-pane.lisp,
;;;;                         src/dispatch-commands-auto.lisp,
;;;;                         src/dispatch-commands-runner.lisp,
;;;;                         src/dispatch-control.lisp,
;;;;                         src/dispatch-handlers.lisp,
;;;;                         src/dispatch-handlers-buffer.lisp).
;;;; Tests: dispatch-suite — dispatch-command, dispatch-prefix-command,
;;;; next-cyclic, prev-cyclic, %copy-mode-active-p.

(def-suite dispatch-suite :description "Command dispatch and prefix routing")
(in-suite dispatch-suite)

;;; ── Cyclic helpers (generated by define-cyclic-navigators) ─────────────────

(test next-cyclic-wraps
  "next-cyclic advances and wraps past the end."
  (is (eql 'b (cl-tmux::next-cyclic '(a b c) 'a)))
  (is (eql 'a (cl-tmux::next-cyclic '(a b c) 'c)))
  (is (eql 'b (cl-tmux::next-cyclic '(a b c) 'missing))))   ; unknown → idx 0 → element 1

(test prev-cyclic-wraps
  "prev-cyclic steps back and wraps past the front."
  (is (eql 'a (cl-tmux::prev-cyclic '(a b c) 'b)))
  (is (eql 'c (cl-tmux::prev-cyclic '(a b c) 'a))))

(test define-cyclic-navigators-macro-is-defined
  "define-cyclic-navigators is a defined macro that generated next-cyclic and prev-cyclic."
  (is (macro-function 'cl-tmux::define-cyclic-navigators)
      "define-cyclic-navigators must be a macro")
  ;; Both generated functions are symmetric: stepping n and -n return to original.
  (is (eql 'a (cl-tmux::prev-cyclic '(a b c)
                                    (cl-tmux::next-cyclic '(a b c) 'a)))
      "next then prev returns to same element"))

;;; ── with-active-pane macro ──────────────────────────────────────────────────

(test with-active-pane-returns-nil-for-empty-session
  "with-active-pane evaluates to NIL when there is no active pane."
  (with-empty-session (s)
    (with-loop-state
      ;; %active-screen uses with-active-pane internally
      (is (null (cl-tmux::%active-screen s))
          "empty session has no active screen"))))

(test with-active-pane-macro-is-defined
  "with-active-pane is a defined macro."
  (is (macro-function 'cl-tmux::with-active-pane)))

;;; ── Window / pane selection ────────────────────────────────────────────────

(test dispatch-next-window-cycles
  "C-b n moves to the next window and wraps around."
  (with-fake-session (s :nwindows 2)
    (cl-tmux::dispatch-command s :next-window nil)
    (is (eq (second (session-windows s)) (session-active-window s)))
    (cl-tmux::dispatch-command s :next-window nil)
    (is (eq (first (session-windows s)) (session-active-window s))
        "second :next-window should wrap back to window 1")))

(test dispatch-prev-window-wraps
  "C-b p from the first window wraps to the last."
  (with-fake-session (s :nwindows 2)
    (cl-tmux::dispatch-command s :prev-window nil)
    (is (eq (second (session-windows s)) (session-active-window s)))))

(test notify-pane-focus-fires-focus-hooks
  "%notify-pane-focus fires pane-focus-in / pane-focus-out independent of ?1004."
  (with-isolated-hooks
    (let* ((s        (make-fake-session :nwindows 1 :npanes 1))
           (pane     (session-active-pane s))
           (in-fired nil) (out-fired nil))
      (cl-tmux/hooks:add-hook "pane-focus-in"
                              (lambda (&rest _) (declare (ignore _)) (setf in-fired t)))
      (cl-tmux/hooks:add-hook "pane-focus-out"
                              (lambda (&rest _) (declare (ignore _)) (setf out-fired t)))
      (cl-tmux::%notify-pane-focus pane t)
      (is-true in-fired "focus-in hook fires on focus gain")
      (cl-tmux::%notify-pane-focus pane nil)
      (is-true out-fired "focus-out hook fires on focus loss"))))

(test select-pane-with-focus-fires-out-then-in
  "Switching panes fires focus-out for the old pane and focus-in for the new."
  (with-isolated-hooks
    (let* ((s         (make-fake-session :nwindows 1 :npanes 2))
           (win       (session-active-window s))
           (panes     (window-panes win))
           (in-count 0) (out-count 0))
      (cl-tmux/hooks:add-hook "pane-focus-in"
                              (lambda (&rest _) (declare (ignore _)) (incf in-count)))
      (cl-tmux/hooks:add-hook "pane-focus-out"
                              (lambda (&rest _) (declare (ignore _)) (incf out-count)))
      (cl-tmux::%select-pane-with-focus win (second panes))
      (is (= 1 out-count) "focus-out fires once (old pane)")
      (is (= 1 in-count)  "focus-in fires once (new pane)"))))

(test run-command-tokens-abbrev-next-dispatches
  "%run-command-tokens resolves the tmux abbreviation 'next' (no-arg named-table
   path) to :next-window."
  (with-fake-session (s :nwindows 2)
    (cl-tmux::%run-command-tokens s '("next"))
    (is (eq (second (session-windows s)) (session-active-window s))
        "abbrev 'next' must advance to the next window")))

(test run-command-tokens-abbrev-prev-dispatches
  "%run-command-tokens resolves the abbreviation 'prev' (no-arg named-table path)
   to :prev-window, which from the first window wraps to the last."
  (with-fake-session (s :nwindows 2)
    (cl-tmux::%run-command-tokens s '("prev"))
    (is (eq (second (session-windows s)) (session-active-window s))
        "abbrev 'prev' must wrap to the last window")))

(test run-command-tokens-abbrev-renamew-with-arg
  "%run-command-tokens resolves the arg-bearing abbreviation 'renamew' through
   *arg-command-table* to rename the active window."
  (with-fake-session (s :nwindows 1)
    (cl-tmux::%run-command-tokens s '("renamew" "myname"))
    (is (string= "myname" (window-name (session-active-window s)))
        "renamew must rename the active window via the arg-table alias")))

(test dispatch-next-pane-cycles
  "C-b o moves to the next pane within the active window."
  (let* ((s   (make-fake-session :nwindows 1 :npanes 2))
         (win (session-active-window s))
         (p0  (first  (window-panes win)))
         (p1  (second (window-panes win))))
    (with-loop-state
      (is (eq p0 (window-active-pane win)))
      (cl-tmux::dispatch-command s :next-pane nil)
      (is (eq p1 (window-active-pane win))))))

(test dispatch-select-window-by-digit
  "C-b <n>: :select-window uses the pressed digit byte to pick the window."
  (with-fake-session (s :nwindows 3)
    (cl-tmux::dispatch-command s :select-window (char-code #\2))
    (is (eq (third (session-windows s)) (session-active-window s)))
    (cl-tmux::dispatch-command s :select-window (char-code #\0))
    (is (eq (first (session-windows s)) (session-active-window s)))))

(test dispatch-unknown-command-passes-through
  "An unrecognized command falls through to the passthrough branch: it returns
   NIL (no quit), doesn't error, and still marks the session dirty."
  (with-fake-session (s)
    (is (null (cl-tmux::dispatch-command s :no-such-command (char-code #\a))))
    (is-true cl-tmux::*dirty* "dispatch marks dirty even on passthrough")))

;;; ── Rename ──────────────────────────────────────────────────────────────────

(test dispatch-rename-window-opens-prompt
  "C-b , opens a rename prompt seeded with the active window's name, and its
   on-submit closure renames the active window."
  (with-fake-session (s :nwindows 1)
    (let ((*prompt* nil))
      (cl-tmux::dispatch-command s :rename-window nil)
      (is (prompt-active-p) "rename should open a prompt")
      (is (string= "0" (prompt-buffer *prompt*))
          "prompt seeded with current window name")
      (is (functionp (prompt-on-submit *prompt*))
          "prompt should carry an on-submit closure")
      (funcall (prompt-on-submit *prompt*) "renamed")
      (is (string= "renamed" (window-name (session-active-window s)))
          "on-submit closure should rename the active window"))))

;;; ── Copy mode ───────────────────────────────────────────────────────────────

(test dispatch-copy-mode-enter-exit
  "C-b [ enters copy mode on the active screen; exit clears it."
  (with-fake-session (s)
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (is (screen-copy-mode-p (active-screen s)) "copy mode should be on after enter")
    (cl-tmux::dispatch-command s :copy-mode-exit nil)
    (is-false (screen-copy-mode-p (active-screen s)) "copy mode should be off after exit")))

(test copy-mode-active-p-reflects-state
  "%copy-mode-active-p tracks the active screen's copy-mode flag."
  (with-fake-session (s)
    (is-false (cl-tmux::%copy-mode-active-p s))
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (is (cl-tmux::%copy-mode-active-p s))))

(test send-keys-R-resets-pane-terminal-state
  "send-keys -R resets the target pane's terminal state (RIS): the cursor is homed."
  (let* ((s    (make-fake-session :nwindows 1 :npanes 1))
         (win  (cl-tmux/model:session-active-window s))
         (pane (cl-tmux/model:window-active-pane win))
         (scr  (cl-tmux/model:pane-screen pane)))
    (with-loop-state
      (setf (cl-tmux/terminal/types:screen-cursor-x scr) 5
            (cl-tmux/terminal/types:screen-cursor-y scr) 3)
      (cl-tmux::%cmd-send-keys-arg s '("-R"))
      (is (= 0 (cl-tmux/terminal/types:screen-cursor-x scr))
          "send-keys -R must home the cursor x")
      (is (= 0 (cl-tmux/terminal/types:screen-cursor-y scr))
          "send-keys -R must home the cursor y"))))

;;; ── send-keys -X copy-mode commands: cursor-left/right + rectangle-toggle ────

(test send-keys-x-command-table-maps-cursor-and-rectangle
  "The send-keys -X command table maps cursor-left/right and rectangle-toggle to
   their proper copy-mode keywords (no longer the begin-selection approximation)."
  (flet ((kw (name) (cdr (assoc name cl-tmux::*copy-mode-x-commands* :test #'string-equal))))
    (is (eq :copy-mode-cursor-left      (kw "cursor-left")))
    (is (eq :copy-mode-cursor-right     (kw "cursor-right")))
    (is (eq :copy-mode-cursor-up        (kw "cursor-up")))
    (is (eq :copy-mode-cursor-down      (kw "cursor-down")))
    (is (eq :copy-mode-rectangle-toggle (kw "rectangle-toggle")))))

(test send-keys-x-command-table-maps-select-word-and-other-end
  "select-word maps to :copy-mode-select-word, and both other-end (real tmux
   name) and toggle-position map to :copy-mode-other-end (no longer the
   begin-selection placeholder)."
  (flet ((kw (name) (cdr (assoc name cl-tmux::*copy-mode-x-commands* :test #'string-equal))))
    (is (eq :copy-mode-select-word (kw "select-word")))
    (is (eq :copy-mode-other-end   (kw "other-end")))
    (is (eq :copy-mode-other-end   (kw "toggle-position")))))

(test send-keys-x-rectangle-toggle-toggles-rect-select
  "send -X rectangle-toggle flips the screen's rectangle (block) selection flag
   instead of starting a stream selection."
  (with-fake-session (s)
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (let ((screen (active-screen s)))
      (is-false (screen-copy-rect-select-p screen) "rect-select off on entry")
      (is (cl-tmux::%dispatch-send-keys-X s "rectangle-toggle")
          "rectangle-toggle must be a handled -X command")
      (is (screen-copy-rect-select-p screen) "rectangle-toggle turns rect-select ON")
      (cl-tmux::%dispatch-send-keys-X s "rectangle-toggle")
      (is-false (screen-copy-rect-select-p screen) "a second toggle turns it OFF"))))

(test send-keys-x-cursor-left-right-move-cursor
  "send -X cursor-right / cursor-left move the copy-mode cursor horizontally
   (previously both mis-mapped to begin-selection, which did not move it)."
  (with-fake-session (s)
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (let ((screen (active-screen s)))
      (cl-tmux::%dispatch-send-keys-X s "cursor-right")
      (is (= 1 (cdr (screen-copy-cursor screen)))
          "cursor-right moves the cursor to column 1 (from the initial column 0)")
      (cl-tmux::%dispatch-send-keys-X s "cursor-left")
      (is (= 0 (cdr (screen-copy-cursor screen)))
          "cursor-left moves the cursor back to column 0"))))

(test send-keys-x-cursor-up-down-move-cursor-vertically
  "send -X cursor-up / cursor-down move the copy cursor vertically (the -X names
   previously only scrolled a line, inconsistent with the arrow-key path)."
  (with-fake-session (s)
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (let* ((screen (active-screen s))
           (h      (screen-height screen)))
      (cl-tmux::%dispatch-send-keys-X s "cursor-up")
      (is (= (- h 2) (car (screen-copy-cursor screen)))
          "cursor-up moves the cursor one row up from the bottom")
      (cl-tmux::%dispatch-send-keys-X s "cursor-down")
      (is (= (- h 1) (car (screen-copy-cursor screen)))
          "cursor-down moves the cursor back to the bottom row"))))

;;; ── Detach / kill ───────────────────────────────────────────────────────────

(test dispatch-detach-returns-detach
  "C-b d returns :detach and does NOT clear *running* itself (the caller decides:
   standalone stops, a server merely disconnects the client)."
  (with-fake-session (s)
    (is (eq :detach (cl-tmux::dispatch-command s :detach nil)))
    (is-true cl-tmux::*running* "dispatch-command must not clear *running*")))

(test dispatch-kill-last-window-quits
  "Killing the only window ends the session (:quit)."
  (with-fake-session (s :nwindows 1)
    (is (eq :quit (cl-tmux::dispatch-command s :kill-window nil)))))

(test dispatch-kill-one-of-two-windows-survives
  "Killing one of two windows leaves the session running with the other."
  (with-fake-session (s :nwindows 2)
    (is (null (cl-tmux::dispatch-command s :kill-window nil)))
    (is (= 1 (length (session-windows s))))))

(test dispatch-kill-last-pane-quits
  "Killing the sole pane of the sole window ends the session (:quit)."
  (with-fake-session (s :nwindows 1 :npanes 1)
    (is (eq :quit (cl-tmux::dispatch-command s :kill-pane nil)))))

;;; ── Prefix routing ──────────────────────────────────────────────────────────

(test dispatch-prefix-routes-binding
  "dispatch-prefix-command looks the byte up in the binding table (d → detach)."
  (with-fake-session (s)
    (is (eq :detach (cl-tmux::dispatch-prefix-command s (char-code #\d))))))

(test prefix-q-exits-copy-mode
  "In copy mode, the prefix-routed 'q' exits copy mode."
  (with-fake-session (s)
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (cl-tmux::dispatch-prefix-command s (char-code #\q))
    (is-false (screen-copy-mode-p (active-screen s)))))

;;; ── %active-screen ───────────────────────────────────────────────────────────

(test active-screen-returns-active-pane-screen
  "%active-screen returns the screen of the session's active pane."
  (with-fake-session (s)
    (let ((ap (session-active-pane s)))
      (is (eq (pane-screen ap)
              (cl-tmux::%active-screen s))
          "%active-screen must return the active pane's screen"))))

(test active-screen-returns-nil-for-empty-session
  "%active-screen returns NIL when no pane is active."
  (with-empty-session (s)
    (with-loop-state
      (is (null (cl-tmux::%active-screen s))))))

;;; ── %cmd-cycle-window ────────────────────────────────────────────────────────

(test cmd-cycle-window-advances-selection
  "%cmd-cycle-window advances the active window via CYCLER."
  (let* ((s  (make-fake-session :nwindows 3))
         (w1 (first  (session-windows s)))
         (w2 (second (session-windows s))))
    (with-loop-state
      (is (eq w1 (session-active-window s)))
      (cl-tmux::%cmd-cycle-window s #'cl-tmux::next-cyclic)
      (is (eq w2 (session-active-window s))))))

;;; ── %cmd-cycle-pane ──────────────────────────────────────────────────────────

(test cmd-cycle-pane-advances-pane-selection
  "%cmd-cycle-pane advances the active pane via CYCLER."
  (let* ((s   (make-fake-session :nwindows 1 :npanes 2))
         (win (session-active-window s))
         (p0  (first  (window-panes win)))
         (p1  (second (window-panes win))))
    (with-loop-state
      (is (eq p0 (window-active-pane win)))
      (cl-tmux::%cmd-cycle-pane s #'cl-tmux::next-cyclic)
      (is (eq p1 (window-active-pane win))))))

;;; ── focus events (?1004) on pane switch ──────────────────────────────────────

(test notify-pane-focus-noop-without-pty
  "%notify-pane-focus is a safe no-op for a pane with no live PTY (fd <= 0),
   even when focus events are enabled."
  (let ((pane (make-pane :id 1 :x 0 :y 0 :width 20 :height 5 :fd -1
                         :screen (make-screen 20 5))))
    (setf (cl-tmux/terminal/types:screen-focus-events (pane-screen pane)) t)
    (is (null (cl-tmux::%notify-pane-focus pane t))
        "no PTY → %notify-pane-focus returns NIL without writing")
    (finishes (cl-tmux::%notify-pane-focus pane nil))))

(test notify-pane-focus-writes-focus-in-to-pty
  "With focus events enabled and a live fd, %notify-pane-focus delivers the
   focus-gained report ESC[I to the pane's PTY."
  (with-pipe-fds (rfd wfd)
    (let ((pane (make-pane :id 1 :x 0 :y 0 :width 20 :height 5 :fd wfd
                           :screen (make-screen 20 5))))
      (setf (cl-tmux/terminal/types:screen-focus-events (pane-screen pane)) t)
      (cl-tmux::%notify-pane-focus pane t)
      (let ((ready (cl-tmux/pty:select-fds (list rfd) 200000)))  ; 200 ms
        (is-true ready "the PTY read-end must be readable after a focus report")
        (when ready
          (cffi:with-foreign-object (buf :uint8 8)
            (let ((n (cffi:foreign-funcall "read"
                                           :int rfd :pointer buf :unsigned-long 3
                                           :long)))
              (is (= 3 n) "focus-in report must be exactly 3 bytes (got ~D)" n)
              (is (= 27 (cffi:mem-aref buf :uint8 0)) "byte 0 must be ESC (27)")
              (is (= 91 (cffi:mem-aref buf :uint8 1)) "byte 1 must be #\\[ (91)")
              (is (= 73 (cffi:mem-aref buf :uint8 2)) "byte 2 must be #\\I (73)"))))))))

(test notify-pane-focus-disabled-screen-writes-nothing
  "A pane whose app did NOT enable focus events receives no report even with a
   live fd, and select-fds reports the pipe idle."
  (with-pipe-fds (rfd wfd)
    (let ((pane (make-pane :id 1 :x 0 :y 0 :width 20 :height 5 :fd wfd
                           :screen (make-screen 20 5))))
      ;; focus-events left NIL (default)
      (cl-tmux::%notify-pane-focus pane t)
      (is (null (cl-tmux/pty:select-fds (list rfd) 20000))
          "no focus report must reach an opted-out pane (pipe must stay idle)"))))

(test select-pane-with-focus-switches-and-tolerates-no-pty
  "%select-pane-with-focus changes the active pane and runs the focus-notify path
   without error even when panes have no PTY and focus events are enabled."
  (let* ((s   (make-fake-session :nwindows 1 :npanes 2))
         (win (session-active-window s))
         (p0  (first  (window-panes win)))
         (p1  (second (window-panes win))))
    (setf (cl-tmux/terminal/types:screen-focus-events (pane-screen p0)) t)
    (setf (cl-tmux/terminal/types:screen-focus-events (pane-screen p1)) t)
    (with-loop-state
      (is (eq p0 (window-active-pane win)))
      (finishes (cl-tmux::%select-pane-with-focus win p1))
      (is (eq p1 (window-active-pane win))
          "%select-pane-with-focus must make p1 the active pane"))))

;;; ── focus events (?1004) on window switch ────────────────────────────────────

(test cycle-window-delivers-focus-in-to-new-window-pane
  "Switching windows sends ESC[I (focus gained) to the newly active window's pane
   when that pane's app enabled focus events."
  (with-pipe-fds (rfd wfd)
    (let* ((s   (make-fake-session :nwindows 2 :npanes 1))
           (w1  (second (session-windows s)))
           (p1  (window-active-pane w1)))
      ;; Make the SECOND window's pane a live, focus-aware PTY.
      (setf (pane-fd p1) wfd)
      (setf (cl-tmux/terminal/types:screen-focus-events (pane-screen p1)) t)
      (with-loop-state
        (cl-tmux::%cmd-cycle-window s #'cl-tmux::next-cyclic)
        (is (eq w1 (session-active-window s)) "next-window must activate w1")
        (let ((ready (cl-tmux/pty:select-fds (list rfd) 200000)))  ; 200 ms
          (is-true ready "the new window's pane must receive a focus report")
          (when ready
            (cffi:with-foreign-object (buf :uint8 8)
              (let ((n (cffi:foreign-funcall "read"
                                             :int rfd :pointer buf :unsigned-long 3
                                             :long)))
                (is (= 3 n) "focus-in must be 3 bytes (got ~D)" n)
                (is (= 27 (cffi:mem-aref buf :uint8 0)) "byte 0 must be ESC (27)")
                (is (= 73 (cffi:mem-aref buf :uint8 2))
                    "byte 2 must be #\\I (73) for focus gained")))))))))

(test cycle-window-delivers-focus-out-to-old-window-pane
  "Switching away from a window sends ESC[O (focus lost) to the window being left."
  (with-pipe-fds (rfd wfd)
    (let* ((s   (make-fake-session :nwindows 2 :npanes 1))
           (w0  (first (session-windows s)))
           (p0  (window-active-pane w0)))
      ;; The FIRST (currently active) window's pane is the live, focus-aware PTY.
      (setf (pane-fd p0) wfd)
      (setf (cl-tmux/terminal/types:screen-focus-events (pane-screen p0)) t)
      (with-loop-state
        (cl-tmux::%cmd-cycle-window s #'cl-tmux::next-cyclic)
        (let ((ready (cl-tmux/pty:select-fds (list rfd) 200000)))
          (is-true ready "the old window's pane must receive a focus-out report")
          (when ready
            (cffi:with-foreign-object (buf :uint8 8)
              (let ((n (cffi:foreign-funcall "read"
                                             :int rfd :pointer buf :unsigned-long 3
                                             :long)))
                (is (= 3 n) "focus-out must be 3 bytes (got ~D)" n)
                (is (= 27 (cffi:mem-aref buf :uint8 0)) "byte 0 must be ESC (27)")
                (is (= 79 (cffi:mem-aref buf :uint8 2))
                    "byte 2 must be #\\O (79) for focus lost")))))))))

(test cycle-window-with-focus-events-no-pty-no-error
  "Cycling windows runs the focus-transition path without error when panes have no
   PTY, and still changes the active window."
  (let* ((s   (make-fake-session :nwindows 2 :npanes 1))
         (w0  (first  (session-windows s)))
         (w1  (second (session-windows s))))
    (setf (cl-tmux/terminal/types:screen-focus-events
           (pane-screen (window-active-pane w0))) t)
    (setf (cl-tmux/terminal/types:screen-focus-events
           (pane-screen (window-active-pane w1))) t)
    (with-loop-state
      (is (eq w0 (session-active-window s)))
      (finishes (cl-tmux::%cmd-cycle-window s #'cl-tmux::next-cyclic))
      (is (eq w1 (session-active-window s))
          "cycle-window must activate w1 even with focus events on and no PTY"))))

;;; ── list-keys overlay ───────────────────────────────────────────────────────

(test dispatch-list-keys-shows-overlay
  "C-b ? opens the key-binding help overlay."
  (with-fake-session (s)
    (let ((*overlay* nil))
      (cl-tmux::dispatch-command s :list-keys nil)
      (is (overlay-active-p) "list-keys should open the help overlay"))))

(test define-command-handlers-macro-is-defined
  "define-command-handlers is a defined macro."
  (is (macro-function 'cl-tmux::define-command-handlers)))

(test define-copy-mode-key-overrides-macro-is-defined
  "define-copy-mode-key-overrides is a defined macro."
  (is (macro-function 'cl-tmux::define-copy-mode-key-overrides)))

;;; ── select-pane-left/right/up/down dispatch ─────────────────────────────────
;;;
;;; These tests use the shared fixture macros from helpers.lisp instead of
;;; duplicating the setup inline.  with-two-pane-h-session and
;;; with-two-pane-v-session already encode the exact same geometry.

(test dispatch-select-pane-right-moves-active-pane
  ":select-pane-right moves the active pane to the right neighbour."
  (with-two-pane-h-session (sess win p0 p1)
    (with-loop-state
      (is (eq p0 (window-active-pane win)) "p0 is active initially")
      (cl-tmux::dispatch-command sess :select-pane-right nil)
      (is (eq p1 (window-active-pane win))
          "active pane must be p1 after :select-pane-right"))))

(test dispatch-select-pane-left-moves-active-pane
  ":select-pane-left moves the active pane to the left neighbour."
  (with-two-pane-h-session (sess win p0 p1)
    (with-loop-state
      ;; Start on p1, then go left.
      (window-select-pane win p1)
      (cl-tmux::dispatch-command sess :select-pane-left nil)
      (is (eq p0 (window-active-pane win))
          "active pane must be p0 after :select-pane-left"))))

(test dispatch-select-pane-right-noop-at-rightmost
  ":select-pane-right is a no-op when the active pane has no right neighbour."
  (with-two-pane-h-session (sess win p0 p1)
    (with-loop-state
      ;; Make p1 (rightmost) active, then try to go further right.
      (is (eq p0 (window-active-pane win)) "p0 is active initially")
      (window-select-pane win p1)
      (cl-tmux::dispatch-command sess :select-pane-right nil)
      (is (eq p1 (window-active-pane win))
          "active pane must remain p1 when no right neighbour exists"))))

(test dispatch-select-pane-down-moves-active-pane
  ":select-pane-down moves the active pane to the pane below."
  (with-two-pane-v-session (sess win p0 p1)
    (with-loop-state
      (is (eq p0 (window-active-pane win)) "p0 is active initially")
      (cl-tmux::dispatch-command sess :select-pane-down nil)
      (is (eq p1 (window-active-pane win))
          "active pane must be p1 after :select-pane-down"))))

(test dispatch-select-pane-up-moves-active-pane
  ":select-pane-up moves the active pane to the pane above."
  (with-two-pane-v-session (sess win p0 p1)
    (with-loop-state
      ;; Start on p1 (bottom), then go up.
      (window-select-pane win p1)
      (cl-tmux::dispatch-command sess :select-pane-up nil)
      (is (eq p0 (window-active-pane win))
          "active pane must be p0 after :select-pane-up"))))

;;; ── zoom-toggle dispatch ────────────────────────────────────────────────────

(test dispatch-zoom-toggle-sets-zoom-flag
  ":zoom-toggle zooms the active pane in and marks window-zoom-p as T."
  (with-two-pane-h-session (sess win p0 p1)
    (with-loop-state
      (is (and p0 p1) "both panes exist")
      (cl-tmux::dispatch-command sess :zoom-toggle nil)
      (is-true (cl-tmux/model:window-zoom-p win)
               "window-zoom-p must be T after :zoom-toggle dispatch")
      ;; Toggle back off.
      (cl-tmux::dispatch-command sess :zoom-toggle nil)
      (is-false (cl-tmux/model:window-zoom-p win)
                "window-zoom-p must be NIL after second :zoom-toggle dispatch"))))

;;; ── rename-session dispatch ─────────────────────────────────────────────────

(test dispatch-rename-session-opens-prompt
  ":rename-session opens a prompt seeded with the current session name, and
   its on-submit closure renames the session."
  (with-fake-session (s :nwindows 1)
    (let ((*prompt* nil))
      (cl-tmux::dispatch-command s :rename-session nil)
      (is (prompt-active-p) "rename-session must open a prompt")
      (is (string= "0" (prompt-buffer *prompt*))
          "prompt must be seeded with the current session name \"0\"")
      (funcall (prompt-on-submit *prompt*) "newsess")
      (is (string= "newsess" (session-name s))
          "on-submit must rename the session to the supplied name"))))

;;; ── %select-pane-in-direction ───────────────────────────────────────────────
;;;
;;; Use the shared fixture macros to avoid repeating pane/window/session setup.

(test select-pane-in-direction-right-selects-right-pane
  "%select-pane-in-direction :right from the left pane selects the right pane."
  (with-two-pane-h-session (sess win p0 p1)
    (with-loop-state
      (is (eq p0 (window-active-pane win)) "p0 is active initially")
      (cl-tmux::%select-pane-in-direction sess :right)
      (is (eq p1 (window-active-pane win))
          "active pane must be p1 after %select-pane-in-direction :right"))))

(test select-pane-in-direction-left-selects-left-pane
  "%select-pane-in-direction :left from the right pane selects the left pane."
  (with-two-pane-h-session (sess win p0 p1)
    (with-loop-state
      (window-select-pane win p1)
      (cl-tmux::%select-pane-in-direction sess :left)
      (is (eq p0 (window-active-pane win))
          "active pane must be p0 after %select-pane-in-direction :left"))))

(test select-pane-in-direction-noop-when-no-neighbor
  "%select-pane-in-direction is a no-op when the active pane has no neighbor
   in the requested direction."
  (with-two-pane-h-session (sess win p0 p1)
    (is-false (null p0) "fixture created")
    (window-select-pane win p1)          ; start at the rightmost pane
    (with-loop-state
      (cl-tmux::%select-pane-in-direction sess :right)
      (is (eq p1 (window-active-pane win))
          "active pane must remain p1 when no right neighbor exists"))))

(test select-pane-in-direction-vertical-down-selects-lower-pane
  "%select-pane-in-direction :down from the top pane selects the bottom pane."
  (with-two-pane-v-session (sess win p0 p1)
    (with-loop-state
      (is (eq p0 (window-active-pane win)) "p0 is active initially")
      (cl-tmux::%select-pane-in-direction sess :down)
      (is (eq p1 (window-active-pane win))
          "active pane must be p1 after %select-pane-in-direction :down"))))

;;; ── %apply-named-layout-to-session ──────────────────────────────────────────

(test apply-named-layout-even-horizontal-repositions-panes
  "%apply-named-layout-to-session :even-horizontal repositions two panes into
   equal-width columns and rebuilds the window tree."
  (with-two-pane-layout-session (sess win p0 p1)
    (with-loop-state
      (cl-tmux::%apply-named-layout-to-session sess :even-horizontal)
      ;; After even-horizontal: avail-w = 81 - 1 = 80, each-w = 40.
      ;; p0 should be at x=0, p1 at x=41, both width=40.
      (is (= 0  (pane-x p0)) "p0 x must be 0 after even-horizontal layout")
      (is (= 40 (pane-width p0)) "p0 width must be 40 after even-horizontal layout")
      (is (= 41 (pane-x p1)) "p1 x must be 41 after even-horizontal layout")
      (is (= 40 (pane-width p1)) "p1 width must be 40 after even-horizontal layout"))))

(test apply-named-layout-even-vertical-repositions-panes
  "%apply-named-layout-to-session :even-vertical repositions two panes into
   equal-height rows and rebuilds the window tree."
  ;; Use a vertical split (80×21) so the height arithmetic matches the assertions.
  (with-two-pane-v-session (sess win p0 p1)
    (with-loop-state
      (cl-tmux::%apply-named-layout-to-session sess :even-vertical)
      ;; After even-vertical on an 80×21 window: avail-h = 21 - 1 = 20, each-h = 10.
      ;; p0 should be at y=0, p1 at y=11, both height=10.
      (is (= 0  (pane-y p0)) "p0 y must be 0 after even-vertical layout")
      (is (= 10 (pane-height p0)) "p0 height must be 10 after even-vertical layout")
      (is (= 11 (pane-y p1)) "p1 y must be 11 after even-vertical layout")
      (is (= 10 (pane-height p1)) "p1 height must be 10 after even-vertical layout"))))

(test apply-named-layout-noop-for-empty-session
  "%apply-named-layout-to-session with no active window is a no-op."
  (with-empty-session (sess)
    (with-loop-state
      (finishes (cl-tmux::%apply-named-layout-to-session sess :even-horizontal))
      "calling with no active window must not signal an error")))

;;; ── :list-windows dispatch ───────────────────────────────────────────────────

(test dispatch-list-windows-shows-overlay
  ":list-windows opens an overlay containing the window name and marks *dirty*."
  (with-fake-session (s :nwindows 1)
    (let ((*overlay* nil))
      (cl-tmux::dispatch-command s :list-windows nil)
      (is (overlay-active-p)
          ":list-windows must open the overlay")
      (is-true cl-tmux::*dirty*
               ":list-windows must mark *dirty*"))))

(test dispatch-list-windows-overlay-contains-window-name
  ":list-windows overlay text includes the active window name."
  (with-fake-session (s :nwindows 2)
    (let ((*overlay* nil))
      (cl-tmux::dispatch-command s :list-windows nil)
      (is (overlay-active-p) "overlay must be open")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search "1" text)
            "overlay must contain the first window entry")))))

;;; ── :list-sessions dispatch ──────────────────────────────────────────────────

(test dispatch-list-sessions-empty-registry-shows-overlay
  ":list-sessions with empty *server-sessions* falls back to the session-name
   single-line format and still opens an overlay."
  (with-fake-session (s :nwindows 1)
    (let ((*overlay* nil)
          (cl-tmux::*server-sessions* nil))
      (cl-tmux::dispatch-command s :list-sessions nil)
      (is (overlay-active-p)
          ":list-sessions must open an overlay even when *server-sessions* is nil")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search (session-name s) text)
            "fallback overlay must contain the session name")))))

(test dispatch-list-sessions-populated-registry-shows-all-sessions
  ":list-sessions with *server-sessions* populated lists every registered
   session and marks the current one with an asterisk."
  (let* ((s    (make-fake-session :nwindows 1))
         (name (session-name s)))
    (with-loop-state
      (let ((*overlay* nil)
            (cl-tmux::*server-sessions* (list (cons name s))))
        (cl-tmux::dispatch-command s :list-sessions nil)
        (is (overlay-active-p)
            ":list-sessions must open an overlay")
        (let ((text (format nil "~{~A~%~}" (overlay-lines))))
          (is (search name text)
              "overlay must contain the session name")
          (is (search "*" text)
              "current session must be marked with an asterisk"))))))

;;; ── :display-panes dispatch ──────────────────────────────────────────────────

(test dispatch-display-panes-shows-pane-numbers
  ":display-panes with a 2-pane session arms the per-pane number display (via a
   timing overlay) and renders big-digit pane numbers."
  (with-two-pane-h-session (sess win p0 p1)
    (is (and win p0 p1) "session with 2 panes")
    (with-loop-state
      (let ((*overlay* nil) (cl-tmux/prompt:*display-panes-active* nil))
        (cl-tmux::dispatch-command sess :display-panes nil)
        (is (overlay-active-p)
            ":display-panes opens the (timing) overlay")
        (is-true cl-tmux/prompt:*display-panes-active*
                 ":display-panes arms the per-pane number display")
        (let ((frame (cl-tmux/renderer:render-session-to-string sess 24 81)))
          (is (find #\█ frame)
              ":display-panes must render big-digit pane numbers (got no █)"))))))

(test dispatch-display-panes-marks-dirty
  ":display-panes sets *dirty* to T."
  (let ((sess (make-fake-session :nwindows 1 :npanes 1)))
    (with-loop-state
      (let ((*overlay* nil))
        (cl-tmux::dispatch-command sess :display-panes nil)
        (is-true cl-tmux::*dirty*
                 ":display-panes must mark *dirty*")))))

;;; ── :swap-pane-forward dispatch ──────────────────────────────────────────────
;;;
;;; Use the shared fixture macro to avoid repeating pane/window/session setup.

(test dispatch-swap-pane-forward-changes-pane-order
  ":swap-pane-forward swaps the active pane with the next pane in the list."
  (with-two-pane-h-session (sess win p0 p1)
    (with-loop-state
      ;; p0 is active and at index 0; forward swap puts p1 at index 0.
      (cl-tmux::dispatch-command sess :swap-pane-forward nil)
      (is (eq p1 (first (window-panes win)))
          "after :swap-pane-forward, p1 must be first in the panes list")
      (is (eq p0 (second (window-panes win)))
          "after :swap-pane-forward, p0 must be second in the panes list"))))

(test dispatch-swap-pane-forward-marks-dirty
  ":swap-pane-forward marks *dirty*."
  (with-two-pane-h-session (sess win p0 p1)
    (is (and win p0 p1) "fixture created")
    (with-loop-state
      (cl-tmux::dispatch-command sess :swap-pane-forward nil)
      (is-true cl-tmux::*dirty*
               ":swap-pane-forward must mark *dirty*"))))

(test cmd-swap-pane-s-t-swaps-specific-panes
  "swap-pane -s 1 -t 3 swaps the two named panes' positions in the window list
   (not just the active pane with a neighbour)."
  (let* ((s   (make-fake-session :nwindows 1 :npanes 3))
         (win (session-active-window s))
         (p1  (find 1 (window-panes win) :key #'pane-id))
         (p3  (find 3 (window-panes win) :key #'pane-id)))
    (with-loop-state
      (is (eq p1 (first (window-panes win)))         "pane 1 starts first")
      (is (eq p3 (car (last (window-panes win))))    "pane 3 starts last")
      (cl-tmux::%run-command-line s "swap-pane -s 1 -t 3")
      (is (eq p3 (first (window-panes win)))
          "after swap-pane -s 1 -t 3, pane 3 is first")
      (is (eq p1 (car (last (window-panes win))))
          "after swap, pane 1 is last"))))

(test cmd-swap-pane-t-swaps-active-with-target
  "swap-pane -t 2 swaps the active pane (1) with pane 2 (-s defaults to active)."
  (let* ((s   (make-fake-session :nwindows 1 :npanes 2))
         (win (session-active-window s))
         (p1  (find 1 (window-panes win) :key #'pane-id))
         (p2  (find 2 (window-panes win) :key #'pane-id)))
    (with-loop-state
      (is (eq p1 (first (window-panes win))) "pane 1 (active) starts first")
      (cl-tmux::%run-command-line s "swap-pane -t 2")
      (is (eq p2 (first (window-panes win)))
          "after swap-pane -t 2, pane 2 is first (swapped with active pane 1)"))))

;;; ── :swap-pane-backward dispatch ─────────────────────────────────────────────

(test dispatch-swap-pane-backward-changes-pane-order
  ":swap-pane-backward swaps the active pane with the previous pane (wrapping)."
  (with-two-pane-h-session (sess win p0 p1)
    ;; Start with p1 active so that backward swap moves it to index 0.
    (window-select-pane win p1)
    (with-loop-state
      (cl-tmux::dispatch-command sess :swap-pane-backward nil)
      (is (eq p1 (first (window-panes win)))
          "after :swap-pane-backward from p1, p1 must be first in the panes list")
      (is (eq p0 (second (window-panes win)))
          "after :swap-pane-backward from p1, p0 must be second in the panes list"))))

(test dispatch-swap-pane-backward-marks-dirty
  ":swap-pane-backward marks *dirty*."
  (with-two-pane-h-session (sess win p0 p1)
    (is-false (null p0) "fixture created")
    (window-select-pane win p1)
    (with-loop-state
      (cl-tmux::dispatch-command sess :swap-pane-backward nil)
      (is-true cl-tmux::*dirty*
               ":swap-pane-backward must mark *dirty*"))))

;;; ── :kill-pane-confirm dispatch ──────────────────────────────────────────────

(test dispatch-kill-pane-confirm-opens-prompt
  ":kill-pane-confirm opens a y/n prompt and does NOT kill immediately."
  (with-fake-session (s :nwindows 1 :npanes 2)
    (let ((*prompt* nil))
      (cl-tmux::dispatch-command s :kill-pane-confirm nil)
      (is (prompt-active-p)
          ":kill-pane-confirm must open a prompt")
      ;; Window should still have both panes (no kill yet).
      (is (= 2 (length (window-panes (session-active-window s))))
          ":kill-pane-confirm must not kill the pane before confirmation"))))

(test dispatch-kill-pane-confirm-kills-on-y
  ":kill-pane-confirm kills the pane when the user submits \"y\"."
  (with-fake-session (s :nwindows 1 :npanes 2)
    (let ((*prompt* nil))
      (cl-tmux::dispatch-command s :kill-pane-confirm nil)
      (is (prompt-active-p) "prompt must be open")
      ;; Submit "y" — should kill the active pane.
      (funcall (prompt-on-submit *prompt*) "y")
      (is (= 1 (length (window-panes (session-active-window s))))
          "submitting \"y\" must kill the active pane"))))

(test dispatch-kill-pane-confirm-no-kill-on-n
  ":kill-pane-confirm does NOT kill when the user submits \"n\"."
  (with-fake-session (s :nwindows 1 :npanes 2)
    (let ((*prompt* nil))
      (cl-tmux::dispatch-command s :kill-pane-confirm nil)
      (is (prompt-active-p) "prompt must be open")
      ;; Submit "n" — should NOT kill.
      (funcall (prompt-on-submit *prompt*) "n")
      (is (= 2 (length (window-panes (session-active-window s))))
          "submitting \"n\" must NOT kill the pane"))))

;;; ── :kill-window-confirm dispatch ────────────────────────────────────────────

(test dispatch-kill-window-confirm-opens-prompt
  ":kill-window-confirm opens a y/n prompt and does NOT kill immediately."
  (with-fake-session (s :nwindows 2)
    (let ((*prompt* nil))
      (cl-tmux::dispatch-command s :kill-window-confirm nil)
      (is (prompt-active-p)
          ":kill-window-confirm must open a prompt")
      ;; Both windows should still be present.
      (is (= 2 (length (session-windows s)))
          ":kill-window-confirm must not kill the window before confirmation"))))

(test dispatch-kill-window-confirm-kills-on-y
  ":kill-window-confirm kills the window when the user submits \"y\"."
  (with-fake-session (s :nwindows 2)
    (let ((*prompt* nil))
      (cl-tmux::dispatch-command s :kill-window-confirm nil)
      (is (prompt-active-p) "prompt must be open")
      ;; Submit "y" — should kill the active window.
      (funcall (prompt-on-submit *prompt*) "y")
      (is (= 1 (length (session-windows s)))
          "submitting \"y\" must kill the active window"))))

(test dispatch-kill-window-confirm-no-kill-on-n
  ":kill-window-confirm does NOT kill when the user submits \"n\"."
  (with-fake-session (s :nwindows 2)
    (let ((*prompt* nil))
      (cl-tmux::dispatch-command s :kill-window-confirm nil)
      (is (prompt-active-p) "prompt must be open")
      ;; Submit "n" — should NOT kill.
      (funcall (prompt-on-submit *prompt*) "n")
      (is (= 2 (length (session-windows s)))
          "submitting \"n\" must NOT kill the window"))))

(test dispatch-kill-window-confirm-prompt-includes-window-name
  ":kill-window-confirm prompt label includes the current window name."
  (with-fake-session (s :nwindows 1)
    (let ((*prompt* nil))
      (let ((wname (window-name (session-active-window s))))
        (cl-tmux::dispatch-command s :kill-window-confirm nil)
        (is (prompt-active-p) "prompt must be open")
        (is (search wname (prompt-label *prompt*))
            "prompt label must contain the window name")))))

;;; ── :send-prefix dispatch ────────────────────────────────────────────────────

(test dispatch-send-prefix-command-is-defined
  ":send-prefix command is registered in dispatch-command without error."
  ;; We cannot test actual PTY writes in unit tests (fd=-1), but we verify
  ;; that dispatching :send-prefix does not signal any error and marks dirty.
  (with-fake-session (s)
    ;; Should not error even with fd=-1 (the guard (> fd 0) protects the write).
    (finishes (cl-tmux::dispatch-command s :send-prefix nil))
    (is-true cl-tmux::*dirty* ":send-prefix must mark *dirty*")))

;;; ── unbound prefix key no-op ─────────────────────────────────────────────────

(test dispatch-unknown-command-is-noop
  "An unrecognized prefix key is silently discarded (no passthrough corruption)."
  ;; Previously the otherwise clause called %passthrough-prefix, injecting
  ;; raw bytes into the pane.  After the fix it must be a silent no-op.
  (with-fake-session (s)
    ;; Dispatching an unknown command must return NIL and must not error.
    (is (null (cl-tmux::dispatch-command s :no-such-command-xyz nil))
        "unknown command must return NIL")
    (is-true cl-tmux::*dirty*
             "dispatch must mark *dirty* even for unknown commands")))

;;; ── :paste-buffer bracketed-paste wrapping ───────────────────────────────────

(test dispatch-paste-buffer-no-crash-without-buffer
  ":paste-buffer with an empty paste buffer is a no-op (no error, marks dirty)."
  (with-fake-session (s)
    (finishes (cl-tmux::dispatch-command s :paste-buffer nil))
    (is-true cl-tmux::*dirty* ":paste-buffer must mark *dirty*")))

;;; ── command-prompt %N template substitution ─────────────────────────────────

(test substitute-percent-replaces-single-percent-args
  "%substitute-percent replaces tmux-style %1/%2 (single percent) with the args —
   the classic `command-prompt -p name: \"new-window -n '%1'\"` idiom."
  (is (string= "new-window -n 'shell'"
               (cl-tmux::%substitute-percent "new-window -n '%1'" '("shell")))
      "%1 must be replaced by the first arg")
  (is (string= "swap a b"
               (cl-tmux::%substitute-percent "swap %1 %2" '("a" "b")))
      "%1 and %2 must be replaced positionally"))

(test substitute-percent-handles-literal-and-edge-cases
  "%% is a literal percent; a missing arg expands to empty; %1 does not match
   inside %10; a non-arg %x is left verbatim."
  (is (string= "100% done" (cl-tmux::%substitute-percent "100%% done" '()))
      "%% → literal %")
  (is (string= "x" (cl-tmux::%substitute-percent "x%2" '("only-one")))
      "a reference past the arg list expands to empty")
  (is (string= "v0" (cl-tmux::%substitute-percent "%10" '("v")))
      "%1 must not match inside %10 (single left-to-right pass)")
  (is (string= "%z" (cl-tmux::%substitute-percent "%z" '("a")))
      "a non-digit %x is left verbatim"))

;;; ── :command-prompt dispatch ─────────────────────────────────────────────────

(test dispatch-command-prompt-opens-prompt
  ":command-prompt opens a prompt with label \": \"."
  (with-fake-session (s)
    (let ((*prompt* nil))
      (cl-tmux::dispatch-command s :command-prompt nil)
      (is (prompt-active-p) ":command-prompt must open a prompt")
      (is (string= ": " (prompt-label *prompt*))
          ":command-prompt prompt label must be \": \""))))

(test dispatch-command-prompt-empty-input-is-noop
  ":command-prompt with empty input does not crash."
  (with-fake-session (s)
    (let ((*prompt* nil))
      (cl-tmux::dispatch-command s :command-prompt nil)
      (is (prompt-active-p) "prompt must be open")
      (finishes (funcall (prompt-on-submit *prompt*) "")
                "empty input must not signal an error"))))

(test dispatch-command-prompt-unknown-command-shows-overlay
  ":command-prompt with an unknown command name shows an error overlay."
  (with-fake-session (s)
    (let ((*prompt* nil) (*overlay* nil))
      (cl-tmux::dispatch-command s :command-prompt nil)
      (funcall (prompt-on-submit *prompt*) "no-such-command-xyz")
      (is (overlay-active-p) "unknown command must open an error overlay")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search "unknown command" text)
            "overlay must contain the 'unknown command' error message")))))

(test dispatch-command-prompt-known-command-executes
  ":command-prompt with 'list-windows' executes that command (opens overlay)."
  (with-fake-session (s :nwindows 1)
    (let ((*prompt* nil) (*overlay* nil))
      (cl-tmux::dispatch-command s :command-prompt nil)
      (funcall (prompt-on-submit *prompt*) "list-windows")
      (is (overlay-active-p) "list-windows via command-prompt must open an overlay"))))

;;; ── %run-command-line / display-message with arguments ───────────────────────

(test command-prompt-display-message-expands-format
  ":command-prompt 'display-message #{session_name}' expands the format and shows
   the result (not the literal #{...})."
  (with-fake-session (s)
    (let ((*prompt* nil) (*overlay* nil))
      (cl-tmux::dispatch-command s :command-prompt nil)
      (funcall (prompt-on-submit *prompt*) "display-message #{session_name}")
      (is (overlay-active-p) "display-message must open an overlay")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search "0" text)
            "overlay must contain the expanded session name '0' (got ~S)" text)
        (is (null (search "#{" text))
            "the #{...} format must be expanded, not shown literally (got ~S)" text)))))

(test run-command-line-no-arg-command-falls-through
  "%run-command-line with a bare command name dispatches it by name (no args)."
  (with-fake-session (s :nwindows 2)
    (let ((*overlay* nil))
      (cl-tmux::%run-command-line s "next-window")
      (is (eq (second (session-windows s)) (session-active-window s))
          "next-window via %run-command-line must switch to the second window"))))

(test run-command-line-display-message-joins-args
  "display-message with multiple unquoted args joins them with spaces."
  (with-fake-session (s)
    (let ((*overlay* nil))
      (cl-tmux::%run-command-line s "display-message hello world")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search "hello world" text)
            "joined args 'hello world' must appear in the overlay (got ~S)" text)))))

(test display-message-l-flag-shows-literal-format
  "display-message -l shows ARGS verbatim, WITHOUT expanding #{...} formats —
   the inverse of the default expansion path."
  (with-fake-session (s)
    (let ((*overlay* nil))
      (cl-tmux::%run-command-line s "display-message -l #{session_name}")
      (is (overlay-active-p) "display-message -l must still open an overlay")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search "#{session_name}" text)
            "-l must show the literal #{session_name}, not expand it (got ~S)" text)))))

(test display-message-c-flag-consumes-client-arg
  "display-message -c <client> consumes the client name (a no-op target) instead
   of leaking it into the format text."
  (with-fake-session (s)
    (let ((*overlay* nil))
      (cl-tmux::%run-command-line s "display-message -c someclient #{session_name}")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is (search "0" text) "the expanded session name must appear")
        (is (null (search "someclient" text))
            "-c client name must NOT appear in the message (got ~S)" text)))))

(test run-command-line-empty-is-noop
  "%run-command-line with blank input does not signal an error."
  (with-fake-session (s)
    (finishes (cl-tmux::%run-command-line s "   ")
              "blank command line must be a safe no-op")))

(test run-command-line-set-option-coerces-boolean
  "'set monitor-activity off' stores NIL and 'set ... on' stores T (type-coerced).
   Uses monitor-activity — a side-effect-free :boolean option — because `status` is
   now a choice/string option (off|on|2..5), not a boolean."
  (let ((s (make-fake-session)))
    (with-isolated-options ()
      (cl-tmux::%run-command-line s "set monitor-activity off")
      (is (null (cl-tmux/options:get-option "monitor-activity"))
          "set monitor-activity off → NIL (boolean coercion)")
      (cl-tmux::%run-command-line s "set monitor-activity on")
      (is (eq t (cl-tmux/options:get-option "monitor-activity"))
          "set monitor-activity on → T"))))

(test run-command-line-set-option-string-and-quoted
  "'set' stores string option values, and a quoted value keeps its spaces/format."
  (let ((s (make-fake-session)))
    (with-isolated-options ()
      (cl-tmux::%run-command-line s "set status-left bar")
      (is (string= "bar" (cl-tmux/options:get-option "status-left"))
          "unquoted string value")
      (cl-tmux::%run-command-line s "set status-left \"#{session_name} x\"")
      (is (string= "#{session_name} x" (cl-tmux/options:get-option "status-left"))
          "quoted value keeps its space and #{...} intact"))))

(test run-command-line-set-option-scope-flag
  "'set -g status off' sets the 'status' option (not an option literally named
   '-g') — the canonical tmux form must work."
  (let ((s (make-fake-session)))
    (with-isolated-options ()
      (cl-tmux::%run-command-line s "set -g status off")
      (is (string= "off" (cl-tmux/options:get-option "status"))
          "set -g status off must set 'status' to the choice string \"off\"")
      (is (null (cl-tmux/options:get-option "-g"))
          "must NOT create an option literally named '-g'"))))

(test run-command-line-set-option-append-flag
  "'set -a <name> <value>' appends to the option's current value."
  (let ((s (make-fake-session)))
    (with-isolated-options ("status-left" "A")
      (cl-tmux::%run-command-line s "set -a status-left B")
      (is (string= "AB" (cl-tmux/options:get-option "status-left"))
          "set -a must append B to the existing 'A'"))))

;;; ── %cmd-set-option scope routing: -w / -p / global ──────────────────────

(test cmd-set-option-w-routes-to-window-local
  "'set -w' routes to the active window's local options and leaves the global
   value unchanged."
  (with-option-session (s)
    (let* ((win (cl-tmux/model:session-active-window s)))
      (cl-tmux/options:set-option "synchronize-panes" nil)
      (cl-tmux::%cmd-set-option s '("-w" "synchronize-panes" "on"))
      (is (eq t (cl-tmux/options:get-option-for-window "synchronize-panes" win))
          "active window's synchronize-panes must be T after 'set -w'")
      (is (null (cl-tmux/options:get-option "synchronize-panes"))
          "global synchronize-panes must remain NIL — 'set -w' must not touch it"))))

(test cmd-set-window-option-defaults-to-window-scope
  "setw / set-window-option (no -g) sets a WINDOW-local option, not global —
   tmux's setw is `set -w`."
  (with-option-session (s)
    (let* ((win (cl-tmux/model:session-active-window s)))
      (cl-tmux/options:set-option "synchronize-panes" nil)
      (cl-tmux::%cmd-set-window-option s '("synchronize-panes" "on"))
      (is (eq t (cl-tmux/options:get-option-for-window "synchronize-panes" win))
          "bare setw must set the window-local option to T")
      (is (null (cl-tmux/options:get-option "synchronize-panes"))
          "bare setw must NOT touch the global option"))))

(test cmd-set-window-option-g-overrides-to-global
  "setw -g sets the GLOBAL option (explicit -g wins over the injected -w)."
  (with-option-session (s)
    (let* ((win (cl-tmux/model:session-active-window s)))
      (cl-tmux/options:set-option "synchronize-panes" nil)
      (cl-tmux::%cmd-set-window-option s '("-g" "synchronize-panes" "on"))
      (is (eq t (cl-tmux/options:get-option "synchronize-panes"))
          "setw -g must set the global option")
      (is (null (nth-value 1 (gethash "synchronize-panes"
                                      (cl-tmux/model:window-local-options win))))
          "setw -g must NOT create a window-local override"))))

(test cmd-set-option-p-routes-to-pane-local
  "'set -p' routes to the active pane's local options and leaves the global
   value unchanged."
  (with-option-session (s)
    (let* ((pane (cl-tmux/model:session-active-pane s)))
      (cl-tmux/options:set-option "remain-on-exit" nil)
      (cl-tmux::%cmd-set-option s '("-p" "remain-on-exit" "on"))
      (is (eq t (cl-tmux/options:get-option-for-pane "remain-on-exit" pane))
          "active pane's remain-on-exit must be T after 'set -p'")
      (is (null (cl-tmux/options:get-option "remain-on-exit"))
          "global remain-on-exit must remain NIL — 'set -p' must not touch it"))))

(test cmd-set-option-status-applies-side-effect-at-runtime
  "Runtime `set -g status off/on` runs the option side-effect, updating
   *status-height* — not only the .tmux.conf path (e.g. `bind b set -g status`)."
  (with-option-session (s)
      (cl-tmux::%cmd-set-option s '("-g" "status" "off"))
      (is (= 0 cl-tmux/config:*status-height*)
          "set -g status off must hide the status bar at runtime")
      (cl-tmux::%cmd-set-option s '("-g" "status" "on"))
      (is (= 1 cl-tmux/config:*status-height*)
          "set -g status on must restore the status bar at runtime")))

(test cmd-set-option-default-shell-applies-side-effect-at-runtime
  "Runtime `set -g default-shell` updates *default-shell* via the side-effect."
  (with-option-session (s)
      (cl-tmux::%cmd-set-option s '("-g" "default-shell" "/bin/zsh"))
      (is (string= "/bin/zsh" cl-tmux/config:*default-shell*)
          "runtime set -g default-shell must update *default-shell*")))

(test cmd-set-option-prefix-applies-side-effect-at-runtime
  "Runtime `set -g prefix C-a` rebinds the prefix key code via the side-effect."
  (with-option-session (s)
      (cl-tmux::%cmd-set-option s '("-g" "prefix" "C-a"))
      (is (= 1 cl-tmux/config:*prefix-key-code*)
          "set -g prefix C-a must set *prefix-key-code* to ^A (1) at runtime")))

(test cmd-set-option-escape-time-syncs-to-server-store
  "escape-time is read from the server store by the ESC-flush, but is commonly
   set via `set -g escape-time 0` (global).  The side-effect syncs it across, so
   the common form takes effect."
  (with-option-session (s)
      ;; -g writes the global store; the side-effect mirrors it into the server store.
      (cl-tmux::%cmd-set-option s '("-g" "escape-time" "0"))
      (is (= 0 (cl-tmux/options:get-server-option "escape-time"))
          "set -g escape-time 0 must reach the server store the flush reads")
      ;; bare set (no scope) also syncs.
      (cl-tmux::%cmd-set-option s '("escape-time" "10"))
      (is (= 10 (cl-tmux/options:get-server-option "escape-time"))
          "bare set escape-time must also reach the server store")))

(test cmd-set-option-plain-routes-to-global
  "A plain 'set' (no -w/-p) still sets the global option."
  (with-option-session (s)
      (cl-tmux/options:set-option "synchronize-panes" nil)
      (cl-tmux::%cmd-set-option s '("synchronize-panes" "on"))
      (is (eq t (cl-tmux/options:get-option "synchronize-panes"))
          "plain 'set' must set the global synchronize-panes to T")))

(test cmd-set-option-gw-stays-global
  "'set -g -w' must set the GLOBAL option (the explicit -g overrides -w) and
   leave the active window WITHOUT a local override.  Guards the (not globalp)
   gate in %cmd-set-option."
  (with-option-session (s)
    (let* ((win (cl-tmux/model:session-active-window s)))
      (cl-tmux/options:set-option "synchronize-panes" nil)
      (cl-tmux::%cmd-set-option s '("-g" "-w" "synchronize-panes" "on"))
      (is (eq t (cl-tmux/options:get-option "synchronize-panes"))
          "-g must override -w: global synchronize-panes must be T")
      (is (null (nth-value 1 (gethash "synchronize-panes"
                                      (cl-tmux/model:window-local-options win))))
          "active window must have NO local override (local hash lacks the key)")
      (is (eq t (cl-tmux/options:get-option-for-window "synchronize-panes" win))
          "get-option-for-window must fall back to the global value T"))))

(test cmd-set-option-o-skips-when-already-set
  "'set -o name value' is a no-op when the option already has a value — the
   only-if-unset plugin idiom must NOT clobber a user override."
  (with-option-session (s)
      (cl-tmux/options:set-option "@plugin-opt" "user-value")
      (cl-tmux::%cmd-set-option s '("-o" "@plugin-opt" "default-value"))
      (is (string= "user-value" (cl-tmux/options:get-option "@plugin-opt"))
          "-o must leave the existing value untouched")))

(test cmd-set-option-o-sets-when-unset
  "'set -o name value' DOES set the option when it has no value yet (seeds a
   default that a later plain set can still override)."
  (with-option-session (s)
      ;; Ensure no prior override exists.
      (remhash "@plugin-opt" cl-tmux/options:*global-options*)
      (cl-tmux::%cmd-set-option s '("-o" "@plugin-opt" "default-value"))
      (is (string= "default-value" (cl-tmux/options:get-option "@plugin-opt"))
          "-o must set the option when it is currently unset")))

(test run-command-line-bind-with-args-binds-key
  "Runtime 'bind <key> <command>' (with args) binds via the config directive path,
   not the interactive prompt — so command-prompt / control-mode bind works."
  (with-option-session (s)
      (with-loop-state
        (cl-tmux::%run-command-line s "bind y new-window")
        (is (eq :new-window
                (cl-tmux/config:key-table-command
                 (cl-tmux/config:key-table-lookup "prefix" #\y)))
            "runtime 'bind y new-window' must bind #\\y → :new-window in prefix"))))

(test run-command-line-unbind-a-clears-prefix-table
  "Runtime 'unbind -a' clears the prefix table (arg-bearing unbind routes through
   the config directive logic, including the -a whole-table form)."
  (with-option-session (s)
      (with-loop-state
        (is (not (null (cl-tmux/config:key-table-lookup "prefix" #\c)))
            "prefix has bindings before unbind -a")
        (cl-tmux::%run-command-line s "unbind -a")
        (is (null (cl-tmux/config:key-table-lookup "prefix" #\c))
            "runtime 'unbind -a' must clear the prefix table"))))

(test cmd-set-option-clustered-ga-appends
  "'set -ga name val' (clustered -g -a) APPENDS — regression: the cluster was
   parsed as -g only, silently dropping -a and overwriting instead of appending."
  (with-option-session (s)
      (cl-tmux/options:set-option "@opt" "A")
      (cl-tmux::%run-command-line s "set -ga @opt B")
      (is (string= "AB" (cl-tmux/options:get-option "@opt"))
          "set -ga must append B to A, yielding AB")))

(test cmd-set-option-F-expands-format-value
  "'set -gF name #{...}' expands the format value once at set time."
  (with-option-session (s)                      ; session name is "0"
    (with-loop-state
      (cl-tmux::%run-command-line s "set -gF @opt #{session_name}")
      (is (string= "0" (cl-tmux/options:get-option "@opt"))
          "-F must store the expanded session name, not the literal #{...}"))))

(test run-command-line-rename-window
  "'rename-window <name>' renames the active window."
  (with-fake-session (s :nwindows 1)
    (cl-tmux::%run-command-line s "rename-window mywin")
    (is (string= "mywin" (window-name (session-active-window s)))
        "active window must be renamed to 'mywin'")))

(test run-command-line-rename-window-t-targets-window
  "'rename-window -t 1 newname' renames window-id 1, NOT the active window, and
   does not fold the -t flag tokens into the new name."
  (let* ((s  (make-fake-session :nwindows 2))
         (w0 (first  (session-windows s)))     ; id 0, active
         (w1 (second (session-windows s))))    ; id 1
    (with-loop-state
      (cl-tmux::%run-command-line s "rename-window -t 1 newname")
      (is (string= "newname" (window-name w1))
          "window-id 1 must be renamed to 'newname'")
      (is (not (string= "newname" (window-name w0)))
          "the active window (id 0) must be unchanged"))))

(test run-command-line-rename-session
  "'rename-session <name>' renames the session."
  (with-fake-session (s)
    (cl-tmux::%run-command-line s "rename-session mysess")
    (is (string= "mysess" (session-name s))
        "session must be renamed to 'mysess'")))

(test run-command-line-rename-session-t-targets-session
  "'rename-session -t other newname' renames the -t target session, not the
   current one, and does not fold the flag tokens into the name."
  (let* ((cur   (make-fake-session))
         (other (make-fake-session)))
    (setf (cl-tmux::session-name cur)   "cur"
          (cl-tmux::session-name other) "other")
    (let ((cl-tmux::*server-sessions* (list (cons "cur" cur) (cons "other" other))))
      (with-loop-state
        (cl-tmux::%run-command-line cur "rename-session -t other newname")
        (is (string= "newname" (session-name other))
            "the -t target session must be renamed to 'newname'")
        (is (string= "cur" (session-name cur))
            "the current session must be unchanged")))))

(test cmd-set-window-option-t-targets-window
  "setw -t 1 @wopt myval sets the WINDOW-LOCAL option on window-id 1, not the
   active window — and -t no longer leaks into the option name."
  (let* ((s  (make-fake-session :nwindows 2))
         (w0 (first  (session-windows s)))     ; id 0, active
         (w1 (second (session-windows s))))    ; id 1
    (with-loop-state
      (cl-tmux::%run-command-line s "setw -t 1 @wopt myval")
      (is (string= "myval" (cl-tmux/options:get-option-for-window "@wopt" w1))
          "window-id 1 must have the window-local @wopt = myval")
      (is (null (cl-tmux/options:get-option-for-window "@wopt" w0))
          "the active window (id 0) must NOT have @wopt set"))))

(test cmd-respawn-pane-without-k-errors-on-live-pane
  "respawn-pane without -k on a still-running pane (fd > 0) is an error and does
   NOT respawn — matching tmux (the model would otherwise fork unconditionally)."
  (let* ((s    (make-fake-session :nwindows 1 :npanes 1))
         (pane (window-active-pane (session-active-window s))))
    (setf (cl-tmux/model:pane-fd pane) 5)        ; simulate a live PTY
    (with-loop-state
      (let ((*overlay* nil))
        (cl-tmux::%cmd-respawn-pane-arg s '())
        (is (overlay-active-p)
            "respawn-pane without -k on a live pane must show an error overlay")
        (is (= 5 (cl-tmux/model:pane-fd pane))
            "the live pane must NOT be respawned (fd unchanged → no fork)")))))

(test cmd-respawn-window-without-k-errors-on-live-pane
  "respawn-window without -k errors when ANY pane in the window is still running,
   and does NOT respawn — matching tmux."
  (let* ((s   (make-fake-session :nwindows 1 :npanes 2))
         (win (session-active-window s))
         (p1  (first (window-panes win))))
    (setf (cl-tmux/model:pane-fd p1) 5)          ; one pane is live
    (with-loop-state
      (let ((*overlay* nil))
        (cl-tmux::%cmd-respawn-window-arg s '())
        (is (overlay-active-p)
            "respawn-window without -k with a live pane must show an error overlay")
        (is (= 5 (cl-tmux/model:pane-fd p1))
            "the window must NOT be respawned (live pane fd unchanged → no fork)")))))

(test set-hook-after-select-window-fires-config-command
  "set-hook -g after-select-window <cmd> (the .tmux.conf path) fires the command
   when select-window runs — i.e. the hook reaches run-command-hooks, not just the
   programmatic add-hook registry."
  (with-fake-session (s :nwindows 2)
    (cl-tmux/hooks:clear-command-hooks "after-select-window")
    (let ((*overlay* nil))
      (cl-tmux::%run-command-line
       s "set-hook -g after-select-window \"display-message hooked\"")
      (cl-tmux::%run-command-line s "select-window -n")
      (is-true (search "hooked" (format nil "~{~A~%~}" (overlay-lines)))
               "the set-hook after-select-window command must fire (display 'hooked')")
      (cl-tmux/hooks:clear-command-hooks "after-select-window"))))

(test set-hook-after-select-pane-fires-config-command
  "set-hook -g after-select-pane <cmd> fires when select-pane runs (config path)."
  (with-fake-session (s :nwindows 1 :npanes 2)
    (cl-tmux/hooks:clear-command-hooks "after-select-pane")
    (let ((*overlay* nil))
      (cl-tmux::%run-command-line
       s "set-hook -g after-select-pane \"display-message picked\"")
      (cl-tmux::%run-command-line s "select-pane -t 2")
      (is-true (search "picked" (format nil "~{~A~%~}" (overlay-lines)))
               "the set-hook after-select-pane command must fire")
      (cl-tmux/hooks:clear-command-hooks "after-select-pane"))))

(test set-hook-window-pane-changed-fires-config-command
  "set-hook -g window-pane-changed <cmd> fires when the active pane changes —
   via the window→session lookup at the sessionless chokepoint."
  (with-fake-session (s :nwindows 1 :npanes 2)
    (cl-tmux/hooks:clear-command-hooks "window-pane-changed")
    (let ((cl-tmux::*server-sessions* (list (cons "0" s)))
          (*overlay* nil))
      (cl-tmux::%run-command-line
       s "set-hook -g window-pane-changed \"display-message swapped\"")
      (cl-tmux::%run-command-line s "select-pane -t 2")
      (is-true (search "swapped" (format nil "~{~A~%~}" (overlay-lines)))
               "the set-hook window-pane-changed command must fire via session lookup")
      (cl-tmux/hooks:clear-command-hooks "window-pane-changed"))))

(test set-hook-after-rename-window-fires-config-via-unified-run-hooks
  "set-hook -g after-rename-window <cmd> fires on rename — proving the unified
   run-hooks now drives .tmux.conf set-hook for hooks whose firing point only
   called run-hooks (after-rename-window was previously config-broken)."
  (with-fake-session (s :nwindows 1)
    (cl-tmux/hooks:clear-command-hooks "after-rename-window")
    (let ((cl-tmux::*server-sessions* (list (cons "0" s)))
          (*overlay* nil))
      (cl-tmux::%run-command-line
       s "set-hook -g after-rename-window \"display-message renamed-hook\"")
      (cl-tmux::%run-command-line s "rename-window newname")
      (is-true (search "renamed-hook" (format nil "~{~A~%~}" (overlay-lines)))
               "after-rename-window set-hook must fire via the unified run-hooks")
      (cl-tmux/hooks:clear-command-hooks "after-rename-window"))))

(test set-hook-pane-focus-in-fires-config-command
  "set-hook -g pane-focus-in <cmd> fires when a pane gains focus (config path via
   the pane→session lookup at %notify-pane-focus)."
  (with-fake-session (s :nwindows 1 :npanes 2)
    (cl-tmux/hooks:clear-command-hooks "pane-focus-in")
    (let ((cl-tmux::*server-sessions* (list (cons "0" s)))
          (*overlay* nil))
      (cl-tmux::%run-command-line
       s "set-hook -g pane-focus-in \"display-message focused\"")
      (cl-tmux::%run-command-line s "select-pane -t 2")
      (is-true (search "focused" (format nil "~{~A~%~}" (overlay-lines)))
               "the set-hook pane-focus-in command must fire via session lookup")
      (cl-tmux/hooks:clear-command-hooks "pane-focus-in"))))

(test cmd-list-commands-filters-by-name
  "list-commands <name> shows only that command (tmux's filter); bare
   list-commands shows the full list."
  (with-fake-session (s)
    (let ((*overlay* nil))
      (cl-tmux::%run-command-line s "list-commands new-window")
      (let ((text (format nil "~{~A~%~}" (overlay-lines))))
        (is-true (search "new-window" text)
                 "list-commands new-window must list new-window")
        (is (null (search "kill-pane" text))
            "the filtered output must not contain unrelated commands (kill-pane)")))))

(test run-command-line-rename-window-no-arg-opens-prompt
  "'rename-window' with no argument falls through to the prompt (name table)."
  (with-fake-session (s :nwindows 1)
    (let ((*prompt* nil))
      (cl-tmux::%run-command-line s "rename-window")
      (is (prompt-active-p)
          "no-arg rename-window must open the rename prompt"))))

