(in-package #:cl-tmux/test)

;;;; Command dispatch tests (src/dispatch-core.lisp,
;;;;                         src/dispatch-commands.lisp,
;;;;                         src/dispatch-commands-pane.lisp,
;;;;                         src/dispatch-commands-list.lisp,
;;;;                         src/dispatch-commands-auto.lisp,
;;;;                         src/dispatch-commands-runner.lisp,
;;;;                         src/dispatch-control.lisp,
;;;;                         src/dispatch-handlers.lisp,
;;;;                         src/dispatch-handlers-buffer.lisp).
;;;; Tests: dispatch-suite — dispatch-command, dispatch-prefix-command,
;;;; next-cyclic, prev-cyclic, %copy-mode-active-p.

(def-suite dispatch-suite :description "Command dispatch and prefix routing")
(in-suite dispatch-suite)

(defmacro with-copy-mode-active-screen ((session-var screen-var &key feed) &body body)
  "Bind SESSION-VAR and SCREEN-VAR in an active copy-mode session.
   Optional FEED seeds the screen before BODY runs."
  `(with-fake-session (,session-var)
     (cl-tmux::dispatch-command ,session-var :copy-mode-enter nil)
     (let ((,screen-var (active-screen ,session-var)))
       ,@(when feed `((feed ,screen-var ,feed)))
       ,@body)))

;;; ── Cyclic helpers (generated by define-cyclic-navigators) ─────────────────

(test next-cyclic-wraps
  "next-cyclic advances and wraps past the end."
  (dolist (c '(((a b c) a b "advance: a -> b")
               ((a b c) c a "wrap past end: c -> a")
               ((a b c) missing b "unknown: idx 0 -> element 1")))
    (destructuring-bind (lst cur expected desc) c
      (is (eql expected (cl-tmux::next-cyclic lst cur)) "~A" desc))))

(test prev-cyclic-wraps
  "prev-cyclic steps back and wraps past the front."
  (is (eql 'a (cl-tmux::prev-cyclic '(a b c) 'b)))
  (is (eql 'c (cl-tmux::prev-cyclic '(a b c) 'a))))

(test define-cyclic-navigators-macro-is-defined
  "define-cyclic-navigators is a defined macro that generated next-cyclic and prev-cyclic."
  (is (macro-function 'cl-tmux::define-cyclic-navigators)
      "define-cyclic-navigators must be a macro")
  ;; Both generated functions are symmetric: stepping n and -n return to original.
  (is (eql 'a (cl-tmux::prev-cyclic '(a b c)
                                    (cl-tmux::next-cyclic '(a b c) 'a)))
      "next then prev returns to same element"))

;;; ── with-active-pane macro ──────────────────────────────────────────────────

(test with-active-pane-returns-nil-for-empty-session
  "with-active-pane evaluates to NIL when there is no active pane."
  (with-fake-session (s :nwindows 0)
    ;; %active-screen uses with-active-pane internally
    (is (null (cl-tmux::%active-screen s))
        "empty session has no active screen")))

(test with-active-pane-macro-is-defined
  "with-active-pane is a defined macro."
  (is (macro-function 'cl-tmux::with-active-pane)))

;;; ── Window / pane selection ────────────────────────────────────────────────

(test dispatch-next-window-cycles
  "C-b n moves to the next window and wraps around."
  (with-fake-session (s :nwindows 2)
    (cl-tmux::dispatch-command s :next-window nil)
    (is (eq (second (session-windows s)) (session-active-window s)))
    (cl-tmux::dispatch-command s :next-window nil)
    (is (eq (first (session-windows s)) (session-active-window s))
        "second :next-window should wrap back to window 1")))

(test dispatch-prev-window-wraps
  "C-b p from the first window wraps to the last."
  (with-fake-session (s :nwindows 2)
    (cl-tmux::dispatch-command s :prev-window nil)
    (is (eq (second (session-windows s)) (session-active-window s)))))

(test notify-pane-focus-fires-focus-hooks
  "%notify-pane-focus fires pane-focus-in / pane-focus-out independent of ?1004."
  (with-isolated-hooks
    (let* ((s        (make-fake-session :nwindows 1 :npanes 1))
           (pane     (session-active-pane s))
           (in-fired nil) (out-fired nil))
      (cl-tmux/hooks:add-hook "pane-focus-in"
                              (lambda (&rest _) (declare (ignore _)) (setf in-fired t)))
      (cl-tmux/hooks:add-hook "pane-focus-out"
                              (lambda (&rest _) (declare (ignore _)) (setf out-fired t)))
      (cl-tmux::%notify-pane-focus pane t)
      (is-true in-fired "focus-in hook fires on focus gain")
      (cl-tmux::%notify-pane-focus pane nil)
      (is-true out-fired "focus-out hook fires on focus loss"))))

(test select-pane-with-focus-fires-out-then-in
  "Switching panes fires focus-out for the old pane and focus-in for the new."
  (with-isolated-hooks
    (let* ((s         (make-fake-session :nwindows 1 :npanes 2))
           (win       (session-active-window s))
           (panes     (window-panes win))
           (in-count 0) (out-count 0))
      (cl-tmux/hooks:add-hook "pane-focus-in"
                              (lambda (&rest _) (declare (ignore _)) (incf in-count)))
      (cl-tmux/hooks:add-hook "pane-focus-out"
                              (lambda (&rest _) (declare (ignore _)) (incf out-count)))
      (cl-tmux::%select-pane-with-focus win (second panes))
      (is (= 1 out-count) "focus-out fires once (old pane)")
      (is (= 1 in-count)  "focus-in fires once (new pane)"))))

(test run-command-tokens-canonical-next-previous-table
  "%run-command-tokens resolves canonical next-window and previous-window commands;
   in a 2-window session both select the second window (next advances, previous wraps)."
  (dolist (row '(("next-window" "next-window must advance to the next window")
                 ("previous-window" "previous-window must wrap to the last window")))
    (destructuring-bind (abbrev desc) row
      (with-fake-session (s :nwindows 2)
        (cl-tmux::%run-command-tokens s (list abbrev))
        (is (eq (second (session-windows s)) (session-active-window s)) desc)))))

(test run-command-tokens-canonical-rename-window-with-arg
  "%run-command-tokens resolves the canonical 'rename-window' command through
   *arg-command-table* to rename the active window."
  (with-fake-session (s :nwindows 1)
    (cl-tmux::%run-command-tokens s '("rename-window" "myname"))
    (is (string= "myname" (window-name (session-active-window s)))
        "rename-window must rename the active window via the arg-table entry")))

(test dispatch-next-pane-cycles
  "C-b o moves to the next pane within the active window."
  (with-fake-two-pane-session (s)
    (let* ((win (session-active-window s))
           (p0  (first  (window-panes win)))
           (p1  (second (window-panes win))))
      (is (eq p0 (window-active-pane win)))
      (cl-tmux::dispatch-command s :next-pane nil)
      (is (eq p1 (window-active-pane win))))))

(test dispatch-select-window-by-digit
  "C-b <n>: :select-window uses the pressed digit byte to pick the window."
  (with-fake-session (s :nwindows 3)
    (cl-tmux::dispatch-command s :select-window (char-code #\2))
    (is (eq (third (session-windows s)) (session-active-window s)))
    (cl-tmux::dispatch-command s :select-window (char-code #\0))
    (is (eq (first (session-windows s)) (session-active-window s)))))

(test dispatch-unknown-command-passes-through
  "An unrecognized command falls through to the passthrough branch: it returns
   NIL (no quit), doesn't error, and still marks the session dirty."
  (with-fake-session (s)
    (is (null (cl-tmux::dispatch-command s :no-such-command (char-code #\a))))
    (is-true cl-tmux::*dirty* "dispatch marks dirty even on passthrough")))

;;; ── Rename ──────────────────────────────────────────────────────────────────

(test dispatch-rename-window-opens-prompt
  "C-b , opens a rename prompt seeded with the active window's name, and its
   on-submit closure renames the active window."
  (with-fake-session (s :nwindows 1)
    (let ((*prompt* nil))
      (cl-tmux::dispatch-command s :rename-window nil)
      (is (prompt-active-p) "rename should open a prompt")
      (is (string= "0" (prompt-buffer *prompt*))
          "prompt seeded with current window name")
      (is (functionp (prompt-on-submit *prompt*))
          "prompt should carry an on-submit closure")
      (funcall (prompt-on-submit *prompt*) "renamed")
      (is (string= "renamed" (window-name (session-active-window s)))
          "on-submit closure should rename the active window"))))

;;; ── Copy mode ───────────────────────────────────────────────────────────────

(test dispatch-copy-mode-enter-exit
  "C-b [ enters copy mode on the active screen; exit clears it."
  (with-fake-session (s)
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (is (screen-copy-mode-p (active-screen s)) "copy mode should be on after enter")
    (cl-tmux::dispatch-command s :copy-mode-exit nil)
    (is-false (screen-copy-mode-p (active-screen s)) "copy mode should be off after exit")))

(test copy-mode-active-p-reflects-state
  "%copy-mode-active-p tracks the active screen's copy-mode flag."
  (with-fake-session (s)
    (is-false (cl-tmux::%copy-mode-active-p s))
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (is (cl-tmux::%copy-mode-active-p s))))

(test send-keys-R-resets-pane-terminal-state
  "send-keys -R resets the target pane's terminal state (RIS): the cursor is homed."
  (with-fake-session (s :nwindows 1 :npanes 1)
    (let* ((win  (cl-tmux/model:session-active-window s))
           (pane (cl-tmux/model:window-active-pane win))
           (scr  (cl-tmux/model:pane-screen pane)))
      (setf (cl-tmux/terminal/types:screen-cursor-x scr) 5
            (cl-tmux/terminal/types:screen-cursor-y scr) 3)
      (cl-tmux::%cmd-send-keys-arg s '("-R"))
      (is (= 0 (cl-tmux/terminal/types:screen-cursor-x scr))
          "send-keys -R must home the cursor x")
      (is (= 0 (cl-tmux/terminal/types:screen-cursor-y scr))
          "send-keys -R must home the cursor y"))))

;;; ── send-keys -X copy-mode commands: cursor-left/right + rectangle-toggle ────

(test send-keys-x-command-table
  "The *copy-mode-x-commands* table maps all send-keys -X names to their
   proper copy-mode keywords."
  (dolist (c '(("cursor-left"      :copy-mode-cursor-left)
               ("cursor-right"     :copy-mode-cursor-right)
               ("cursor-up"        :copy-mode-cursor-up)
               ("cursor-down"      :copy-mode-cursor-down)
               ("rectangle-toggle" :copy-mode-rectangle-toggle)
               ("copy-selection"   :copy-mode-yank)
               ("select-word"      :copy-mode-select-word)
               ("other-end"        :copy-mode-other-end)
               ("copy-pipe"        :copy-mode-copy-pipe-no-cancel)
               ("copy-pipe-and-cancel" :copy-mode-copy-pipe-and-cancel)
               ("copy-pipe-end-of-line-and-cancel"
                :copy-mode-copy-pipe-end-of-line-and-cancel)
               ("next-matching-bracket" :copy-mode-next-matching-bracket)
               ("previous-matching-bracket"
                :copy-mode-previous-matching-bracket)))
    (destructuring-bind (name expected) c
      (is (eq expected (copy-mode-x-command-value name))
          "~S must map to ~S" name expected))))

(test send-keys-x-rectangle-toggle-toggles-rect-select
  "send -X rectangle-toggle flips the screen's rectangle (block) selection flag
   instead of starting a stream selection."
  (with-copy-mode-active-screen (s screen)
    (is-false (screen-copy-rect-select-p screen) "rect-select off on entry")
    (is (cl-tmux::%dispatch-send-keys-X s "rectangle-toggle")
        "rectangle-toggle must be a handled -X command")
    (is (screen-copy-rect-select-p screen) "rectangle-toggle turns rect-select ON")
    (cl-tmux::%dispatch-send-keys-X s "rectangle-toggle")
    (is-false (screen-copy-rect-select-p screen) "a second toggle turns it OFF")))

(test send-keys-x-rectangle-toggle-restores-temporary-focus
  "send -X rectangle-toggle must temporarily focus the target pane and restore
   the original session/window focus afterward."
  (with-fake-session (s :nwindows 2)
    (let* ((original-window (session-active-window s))
           (original-pane   (session-active-pane s))
           (target-window   (second (session-windows s)))
           (target-pane     (first (window-panes target-window)))
           (target-screen   (pane-screen target-pane)))
      (setf (cl-tmux/model::session-active s) target-window
            (cl-tmux/model::window-active target-window) target-pane)
      (cl-tmux::dispatch-command s :copy-mode-enter nil)
      (setf (cl-tmux/model::session-active s) original-window
            (cl-tmux/model::window-active original-window) original-pane
            (cl-tmux/model::window-active target-window) target-pane)
      (is-false (screen-copy-rect-select-p target-screen)
                "rect-select starts off on the target screen")
      (is (cl-tmux::%dispatch-send-keys-X s "rectangle-toggle" target-pane target-window nil)
          "rectangle-toggle must be handled via the temporary focus helper")
      (is (screen-copy-rect-select-p target-screen)
          "rectangle-toggle must toggle the target screen")
      (is (eq original-window (session-active-window s))
          "session focus must be restored to the original window")
      (is (eq original-pane (session-active-pane s))
          "session focus must be restored to the original pane"))))

(test send-keys-x-copy-pipe-and-cancel-no-arg-copies-and-exits
  "send -X copy-pipe-and-cancel without an explicit command still uses the
   copy-pipe path, allowing copy-command fallback and exiting copy mode."
  (let ((cl-tmux/buffer:*paste-buffers* nil))
    (with-option-session (s)
      (with-loop-state
        (cl-tmux/options:set-option "copy-command" "")
        (let ((screen (active-screen s)))
          (feed screen "pipe-me")
          (cl-tmux::dispatch-command s :copy-mode-enter nil)
          (setf (screen-copy-selecting screen) t
                (screen-copy-mark screen) (cons 0 0)
                (screen-copy-cursor screen) (cons 0 7))
          (is (cl-tmux::%dispatch-send-keys-X s "copy-pipe-and-cancel")
              "copy-pipe-and-cancel must be handled through the -X table")
          (is (string= "pipe-me" (cl-tmux/buffer:get-paste-buffer 0))
              "selected text must be copied into the paste buffer")
          (is-false (screen-copy-mode-p screen)
                    "copy-pipe-and-cancel must exit copy mode"))))))

(test send-keys-x-copy-pipe-and-cancel-explicit-command-pipes-and-exits
  "send -X copy-pipe-and-cancel with an argument pipes the copied text to the
   provided command instead of falling back to copy-command."
  (let ((cl-tmux/buffer:*paste-buffers* nil))
    (with-option-session (s)
      (with-loop-state
        (cl-tmux/options:set-option "copy-command" "")
        (let ((screen (active-screen s)))
          (feed screen "pipe-me")
          (cl-tmux::dispatch-command s :copy-mode-enter nil)
          (setf (screen-copy-selecting screen) t
                (screen-copy-mark screen) (cons 0 0)
                (screen-copy-cursor screen) (cons 0 7))
          (is (cl-tmux::%dispatch-send-keys-X s "copy-pipe-and-cancel" nil nil '("cat"))
              "copy-pipe-and-cancel with an argument must be handled")
          (is (string= "pipe-me" (cl-tmux/buffer:get-paste-buffer 0))
              "selected text must still be copied into the paste buffer")
          (is-false (screen-copy-mode-p screen)
                    "copy-pipe-and-cancel with an argument must exit copy mode"))))))

(test send-keys-x-copy-pipe-end-of-line-and-cancel-copies-to-eol-and-exits
  "send -X copy-pipe-end-of-line-and-cancel with an explicit command should
   copy from the cursor position through the end of the line and exit copy
   mode."
  (let ((cl-tmux/buffer:*paste-buffers* nil))
    (with-option-session (s)
      (with-loop-state
        (cl-tmux/options:set-option "copy-command" "")
        (let ((screen (active-screen s)))
          (feed screen "pipe-me now")
          (cl-tmux::dispatch-command s :copy-mode-enter nil)
          (setf (screen-copy-selecting screen) t
                (screen-copy-mark screen) (cons 0 5)
                (screen-copy-cursor screen) (cons 0 5))
          (is (cl-tmux::%dispatch-send-keys-X s
                                              "copy-pipe-end-of-line-and-cancel"
                                              nil nil
                                              '("cat"))
              "copy-pipe-end-of-line-and-cancel with an argument must be handled")
          (is (string= "me now" (cl-tmux/buffer:get-paste-buffer 0))
              "text from the cursor through the end of the line must be copied")
          (is-false (screen-copy-mode-p screen)
                    "copy-pipe-end-of-line-and-cancel must exit copy mode"))))))

(test send-keys-x-explicit-jump-commands
  "send -X jump-forward / jump-backward / jump-to / jump-to-backward must pass
   explicit character arguments through to the copy-mode jump helpers."
  (with-copy-mode-active-screen (s screen :feed "hello world")
    (labels ((invoke (command start args)
               (setf (screen-copy-cursor screen) start)
               (is (cl-tmux::%dispatch-send-keys-X s command nil nil args)
                   "~A with an explicit argument must be handled" command)
               (screen-copy-cursor screen)))
      (check-table
       (list
        (list (invoke "jump-forward" (cons 0 0) '("l"))
              (cons 0 2)
              "jump-forward must land on the next matching character")
        (list (invoke "jump-backward" (cons 0 5) '("l"))
              (cons 0 3)
              "jump-backward must land on the previous matching character")
        (list (invoke "jump-to" (cons 0 0) '("l"))
              (cons 0 1)
              "jump-to must land just before the next matching character")
        (list (invoke "jump-to-backward" (cons 0 5) '("l"))
              (cons 0 4)
              "jump-to-backward must land just after the previous matching character"))
       :test #'equal))))

(test send-keys-x-explicit-text-commands
  "send -X search-forward-text / search-backward-text must accept explicit
   search text, including multi-token arguments, without opening a prompt."
  (labels ((invoke (feed command start args)
             (with-copy-mode-active-screen (s screen :feed feed)
               (setf (screen-copy-cursor screen) start)
               (is (cl-tmux::%dispatch-send-keys-X s command nil nil args)
                   "~A with an explicit argument must be handled" command)
               (list (screen-copy-cursor screen)
                     (cl-tmux/terminal/types:screen-copy-search-term screen)))))
    (check-table
     (list
      (list (invoke "abc def abc" "search-forward-text" (cons 0 0) '("abc"))
            (list (cons 0 8) "abc")
            "search-forward-text must jump to the next matching text")
      (list (invoke "abc def abc" "search-backward-text" (cons 0 11) '("abc"))
            (list (cons 0 8) "abc")
            "search-backward-text must jump to the previous matching text")
      (list (invoke "zzzabc defzzz" "search-forward-text" (cons 0 0) '("abc" "def"))
            (list (cons 0 3) "abc def")
            "search-forward-text must join multiple positional tokens"))
     :test #'equal)))

(test send-keys-x-goto-line-jumps-to-line-number
  "send -X goto-line with an argument parses the line number and moves the copy
   cursor to the requested row."
  (with-copy-mode-active-screen (s screen)
    (labels ((invoke (args)
               (setf (screen-copy-cursor screen) (cons 0 0))
               (is (cl-tmux::%dispatch-send-keys-X s "goto-line" nil nil args)
                   "goto-line with explicit arguments must be handled")
               (screen-copy-cursor screen)))
      (check-table
       (list
        (list (invoke '("2"))
              (cons 1 0)
              "goto-line 2 must land on row 1")
        (list (invoke '("2" "ignored"))
              (cons 1 0)
              "goto-line must ignore trailing positional tokens"))
       :test #'equal))))

(test send-keys-x-cursor-left-right-move-cursor
  "send -X cursor-right / cursor-left move the copy-mode cursor horizontally
   (previously both mis-mapped to begin-selection, which did not move it)."
  (with-fake-session (s)
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (let ((screen (active-screen s)))
      (cl-tmux::%dispatch-send-keys-X s "cursor-right")
      (is (= 1 (cdr (screen-copy-cursor screen)))
          "cursor-right moves the cursor to column 1 (from the initial column 0)")
      (cl-tmux::%dispatch-send-keys-X s "cursor-left")
      (is (= 0 (cdr (screen-copy-cursor screen)))
          "cursor-left moves the cursor back to column 0"))))

(test send-keys-x-cursor-up-down-move-cursor-vertically
  "send -X cursor-up / cursor-down move the copy cursor vertically (the -X names
   previously only scrolled a line, inconsistent with the arrow-key path)."
  (with-fake-session (s)
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (let* ((screen (active-screen s))
           (h      (screen-height screen)))
      (cl-tmux::%dispatch-send-keys-X s "cursor-up")
      (is (= (- h 2) (car (screen-copy-cursor screen)))
          "cursor-up moves the cursor one row up from the bottom")
      (cl-tmux::%dispatch-send-keys-X s "cursor-down")
      (is (= (- h 1) (car (screen-copy-cursor screen)))
          "cursor-down moves the cursor back to the bottom row"))))

;;; ── Detach / kill ───────────────────────────────────────────────────────────

(test dispatch-detach-returns-detach
  "C-b d returns :detach and does NOT clear *running* itself (the caller decides:
   standalone stops, a server merely disconnects the client)."
  (with-fake-session (s)
    (is (eq :detach (cl-tmux::dispatch-command s :detach nil)))
    (is-true cl-tmux::*running* "dispatch-command must not clear *running*")))

(test dispatch-kill-last-returns-quit-table
  "Killing the last window or last pane ends the session with :quit."
  (with-fake-session (s :nwindows 1)
    (is (eq :quit (cl-tmux::dispatch-command s :kill-window nil))
        "killing last window → :quit"))
  (with-fake-session (s :nwindows 1 :npanes 1)
    (is (eq :quit (cl-tmux::dispatch-command s :kill-pane nil))
        "killing last pane → :quit")))

(test dispatch-kill-one-of-two-windows-survives
  "Killing one of two windows leaves the session running with the other."
  (with-fake-session (s :nwindows 2)
    (is (null (cl-tmux::dispatch-command s :kill-window nil)))
    (is (= 1 (length (session-windows s))))))

;;; ── Prefix routing ──────────────────────────────────────────────────────────

(test dispatch-prefix-routes-binding
  "dispatch-prefix-command looks the byte up in the binding table (d → detach)."
  (with-fake-session (s)
    (is (eq :detach (cl-tmux::dispatch-prefix-command s (char-code #\d))))))

(test prefix-q-exits-copy-mode
  "In copy mode, the prefix-routed 'q' exits copy mode."
  (with-fake-session (s)
    (cl-tmux::dispatch-command s :copy-mode-enter nil)
    (cl-tmux::dispatch-prefix-command s (char-code #\q))
    (is-false (screen-copy-mode-p (active-screen s)))))

;;; ── %active-screen ───────────────────────────────────────────────────────────

(test active-screen-returns-active-pane-screen
  "%active-screen returns the screen of the session's active pane."
  (with-fake-session (s)
    (let ((ap (session-active-pane s)))
      (is (eq (pane-screen ap)
              (cl-tmux::%active-screen s))
          "%active-screen must return the active pane's screen"))))

(test active-screen-returns-nil-for-empty-session
  "%active-screen returns NIL when no pane is active."
  (with-fake-session (s :nwindows 0)
    (is (null (cl-tmux::%active-screen s)))))

;;; ── %cmd-cycle-window ────────────────────────────────────────────────────────

(test cmd-cycle-window-advances-selection
  "%cmd-cycle-window advances the active window via CYCLER."
  (with-fake-session (s :nwindows 3)
    (let* ((w1 (first  (session-windows s)))
           (w2 (second (session-windows s))))
      (is (eq w1 (session-active-window s)))
      (cl-tmux::%cmd-cycle-window s #'cl-tmux::next-cyclic)
      (is (eq w2 (session-active-window s))))))

;;; ── %cmd-cycle-pane ──────────────────────────────────────────────────────────

(test cmd-cycle-pane-advances-pane-selection
  "%cmd-cycle-pane advances the active pane via CYCLER."
  (with-fake-two-pane-session (s)
    (let* ((win (session-active-window s))
           (p0  (first  (window-panes win)))
           (p1  (second (window-panes win))))
      (is (eq p0 (window-active-pane win)))
      (cl-tmux::%cmd-cycle-pane s #'cl-tmux::next-cyclic)
      (is (eq p1 (window-active-pane win))))))

;;; ── focus events (?1004) on pane switch ──────────────────────────────────────

(test notify-pane-focus-noop-without-pty
  "%notify-pane-focus is a safe no-op for a pane with no live PTY (fd <= 0),
   even when focus events are enabled."
  (let ((pane (make-pane :id 1 :x 0 :y 0 :width 20 :height 5 :fd -1
                         :screen (make-screen 20 5))))
    (setf (cl-tmux/terminal/types:screen-focus-events (pane-screen pane)) t)
    (is (null (cl-tmux::%notify-pane-focus pane t))
        "no PTY → %notify-pane-focus returns NIL without writing")
    (finishes (cl-tmux::%notify-pane-focus pane nil))))

(test notify-pane-focus-writes-focus-in-to-pty
  "With focus events enabled and a live fd, %notify-pane-focus delivers the
   focus-gained report ESC[I to the pane's PTY."
  (with-pipe-fds (rfd wfd)
    (let ((pane (make-pane :id 1 :x 0 :y 0 :width 20 :height 5 :fd wfd
                           :screen (make-screen 20 5))))
      (setf (cl-tmux/terminal/types:screen-focus-events (pane-screen pane)) t)
      (cl-tmux::%notify-pane-focus pane t)
      (let ((ready (cl-tmux/pty:select-fds (list rfd) 200000)))  ; 200 ms
        (is-true ready "the PTY read-end must be readable after a focus report")
        (when ready
          (cffi:with-foreign-object (buf :uint8 8)
            (let ((n (cffi:foreign-funcall "read"
                                           :int rfd :pointer buf :unsigned-long 3
                                           :long)))
              (is (= 3 n) "focus-in report must be exactly 3 bytes (got ~D)" n)
              (is (= 27 (cffi:mem-aref buf :uint8 0)) "byte 0 must be ESC (27)")
              (is (= 91 (cffi:mem-aref buf :uint8 1)) "byte 1 must be #\\[ (91)")
              (is (= 73 (cffi:mem-aref buf :uint8 2)) "byte 2 must be #\\I (73)"))))))))

(test notify-pane-focus-disabled-screen-writes-nothing
  "A pane whose app did NOT enable focus events receives no report even with a
   live fd, and select-fds reports the pipe idle."
  (with-pipe-fds (rfd wfd)
    (let ((pane (make-pane :id 1 :x 0 :y 0 :width 20 :height 5 :fd wfd
                           :screen (make-screen 20 5))))
      ;; focus-events left NIL (default)
      (cl-tmux::%notify-pane-focus pane t)
      (is (null (cl-tmux/pty:select-fds (list rfd) 20000))
          "no focus report must reach an opted-out pane (pipe must stay idle)"))))

(test select-pane-with-focus-switches-and-tolerates-no-pty
  "%select-pane-with-focus changes the active pane and runs the focus-notify path
   without error even when panes have no PTY and focus events are enabled."
  (with-fake-two-pane-session (s)
    (let* ((win (session-active-window s))
           (p0  (first  (window-panes win)))
           (p1  (second (window-panes win))))
      (setf (cl-tmux/terminal/types:screen-focus-events (pane-screen p0)) t)
      (setf (cl-tmux/terminal/types:screen-focus-events (pane-screen p1)) t)
      (is (eq p0 (window-active-pane win)))
      (finishes (cl-tmux::%select-pane-with-focus win p1))
      (is (eq p1 (window-active-pane win))
          "%select-pane-with-focus must make p1 the active pane"))))
