;;; Application command and public facade packages.

(defpackage #:cl-tmux/commands
  (:use #:cl #:bordeaux-threads
        #:cl-tmux/config
        #:cl-tmux/pty
        #:cl-tmux/terminal
        #:cl-tmux/model
        #:cl-tmux/hooks)
  (:export
   #:kill-pane
   #:close-pane-pty
   #:kill-window
   #:resize-pane
   #:rename-window
   #:select-window-by-number
   #:copy-mode-enter
   #:copy-mode-exit
   #:copy-mode-copy-selection-no-cancel
   #:copy-mode-copy-selection-no-clear
   #:copy-mode-pipe-no-cancel #:copy-mode-pipe-no-clear #:copy-mode-pipe-and-cancel
   #:copy-mode-copy-pipe-no-clear #:copy-mode-copy-pipe-line
   #:copy-mode-copy-pipe-line-and-cancel
   #:copy-mode-rectangle-on #:copy-mode-rectangle-off
   #:copy-mode-cursor-centre-vertical #:copy-mode-cursor-centre-horizontal
   #:copy-mode-scroll
   #:copy-mode-move-cursor
   #:copy-mode-set-cursor
   #:copy-mode-begin-selection
   #:copy-mode-cancel-selection
   #:copy-mode-other-end
   #:copy-mode-jump-to-mark
   #:copy-mode-clear-selection
   #:copy-mode-select-word
   #:copy-mode-yank
   #:copy-mode-word-forward
   #:copy-mode-word-backward
   #:copy-mode-word-end
   #:copy-mode-space-forward
   #:copy-mode-space-backward
   #:copy-mode-space-end
   #:copy-mode-line-start
   #:copy-mode-back-to-indentation
   #:copy-mode-line-end
   #:copy-mode-top
   #:copy-mode-bottom
   #:copy-mode-high
   #:copy-mode-middle
   #:copy-mode-low
   #:copy-mode-page-up
   #:copy-mode-page-down
   #:copy-mode-half-page-up
   #:copy-mode-half-page-down
   #:copy-mode-scroll-up-line
   #:copy-mode-scroll-down-line
   #:copy-mode-scroll-middle
   #:copy-mode-scroll-down-and-cancel
   #:copy-mode-page-down-and-cancel
   #:copy-mode-cursor-down-and-cancel
   #:copy-mode-selection-mode
   #:copy-mode-scroll-to-mouse
   #:copy-mode-previous-paragraph
   #:copy-mode-next-paragraph
   #:copy-mode-begin-line-selection
   #:copy-mode-goto-line
   #:copy-mode-copy-end-of-line
   #:copy-mode-copy-end-of-line-and-cancel
   #:copy-mode-copy-line
   #:copy-mode-copy-line-and-cancel
   #:copy-mode-jump-forward
   #:copy-mode-jump-backward
   #:copy-mode-jump-to
   #:copy-mode-jump-to-backward
   #:copy-mode-jump-again
   #:copy-mode-jump-reverse
   #:*copy-mode-last-jump*
   #:copy-mode-search-forward
   #:copy-mode-search-backward
   #:copy-mode-search-next
   #:copy-mode-search-prev
   #:copy-mode-search-forward-incremental
   #:copy-mode-search-backward-incremental
   #:copy-mode-next-matching-bracket
   #:copy-mode-previous-matching-bracket
   #:copy-mode-toggle-rectangle
   #:copy-mode-set-mark
   #:copy-mode-stop-selection
   #:copy-mode-toggle-position
   #:copy-mode-previous-prompt
   #:copy-mode-next-prompt
   #:copy-mode-half-page-down-and-cancel
   #:copy-mode-copy-pipe-end-of-line-no-cancel
   #:copy-mode-append-selection
   #:copy-mode-append-selection-and-cancel
   #:copy-mode-copy-pipe
   #:copy-mode-copy-pipe-no-cancel
   #:copy-mode-copy-pipe-end-of-line
   #:rename-session
   #:run-shell
   #:if-shell
   #:swap-pane
   #:swap-two-panes
   #:capture-pane
   #:break-pane
   #:join-pane
   #:pipe-pane-open
   #:pipe-pane-close
   #:pipe-pane-write
   #:send-keys-to-pane
   #:tokenize-command-string))

(defpackage #:cl-tmux
  (:use #:cl #:bordeaux-threads
        #:cl-tmux/config
        #:cl-tmux/pty
        #:cl-tmux/terminal
        #:cl-tmux/model
        #:cl-tmux/renderer
        #:cl-tmux/input
        #:cl-tmux/commands
        #:cl-tmux/prompt
        #:cl-tmux/protocol
        #:cl-tmux/transport
        #:cl-tmux/net)
  (:export
   #:main
   #:*server-sessions*
   #:*server-marked-pane*
   #:*client-read-only*
   #:server-add-session
   #:server-find-session
   #:server-remove-session
   #:server-all-sessions
   #:server-current-session
   #:in-memory-session-store
   #:*session-groups*
   #:*group-id-counter*
   #:server-new-session-in-group
   #:new-session
   #:resolve-target
   #:resolve-target-context
   #:find-session-by-target
   #:find-window-by-target
   #:find-pane-by-target
   #:*wait-channels*
   #:%ensure-channel
   #:wait-for-channel
   #:signal-channel
   #:lock-channel
   #:unlock-channel
   #:*message-log*
   #:add-message-log
   #:*prompt-history*
   #:add-prompt-history
   #:save-prompt-history
   #:load-prompt-history
   #:*clock-mode-pane-id*
   #:stop-reader-threads
   #:start-status-timer
   #:+max-message-log-entries+
   #:+max-prompt-history+))
